/**
 * Vercingetorix - Arverni.
 *
 * The Gallic sword has no point worth the name. It is a long edge on the end
 * of a long arm, and it is used the way the sources describe: raised high and
 * brought down, over and over, with the whole body behind it. That is a
 * fighter who is enormous when he is already winning and hopeless when he has
 * been stopped, which is also the shape of his war.
 *
 * Onset is the mechanic and the argument. It fills when he is pressing and
 * drains when he is not, and his best moves are only available while it is
 * up - so the way to beat him is the way Caesar beat him: make him wait.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const IRON = "#b6bec7";
const BRONZE = "#c08a3e";
const WOAD = "#3f6b8f";
const WOOL = "#8f4a3a";
const LIME = "#e8dfc0";

const STANCE = {
  torso: 6,
  head: -3,
  hipF: 20,
  kneeF: 20,
  hipB: -24,
  kneeB: 34,
  // Sword carried high and back, shield forward and low. A Gallic guard is a
  // wind-up held in reserve rather than a point kept on line.
  //
  // These three are load-bearing: a prop's world angle is roughly
  // (forearm angle - 90 + weapon angle), and on a blade this long a wrong
  // guess does not look slightly off, it looks like a flagpole. This lands
  // the sword at about 50 degrees - raised and cocked, not vertical.
  shoulderF: 34,
  elbowF: 62,
  shoulderB: 38,
  elbowB: 76,
  weaponBack: 26,
  crouch: 0.1,
};

const IDLE_ARMS = { shoulderF: 34, elbowF: 62, shoulderB: 38, elbowB: 76, weaponBack: 26 };

export const CELT: FighterDef = {
  id: "celt",
  name: "Vercingetorix",
  title: "King of the Arverni",
  era: "Alesia, 52 BC",
  bio: "The one man who got the Gallic tribes to stop fighting each other long enough to fight Rome, and very nearly finished it. He burned his own towns to starve Caesar out, beat him at Gergovia, and then let himself be shut inside Alesia, where two Roman walls and a relief army that could not break them ended six centuries of Gallic independence in about a month.",
  archetype: "Momentum / Rushdown",
  difficulty: 3,
  strengths: ["Longest swings on the roster", "Onset turns pressure into more pressure", "The gaesum makes them come to him"],
  weaknesses: ["Onset drains the moment he stops", "Everything is committal", "Nothing safe once he has been backed up"],
  winQuote: "You should have come to the field. I would have been there.",
  palette: {
    body: "#dcc4a2",
    outline: "#161009",
    accent: WOAD,
    cloth: WOOL,
    metal: IRON,
    aura: "#6fb4e0",
  },
  stats: {
    health: 1040,
    walkF: 3.2,
    walkB: 2.2,
    dashSpeed: 9.0,
    dashFrames: 15,
    backdashFrames: 21,
    jumpVel: 12.0,
    jumpFwd: 5.0,
    gravity: 0.62,
    weight: 1.1,
    airMoves: 1,
    doubleJump: false,
    airDash: false,
    width: 21,
    standHeight: 108,
    crouchHeight: 66,
    scale: 1.04,
  },
  stance: STANCE,
  clips: guardClips({
    // A body shield only reads as one while it stands up. The lead arm angles
    // here are deliberately shallow: fold the elbow any further and the oval
    // lies over on its side and turns into a table.
    high: { torso: 2, head: -8, shoulderF: 8, elbowF: 98, shoulderB: 40, elbowB: 92, weaponBack: 62, hipF: 16, kneeF: 24, hipB: -24, kneeB: 36, offX: -3 },
    low: { torso: 8, head: -6, shoulderF: 12, elbowF: 94, shoulderB: 34, elbowB: 96, weaponBack: 66, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88, offX: -3 },
  }),
  resource: {
    name: "Onset",
    max: 3,
    start: 1,
    // It comes from doing something to them, not from waiting. Blocked counts,
    // because a Gallic charge into a shield wall is still a charge - it just
    // does not pay as well.
    gainOnHit: 0.5,
    gainOnBlocked: 0.25,
    color: WOAD,
    pips: true,
  },
  props: [
    {
      id: "limehair",
      attach: "head",
      // Hair worked back with lime wash until it stands off the skull, and a
      // long moustache. Both are Diodorus, describing Gauls at length and
      // clearly enjoying himself.
      parts: [
        { geo: "poly", size: [-11, -6, -9, 8, 0, 13, 9, 8, 11, -6], pos: [-1, 4], color: LIME },
        // Swept back off the forehead, not standing up off the crown. Lime
        // wash stiffens the hair backwards into a mane; drawn as vertical
        // spikes it turns into a diadem, which is the opposite of the point.
        { geo: "poly", size: [8, 6, 0, 12, -14, 12, -22, 4, -12, 2, -2, 0], pos: [-4, 10], color: LIME },
        { geo: "poly", size: [4, 3, -6, 8, -19, 7, -25, 0, -12, -1, -2, -2], pos: [-4, 6], color: "#d8cca8" },
        { geo: "poly", size: [2, 2, -8, 5, -18, 3, -22, -3, -10, -4], pos: [-4, 1], color: "#c9b489" },
        // Moustache, hanging past the jaw.
        { geo: "box", size: [12, 3], pos: [2, -6], color: "#c9b489" },
        { geo: "poly", size: [-2, 4, 2, 4, 1.6, -7, -2, -6], pos: [-3, -10], color: "#c9b489" },
        { geo: "poly", size: [-2, 4, 2, 4, 2, -7, -1.6, -6], pos: [7, -10], color: "#c9b489" },
        { geo: "box", size: [10, 1.4], pos: [4, -7], rot: -6, color: "#241a10", z: 0.4 },
      ],
    },
    {
      id: "torc",
      attach: "neck",
      // Gold neck ring with buffer terminals. The single most Gallic object
      // there is, and a rank marker rather than jewellery.
      parts: [
        { geo: "ring", size: [9, 2.6], pos: [0, -1], color: BRONZE, z: 0.6 },
        { geo: "disc", size: [2.6], pos: [-6, -6], color: "#e8c06a", z: 0.65 },
        { geo: "disc", size: [2.6], pos: [6, -6], color: "#e8c06a", z: 0.65 },
      ],
    },
    {
      id: "cloak",
      attach: "torso",
      // Mail over a checked tunic, with a heavy wool cloak pinned at the
      // shoulder. Mail is a Celtic invention the Romans took off them.
      parts: [
        { geo: "poly", size: [-12, -16, 12, -16, 13, 7, 8, 16, -8, 16, -13, 7], pos: [0, 3], color: "#6f7681" },
        { geo: "box", size: [24, 1.8], pos: [0, 10], color: "#585f69" },
        { geo: "box", size: [24, 1.8], pos: [0, 4], color: "#585f69" },
        { geo: "box", size: [23, 1.8], pos: [0, -2], color: "#585f69" },
        { geo: "box", size: [22, 1.8], pos: [0, -8], color: "#585f69" },
        // The check, showing at the hem below the mail.
        { geo: "box", size: [22, 5], pos: [0, -15], color: WOOL },
        { geo: "box", size: [4, 5], pos: [-7, -15], color: "#5c6b4a" },
        { geo: "box", size: [4, 5], pos: [3, -15], color: "#5c6b4a" },
        { geo: "disc", size: [3.4], pos: [-11, 12], color: BRONZE, z: 0.5 },
      ],
      cloth: {
        segments: 4,
        segmentLength: 13,
        width: 25,
        endWidth: 20,
        color: WOOL,
        lining: "#5c6b4a",
        gravity: 0.44,
        stiffness: 0.5,
        drift: -0.3,
      },
    },
    {
      id: "braccae",
      attach: "pelvis",
      // Checked trousers. Rome found them ridiculous and then adopted them.
      parts: [
        { geo: "poly", size: [-13, 4, 13, 3.5, 13, -4, -13, -4.5], pos: [0, 1], color: "#5f452b" },
        { geo: "box", size: [26, 2], pos: [0, 2], color: BRONZE, z: 0.2 },
        { geo: "box", size: [8, 18], pos: [-8, -10], rot: 4, color: WOOL },
        { geo: "box", size: [8, 18], pos: [8, -10], rot: -4, color: "#7a3f31" },
        { geo: "box", size: [8, 2.4], pos: [-8, -6], color: "#5c6b4a" },
        { geo: "box", size: [8, 2.4], pos: [-8, -14], color: "#5c6b4a" },
        { geo: "box", size: [8, 2.4], pos: [8, -6], color: "#5c6b4a" },
        { geo: "box", size: [8, 2.4], pos: [8, -14], color: "#5c6b4a" },
      ],
    },
    {
      id: "longsword",
      attach: "handB",
      // La Tene long sword: parallel edges, a rounded point that is not for
      // thrusting, and a short organic grip. All the weight is in the swing.
      parts: [
        // Wide parallel edges and a rounded end. Drawn narrow it reads as a
        // needle, which is the one thing a Gallic sword is not - it has no
        // point worth the name and all of it is edge.
        { geo: "poly", size: [0, 4, 4, 8.5, -58, 9, -66, 7.5, -66, -7.5, -58, -9, 4, -8.5, 0, -4], pos: [72, 0], color: IRON },
        { geo: "poly", size: [0, 2, -56, 2.4, -64, 2, -64, -2, -56, -2.4, 0, -2], pos: [70, 0], color: "#e6edf3" },
        { geo: "box", size: [4, 15], pos: [8, 0], color: "#5a4630" },
        { geo: "cyl", size: [3, 18], pos: [-2, 0], rot: 90, color: "#4a3524" },
        { geo: "box", size: [16, 1.6], pos: [-2, 1.8], color: "#8a6a42" },
        { geo: "poly", size: [-5, 4, 5, 4, 4, -4, -4, -4], pos: [-13, 0], color: BRONZE },
      ],
    },
    {
      id: "shield",
      attach: "forearmF",
      // Long oval body shield with a spindle boss over the horizontal grip -
      // wood and hide, so it is light for its size and does not last.
      parts: [
        { geo: "poly", size: [-13, 32, 0, 38, 13, 32, 13, -32, 0, -38, -13, -32], pos: [10, 0], color: "#6b4a30", z: 0.5 },
        { geo: "poly", size: [-10, 29, 0, 34, 10, 29, 10, -29, 0, -34, -10, -29], pos: [10, 0], color: "#7a5a3a", z: 0.52 },
        // Painted device: a spiral, the one motif the La Tene smiths never let go.
        { geo: "ring", size: [11, 2.6], pos: [10, 0], color: WOAD, z: 0.55 },
        { geo: "ring", size: [6, 2.2], pos: [10, 0], color: WOAD, z: 0.56 },
        // Spine and boss.
        { geo: "box", size: [7, 70], pos: [10, 0], color: "#5a4429", z: 0.58 },
        { geo: "poly", size: [-9, 5, -4, 10, 4, 10, 9, 5, 9, -5, 4, -10, -4, -10, -9, -5], pos: [10, 0], color: IRON, z: 0.6 },
        { geo: "disc", size: [3.4], pos: [10, 0], color: "#dfe6ee", z: 0.62 },
      ],
    },
    {
      id: "gaesum",
      attach: "handF",
      conditional: true,
      // Light throwing spear with a long narrow head. Named after it: the
      // gaesatae were the men who fought with nothing else on.
      parts: [
        { geo: "cyl", size: [2.4, 74], pos: [24, 0], rot: 90, color: "#7a5f3a" },
        { geo: "poly", size: [0, 0, -22, 3.4, -26, 2, -26, -2, -22, -3.4], pos: [86, 0], color: IRON },
        { geo: "poly", size: [0, 0, -20, 1.1, -24, 0.8, -24, -0.8, -20, -1.1], pos: [85, 0], color: "#e6edf3" },
        { geo: "box", size: [7, 4.4], pos: [60, 0], color: "#8f979f" },
        { geo: "box", size: [5, 4], pos: [-11, 0], color: BRONZE },
      ],
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 128,
      backThrowDamage: 140,
      throwRange: 62,
      rollSpeed: 8.0,
      weaponIdle: IDLE_ARMS,
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Edge Flick",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 12,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 11],
      followUps: [{ button: "B", move: "5B", from: 4, to: 10, string: "Open the Line" }],
      hits: [hit(4, 6, bx(22, 54, 56, 20), 26, { fx: "slash", hitstun: 14, blockstun: 10, pushX: 2.4 })],
      desc: "A short cut off the wrist, thrown to make room for the real one.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderB: 94, elbowB: 18, weaponBack: 6, torso: 14, offX: 3 }),
        kf(8, { ...STANCE, shoulderB: 66, elbowB: 54, weaponBack: 32, torso: 8 }, "inOut"),
        kf(12, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Long Cut",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 22,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [9, 20],
      followUps: [{ button: "C", move: "5C", from: 9, to: 19, string: "All of It" }],
      hits: [hit(8, 12, bx(32, 44, 96, 32), 54, { fx: "slash", pushX: 4.6, hitstun: 19 })],
      desc: "The sword taken across at full arm. Reaches further than it looks like it should.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderB: 8, elbowB: 96, weaponBack: 92, torso: -10, offX: -4 }),
        kf(8, { ...STANCE, shoulderB: 96, elbowB: 6, weaponBack: -12, torso: 22, hipF: 32, offX: 7 }, "out"),
        kf(15, { ...STANCE, shoulderB: 68, elbowB: 44, weaponBack: 26, torso: 12 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Overhand Cut",
      input: { button: "C", stance: "stand" },
      tags: ["heavy"],
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [15, 28],
      hits: [
        hit(15, 19, bx(26, 30, 100, 60), 90, {
          fx: "slash",
          pushX: 8,
          knockdown: "soft",
          hitstun: 24,
          hitstop: 11,
          shake: 2,
        }),
      ],
      desc: "Raised over the head and brought straight down, which is the only thing Roman writers ever describe a Gaul doing.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderB: -12, elbowB: 104, weaponBack: 116, torso: -16, hipB: -32, kneeB: 46, offX: -5 }, "inOut"),
        kf(15, { ...STANCE, shoulderB: 112, elbowB: -6, weaponBack: -30, shoulderF: 30, elbowF: 70, torso: 32, hipF: 38, kneeF: 20, offX: 8 }, "out"),
        kf(23, { ...STANCE, shoulderB: 86, elbowB: 24, weaponBack: 2, torso: 20, offX: 4 }),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Flick",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 12,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 11],
      hits: [hit(4, 6, bx(20, 12, 52, 18), 24, { guard: "low", fx: "slash", hitstun: 13, blockstun: 10, pushX: 2.2 })],
      desc: "Turns the edge over and takes it across a shin.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 22, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88, shoulderB: 78, elbowB: 26, weaponBack: 4, offX: 4 }),
        kf(8, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88, shoulderB: 58, elbowB: 60 }, "inOut"),
        kf(12, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88 }),
      ],
    },
    {
      id: "2B",
      name: "Hamstring",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 23,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [9, 21],
      hits: [hit(8, 12, bx(28, 8, 86, 22), 52, { guard: "low", fx: "slash", pushX: 3.8, hitstun: 18 })],
      desc: "The long cut taken down to the back of the knee.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 8, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88, shoulderB: 16, elbowB: 92, weaponBack: 82 }),
        kf(8, { ...STANCE, crouch: 1, torso: 28, hipF: 42, kneeF: 82, hipB: -24, kneeB: 88, shoulderB: 58, elbowB: 8, weaponBack: -32, offX: 8 }, "out"),
        kf(15, { ...STANCE, crouch: 1, torso: 20, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88, shoulderB: 46, elbowB: 50, weaponBack: 10 }, "inOut"),
        kf(23, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88 }),
      ],
    },
    {
      id: "2C",
      name: "Scythe",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 30,
      cancelInto: ["special", "super"],
      cancelWindow: [14, 26],
      hits: [hit(12, 16, bx(24, 2, 100, 22), 74, { guard: "low", knockdown: "sweep", fx: "slash", pushX: 5.4 })],
      desc: "Puts the whole blade along the floor and turns with it.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88 }, "out"),
        kf(6, { ...STANCE, crouch: 1, torso: 4, hipF: 30, kneeF: 74, hipB: -26, kneeB: 84, shoulderB: 6, elbowB: 96, weaponBack: 90, offX: -4 }, "inOut"),
        kf(12, { ...STANCE, crouch: 1.15, spin: -14, torso: 32, hipF: 56, kneeF: 86, hipB: -28, kneeB: 92, shoulderB: 46, elbowB: 4, weaponBack: -40, offX: 9 }, "out"),
        kf(22, { ...STANCE, crouch: 1, torso: 22, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88, shoulderB: 40, elbowB: 54, weaponBack: 10 }, "inOut"),
        kf(30, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88 }),
      ],
    },
    {
      id: "6A",
      name: "Boss Punch",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 17,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [6, 15],
      vel: [{ at: 4, x: 3.6 }, { at: 10, x: 0 }],
      friction: 0.88,
      hits: [hit(6, 9, bx(14, 48, 46, 38), 34, { fx: "blunt", pushX: 4, hitstun: 16, hitstop: 6 })],
      desc: "Punches the boss out to meet them, and steps in behind it.",
      notation: "→ + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderF: 20, elbowF: 96, torso: 0, offX: -2 }),
        kf(6, { ...STANCE, shoulderF: 74, elbowF: 16, torso: 22, hipF: 38, kneeF: 24, offX: 8 }, "out"),
        kf(12, { ...STANCE, shoulderF: 50, elbowF: 50, torso: 12, offX: 4 }, "inOut"),
        kf(17, { ...STANCE }),
      ],
    },
    {
      id: "6B",
      name: "Rising Edge",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "medium", "overhead"],
      priority: 12,
      duration: 29,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [16, 26],
      hits: [hit(15, 18, bx(24, 36, 82, 54), 60, { guard: "overhead", fx: "slash", pushX: 5, hitstun: 21, hitstop: 8 })],
      desc: "Comes over the top of the shield. Standing block only.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderB: -4, elbowB: 100, weaponBack: 108, torso: -12, offX: -4 }, "inOut"),
        kf(15, { ...STANCE, shoulderB: 106, elbowB: -2, weaponBack: -26, torso: 28, hipF: 34, offX: 7 }, "out"),
        kf(22, { ...STANCE, shoulderB: 78, elbowB: 26, weaponBack: 4, torso: 18, offX: 3 }),
        kf(29, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Lift",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy", "launcher"],
      priority: 12,
      duration: 34,
      cancelInto: ["special", "super"],
      cancelWindow: [17, 30],
      hits: [
        hit(13, 17, bx(22, 26, 78, 76), 80, {
          launch: [2.4, 11.5],
          knockdown: "launch",
          fx: "slash",
          hitstun: 25,
          hitstop: 10,
          shake: 1.9,
        }),
      ],
      desc: "Turns the edge up and takes them off their feet with the backswing.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, crouch: 0.55, shoulderB: -18, elbowB: 44, weaponBack: 16, torso: 4, hipF: 30, kneeF: 56, offX: -3 }, "inOut"),
        kf(13, { ...STANCE, shoulderB: 132, elbowB: -18, weaponBack: -62, shoulderF: 66, elbowF: 40, torso: -12, hipF: 22, kneeF: 10, offX: 5, offY: 3 }, "out"),
        kf(23, { ...STANCE, shoulderB: 96, elbowB: 14, weaponBack: -18, torso: 2, offX: 2 }),
        kf(34, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Shield Rim",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 15,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [6, 13],
      hits: [hit(5, 8, bx(12, 52, 40, 26), 30, { fx: "blunt", hitstun: 15, blockstun: 11, pushX: 3.6 })],
      desc: "Chops the rim up into the chin while stepping back off the line.",
      notation: "← + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderF: 10, elbowF: 100, torso: -2, offX: -3 }),
        kf(5, { ...STANCE, shoulderF: 70, elbowF: 44, torso: 16, offX: 2 }, "out"),
        kf(10, { ...STANCE, shoulderF: 46, elbowF: 72, torso: 8 }, "inOut"),
        kf(15, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Backhand Edge",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 25,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [10, 23],
      hits: [hit(9, 13, bx(30, 42, 92, 34), 54, { fx: "slash", pushX: 6.5, hitstun: 19, hitstop: 7 })],
      desc: "The return half of the swing, thrown on the retreat to buy the room back.",
      notation: "← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderB: 100, elbowB: 4, weaponBack: -18, torso: 18, offX: 2 }),
        kf(9, { ...STANCE, shoulderB: 4, elbowB: 94, weaponBack: 90, torso: -14, offX: -5 }, "out"),
        kf(17, { ...STANCE, shoulderB: 24, elbowB: 76, weaponBack: 60, torso: -4 }, "inOut"),
        kf(25, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Held Blow",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 46,
      cancelInto: ["special", "super"],
      cancelWindow: [28, 42],
      resourceGain: 1,
      hits: [hit(21, 25, bx(18, 20, 100, 88), 104, { guard: "overhead", fx: "slash", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 })],
      desc: "Holds the sword up and waits before letting it fall. Slow, standing block only, and the wait is worth one Onset whether it lands or not.",
      notation: "← + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(9, { ...STANCE, shoulderB: -8, elbowB: 104, weaponBack: 118, torso: -14, offX: -5 }, "inOut"),
        kf(16, { ...STANCE, shoulderB: -22, elbowB: 110, weaponBack: 134, torso: -22, hipB: -30, kneeB: 42, offY: 4, offX: -3 }, "out"),
        kf(21, { ...STANCE, shoulderB: 124, elbowB: -10, weaponBack: -38, shoulderF: 36, elbowF: 62, torso: 36, hipF: 40, kneeF: 18, offX: 7 }, "out"),
        kf(28, { ...STANCE, shoulderB: 100, elbowB: 12, weaponBack: -10, torso: 26, offX: 4 }),
        kf(38, { ...STANCE, shoulderB: 62, elbowB: 48, weaponBack: 30, torso: 12 }, "inOut"),
        kf(46, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Flick",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 18,
      airborne: true,
      landCancel: true,
      landRecovery: 3,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [5, 16],
      hits: [hit(5, 10, bx(20, 30, 54, 28), 28, { fx: "slash", hitstun: 14, pushX: 2.2 })],
      desc: "Short cut thrown on the way through.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 32, kneeF: 46, hipB: -24, kneeB: 46 }, "out"),
        kf(5, { ...STANCE, free: 1, shoulderB: 78, elbowB: 16, weaponBack: 8, torso: 12 }),
        kf(12, { ...STANCE, free: 1, shoulderB: 58, elbowB: 58, weaponBack: 34, torso: 6 }, "inOut"),
        kf(18, { ...STANCE, free: 1, hipF: 32, kneeF: 46, hipB: -24, kneeB: 46 }),
      ],
    },
    {
      id: "jB",
      name: "Air Cut",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 24,
      airborne: true,
      landCancel: true,
      landRecovery: 5,
      cancelInto: ["heavy", "special"],
      hits: [hit(7, 14, bx(26, 16, 84, 42), 56, { fx: "slash", pushX: 3.8, hitstun: 18 })],
      desc: "Swings the whole blade out flat underneath him.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 32, kneeF: 44, hipB: -22, kneeB: 42 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderB: 16, elbowB: 92, weaponBack: 84, torso: -8 }),
        kf(8, { ...STANCE, free: 1, shoulderB: 64, elbowB: 6, weaponBack: -26, torso: 20, hipF: 40 }, "out"),
        kf(16, { ...STANCE, free: 1, shoulderB: 54, elbowB: 52, weaponBack: 16, torso: 8 }, "inOut"),
        kf(24, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "jC",
      name: "Falling Edge",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 28,
      airborne: true,
      landCancel: true,
      landRecovery: 7,
      hits: [
        hit(8, 18, bx(8, 2, 70, 52), 78, {
          guard: "overhead",
          fx: "slash",
          knockdown: "soft",
          pushX: 4.6,
          shake: 1.5,
        }),
      ],
      desc: "Brings it down the whole way from the top of the jump. His jump-in.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, torso: -18, shoulderB: -10, elbowB: 106, weaponBack: 124, hipF: 40, kneeF: 56 }),
        kf(8, { ...STANCE, free: 1, torso: 30, shoulderB: 100, elbowB: 0, weaponBack: -54, hipF: 14, kneeF: 18 }, "out"),
        kf(28, { ...STANCE, free: 1, torso: 24, shoulderB: 92, elbowB: 6, weaponBack: -48 }),
      ],
    },
    {
      id: "dashAttack",
      name: "The Charge",
      input: { button: "C", dir: "f", stance: "stand", whileDashing: true },
      tags: ["command"],
      priority: 12,
      duration: 32,
      vel: [
        { at: 3, x: 11 },
        { at: 17, x: 0 },
      ],
      friction: 0.9,
      resourceGain: 1,
      hits: [hit(8, 13, bx(24, 26, 88, 50), 70, { fx: "slash", pushX: 7, knockdown: "soft", hitstun: 21, shake: 1.5 })],
      desc: "Arrives with the sword already coming over. Worth one Onset - the charge is the point of him.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 26, crouch: 0.4, shoulderB: 0, elbowB: 100, weaponBack: 96, offX: -3 }),
        kf(8, { ...STANCE, torso: 34, crouch: 0.3, shoulderB: 100, elbowB: 0, weaponBack: -22, hipF: 46, kneeF: 24, offX: 9 }, "out"),
        kf(22, { ...STANCE, torso: 16, shoulderB: 66, elbowB: 48, weaponBack: 28, offX: 3 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },

    // -------------------------------------------------------- five specials
    {
      id: "gaesumThrow",
      name: "Gaesum",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 20,
      duration: 36,
      resourceCost: 1,
      showProps: ["gaesum"],
      hideProps: ["shield"],
      projectiles: [
        {
          at: 13,
          kind: "javelin",
          x: 52,
          y: 68,
          vx: 19,
          vy: 0.6,
          gravity: 0.06,
          life: 70,
          box: { x: -22, y: -4, w: 44, h: 9 },
          damage: 58,
          hitstun: 21,
          blockstun: 13,
          chip: 6,
          pushX: 6,
          clashes: true,
          fx: "pierce",
          hitstop: 7,
          color: IRON,
          trail: "#cdd6df",
        },
      ],
      vfx: [{ at: 13, kind: "dust", x: 56, y: 68, scale: 0.6, color: "#cdd6df" }],
      desc: "Puts the light spear across the gap flat and hard. He does not own many, so it is a question rather than a wall.",
      notation: "↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 4, elbowF: 30, torso: -14, hipB: -32, kneeB: 44, offX: -5 }, "inOut"),
        kf(13, { ...STANCE, shoulderF: 128, elbowF: -12, torso: 26, hipF: 42, kneeF: 22, offX: 9 }, "out"),
        kf(24, { ...STANCE, shoulderF: 78, elbowF: 30, torso: 14, offX: 3 }, "inOut"),
        kf(36, { ...STANCE }),
      ],
    },
    {
      id: "overrun",
      name: "Overrun",
      input: { button: "C", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 22,
      duration: 42,
      resourceCost: 1,
      resourceMin: 1,
      vel: [
        { at: 5, x: 12 },
        { at: 26, x: 0 },
      ],
      friction: 0.9,
      armor: [{ from: 5, to: 16, hits: 1, damageScale: 0.45 }],
      hits: [
        hit(12, 16, bx(20, 34, 76, 52), 58, { group: 1, fx: "blunt", pushX: 2, hitstun: 19, hitstop: 7 }),
        hit(22, 27, bx(22, 28, 92, 62), 82, {
          group: 2,
          fx: "slash",
          pushX: 11,
          knockdown: "hard",
          hitstun: 26,
          hitstop: 13,
          shake: 2.3,
        }),
      ],
      desc: "Runs the shield in and brings the sword over the top of it. Armoured, and it costs one Onset - he can only do this while he is already winning.",
      notation: "↓↘→ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.35 }, "out"),
        kf(5, { ...STANCE, torso: 30, crouch: 0.4, shoulderF: 30, elbowF: 70, shoulderB: -6, elbowB: 96, weaponBack: 100, offX: -2 }, "out"),
        kf(12, { ...STANCE, torso: 36, shoulderF: 76, elbowF: 20, shoulderB: 10, elbowB: 90, weaponBack: 106, hipF: 44, kneeF: 26, offX: 9 }, "out"),
        kf(22, { ...STANCE, torso: 34, shoulderB: 118, elbowB: -8, weaponBack: -34, shoulderF: 40, elbowF: 60, hipF: 46, kneeF: 22, offX: 11 }, "out"),
        kf(32, { ...STANCE, torso: 18, shoulderB: 74, elbowB: 40, weaponBack: 20, offX: 4 }, "inOut"),
        kf(42, { ...STANCE }),
      ],
    },
    {
      id: "shieldBash",
      name: "Boss Charge",
      input: { button: "A", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 24,
      duration: 28,
      vel: [{ at: 4, x: 6.4 }, { at: 14, x: 0 }],
      friction: 0.86,
      resourceGain: 1,
      hits: [
        hit(7, 11, bx(12, 44, 48, 46), 50, {
          fx: "blunt",
          pushX: 8,
          hitstun: 22,
          blockstun: 17,
          hitstop: 9,
          shake: 1.3,
        }),
      ],
      desc: "Drives the spindle boss into them and keeps walking. Plus on block, and it is worth one Onset - this is how the pressure starts.",
      notation: "↓↙← + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 16, elbowF: 104, torso: -6, crouch: 0.35, offX: -3 }, "out"),
        kf(7, { ...STANCE, shoulderF: 66, elbowF: 24, torso: 30, hipF: 44, kneeF: 26, offX: 9 }, "out"),
        kf(16, { ...STANCE, shoulderF: 48, elbowF: 58, torso: 18, offX: 4 }, "inOut"),
        kf(28, { ...STANCE }),
      ],
    },
    {
      id: "carnyxCall",
      name: "Carnyx",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 26,
      duration: 34,
      friction: 0.82,
      resourceGain: 2,
      meterGain: 18,
      armor: [{ from: 6, to: 26, hits: 1, damageScale: 0.6 }],
      vfx: [
        { at: 6, kind: "spark", x: 10, y: 78, scale: 1.2, color: "#6fb4e0" },
        { at: 16, kind: "dust", x: 14, y: 70, scale: 1.1, color: "#6fb4e0" },
      ],
      desc: "The war horn, held up and sounded. Two Onset and a hit of armour while it plays - he can be interrupted, but not by the first thing thrown at him.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 140, elbowF: -24, torso: -14, head: 10, hipB: -30, kneeB: 42, offX: -3 }, "out"),
        kf(16, { ...STANCE, shoulderF: 148, elbowF: -30, torso: -18, head: 12, hipF: 24, kneeF: 16, offX: -2 }, "inOut"),
        kf(26, { ...STANCE, shoulderF: 96, elbowF: 20, torso: -4, head: 4 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },
    {
      id: "risingCut",
      name: "Up and Over",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 26,
      duration: 44,
      airborne: true,
      invuln: [{ from: 1, to: 7, kind: "strike" }],
      vel: [
        { at: 1, x: 3.2, y: 12.4 },
        { at: 25, y: -1, mode: "add" },
      ],
      hits: [
        hit(4, 10, bx(14, 40, 70, 84), 84, { launch: [2.2, 11.2], knockdown: "launch", fx: "slash", hitstun: 26, shake: 1.8 }),
        hit(11, 18, bx(12, 56, 62, 66), 34, { group: 2, launch: [1.6, 5.5], fx: "slash", hitstun: 18 }),
      ],
      desc: "Comes up off the back foot with the edge leading. Invincible for the first frames - his only reversal, and it goes a long way up.",
      notation: "→↓↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.7, hipF: 26, kneeF: 54 }, "out"),
        kf(4, { ...STANCE, free: 1, torso: -18, shoulderB: 152, elbowB: -14, weaponBack: -50, shoulderF: 100, elbowF: 30, hipF: 46, kneeF: 62, hipB: -32, kneeB: 44 }, "out"),
        kf(16, { ...STANCE, free: 1, torso: -22, shoulderB: 164, elbowB: -18, weaponBack: -56, hipF: 36, kneeF: 74 }),
        kf(31, { ...STANCE, free: 1, torso: -4, shoulderB: 110, elbowB: 24, weaponBack: -6, hipF: 32, kneeF: 48 }, "inOut"),
        kf(44, { ...STANCE, free: 1 }),
      ],
    },

    // ----------------------------------------------------------------- skill
    {
      id: "vergobret",
      name: "Take the Field",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill"],
      priority: 18,
      duration: 30,
      friction: 0.8,
      resourceGain: 1,
      meterGain: 24,
      vfx: [{ at: 5, kind: "spark", x: 14, y: 66, scale: 1.1, color: "#6fb4e0" }],
      desc: "SKILL. Raises the sword where they can all see it. One Onset, a lot of meter, and it commits him to the front foot.",
      notation: "A + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderB: 152, elbowB: -30, weaponBack: -40, shoulderF: 24, elbowF: 74, torso: 8, head: 8, hipF: 26, kneeF: 22, offX: 2 }, "out"),
        kf(14, { ...STANCE, shoulderB: 160, elbowB: -36, weaponBack: -46, torso: 12, head: 10, hipF: 30, kneeF: 18, offX: 3 }, "inOut"),
        kf(22, { ...STANCE, shoulderB: 104, elbowB: 16, weaponBack: 2, torso: 6, head: 2 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "Gergovia",
      input: { button: "S", motion: "dd", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 102,
      meterCost: 100,
      superFreeze: 42,
      invuln: [{ from: 1, to: 14, kind: "strike" }],
      vel: [
        { at: 6, x: 11 },
        { at: 30, x: 6 },
        { at: 54, x: 5 },
        { at: 72, x: 0 },
      ],
      friction: 0.93,
      hits: [
        hit(13, 17, bx(14, 42, 54, 42), 46, { group: 1, fx: "blunt", pushX: 1, hitstun: 19, hitstop: 5 }),
        hit(24, 28, bx(26, 40, 94, 36), 48, { group: 2, fx: "slash", pushX: 1, hitstun: 19, hitstop: 5 }),
        hit(35, 39, bx(24, 18, 92, 30), 44, { group: 3, guard: "low", fx: "slash", pushX: 1, hitstun: 18, hitstop: 4 }),
        hit(47, 51, bx(24, 38, 96, 48), 50, { group: 4, fx: "slash", pushX: 1, hitstun: 19, hitstop: 5 }),
        hit(62, 68, bx(18, 14, 104, 90), 140, {
          group: 5,
          fx: "slash",
          pushX: 12,
          knockdown: "hard",
          launch: [6, 8.5],
          hitstop: 17,
          shake: 3,
        }),
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 52, scale: 2.4, color: "#6fb4e0" },
        { at: 62, kind: "explode", x: 56, y: 44, scale: 1.3 },
      ],
      desc: "SUPER. The one battle he won outright. Shield, edge, edge low, edge, and then the whole length of it brought down.",
      notation: "↓↓ + S (100 meter)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5, torso: -10 }, "out"),
        kf(7, { ...STANCE, shoulderF: 14, elbowF: 100, torso: -8, offX: -3 }, "out"),
        kf(13, { ...STANCE, shoulderF: 72, elbowF: 20, torso: 28, hipF: 40, offX: 8 }, "out"),
        kf(19, { ...STANCE, shoulderB: 10, elbowB: 96, weaponBack: 90, torso: 6 }, "inOut"),
        kf(24, { ...STANCE, shoulderB: 100, elbowB: 2, weaponBack: -16, torso: 26, hipF: 36, offX: 8 }, "out"),
        kf(31, { ...STANCE, crouch: 0.5, shoulderB: 18, elbowB: 90, weaponBack: 86, torso: 8 }, "inOut"),
        kf(35, { ...STANCE, crouch: 0.7, shoulderB: 54, elbowB: 6, weaponBack: -34, torso: 32, hipF: 46, kneeF: 40, offX: 8 }, "out"),
        kf(42, { ...STANCE, shoulderB: 22, elbowB: 86, weaponBack: 80, torso: -6 }, "inOut"),
        kf(47, { ...STANCE, spin: 10, shoulderB: 92, elbowB: 4, weaponBack: -14, torso: 30, hipF: 40, offX: 9 }, "out"),
        kf(56, { ...STANCE, shoulderB: -22, elbowB: 112, weaponBack: 136, torso: -26, hipB: -32, kneeB: 48, offX: -6 }, "inOut"),
        kf(62, { ...STANCE, shoulderB: 128, elbowB: -12, weaponBack: -42, shoulderF: 40, elbowF: 58, torso: 38, hipF: 46, kneeF: 22, hipB: -22, kneeB: 56, offX: 12 }, "out"),
        kf(82, { ...STANCE, shoulderB: 76, elbowB: 40, weaponBack: 24, torso: 14, offX: 4 }, "inOut"),
        kf(102, { ...STANCE }),
      ],
    },
  ],
};
