/**
 * Julie d'Aubigny - La Maupin.
 *
 * Eighteen other people on this roster and not one of them fences. Everyone
 * else swings, hacks, thrusts with two hands or shoots; she is the only one
 * here holding a weapon that weighs nothing and is pointed the entire time.
 *
 * So she is built inside out from the rest of the roster. Her buttons are
 * thin and fast and reach much further than they look, and almost none of
 * them are worth anything on their own - the damage is in the riposte, which
 * only exists if she has read the other person correctly. Tempo is the whole
 * character: she keeps it while she is measuring, and she spends it the
 * instant somebody commits.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const STEEL = "#e4eaf1";
const COAT = "#3b2a46";
const LACE = "#f2ece0";
const GOLD = "#c9a24a";

const STANCE = {
  torso: 2,
  head: -2,
  // Side-on, weight back, front foot pointed - a fencing guard, not a stance.
  hipF: 30,
  kneeF: 16,
  hipB: -34,
  kneeB: 44,
  shoulderF: 78,
  elbowF: 22,
  weapon: 4,
  shoulderB: -26,
  elbowB: 62,
  crouch: 0.14,
};

const IDLE_ARMS = { shoulderF: 78, elbowF: 22, weapon: 4, shoulderB: -26, elbowB: 62 };

export const DUELIST: FighterDef = {
  id: "duelist",
  name: "Julie d'Aubigny",
  title: "La Maupin",
  era: "Paris and the provinces, 1690s",
  bio: "Taught to fence as a child among the pages at Versailles, then made a living on stage at the Paris Opéra and a reputation off it. She fought men who did not expect to be fought, was condemned for it, and was pardoned by Louis XIV more than once. The outline is documented; a good deal of what gets told about her is not, and the two have been travelling together for three hundred years.",
  archetype: "Counter / Footsies",
  difficulty: 5,
  strengths: ["Reaches further than anything that thin should", "The riposte turns their turn into hers", "Fastest recovery on the roster"],
  weaknesses: ["Almost nothing hurts without a counter behind it", "Lowest health in the game", "Loses the exchange outright if she guesses wrong"],
  winQuote: "You were fighting the sword. I was fighting you.",
  palette: {
    body: "#e8cdb4",
    outline: "#140f18",
    accent: "#a8447a",
    cloth: COAT,
    metal: STEEL,
    aura: "#f0a0c8",
  },
  stats: {
    health: 860,
    walkF: 3.5,
    walkB: 3.4,
    dashSpeed: 10.2,
    dashFrames: 12,
    backdashFrames: 15,
    jumpVel: 12.4,
    jumpFwd: 5.1,
    gravity: 0.63,
    weight: 1.0,
    airMoves: 1,
    doubleJump: false,
    airDash: false,
    width: 17,
    standHeight: 99,
    crouchHeight: 60,
    scale: 0.985,
  },
  stance: STANCE,
  clips: guardClips({
    high: { torso: -4, head: -6, shoulderF: 54, elbowF: 78, weapon: 74, shoulderB: -14, elbowB: 74, crouch: 0.1, hipF: 28, kneeF: 20, hipB: -32, kneeB: 46, offX: -3 },
    low: { torso: 6, head: -5, shoulderF: 58, elbowF: 72, weapon: 70, shoulderB: -8, elbowB: 70, hipF: 34, kneeF: 76, hipB: -24, kneeB: 88, offX: -3 },
  }),
  resource: {
    name: "Tempo",
    max: 3,
    start: 1,
    // Measured, not earned: it fills while she holds her distance.
    regen: 0.0075,
    regenIdleOnly: true,
    color: "#f0a0c8",
    pips: true,
  },
  props: [
    {
      id: "hair",
      attach: "head",
      parts: [
        { geo: "poly", size: [-11, -5, -10, 7, 0, 11, 10, 6, 11, -5], pos: [-1, 6], color: "#4a2d1e" },
        // Loose curls tied back off the collar.
        { geo: "disc", size: [5.5], pos: [-12, 1], color: "#5c3826", behind: true },
        { geo: "disc", size: [4.5], pos: [-15, -6], color: "#4a2d1e", behind: true },
        { geo: "disc", size: [3.5], pos: [-13, -13], color: "#5c3826", behind: true },
        { geo: "poly", size: [-3, 3, 3, 2.4, 2.4, -3, -3, -2.4], pos: [-10, 6], color: "#a8447a", z: 0.4 },
      ],
    },
    {
      id: "coat",
      attach: "torso",
      // Justaucorps: long coat, deep cuffs, lace at the throat.
      parts: [
        { geo: "poly", size: [-12, -16, 12, -16, 13, 6, 8, 16, -8, 16, -13, 6], pos: [0, 4], color: COAT },
        { geo: "poly", size: [-7, -10, 7, -10, 8, 4, 4, 10, -4, 10, -8, 4], pos: [0, 4], color: "#4c3859" },
        // Lace jabot at the throat, and the buttons down the front.
        { geo: "poly", size: [-5, 5, 5, 4, 4, -6, -5, -5], pos: [3, 13], color: LACE, z: 0.4 },
        { geo: "disc", size: [1.5], pos: [6, 6], color: GOLD, z: 0.3 },
        { geo: "disc", size: [1.5], pos: [6, 1], color: GOLD, z: 0.3 },
        { geo: "disc", size: [1.5], pos: [6, -4], color: GOLD, z: 0.3 },
        { geo: "box", size: [18, 2], pos: [0, -12], color: GOLD, z: 0.2 },
      ],
      cloth: {
        segments: 4,
        segmentLength: 12,
        width: 22,
        endWidth: 20,
        color: COAT,
        lining: "#a8447a",
        gravity: 0.44,
        stiffness: 0.44,
        drift: -0.34,
      },
    },
    {
      id: "sash",
      attach: "pelvis",
      parts: [
        { geo: "poly", size: [-12, 4, 12, 3.5, 12, -4, -12, -4.5], pos: [0, 1], color: "#8a2f58" },
        { geo: "box", size: [6, 5], pos: [3, 0], color: GOLD, z: 0.2 },
      ],
    },
    {
      id: "smallsword",
      attach: "handF",
      // A smallsword is almost nothing: a metre of triangular section, a shell
      // guard and a knuckle bow. It is drawn thin on purpose - the threat is
      // the point, and there is no edge worth showing.
      parts: [
        { geo: "poly", size: [0, 0, -84, 2.2, -92, 1.4, -92, -1.4, -84, -2.2], pos: [96, 0], color: STEEL },
        { geo: "box", size: [70, 0.9], pos: [46, 0.6], color: "#ffffff" },
        // Shell guard, knuckle bow and quillon.
        { geo: "disc", size: [5.5], pos: [9, 0], color: GOLD },
        { geo: "disc", size: [3.4], pos: [9, 0], color: "#8f7530", z: 0.1 },
        { geo: "poly", size: [-1.6, -9, 1.6, -9, 2.2, 0, 1.6, 9, -1.6, 9, -2.2, 0], pos: [8, 0], color: GOLD },
        { geo: "poly", size: [0, 0, 5, -4, 9, -9, 6, -11, 1, -6, -2, -1], pos: [4, -6], color: GOLD },
        { geo: "box", size: [12, 4.4], pos: [-1, 0], color: "#3a2a1e" },
        { geo: "box", size: [12, 1.2], pos: [-1, 1.2], color: GOLD },
        { geo: "disc", size: [3], pos: [-9, 0], color: GOLD },
      ],
    },
    {
      id: "dagger",
      attach: "handB",
      conditional: true,
      // Left-hand dagger, for the parries she does not want to make with the
      // sword. Only out when she is using it.
      parts: [
        { geo: "poly", size: [0, 0, -26, 3, -30, 2, -30, -2, -26, -3], pos: [32, 0], color: "#dce3ea" },
        { geo: "poly", size: [-1.4, -7, 1.4, -7, 2, 0, 1.4, 7, -1.4, 7, -2, 0], pos: [5, 0], color: GOLD },
        { geo: "box", size: [9, 3.6], pos: [-1, 0], color: "#3a2a1e" },
        { geo: "disc", size: [2.2], pos: [-7, 0], color: GOLD },
      ],
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 108,
      backThrowDamage: 124,
      throwRange: 52,
      rollSpeed: 9.4,
      weaponIdle: IDLE_ARMS,
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Straight Thrust",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 11,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [3, 10],
      followUps: [{ button: "A", move: "6A", from: 3, to: 9, string: "Phrase" }],
      hits: [hit(3, 5, bx(28, 54, 62, 14), 22, { fx: "pierce", hitstun: 13, blockstun: 9, pushX: 2 })],
      desc: "Arm only. Three frames, almost no damage, and it reaches past anything else that fast.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderF: 88, elbowF: -2, weapon: -4, torso: 6, offX: 4 }),
        kf(7, { ...STANCE, shoulderF: 82, elbowF: 14, weapon: 0, torso: 3 }, "inOut"),
        kf(11, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Disengage",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 19,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [7, 17],
      followUps: [{ button: "C", move: "6C", from: 7, to: 16, string: "Phrase" }],
      hits: [hit(7, 10, bx(30, 46, 74, 22), 44, { fx: "pierce", pushX: 3.6, hitstun: 17 })],
      desc: "Drops the point under their blade and comes back up the other side of it.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderF: 62, elbowF: 34, weapon: 34, torso: -4, offX: -2 }),
        kf(7, { ...STANCE, shoulderF: 94, elbowF: -6, weapon: -14, torso: 12, hipF: 40, kneeF: 8, offX: 8 }, "out"),
        kf(13, { ...STANCE, shoulderF: 84, elbowF: 12, weapon: -2, torso: 6, offX: 3 }, "inOut"),
        kf(19, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Lunge",
      input: { button: "C", stance: "stand" },
      tags: ["heavy"],
      duration: 30,
      vel: [{ at: 9, x: 5.4 }, { at: 20, x: 0 }],
      friction: 0.86,
      cancelInto: ["special", "super"],
      cancelWindow: [14, 26],
      hits: [
        hit(11, 15, bx(34, 44, 106, 22), 74, {
          fx: "pierce",
          pushX: 6,
          hitstun: 22,
          hitstop: 9,
          shake: 1.4,
        }),
      ],
      desc: "The whole body behind the point. Enormous reach, and she is stuck out there if it misses.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, crouch: 0.35, torso: -6, shoulderF: 56, elbowF: 40, weapon: 34, hipB: -40, kneeB: 56, offX: -4 }, "out"),
        // Front leg thrown out, back leg locked straight behind - the lunge.
        kf(11, { ...STANCE, torso: 14, shoulderF: 96, elbowF: -8, weapon: -12, hipF: 88, kneeF: 4, hipB: -52, kneeB: 2, crouch: 0.5, offX: 14 }, "out"),
        kf(18, { ...STANCE, torso: 10, shoulderF: 90, elbowF: 0, weapon: -6, hipF: 76, kneeF: 10, hipB: -46, kneeB: 8, crouch: 0.45, offX: 11 }),
        kf(24, { ...STANCE, torso: 2, shoulderF: 72, elbowF: 28, weapon: 16, crouch: 0.3, offX: 4 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Point",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 12,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 11],
      hits: [hit(4, 6, bx(24, 12, 56, 14), 20, { guard: "low", fx: "pierce", hitstun: 13, blockstun: 9, pushX: 2 })],
      desc: "Point dropped to the ankle without moving her feet.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 14, hipF: 34, kneeF: 76, hipB: -24, kneeB: 88 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 20, hipF: 34, kneeF: 76, hipB: -24, kneeB: 88, shoulderF: 54, elbowF: 0, weapon: -8, offX: 5 }),
        kf(8, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -24, kneeB: 88, shoulderF: 64, elbowF: 16 }, "inOut"),
        kf(12, { ...STANCE, crouch: 1, torso: 14, hipF: 34, kneeF: 76, hipB: -24, kneeB: 88 }),
      ],
    },
    {
      id: "2B",
      name: "Passata Sotto",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 22,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [9, 20],
      hits: [hit(8, 11, bx(28, 8, 80, 20), 46, { guard: "low", fx: "pierce", pushX: 3.4, hitstun: 17 })],
      desc: "Ducks under the line with a hand on the floor and thrusts from down there.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 14, hipF: 34, kneeF: 76, hipB: -24, kneeB: 88 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 6, hipF: 34, kneeF: 76, hipB: -24, kneeB: 88, shoulderF: 44, elbowF: 34, weapon: 30, shoulderB: -70, elbowB: 20 }),
        kf(8, { ...STANCE, crouch: 1, torso: 24, hipF: 52, kneeF: 78, hipB: -30, kneeB: 92, shoulderF: 62, elbowF: -6, weapon: -16, shoulderB: -96, elbowB: 6, offX: 8 }, "out"),
        kf(15, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 76, hipB: -24, kneeB: 88, shoulderF: 62, elbowF: 18 }, "inOut"),
        kf(22, { ...STANCE, crouch: 1, torso: 14, hipF: 34, kneeF: 76, hipB: -24, kneeB: 88 }),
      ],
    },
    {
      id: "2C",
      name: "Foot Cut",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 28,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 24],
      hits: [hit(10, 14, bx(22, 2, 84, 20), 64, { guard: "low", knockdown: "sweep", fx: "slash", pushX: 5 })],
      desc: "Sweeps the edge through both ankles. There is an edge on it after all, barely.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 14, hipF: 34, kneeF: 76, hipB: -24, kneeB: 88 }, "out"),
        kf(5, { ...STANCE, crouch: 1, torso: 20, hipF: 14, kneeF: 94, hipB: -34, kneeB: 100, offX: -2 }),
        kf(10, { ...STANCE, crouch: 1, torso: 26, spin: -6, hipF: 82, kneeF: 8, hipB: -38, kneeB: 104, shoulderF: 46, elbowF: -4, weapon: -22, offX: 7 }, "out"),
        kf(19, { ...STANCE, crouch: 1, torso: 18, hipF: 50, kneeF: 50, hipB: -28, kneeB: 94 }, "inOut"),
        kf(28, { ...STANCE, crouch: 1, torso: 14, hipF: 34, kneeF: 76, hipB: -24, kneeB: 88 }),
      ],
    },
    {
      id: "6B",
      name: "Coupé",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "overhead"],
      priority: 10,
      duration: 29,
      vel: [{ at: 5, x: 3.2 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [15, 26],
      hits: [hit(14, 18, bx(24, 36, 62, 40), 52, { guard: "overhead", fx: "pierce", pushX: 4.4, hitstun: 20 })],
      desc: "Lifts the point clear over their blade and comes down the far side. Blocked standing.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, crouch: 0.4, torso: 8, shoulderF: 44, elbowF: 52, weapon: 56 }),
        kf(10, { ...STANCE, free: 1, offY: 9, torso: -10, shoulderF: 20, elbowF: 74, weapon: 96, hipF: 90, kneeF: 18 }, "out"),
        kf(14, { ...STANCE, free: 1, offY: 3, torso: 22, shoulderF: 106, elbowF: -10, weapon: -26, hipF: 28, kneeF: 6, offX: 6 }, "out"),
        kf(21, { ...STANCE, offY: 0, torso: 10, hipF: 34, kneeF: 30 }, "inOut"),
        kf(29, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Rising Point",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 29,
      cancelInto: ["special", "super"],
      cancelWindow: [11, 25],
      hits: [hit(9, 13, bx(16, 40, 52, 76), 60, { launch: [1.8, 12.2], knockdown: "launch", fx: "pierce", hitstun: 26 })],
      desc: "Comes up under the chin off the back foot. Launches.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 26, kneeF: 46 }, "out"),
        kf(4, { ...STANCE, crouch: 0.8, torso: 12, shoulderF: 46, elbowF: 40, weapon: 40 }),
        kf(9, { ...STANCE, torso: -14, shoulderF: 152, elbowF: -12, weapon: -30, hipF: 18, kneeF: 12, offY: 4 }, "out"),
        kf(17, { ...STANCE, torso: -6, shoulderF: 118, elbowF: 6, weapon: -10 }),
        kf(23, { ...STANCE, torso: 0, shoulderF: 92, elbowF: 16, weapon: 4 }, "inOut"),
        kf(29, { ...STANCE }),
      ],
    },
    {
      id: "6A",
      name: "Advance Thrust",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 19,
      vel: [{ at: 2, x: 2.6 }],
      friction: 0.88,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [6, 17],
      followUps: [{ button: "A", move: "5A", from: 6, to: 16, string: "Phrase" }],
      hits: [hit(5, 7, bx(30, 52, 66, 16), 24, { guard: "high", fx: "pierce", pushX: 2.6, hitstun: 13, hitstop: 4 })],
      desc: "A step and a thrust in the same beat. The fastest way she closes a foot of ground.",
      notation: "→ + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(2, { ...STANCE, shoulderF: 64, elbowF: 30, weapon: 26, offX: -1 }, "out"),
        kf(5, { ...STANCE, shoulderF: 92, elbowF: -6, weapon: -10, torso: 8, hipF: 44, kneeF: 8, offX: 8 }, "out"),
        kf(11, { ...STANCE, shoulderF: 84, elbowF: 12, weapon: 0, torso: 4, offX: 4 }, "inOut"),
        kf(19, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Fleche",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 38,
      vel: [{ at: 7, x: 7.2 }, { at: 24, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [20, 34],
      hits: [hit(13, 17, bx(26, 30, 92, 44), 84, { guard: "mid", fx: "pierce", pushX: 16, hitstun: 24, hitstop: 11, knockdown: "wallbounce", shake: 2 })],
      desc: "Runs at them behind the point rather than stepping. Carries them into the wall.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, crouch: 0.4, torso: -8, shoulderF: 58, elbowF: 36, weapon: 32, hipB: -44, kneeB: 52, offX: -4 }, "out"),
        kf(13, { ...STANCE, free: 1, torso: 26, shoulderF: 98, elbowF: -10, weapon: -14, hipF: 70, kneeF: 10, hipB: -56, kneeB: 12, offY: 5, offX: 12 }, "out"),
        kf(22, { ...STANCE, torso: 16, shoulderF: 86, elbowF: 6, weapon: -2, hipF: 40, kneeF: 20, offX: 7 }),
        kf(30, { ...STANCE, torso: 4, shoulderF: 72, elbowF: 26, weapon: 14, offX: 3 }, "inOut"),
        kf(38, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Retreat Thrust",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 20,
      vel: [{ at: 1, x: -3 }],
      friction: 0.86,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [7, 18],
      hits: [hit(7, 9, bx(30, 48, 64, 20), 32, { guard: "mid", fx: "pierce", pushX: 5, hitstun: 15, hitstop: 5 })],
      desc: "Steps back and leaves the point exactly where their face was going to be.",
      notation: "← + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -8, shoulderF: 60, elbowF: 36, weapon: 30, hipB: -40, kneeB: 50, offX: -7 }, "out"),
        kf(7, { ...STANCE, torso: 0, shoulderF: 90, elbowF: -4, weapon: -8, hipF: 24, kneeF: 16, offX: -4 }, "out"),
        kf(13, { ...STANCE, torso: -2, shoulderF: 80, elbowF: 16, weapon: 4, offX: -5 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Rear Kick",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 28,
      vel: [{ at: 1, x: -3.4 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [15, 25],
      hits: [hit(11, 14, bx(22, 42, 56, 30), 50, { guard: "mid", fx: "blunt", pushX: 7, hitstun: 18, hitstop: 7 })],
      desc: "Not fencing at all: a boot, thrown because it works.",
      notation: "← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, hipF: 62, kneeF: 96, torso: -12, hipB: -34, kneeB: 46, offX: -8 }, "inOut"),
        kf(11, { ...STANCE, hipF: 92, kneeF: 10, hipB: -26, kneeB: 20, torso: -14, head: 6, offX: -4 }, "out"),
        kf(16, { ...STANCE, hipF: 86, kneeF: 14, torso: -12, offX: -6 }),
        kf(22, { ...STANCE, hipF: 42, kneeF: 50, torso: -2, offX: -4 }, "inOut"),
        kf(28, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Descending Point",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 42,
      cancelInto: ["special", "super"],
      cancelWindow: [25, 38],
      hits: [hit(19, 22, bx(18, 22, 58, 84), 88, { guard: "overhead", fx: "pierce", pushX: 8, hitstun: 28, hitstop: 12, knockdown: "hard", shake: 2.2 })],
      desc: "Takes the point high and drives it down over the guard. Blocked standing only.",
      notation: "← + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 30, elbowF: 66, weapon: 84, torso: -10, offX: -5 }, "inOut"),
        kf(14, { ...STANCE, shoulderF: 4, elbowF: 82, weapon: 112, torso: -20, hipB: -30, kneeB: 40, offY: 4, offX: -3 }, "out"),
        kf(19, { ...STANCE, shoulderF: 116, elbowF: -14, weapon: -40, torso: 30, hipF: 36, kneeF: 14, offX: 6 }, "out"),
        kf(26, { ...STANCE, shoulderF: 98, elbowF: -2, weapon: -18, torso: 22, offX: 4 }),
        kf(35, { ...STANCE, shoulderF: 78, elbowF: 18, weapon: 6, torso: 6 }, "inOut"),
        kf(42, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Point",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 16,
      airborne: true,
      landCancel: true,
      landRecovery: 2,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [4, 14],
      hits: [hit(4, 9, bx(24, 32, 58, 18), 24, { fx: "pierce", hitstun: 14, pushX: 2 })],
      desc: "Point stuck out in front of her on the way through.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 34, kneeF: 44, hipB: -24, kneeB: 44 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderF: 86, elbowF: -4, weapon: -6, torso: 10 }),
        kf(11, { ...STANCE, free: 1, shoulderF: 78, elbowF: 16, weapon: 4, torso: 4 }, "inOut"),
        kf(16, { ...STANCE, free: 1, hipF: 34, kneeF: 44, hipB: -24, kneeB: 44 }),
      ],
    },
    {
      id: "jB",
      name: "Air Cut",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 22,
      airborne: true,
      landCancel: true,
      landRecovery: 4,
      cancelInto: ["heavy", "special"],
      hits: [hit(6, 13, bx(20, 20, 62, 38), 48, { fx: "slash", pushX: 3.6, hitstun: 18 })],
      desc: "Cuts across underneath her in the air.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 32, kneeF: 42, hipB: -22, kneeB: 40 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderF: 34, elbowF: 54, weapon: 60, torso: -8 }),
        kf(7, { ...STANCE, free: 1, shoulderF: 92, elbowF: -6, weapon: -26, torso: 18, hipF: 38 }, "out"),
        kf(15, { ...STANCE, free: 1, shoulderF: 78, elbowF: 20, weapon: 6, torso: 6 }, "inOut"),
        kf(22, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "jC",
      name: "Falling Point",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 26,
      airborne: true,
      landCancel: true,
      landRecovery: 6,
      hits: [
        hit(7, 17, bx(10, 4, 52, 48), 70, {
          guard: "overhead",
          fx: "pierce",
          knockdown: "soft",
          pushX: 4.4,
          shake: 1.4,
        }),
      ],
      desc: "Point turned straight down and dropped on them. Her jump-in.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, torso: -16, shoulderF: 6, elbowF: 86, weapon: 108, hipF: 40, kneeF: 54 }),
        kf(8, { ...STANCE, free: 1, torso: 28, shoulderF: 100, elbowF: -14, weapon: -66, hipF: 14, kneeF: 16 }, "out"),
        kf(26, { ...STANCE, free: 1, torso: 22, shoulderF: 94, elbowF: -10, weapon: -62 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Running Thrust",
      input: { button: "C", dir: "f", stance: "stand", whileDashing: true },
      tags: ["command"],
      priority: 12,
      duration: 29,
      vel: [
        { at: 3, x: 11.5 },
        { at: 15, x: 0 },
      ],
      friction: 0.9,
      hits: [hit(6, 11, bx(28, 30, 76, 40), 62, { fx: "pierce", pushX: 6, knockdown: "soft", hitstun: 21, shake: 1.3 })],
      desc: "Closes the whole gap with the point already out.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 20, crouch: 0.35, shoulderF: 60, elbowF: 30, weapon: 26, offX: -2 }),
        kf(6, { ...STANCE, torso: 26, crouch: 0.3, shoulderF: 96, elbowF: -10, weapon: -14, hipF: 48, kneeF: 14, offX: 9 }, "out"),
        kf(19, { ...STANCE, torso: 12, shoulderF: 78, elbowF: 20, weapon: 6, offX: 3 }, "inOut"),
        kf(29, { ...STANCE }),
      ],
    },

    // -------------------------------------------------------- five specials
    {
      id: "riposte",
      name: "Parry Riposte",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 28,
      duration: 34,
      parryWindow: [2, 11],
      friction: 0.8,
      resourceGain: 1,
      // The counter lands whether or not the parry caught anything, but it is
      // the parry window that makes it worth pressing.
      hits: [hit(14, 18, bx(30, 44, 96, 24), 92, { fx: "pierce", pushX: 7, hitstun: 26, hitstop: 12, knockdown: "soft", shake: 1.7 })],
      desc: "Turns their blade aside and answers down the same line. The parry is the read; the thrust is what it is worth. Pays a Tempo back.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        // Small, tight, sideways - a parry is a wrist, not a swing.
        kf(2, { ...STANCE, shoulderF: 68, elbowF: 40, weapon: 52, torso: -4, offX: -2 }, "out"),
        kf(9, { ...STANCE, shoulderF: 58, elbowF: 52, weapon: 66, torso: -8, offX: -4 }, "inOut"),
        kf(14, { ...STANCE, shoulderF: 96, elbowF: -10, weapon: -16, torso: 16, hipF: 68, kneeF: 6, hipB: -48, kneeB: 6, crouch: 0.42, offX: 12 }, "out"),
        kf(22, { ...STANCE, shoulderF: 86, elbowF: 6, weapon: -2, torso: 8, crouch: 0.3, offX: 6 }),
        kf(34, { ...STANCE }),
      ],
    },
    {
      id: "inQuartata",
      name: "In Quartata",
      input: { button: "A", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "movement"],
      priority: 24,
      duration: 26,
      resourceCost: 1,
      resourceMin: 1,
      // Turning the body off the line is the oldest answer in fencing to
      // something coming straight at you.
      invuln: [{ from: 3, to: 14, kind: "strike" }],
      vel: [{ at: 3, x: -5 }, { at: 14, x: 0 }],
      friction: 0.86,
      hits: [hit(9, 12, bx(26, 46, 72, 22), 46, { fx: "pierce", pushX: 4, hitstun: 18, hitstop: 7 })],
      desc: "Turns her hips out of the line, lets it go past, and thrusts from where she now is. Costs a Tempo.",
      notation: "↓↙← + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, spin: -14, torso: -14, shoulderF: 70, elbowF: 30, weapon: 26, hipF: 20, kneeF: 30, hipB: -46, kneeB: 48, offX: -6 }, "out"),
        kf(9, { ...STANCE, spin: -20, torso: -6, shoulderF: 94, elbowF: -8, weapon: -12, hipF: 30, kneeF: 22, hipB: -40, kneeB: 40, offX: -3 }, "out"),
        kf(17, { ...STANCE, spin: -8, torso: 0, shoulderF: 80, elbowF: 14, weapon: 2, offX: -2 }, "inOut"),
        kf(26, { ...STANCE }),
      ],
    },
    {
      id: "flurry",
      name: "Phrase d'Armes",
      input: { button: "C", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 22,
      duration: 42,
      vel: [{ at: 4, x: 3 }, { at: 12, x: 2.4 }, { at: 22, x: 2.4 }, { at: 32, x: 0 }],
      friction: 0.9,
      hits: [
        hit(7, 9, bx(30, 50, 78, 18), 34, { group: 1, fx: "pierce", pushX: 1.4, hitstun: 15, hitstop: 4 }),
        hit(16, 18, bx(30, 40, 82, 18), 32, { group: 2, fx: "pierce", pushX: 1.4, hitstun: 15, hitstop: 4 }),
        hit(26, 30, bx(32, 44, 96, 22), 62, {
          group: 3,
          fx: "pierce",
          pushX: 8,
          knockdown: "soft",
          hitstun: 24,
          hitstop: 10,
          shake: 1.5,
        }),
      ],
      desc: "Three thrusts walking forward, high, low, and then the one that means it.",
      notation: "↓↘→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 62, elbowF: 30, weapon: 26, torso: -4, offX: -2 }, "out"),
        kf(7, { ...STANCE, shoulderF: 92, elbowF: -6, weapon: -10, torso: 10, hipF: 42, kneeF: 10, offX: 6 }, "out"),
        kf(13, { ...STANCE, shoulderF: 60, elbowF: 32, weapon: 30, torso: 2, offX: 3 }, "inOut"),
        kf(16, { ...STANCE, shoulderF: 74, elbowF: -6, weapon: -18, torso: 16, hipF: 46, kneeF: 12, offX: 7 }, "out"),
        kf(22, { ...STANCE, shoulderF: 56, elbowF: 38, weapon: 36, torso: -6, crouch: 0.35, offX: 2 }, "inOut"),
        kf(26, { ...STANCE, shoulderF: 98, elbowF: -12, weapon: -18, torso: 18, hipF: 82, kneeF: 4, hipB: -50, kneeB: 4, crouch: 0.48, offX: 13 }, "out"),
        kf(34, { ...STANCE, shoulderF: 82, elbowF: 10, weapon: 0, torso: 8, crouch: 0.3, offX: 5 }, "inOut"),
        kf(42, { ...STANCE }),
      ],
    },
    {
      id: "leftHand",
      name: "Left-Hand Dagger",
      // One button, not A+B: the universal throw already owns A+B at priority
      // 60, so a two-button special here would simply never come out.
      input: { button: "C", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 30,
      duration: 30,
      showProps: ["dagger"],
      parryWindow: [2, 8],
      friction: 0.82,
      resourceGain: 1,
      hits: [
        hit(11, 14, bx(12, 46, 46, 30), 54, { group: 1, fx: "pierce", pushX: 2, hitstun: 20, hitstop: 8 }),
        hit(15, 19, bx(28, 44, 82, 22), 66, {
          group: 2,
          fx: "pierce",
          pushX: 8,
          knockdown: "hard",
          hitstun: 26,
          hitstop: 11,
          shake: 1.8,
        }),
      ],
      desc: "Catches the blade on the dagger and answers with the sword, which is what the off hand was always for. Works at a range the riposte cannot.",
      notation: "↓↙← + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(2, { ...STANCE, shoulderB: 42, elbowB: 34, weaponBack: 20, shoulderF: 66, elbowF: 42, weapon: 44, torso: -6, offX: -3 }, "out"),
        kf(8, { ...STANCE, shoulderB: 62, elbowB: 12, weaponBack: -4, shoulderF: 58, elbowF: 52, weapon: 58, torso: -10, offX: -4 }, "inOut"),
        kf(11, { ...STANCE, shoulderB: 88, elbowB: -6, weaponBack: -22, shoulderF: 62, elbowF: 40, torso: 18, hipF: 40, offX: 6 }, "out"),
        kf(15, { ...STANCE, shoulderB: 64, elbowB: 16, shoulderF: 98, elbowF: -12, weapon: -18, torso: 22, hipF: 72, kneeF: 6, hipB: -48, kneeB: 6, crouch: 0.44, offX: 12 }, "out"),
        kf(23, { ...STANCE, shoulderF: 84, elbowF: 8, weapon: -2, torso: 8, crouch: 0.28, offX: 6 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "salute",
      name: "Appel",
      input: { button: "B", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 26,
      duration: 24,
      resourceGain: 1,
      meterGain: 18,
      vel: [{ at: 4, x: 1.6 }, { at: 12, x: 0 }],
      friction: 0.88,
      // Invulnerable to nothing. This move is a threat, not an escape.
      hits: [hit(8, 10, bx(24, 52, 56, 18), 30, { fx: "pierce", pushX: 3, hitstun: 22, hitstop: 8, meterGain: 14 })],
      desc: "Stamps the front foot and puts the point in their face - the oldest way to ask a question in fencing. Barely hurts, holds them still, and buys Tempo and meter.",
      notation: "→↓↘ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, crouch: 0.4, torso: 6, hipF: 54, kneeF: 34, shoulderF: 66, elbowF: 30, weapon: 26, offX: 2 }, "out"),
        kf(8, { ...STANCE, crouch: 0.2, torso: 12, hipF: 30, kneeF: 10, shoulderF: 94, elbowF: -8, weapon: -12, offX: 6 }, "out"),
        kf(15, { ...STANCE, torso: 4, shoulderF: 82, elbowF: 12, weapon: 2, offX: 3 }, "inOut"),
        kf(24, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- skill
    {
      id: "measure",
      name: "Measure",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill"],
      priority: 18,
      duration: 26,
      friction: 0.78,
      resourceGain: 1,
      vfx: [{ at: 3, kind: "spark", x: 40, y: 56, scale: 0.8, color: "#f0a0c8" }],
      desc: "SKILL. Takes the distance and holds it - a beat spent finding out where they are rather than hitting them. Fills a Tempo outright.",
      notation: "A + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -6, shoulderF: 84, elbowF: 8, weapon: 2, hipF: 34, kneeF: 12, hipB: -40, kneeB: 50, crouch: 0.26, offX: -3 }, "out"),
        kf(12, { ...STANCE, torso: -4, shoulderF: 88, elbowF: 2, weapon: -2, crouch: 0.22, offX: -2 }),
        kf(20, { ...STANCE, torso: 0, shoulderF: 80, elbowF: 16, weapon: 4 }, "inOut"),
        kf(26, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "Botte Secrète",
      input: { button: "S", motion: "dd", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 100,
      meterCost: 100,
      superFreeze: 40,
      invuln: [{ from: 1, to: 16, kind: "full" }],
      vel: [
        { at: 8, x: 11 },
        { at: 26, x: 7 },
        { at: 44, x: 7 },
        { at: 62, x: 9 },
        { at: 78, x: 0 },
      ],
      friction: 0.9,
      hits: [
        hit(13, 16, bx(30, 50, 84, 18), 40, { group: 1, fx: "pierce", pushX: 0.8, hitstun: 19, hitstop: 4 }),
        hit(24, 27, bx(30, 38, 86, 18), 36, { group: 2, fx: "pierce", pushX: 0.8, hitstun: 18, hitstop: 4 }),
        hit(35, 38, bx(30, 24, 88, 18), 36, { group: 3, guard: "low", fx: "pierce", pushX: 0.8, hitstun: 18, hitstop: 4 }),
        hit(46, 49, bx(30, 46, 88, 18), 36, { group: 4, fx: "pierce", pushX: 0.8, hitstun: 18, hitstop: 4 }),
        // The secret thrust: the one nobody has an answer to, because nobody
        // has seen it. Every fencing master in the period claimed one.
        hit(62, 68, bx(28, 34, 122, 30), 142, {
          group: 5,
          fx: "pierce",
          pushX: 11,
          knockdown: "hard",
          launch: [5.5, 8],
          hitstop: 18,
          shake: 2.9,
        }),
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 50, scale: 2.3, color: "#f0a0c8" },
        { at: 62, kind: "spark", x: 74, y: 48, scale: 1.6, color: "#ffffff" },
      ],
      desc: "SUPER. Four thrusts to find out where their hands are, and one that goes through the gap they left.",
      notation: "↓↓ + S (100 meter)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.4, torso: -8 }, "out"),
        kf(8, { ...STANCE, shoulderF: 62, elbowF: 30, weapon: 26, torso: -6, offX: -2 }, "out"),
        kf(13, { ...STANCE, shoulderF: 94, elbowF: -8, weapon: -12, torso: 10, hipF: 48, kneeF: 8, offX: 8 }, "out"),
        kf(20, { ...STANCE, shoulderF: 60, elbowF: 34, weapon: 32, torso: -2 }, "inOut"),
        kf(24, { ...STANCE, shoulderF: 86, elbowF: -6, weapon: -14, torso: 14, hipF: 46, offX: 7 }, "out"),
        kf(31, { ...STANCE, shoulderF: 58, elbowF: 36, weapon: 34, torso: 0, crouch: 0.3 }, "inOut"),
        kf(35, { ...STANCE, shoulderF: 58, elbowF: -8, weapon: -22, torso: 20, crouch: 0.5, hipF: 60, kneeF: 20, offX: 8 }, "out"),
        kf(42, { ...STANCE, shoulderF: 62, elbowF: 32, weapon: 30, torso: -2, crouch: 0.2 }, "inOut"),
        kf(46, { ...STANCE, shoulderF: 92, elbowF: -6, weapon: -12, torso: 12, hipF: 46, offX: 7 }, "out"),
        kf(55, { ...STANCE, crouch: 0.5, torso: -14, shoulderF: 50, elbowF: 46, weapon: 44, hipB: -50, kneeB: 56, offX: -6 }, "inOut"),
        // Everything into one line.
        kf(62, { ...STANCE, torso: 20, shoulderF: 98, elbowF: -12, weapon: -16, hipF: 96, kneeF: 2, hipB: -56, kneeB: 0, crouch: 0.56, offX: 18 }, "out"),
        kf(78, { ...STANCE, torso: 12, shoulderF: 88, elbowF: 2, weapon: -4, crouch: 0.4, offX: 9 }),
        kf(100, { ...STANCE }),
      ],
    },
  ],
};
