/**
 * Ras Alula Engida - Mereb Melash.
 *
 * The shotel is the only weapon on this roster designed around a specific
 * problem: the other man's shield. It is curved far past what a sword needs
 * to cut, because the point of that curve is to travel round the edge of a
 * shield and take the man behind it. So that is what it does here - his hook
 * is the roster's answer to somebody who will not stop blocking, and it is
 * the only normal-speed move in the game that a guard does not solve.
 *
 * He is not only a swordsman, though, and pretending otherwise would be the
 * wrong century. Dogali was won by men with rifles. The Remington gives him a
 * real answer at range, which is also the only reason a fighter built this
 * close-in is not simply food for the zoners.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const STEEL = "#d2d8de";
const HIDE = "#8a6438";
const CLOTH = "#efe9dc";
const GOLD = "#c9a03c";
const GREEN = "#2f7a4a";

const STANCE = {
  torso: 6,
  head: -2,
  hipF: 18,
  kneeF: 24,
  hipB: -20,
  kneeB: 32,
  // Shotel carried high and cocked back - the curve wants to come over the
  // top of a guard, so it is never held out in front like a straight sword.
  shoulderF: 40,
  elbowF: 74,
  shoulderB: 118,
  elbowB: 52,
  weaponBack: 62,
  crouch: 0.16,
};

const IDLE_ARMS = { shoulderB: 118, elbowB: 52, weaponBack: 62 };

export const ETHIOPIA: FighterDef = {
  id: "ethiopia",
  name: "Ras Alula Engida",
  title: "Ras of Mereb Melash",
  era: "Dogali, 1887",
  bio: "Born to a peasant family in Tigray and made a Ras on the strength of what he could do in the field. He beat the Egyptians at Gura, and at Dogali he destroyed an Italian column outright - the defeat that stopped Italy's first attempt on Ethiopia and got him called the Garibaldi of his country by people who meant it as a compliment.",
  archetype: "Punisher / Guard Break",
  difficulty: 4,
  strengths: ["The shotel goes round a shield, not through it", "One rifle answer so zoners cannot sit on him", "Punishes anyone who blocks and waits"],
  weaknesses: ["Cartridges are finite and slow to replace", "Nothing quick enough to check a rushdown", "The hook is committal - whiffing it is a free turn for them"],
  winQuote: "You held the shield exactly where I needed it.",
  palette: {
    body: "#8a5a34",
    outline: "#130d09",
    accent: GREEN,
    cloth: CLOTH,
    metal: STEEL,
    aura: "#f0d26a",
  },
  stats: {
    health: 1030,
    walkF: 3.05,
    walkB: 2.75,
    dashSpeed: 8.9,
    dashFrames: 14,
    backdashFrames: 18,
    jumpVel: 12.2,
    jumpFwd: 4.9,
    gravity: 0.63,
    weight: 1.05,
    airMoves: 1,
    doubleJump: false,
    airDash: false,
    width: 19,
    standHeight: 101,
    crouchHeight: 61,
    scale: 1.0,
  },
  stance: STANCE,
  clips: guardClips({
    high: { torso: 0, head: -6, shoulderF: 26, elbowF: 118, shoulderB: 96, elbowB: 78, weaponBack: 96, crouch: 0.1, hipF: 18, kneeF: 26, hipB: -20, kneeB: 34, offX: -2 },
    low: { torso: 8, head: -5, shoulderF: 32, elbowF: 110, shoulderB: 88, elbowB: 72, weaponBack: 92, hipF: 34, kneeF: 78, hipB: -22, kneeB: 88, offX: -2 },
  }),
  resource: {
    name: "Cartridges",
    max: 4,
    start: 4,
    regen: 0,
    color: "#c9a03c",
    pips: true,
  },
  props: [
    {
      id: "hair",
      attach: "head",
      // Plaited hair worn back off the face, the way he is photographed.
      parts: [
        { geo: "poly", size: [-10, -5, -9, 6, 0, 10, 9, 5, 10, -5], pos: [-1, 6], color: "#1a120c" },
        { geo: "poly", size: [-8, 4, 2, 6, 3, -6, -7, -5], pos: [-10, 2], color: "#221812", behind: true },
        { geo: "box", size: [16, 1.6], pos: [-2, 9], color: "#3a2a1e", z: 0.3 },
        { geo: "box", size: [16, 1.6], pos: [-2, 5], color: "#3a2a1e", z: 0.3 },
      ],
    },
    {
      id: "shamma",
      attach: "torso",
      // The shamma: white cotton with a woven border, worn over the shoulder.
      parts: [
        { geo: "poly", size: [-13, -16, 13, -16, 14, 6, 9, 16, -9, 16, -14, 6], pos: [0, 4], color: CLOTH },
        { geo: "poly", size: [-4, 19, 4, 19, 4, -19, -4, -19], pos: [-3, 4], rot: 13, color: "#e2dac8" },
        // Tibeb: the coloured band along the edge.
        { geo: "box", size: [4, 38], pos: [4, 4], rot: 13, color: GREEN, z: 0.3 },
        { geo: "box", size: [1.6, 38], pos: [6.5, 4], rot: 13, color: GOLD, z: 0.35 },
        { geo: "box", size: [20, 2], pos: [0, -11], color: GOLD, z: 0.2 },
      ],
      cloth: {
        segments: 4,
        segmentLength: 11,
        width: 22,
        endWidth: 15,
        color: CLOTH,
        lining: "#d8cfb8",
        gravity: 0.38,
        stiffness: 0.46,
        drift: -0.3,
      },
    },
    {
      id: "belt",
      attach: "pelvis",
      parts: [
        { geo: "poly", size: [-13, 4, 13, 3.5, 13, -4, -13, -4.5], pos: [0, 1], color: "#4a3520" },
        { geo: "box", size: [7, 6], pos: [2, 0], color: GOLD, z: 0.2 },
        // Cartridge loops along the belt - the reason the rifle is finite.
        { geo: "box", size: [2.6, 7], pos: [-10, -1], color: "#c9a03c" },
        { geo: "box", size: [2.6, 7], pos: [-6, -1], color: "#c9a03c" },
        { geo: "box", size: [2.6, 7], pos: [10, -1], color: "#c9a03c" },
      ],
    },
    {
      id: "shotel",
      attach: "handB",
      // The curve is the weapon. Drawn as a deep sickle so the point ends up
      // pointing back at his own hand, which is what lets it reach round.
      parts: [
        { geo: "box", size: [16, 6], pos: [-2, 0], color: "#4a3520" },
        { geo: "box", size: [16, 1.8], pos: [-2, 1.8], color: "#6b4d2c" },
        { geo: "disc", size: [3.4], pos: [-11, 0], color: GOLD },
        { geo: "box", size: [4, 14], pos: [7, 0], color: GOLD },
        // Blade: out, up and back over, ending with the point turned inward.
        { geo: "poly", size: [
            0, -3, 16, 2, 30, 12, 38, 26, 36, 40, 28, 48,
            24, 44, 31, 36, 32, 25, 25, 14, 13, 6, 0, 3,
          ], pos: [10, 0], color: STEEL },
        // The inside edge, which is the one that does the work.
        { geo: "poly", size: [0, 0, 14, 4, 26, 13, 32, 26, 30, 38, 26, 43, 24, 39, 28, 30, 28, 20, 21, 11, 11, 4],
          pos: [11, 1], color: "#f2f6fa" },
      ],
    },
    {
      id: "gasha",
      attach: "forearmF",
      // Round hide shield with a raised boss and brass mounts.
      parts: [
        { geo: "disc", size: [24], pos: [13, 0], color: "#6b4a28", z: 0.5 },
        { geo: "ring", size: [24, 3.4], pos: [13, 0], color: GOLD, z: 0.55 },
        { geo: "disc", size: [19], pos: [13, 0], color: HIDE, z: 0.6 },
        { geo: "ring", size: [12, 1.8], pos: [13, 0], color: "#a5793f", z: 0.66 },
        { geo: "disc", size: [6.5], pos: [13, 0], color: "#5c3f21", z: 0.7 },
        { geo: "disc", size: [3.4], pos: [13, 0], color: GOLD, z: 0.74 },
        { geo: "disc", size: [1.8], pos: [13, 17], color: GOLD, z: 0.78 },
        { geo: "disc", size: [1.8], pos: [13, -17], color: GOLD, z: 0.78 },
        { geo: "disc", size: [1.8], pos: [30, 0], color: GOLD, z: 0.78 },
      ],
    },
    {
      id: "rifle",
      attach: "handF",
      conditional: true,
      // Remington rolling block: the rifle that armed his infantry.
      parts: [
        { geo: "box", size: [64, 3.4], pos: [30, 3], color: "#5b6067" },
        { geo: "box", size: [30, 5], pos: [10, 0], color: "#6b4a2c" },
        { geo: "poly", size: [-11, 5, 6, 4, 9, -6, -12, -7], pos: [-14, -1], color: "#6b4a2c" },
        { geo: "poly", size: [-4, 5, 5, 4, 4, -5, -5, -4], pos: [2, -1], color: "#4a4f57" },
        { geo: "box", size: [3, 5], pos: [6, -4], color: "#3f444b" },
        { geo: "box", size: [8, 2], pos: [24, 0], color: GOLD },
        { geo: "box", size: [2, 3], pos: [58, 5], color: "#8f97a1" },
      ],
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 126,
      backThrowDamage: 138,
      throwRange: 58,
      rollSpeed: 7.8,
      weaponIdle: IDLE_ARMS,
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Rim Jab",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 12,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 11],
      followUps: [{ button: "B", move: "5B", from: 4, to: 10, string: "Shield and Steel" }],
      hits: [hit(4, 6, bx(16, 52, 44, 22), 26, { fx: "blunt", hitstun: 14, blockstun: 10, pushX: 2.4 })],
      desc: "Punches the shield edge out to buy the half-second the shotel needs.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 88, elbowF: 12, torso: 12, offX: 4 }),
        kf(8, { ...STANCE, shoulderF: 62, elbowF: 48, torso: 8 }, "inOut"),
        kf(12, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Overhand Cut",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 21,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [8, 19],
      followUps: [{ button: "C", move: "6C", from: 8, to: 18, string: "Shield and Steel" }],
      hits: [hit(8, 11, bx(20, 46, 58, 34), 52, { fx: "slash", pushX: 4.2, hitstun: 18 })],
      desc: "The curve brought over the top rather than swung across.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderB: 160, elbowB: 22, weaponBack: 96, torso: -10, offX: -3 }),
        kf(8, { ...STANCE, shoulderB: 78, elbowB: 12, weaponBack: 4, torso: 22, hipF: 28, offX: 6 }, "out"),
        kf(14, { ...STANCE, shoulderB: 104, elbowB: 34, weaponBack: 34, torso: 12 }, "inOut"),
        kf(21, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Round the Guard",
      input: { button: "C", stance: "stand" },
      tags: ["heavy"],
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [15, 28],
      hits: [
        // The whole identity of the weapon: it goes round a shield, so a
        // standing block does not answer it.
        hit(15, 19, bx(18, 40, 62, 44), 78, {
          guard: "unblockable",
          fx: "slash",
          pushX: 7,
          knockdown: "soft",
          hitstun: 24,
          shake: 1.9,
        }),
      ],
      desc: "Hooks the point round the outside of their guard. Slow, obvious, and blocking does not stop it.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderB: 168, elbowB: 34, weaponBack: 110, torso: -16, hipB: -30, kneeB: 46, offX: -5 }, "inOut"),
        kf(15, { ...STANCE, shoulderB: 52, elbowB: -14, weaponBack: -46, torso: 30, hipF: 40, kneeF: 22, offX: 9 }, "out"),
        kf(24, { ...STANCE, shoulderB: 84, elbowB: 14, weaponBack: -4, torso: 18, offX: 4 }),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Cut",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 13,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 12],
      hits: [hit(4, 6, bx(14, 12, 42, 18), 24, { guard: "low", fx: "slash", hitstun: 13, blockstun: 10, pushX: 2.2 })],
      desc: "Quick draw of the point across the shin.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 78, hipB: -22, kneeB: 88 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 24, hipF: 34, kneeF: 78, hipB: -22, kneeB: 88, shoulderB: 62, elbowB: 20, weaponBack: -12, offX: 4 }),
        kf(9, { ...STANCE, crouch: 1, torso: 20, hipF: 34, kneeF: 78, hipB: -22, kneeB: 88, shoulderB: 92, elbowB: 42, weaponBack: 22 }, "inOut"),
        kf(13, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 78, hipB: -22, kneeB: 88 }),
      ],
    },
    {
      id: "2B",
      name: "Hamstring",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 22,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [9, 20],
      hits: [hit(8, 11, bx(18, 6, 64, 24), 50, { guard: "low", fx: "slash", pushX: 3.8, hitstun: 17 })],
      desc: "The inside of the curve dragged through the back of the leg.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 78, hipB: -22, kneeB: 88 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 10, hipF: 34, kneeF: 78, hipB: -22, kneeB: 88, shoulderB: 12, elbowB: 84, weaponBack: 76 }),
        kf(8, { ...STANCE, crouch: 1, torso: 28, hipF: 42, kneeF: 82, hipB: -22, kneeB: 88, shoulderB: 54, elbowB: 6, weaponBack: -34, offX: 6 }, "out"),
        kf(15, { ...STANCE, crouch: 1, torso: 20, hipF: 34, kneeF: 78, hipB: -22, kneeB: 88, shoulderB: 84, elbowB: 40, weaponBack: 14 }, "inOut"),
        kf(22, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 78, hipB: -22, kneeB: 88 }),
      ],
    },
    {
      id: "2C",
      name: "Ankle Hook",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 29,
      cancelInto: ["special", "super"],
      cancelWindow: [13, 25],
      hits: [hit(11, 15, bx(16, 2, 76, 22), 70, { guard: "low", knockdown: "sweep", fx: "slash", pushX: 5.2 })],
      desc: "Puts the hook behind the ankle and takes the leg out from under them.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 78, hipB: -22, kneeB: 88 }, "out"),
        kf(5, { ...STANCE, crouch: 1, torso: 24, hipF: 12, kneeF: 96, hipB: -34, kneeB: 100, offX: -2 }),
        kf(11, { ...STANCE, crouch: 1, torso: 30, spin: -8, hipF: 86, kneeF: 6, hipB: -38, kneeB: 104, shoulderB: 40, elbowB: 10, weaponBack: -40, offX: 6 }, "out"),
        kf(20, { ...STANCE, crouch: 1, torso: 22, hipF: 50, kneeF: 52, hipB: -28, kneeB: 94 }, "inOut"),
        kf(29, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 78, hipB: -22, kneeB: 88 }),
      ],
    },
    {
      id: "6B",
      name: "Shield Rise",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "overhead"],
      priority: 10,
      duration: 31,
      vel: [{ at: 6, x: 2.9 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [17, 28],
      hits: [hit(16, 20, bx(18, 34, 56, 44), 56, { guard: "overhead", fx: "blunt", pushX: 4.6, hitstun: 20 })],
      desc: "Steps in and brings the shield rim down over the top. Blocked standing only.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, crouch: 0.5, torso: 14, shoulderF: 20, elbowF: 96 }),
        kf(12, { ...STANCE, free: 1, offY: 11, torso: -14, shoulderF: 168, elbowF: 20, hipF: 104, kneeF: 16 }, "out"),
        kf(16, { ...STANCE, free: 1, offY: 3, torso: 30, shoulderF: 84, elbowF: 8, hipF: 30, kneeF: 6, offX: 5 }, "out"),
        kf(23, { ...STANCE, offY: 0, torso: 14, hipF: 34, kneeF: 40 }, "inOut"),
        kf(31, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Rising Hook",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 31,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 27],
      hits: [hit(10, 14, bx(14, 40, 54, 76), 66, { launch: [2, 12], knockdown: "launch", fx: "slash", hitstun: 26 })],
      desc: "The point brought up under the chin. Launches.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 52 }, "out"),
        kf(5, { ...STANCE, crouch: 0.8, torso: 16, shoulderB: 8, elbowB: 82, weaponBack: 78 }),
        kf(10, { ...STANCE, torso: -16, shoulderB: 172, elbowB: 4, weaponBack: -30, hipF: 20, kneeF: 14, offY: 4 }, "out"),
        kf(19, { ...STANCE, torso: -6, shoulderB: 128, elbowB: 30, weaponBack: 6 }),
        kf(25, { ...STANCE, torso: 2, shoulderB: 100, elbowB: 46, weaponBack: 40 }, "inOut"),
        kf(31, { ...STANCE }),
      ],
    },
    {
      id: "6A",
      name: "Advancing Cut",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 21,
      vel: [{ at: 2, x: 2.2 }],
      friction: 0.88,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [7, 19],
      hits: [hit(7, 9, bx(20, 52, 48, 26), 28, { guard: "high", fx: "slash", pushX: 3, hitstun: 13, hitstop: 5 })],
      desc: "Steps in and flicks the curve across at head height.",
      notation: "→ + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderB: 148, elbowB: 40, weaponBack: 88, torso: -2, offX: -2 }, "out"),
        kf(7, { ...STANCE, shoulderB: 86, elbowB: 6, weaponBack: 2, torso: 16, hipF: 26, offX: 8 }, "out"),
        kf(13, { ...STANCE, shoulderB: 108, elbowB: 30, weaponBack: 30, torso: 10, offX: 5 }, "inOut"),
        kf(21, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Charging Hook",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 41,
      armor: [{ from: 8, to: 18, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 8, x: 5.2 }, { at: 26, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [21, 37],
      hits: [hit(16, 20, bx(18, 22, 66, 68), 90, { guard: "mid", fx: "slash", pushX: 17, hitstun: 24, hitstop: 12, knockdown: "wallbounce", shake: 2.2 })],
      desc: "Behind the shield until he is in, then the curve comes over. Puts them in the wall.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 22, elbowF: 96, shoulderB: 158, elbowB: 34, weaponBack: 104, torso: -14, hipB: -30, kneeB: 48, offX: -6 }, "out"),
        kf(16, { ...STANCE, shoulderB: 62, elbowB: -6, weaponBack: -34, torso: 32, hipF: 42, kneeF: 20, hipB: -26, kneeB: 26, offX: 12 }, "out"),
        kf(25, { ...STANCE, shoulderB: 88, elbowB: 16, weaponBack: -2, torso: 24, offX: 8 }),
        kf(33, { ...STANCE, shoulderB: 108, elbowB: 40, weaponBack: 36, torso: 10, offX: 3 }, "inOut"),
        kf(41, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Rim Rake",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 23,
      vel: [{ at: 1, x: -2.6 }],
      friction: 0.86,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [9, 21],
      hits: [hit(9, 11, bx(16, 48, 44, 30), 36, { guard: "mid", fx: "blunt", pushX: 6, hitstun: 15, hitstop: 6 })],
      desc: "Gives ground and drags the shield edge across on the way out.",
      notation: "← + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -6, shoulderF: 16, elbowF: 106, hipB: -26, kneeB: 40, offX: -6 }, "out"),
        kf(9, { ...STANCE, torso: 8, shoulderF: 76, elbowF: 22, hipF: 22, kneeF: 20, offX: -3 }, "out"),
        kf(15, { ...STANCE, torso: 2, shoulderF: 48, elbowF: 60, offX: -4 }, "inOut"),
        kf(23, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Backing Cut",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 30,
      vel: [{ at: 1, x: -3.3 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      hits: [hit(12, 15, bx(22, 44, 62, 32), 56, { guard: "mid", fx: "slash", pushX: 7, hitstun: 18, hitstop: 8 })],
      desc: "Steps back and leaves the curve hanging in the space he left.",
      notation: "← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, torso: -12, shoulderB: 150, elbowB: 44, weaponBack: 92, hipB: -32, kneeB: 44, offX: -8 }, "inOut"),
        kf(12, { ...STANCE, torso: 2, shoulderB: 78, elbowB: 8, weaponBack: -6, hipF: 26, kneeF: 18, offX: -4 }, "out"),
        kf(18, { ...STANCE, torso: -2, shoulderB: 104, elbowB: 30, weaponBack: 26, offX: -6 }),
        kf(24, { ...STANCE, torso: 0, shoulderB: 114, elbowB: 44, weaponBack: 50, offX: -4 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Falling Curve",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 45,
      cancelInto: ["special", "super"],
      cancelWindow: [27, 41],
      hits: [hit(20, 23, bx(14, 20, 62, 86), 98, { guard: "overhead", fx: "slash", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 })],
      desc: "Takes the shotel all the way up and drops the whole curve. Blocked standing only.",
      notation: "← + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderB: 152, elbowB: 46, weaponBack: 104, torso: -12, offX: -5 }, "inOut"),
        kf(15, { ...STANCE, shoulderB: 176, elbowB: 26, weaponBack: 128, torso: -22, hipB: -26, kneeB: 38, offY: 4, offX: -3 }, "out"),
        kf(20, { ...STANCE, shoulderB: 64, elbowB: -10, weaponBack: -44, torso: 34, hipF: 36, kneeF: 18, hipB: -12, kneeB: 32, offX: 6 }, "out"),
        kf(27, { ...STANCE, shoulderB: 86, elbowB: 8, weaponBack: -12, torso: 26, offX: 4 }),
        kf(37, { ...STANCE, shoulderB: 112, elbowB: 40, weaponBack: 40, torso: 8 }, "inOut"),
        kf(45, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Cut",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 18,
      airborne: true,
      landCancel: true,
      landRecovery: 3,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [5, 16],
      hits: [hit(5, 10, bx(14, 32, 44, 28), 28, { fx: "slash", hitstun: 14, pushX: 2.2 })],
      desc: "Short flick of the point in the air.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 34, kneeF: 46, hipB: -24, kneeB: 46 }, "out"),
        kf(5, { ...STANCE, free: 1, shoulderB: 82, elbowB: 14, weaponBack: 6, torso: 12 }),
        kf(12, { ...STANCE, free: 1, shoulderB: 106, elbowB: 40, weaponBack: 34, torso: 6 }, "inOut"),
        kf(18, { ...STANCE, free: 1, hipF: 34, kneeF: 46, hipB: -24, kneeB: 46 }),
      ],
    },
    {
      id: "jB",
      name: "Air Shield",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 24,
      airborne: true,
      landCancel: true,
      landRecovery: 5,
      cancelInto: ["heavy", "special"],
      hits: [hit(6, 14, bx(16, 20, 52, 42), 52, { fx: "blunt", pushX: 3.8, hitstun: 18 })],
      desc: "Drops the shield edge on them from above.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 32, kneeF: 44, hipB: -22, kneeB: 42 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderF: 8, elbowF: 110, torso: -8 }),
        kf(7, { ...STANCE, free: 1, shoulderF: 78, elbowF: 24, torso: 22, hipF: 40 }, "out"),
        kf(16, { ...STANCE, free: 1, shoulderF: 46, elbowF: 66, torso: 8 }, "inOut"),
        kf(24, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "jC",
      name: "Falling Hook",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 28,
      airborne: true,
      landCancel: true,
      landRecovery: 7,
      hits: [
        hit(8, 18, bx(6, 4, 54, 48), 76, {
          guard: "overhead",
          fx: "slash",
          knockdown: "soft",
          pushX: 4.6,
          shake: 1.5,
        }),
      ],
      desc: "Comes down with the curve leading. His jump-in.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, torso: -18, shoulderB: 172, elbowB: 22, weaponBack: 116, hipF: 40, kneeF: 56 }),
        kf(8, { ...STANCE, free: 1, torso: 30, shoulderB: 46, elbowB: -10, weaponBack: -58, hipF: 14, kneeF: 18 }, "out"),
        kf(28, { ...STANCE, free: 1, torso: 24, shoulderB: 40, elbowB: -6, weaponBack: -54 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Shield Rush",
      input: { button: "C", dir: "f", stance: "stand", whileDashing: true },
      tags: ["command"],
      priority: 12,
      duration: 31,
      vel: [
        { at: 3, x: 10.5 },
        { at: 15, x: 0 },
      ],
      friction: 0.9,
      hits: [hit(7, 12, bx(16, 26, 58, 46), 66, { fx: "blunt", pushX: 6.5, knockdown: "soft", hitstun: 21, shake: 1.4 })],
      desc: "Puts the whole shield into them at a run.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 26, crouch: 0.4, shoulderF: 24, elbowF: 88, offX: -3 }),
        kf(7, { ...STANCE, torso: 34, crouch: 0.3, shoulderF: 72, elbowF: 26, hipF: 46, kneeF: 24, offX: 8 }, "out"),
        kf(21, { ...STANCE, torso: 16, shoulderF: 46, elbowF: 62, offX: 3 }, "inOut"),
        kf(31, { ...STANCE }),
      ],
    },

    // -------------------------------------------------------- five specials
    {
      id: "remington",
      name: "Remington",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      priority: 20,
      duration: 40,
      resourceCost: 1,
      resourceMin: 1,
      showProps: ["rifle"],
      hideProps: ["shotel"],
      projectiles: [
        {
          at: 14,
          kind: "shot",
          x: 46,
          y: 58,
          vx: 21,
          vy: 0,
          life: 60,
          box: { x: -12, y: -5, w: 24, h: 10 },
          damage: 64,
          hitstun: 20,
          blockstun: 14,
          chip: 5,
          pushX: 5,
          clashes: true,
          fx: "shot",
          color: "#ffe6a8",
          trail: "#c9a03c",
        },
      ],
      vfx: [{ at: 14, kind: "shot", x: 50, y: 58, scale: 1.1, color: "#ffe6a8" }],
      desc: "Shoulders the rifle and puts one down the middle. Four rounds on the belt and no way to get more of them mid-fight.",
      notation: "↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderF: 66, elbowF: 20, shoulderB: 84, elbowB: 44, torso: -4, offX: -3 }, "inOut"),
        kf(14, { ...STANCE, shoulderF: 82, elbowF: 2, shoulderB: 96, elbowB: 26, torso: 4, hipF: 24, offX: 2 }, "out"),
        kf(22, { ...STANCE, shoulderF: 92, elbowF: -6, shoulderB: 104, elbowB: 20, torso: -8, offX: -3 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "shotelHook",
      name: "Round the Shield",
      input: { button: "C", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 24,
      duration: 44,
      vel: [{ at: 10, x: 3.6 }, { at: 24, x: 0 }],
      friction: 0.92,
      hits: [
        // The move the weapon exists for. It cannot be blocked, and it is slow
        // enough that anybody paying attention can simply not be there.
        hit(18, 22, bx(16, 30, 74, 52), 96, {
          guard: "unblockable",
          fx: "slash",
          pushX: 10,
          knockdown: "hard",
          hitstun: 28,
          hitstop: 14,
          shake: 2.3,
        }),
      ],
      desc: "Steps in and takes the point the long way round their guard. Unblockable, and eighteen frames of telling them so.",
      notation: "↓↘→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(9, { ...STANCE, shoulderB: 174, elbowB: 40, weaponBack: 122, shoulderF: 26, elbowF: 92, torso: -18, hipB: -32, kneeB: 48, offX: -6 }, "inOut"),
        kf(14, { ...STANCE, shoulderB: 150, elbowB: 20, weaponBack: 96, torso: -8, offX: -2 }, "out"),
        kf(18, { ...STANCE, shoulderB: 46, elbowB: -18, weaponBack: -56, torso: 34, hipF: 44, kneeF: 22, offX: 10 }, "out"),
        kf(28, { ...STANCE, shoulderB: 80, elbowB: 6, weaponBack: -16, torso: 20, offX: 5 }),
        kf(36, { ...STANCE, shoulderB: 106, elbowB: 34, weaponBack: 28, torso: 8 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "brace",
      name: "Behind the Gasha",
      input: { button: "A", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 22,
      duration: 32,
      armor: [{ from: 3, to: 20, hits: 2, damageScale: 0.25 }],
      vel: [{ at: 4, x: 2.6 }, { at: 18, x: 0 }],
      friction: 0.9,
      hits: [hit(20, 24, bx(16, 34, 56, 44), 60, { fx: "blunt", pushX: 8, knockdown: "soft", hitstun: 22, shake: 1.6 })],
      desc: "Walks forward behind the hide and eats two hits doing it, then shoulders the shield through them. The way to cross a screen somebody is shooting at.",
      notation: "↓↙← + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, crouch: 0.4, torso: 22, shoulderF: 18, elbowF: 104, shoulderB: 96, elbowB: 66, weaponBack: 80, hipF: 26, kneeF: 30, offX: 3 }, "out"),
        kf(14, { ...STANCE, crouch: 0.35, torso: 26, shoulderF: 16, elbowF: 108, hipF: 30, kneeF: 26, offX: 5 }),
        kf(20, { ...STANCE, torso: 34, shoulderF: 74, elbowF: 24, hipF: 44, kneeF: 22, offX: 9 }, "out"),
        kf(28, { ...STANCE, torso: 16, shoulderF: 46, elbowF: 66, offX: 4 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "hold",
      name: "Hold the Line",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 26,
      duration: 30,
      parryWindow: [2, 10],
      friction: 0.82,
      meterGain: 26,
      vfx: [{ at: 2, kind: "spark", x: 26, y: 54, scale: 1, color: "#f0d26a" }],
      desc: "Takes it on the boss of the shield and turns it away. Deflects what lands in the first frames, and the read pays in meter.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, crouch: 0.6, torso: 20, shoulderF: 22, elbowF: 100, shoulderB: 108, elbowB: 60, weaponBack: 78, offY: -2, offX: 2 }, "out"),
        kf(10, { ...STANCE, crouch: 0.45, torso: -8, shoulderF: 62, elbowF: 54, shoulderB: 124, elbowB: 44, offX: -4 }, "inOut"),
        kf(19, { ...STANCE, torso: 4, shoulderF: 46, elbowF: 68 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "dogali",
      name: "Dogali Charge",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 26,
      duration: 46,
      airborne: true,
      invuln: [{ from: 1, to: 8, kind: "strike" }],
      vel: [
        { at: 1, x: 3.4, y: 12 },
        { at: 26, y: -1, mode: "add" },
      ],
      hits: [
        hit(4, 10, bx(12, 40, 60, 78), 80, { launch: [2.2, 11], knockdown: "launch", fx: "pierce", hitstun: 26, shake: 1.8 }),
        hit(11, 18, bx(10, 56, 54, 64), 34, { group: 2, launch: [1.6, 5.5], fx: "pierce", hitstun: 17 }),
      ],
      desc: "Straight up off the front foot with the curve leading, shield tucked. Invincible on the way in - his reversal.",
      notation: "→↓↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.7, hipF: 24, kneeF: 52 }, "out"),
        kf(4, { ...STANCE, free: 1, torso: -18, shoulderB: 168, elbowB: 6, weaponBack: -34, shoulderF: 30, elbowF: 96, hipF: 44, kneeF: 60, hipB: -30, kneeB: 42 }, "out"),
        kf(16, { ...STANCE, free: 1, torso: -22, shoulderB: 178, elbowB: 2, weaponBack: -40, hipF: 34, kneeF: 72 }),
        kf(32, { ...STANCE, free: 1, torso: -4, shoulderB: 120, elbowB: 30, weaponBack: 6, hipF: 32, kneeF: 46 }, "inOut"),
        kf(46, { ...STANCE, free: 1 }),
      ],
    },

    // ----------------------------------------------------------------- skill
    {
      id: "reload",
      name: "Reload",
      // A+C, like every other fighter on this roster who can run out. Nobody
      // reaches for a motion input to rearm mid-round, and the engine also
      // reaches for this automatically when he pulls an empty trigger.
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill"],
      priority: 18,
      duration: 46,
      resourceGain: 2,
      showProps: ["rifle"],
      hideProps: ["shotel"],
      desc: "SKILL. Two rounds off the belt and into the block. Takes most of a second he does not have, which is the whole cost of carrying a rifle.",
      notation: "A + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 54, elbowF: 44, shoulderB: 70, elbowB: 84, torso: -8, crouch: 0.3, offX: -3 }, "inOut"),
        kf(20, { ...STANCE, shoulderF: 48, elbowF: 56, shoulderB: 46, elbowB: 96, torso: -12, crouch: 0.35, offX: -4 }, "inOut"),
        kf(32, { ...STANCE, shoulderF: 60, elbowF: 36, shoulderB: 76, elbowB: 70, torso: -4, crouch: 0.2, offX: -2 }, "inOut"),
        kf(46, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "The Column at Dogali",
      input: { button: "S", motion: "dd", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 108,
      meterCost: 100,
      superFreeze: 42,
      invuln: [{ from: 1, to: 16, kind: "full" }],
      armor: [{ from: 17, to: 70, hits: 4, damageScale: 0.12 }],
      vel: [
        { at: 8, x: 10 },
        { at: 30, x: 6 },
        { at: 54, x: 4 },
        { at: 72, x: 0 },
      ],
      friction: 0.93,
      hits: [
        hit(14, 18, bx(20, 38, 64, 44), 52, { group: 1, fx: "blunt", pushX: 1, hitstun: 20, hitstop: 5 }),
        hit(26, 30, bx(18, 34, 68, 46), 46, { group: 2, fx: "slash", pushX: 1, hitstun: 18, hitstop: 4 }),
        hit(38, 42, bx(18, 26, 70, 54), 46, { group: 3, fx: "slash", pushX: 1, hitstun: 18, hitstop: 4 }),
        hit(50, 54, bx(18, 34, 70, 48), 48, { group: 4, fx: "blunt", pushX: 1, hitstun: 18, hitstop: 5 }),
        hit(64, 70, bx(14, 14, 82, 84), 138, {
          group: 5,
          // It ends the way the weapon is meant to: round the guard.
          guard: "unblockable",
          fx: "slash",
          pushX: 12,
          knockdown: "hard",
          launch: [6, 8.5],
          hitstop: 18,
          shake: 3.1,
        }),
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 50, scale: 2.4, color: "#f0d26a" },
        { at: 64, kind: "slash", x: 46, y: 48, scale: 1.7, color: "#f2f6fa" },
      ],
      desc: "SUPER. Walks the whole way in behind the shield, taking whatever they have, and finishes with the one cut a guard cannot answer.",
      notation: "↓↓ + S (100 meter)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5, torso: -8 }, "out"),
        kf(8, { ...STANCE, crouch: 0.4, torso: 26, shoulderF: 18, elbowF: 104, hipF: 30, offX: 5 }, "out"),
        kf(14, { ...STANCE, torso: 32, shoulderF: 76, elbowF: 22, hipF: 40, offX: 8 }, "out"),
        kf(22, { ...STANCE, crouch: 0.35, torso: 20, shoulderF: 20, elbowF: 100, shoulderB: 150, elbowB: 40, weaponBack: 94 }, "inOut"),
        kf(26, { ...STANCE, torso: 28, shoulderB: 74, elbowB: 4, weaponBack: -20, hipF: 36, offX: 7 }, "out"),
        kf(34, { ...STANCE, crouch: 0.35, torso: 16, shoulderB: 156, elbowB: 38, weaponBack: 100 }, "inOut"),
        kf(38, { ...STANCE, torso: 30, spin: -8, shoulderB: 56, elbowB: -8, weaponBack: -40, hipF: 40, offX: 8 }, "out"),
        kf(46, { ...STANCE, crouch: 0.4, torso: 18, shoulderF: 20, elbowF: 102 }, "inOut"),
        kf(50, { ...STANCE, torso: 32, shoulderF: 80, elbowF: 20, hipF: 42, offX: 8 }, "out"),
        kf(58, { ...STANCE, torso: -20, shoulderB: 178, elbowB: 30, weaponBack: 130, hipB: -32, kneeB: 48, offX: -6 }, "inOut"),
        kf(64, { ...STANCE, torso: 36, shoulderB: 44, elbowB: -20, weaponBack: -60, shoulderF: 40, elbowF: 60, hipF: 46, kneeF: 24, offX: 12 }, "out"),
        kf(86, { ...STANCE, torso: 14, shoulderB: 100, elbowB: 30, weaponBack: 20, offX: 4 }, "inOut"),
        kf(108, { ...STANCE }),
      ],
    },
  ],
};
