/**
 * Tzilacatzin - Otomi warrior of Tlatelolco, siege of Tenochtitlan 1521.
 *
 * Named in Book XII of the Florentine Codex, the Nahua account of the conquest
 * collected by Sahagun from men who were there. He is described breaking the
 * Spanish advance with hurled stones, and going out on different days in
 * different warrior insignia so that he could not be picked out and shot.
 *
 * He fights with a macuahuitl: a flat hardwood sword set with obsidian blades
 * down both edges. Obsidian takes an edge finer than steel and shatters like
 * the glass it is, so every heavy swing costs him a blade. Empty, he is a man
 * holding a stick; full, nothing on the roster trades with him.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const PELT = "#d9a441";
const PELT_DARK = "#a97425";
const OBSIDIAN = "#2f2a3d";
const COTTON = "#efe6d4";
const JADE = "#3fae8f";
const BLOOD = "#a8382b";

/** Low and forward - the macuahuitl held back and level, ready to swing. */
const STANCE = {
  torso: 12,
  head: -4,
  hipF: 20,
  kneeF: 22,
  hipB: -20,
  kneeB: 34,
  shoulderF: 30,
  elbowF: 84,
  shoulderB: 44,
  elbowB: 62,
  weapon: -14,
};

const guard = { shoulderB: 66, elbowB: 74 };

export const JAGUAR: FighterDef = {
  id: "jaguar",
  name: "Tzilacatzin",
  title: "Otomitl of Tlatelolco",
  era: "Tenochtitlan, 1521",
  bio: "The Florentine Codex remembers him breaking Spanish advances single-handed with hurled stones, and changing his war insignia daily so no crossbowman could learn his face. Ends fights fast because obsidian does not last.",
  archetype: "Rushdown / Mix-up",
  difficulty: 3,
  strengths: ["Fastest walk in the roster", "Brutal overhead/low mix-up", "Cancels everything into everything"],
  weaknesses: ["Fragile", "Heavies run on a resource", "Nothing to do at full screen"],
  winQuote: "Tomorrow I wear another face. You will not find me either.",
  palette: {
    body: "#c99562",
    outline: "#1a1414",
    accent: PELT,
    cloth: "#8c4a2a",
    metal: OBSIDIAN,
    aura: "#ffd166",
  },
  stats: {
    health: 940,
    walkF: 3.35,
    walkB: 2.85,
    dashSpeed: 9.4,
    dashFrames: 13,
    backdashFrames: 17,
    jumpVel: 13.2,
    jumpFwd: 6,
    gravity: 0.66,
    weight: 0.88,
    airMoves: 2,
    doubleJump: true,
    airDash: false,
    width: 19,
    standHeight: 102,
    crouchHeight: 62,
    scale: 0.98,
  },
  stance: STANCE,
  // Macuahuitl held across the face with the off hand braced behind it.
  clips: guardClips({
    high: { torso: 2, head: -7, shoulderF: 24, elbowF: 126, weapon: 52, shoulderB: 16, elbowB: 120, hipF: 14, kneeF: 24, hipB: -18, kneeB: 36, offX: -2 },
    low: { torso: 10, head: -5, shoulderF: 32, elbowF: 114, weapon: 48, shoulderB: 22, elbowB: 114, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, offX: -2 },
  }),
  resource: {
    name: "Obsidian",
    max: 6,
    start: 6,
    // Blades chip out under use and have to be reset into the wood, which is
    // slow work - he gets a little of it back for every clean hit he lands.
    regen: 0.004,
    gainOnHit: 0.12,
    color: "#7f6fae",
    pips: true,
  },
  props: [
    {
      id: "jaguarHelm",
      attach: "head",
      // The helm is a jaguar's head with the jaws open and the warrior's face
      // looking out of the mouth: rounded skull, ears, a muzzle running forward
      // over the brow, and the lower jaw under the chin.
      parts: [
        // Skull of the beast over the crown, spotted.
        { geo: "poly", size: [-12, -2, -11, 5, -6, 11, 2, 13, 9, 10, 12, 4, 12, -3, 4, -6, -6, -5], pos: [-1, 3], color: PELT },
        // Ears.
        { geo: "poly", size: [0, 0, -4, 6, 3, 5], pos: [-7, 13], color: PELT },
        { geo: "poly", size: [0, 0, -3, 5, 3, 4], pos: [3, 15], color: PELT },
        { geo: "poly", size: [0, 0, -2, 3, 2, 2.5], pos: [-7, 13], color: BLOOD, z: 0.1 },
        // Upper jaw thrown forward over the brow, with teeth showing.
        { geo: "poly", size: [-6, 5, 9, 4, 13, -1, 10, -5, -6, -4], pos: [8, 4], color: PELT_DARK, z: 0.7 },
        { geo: "poly", size: [0, 0, -2.5, -5, 2.5, -4.5], pos: [14, 1], color: COTTON, z: 0.8 },
        { geo: "poly", size: [0, 0, -2, -4, 2, -3.5], pos: [8, 1], color: COTTON, z: 0.8 },
        // Lower jaw under the chin, teeth pointing up.
        { geo: "poly", size: [-7, 3, 9, 2, 12, -2, -6, -4], pos: [7, -9], color: PELT_DARK, behind: true },
        { geo: "poly", size: [0, 0, -2, 4, 2, 3.5], pos: [13, -8], color: COTTON, z: 0.6 },
        // Spots.
        { geo: "disc", size: [1.5], pos: [-6, 7], color: "#5c3a12", z: 0.2 },
        { geo: "disc", size: [1.3], pos: [1, 11], color: "#5c3a12", z: 0.2 },
        { geo: "disc", size: [1.4], pos: [-10, 1], color: "#5c3a12", z: 0.2 },
      ],
    },
    {
      id: "macuahuitl",
      attach: "handF",
      // Flat hardwood paddle, widening towards the end, with obsidian blades
      // sunk into slots down both edges.
      parts: [
        { geo: "poly", size: [-2, -5, 52, -8, 58, -6, 58, 6, 52, 8, -2, 5], pos: [16, 0], color: "#8a5a30" },
        { geo: "poly", size: [-2, -3, 50, -5, 54, -4, 54, 4, 50, 5, -2, 3], pos: [16, 0], color: "#a97445", z: 0.1 },
        // Obsidian teeth along the top edge.
        { geo: "poly", size: [0, 0, -4, 5, 4, 4], pos: [24, 7], color: OBSIDIAN, z: 0.2 },
        { geo: "poly", size: [0, 0, -4, 5, 4, 4], pos: [36, 7.5], color: OBSIDIAN, z: 0.2 },
        { geo: "poly", size: [0, 0, -4, 5, 4, 4], pos: [48, 8], color: OBSIDIAN, z: 0.2 },
        { geo: "poly", size: [0, 0, -4, 5, 4, 4], pos: [60, 8], color: OBSIDIAN, z: 0.2 },
        // And along the bottom.
        { geo: "poly", size: [0, 0, -4, -5, 4, -4], pos: [24, -7], color: OBSIDIAN, z: 0.2 },
        { geo: "poly", size: [0, 0, -4, -5, 4, -4], pos: [36, -7.5], color: OBSIDIAN, z: 0.2 },
        { geo: "poly", size: [0, 0, -4, -5, 4, -4], pos: [48, -8], color: OBSIDIAN, z: 0.2 },
        { geo: "poly", size: [0, 0, -4, -5, 4, -4], pos: [60, -8], color: OBSIDIAN, z: 0.2 },
        // The end blade, twice the size of the rest.
        { geo: "poly", size: [0, 8, 9, 3, 9, -3, 0, -8], pos: [70, 0], color: OBSIDIAN, z: 0.3 },
        // Grip, bound in dyed cord.
        { geo: "box", size: [15, 6], pos: [0, 0], color: "#5c3a1e" },
        { geo: "box", size: [15, 1.8], pos: [0, 1.8], color: JADE },
        { geo: "box", size: [15, 1.8], pos: [0, -1.8], color: BLOOD },
      ],
    },
    {
      id: "ichcahuipilli",
      attach: "torso",
      // Quilted cotton armour, soaked in brine and dried - light, and it turns
      // an arrow better than the plate does.
      parts: [
        { geo: "poly", size: [-12, -15, 12, -15, 13, 8, 8, 15, -8, 15, -13, 8], pos: [0, 3], color: COTTON },
        // Quilting: vertical seams stitched through the padding.
        { geo: "box", size: [2, 28], pos: [-8, 2], color: "#d6c9ae" },
        { geo: "box", size: [2, 28], pos: [-2.5, 2], color: "#d6c9ae" },
        { geo: "box", size: [2, 28], pos: [3, 2], color: "#d6c9ae" },
        { geo: "box", size: [2, 28], pos: [8.5, 2], color: "#d6c9ae" },
        // Jaguar pelt worn over the shoulder, spotted.
        { geo: "poly", size: [-11, -6, -8, 8, 4, 11, 10, 4, 8, -8], pos: [-2, 10], color: PELT, z: 0.3 },
        { geo: "disc", size: [1.4], pos: [-6, 12], color: "#5c3a12", z: 0.4 },
        { geo: "disc", size: [1.4], pos: [1, 15], color: "#5c3a12", z: 0.4 },
        { geo: "disc", size: [1.2], pos: [4, 8], color: "#5c3a12", z: 0.4 },
        // Jade collar over the top of it.
        { geo: "poly", size: [-10, 2.5, 10, 2.5, 9, -2.5, -9, -2.5], pos: [0, 17], color: JADE, z: 0.5 },
        { geo: "disc", size: [2], pos: [0, 17], color: "#7fe0c2", z: 0.55 },
      ],
    },
    {
      id: "maxtlatl",
      attach: "pelvis",
      // Loincloth with an embroidered panel hanging in front and behind.
      parts: [
        { geo: "box", size: [26, 7], pos: [0, 1], color: "#8c4a2a" },
        { geo: "poly", size: [-6, 6, 6, 6, 4, -14, -4, -14], pos: [4, -7], color: BLOOD, z: 0.1 },
        { geo: "poly", size: [-3, 2, 3, 2, 3, -2, -3, -2], pos: [4, -16], color: JADE, z: 0.15 },
        { geo: "poly", size: [-7, 6, 7, 6, 5, -16, -5, -16], pos: [-5, -8], color: "#7a3a1e", behind: true },
      ],
    },
    {
      id: "anklets",
      attach: "footF",
      // Shell rattles at the ankle - the sound the other side hears first.
      parts: [
        { geo: "box", size: [4, 8], pos: [-2, 4], color: BLOOD },
        { geo: "disc", size: [1.5], pos: [-4, 7], color: COTTON },
        { geo: "disc", size: [1.5], pos: [1, 8], color: COTTON },
      ],
    },
    {
      id: "pelt",
      attach: "neck",
      parts: [
        { geo: "box", size: [18, 5], pos: [-4, -3], color: PELT_DARK, behind: true },
      ],
      cloth: {
        segments: 4,
        segmentLength: 10,
        width: 17,
        endWidth: 9,
        color: PELT,
        lining: "#5c3a12",
        gravity: 0.42,
        stiffness: 0.42,
        drift: -0.42,
      },
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 110,
      backThrowDamage: 122,
      throwRange: 58,
      rollSpeed: 8.6,
      weaponIdle: { weapon: STANCE.weapon },
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Claw",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 12,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [3, 11],
      hits: [hit(3, 5, bx(18, 54, 40, 20), 28, { blockstun: 9, hitstun: 13, fx: "slash", pushX: 2.6 })],
      desc: "A three-frame rake across the face. The fastest button in the game and it chains into itself.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderB: 92, elbowB: 16, torso: 16, offX: 3 }),
        kf(7, { ...STANCE, shoulderB: 64, elbowB: 46, torso: 13 }, "inOut"),
        kf(12, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Level Cut",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 21,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [7, 19],
      hits: [hit(7, 10, bx(24, 44, 70, 34), 56, { fx: "slash", pushX: 4.4, hitstun: 17 })],
      desc: "A flat swing at chest height. His main poke - fast, long, and it cancels.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 20, elbowF: 104, weapon: 96, torso: 2 }),
        kf(7, { ...STANCE, shoulderF: 76, elbowF: 18, weapon: -8, torso: 24, hipF: 34, kneeF: 20, offX: 6 }, "out"),
        kf(13, { ...STANCE, shoulderF: 70, elbowF: 24, weapon: -6, torso: 20, offX: 4 }),
        kf(21, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Obsidian Rend",
      input: { button: "C", stance: "stand" },
      tags: ["heavy"],
      duration: 30,
      resourceCost: 1,
      resourceMin: 1,
      cancelInto: ["special", "super"],
      cancelWindow: [13, 26],
      hits: [
        hit(13, 17, bx(20, 30, 76, 62), 92, {
          fx: "slash",
          knockdown: "soft",
          pushX: 6.5,
          shake: 1.5,
        }),
      ],
      vfx: [{ at: 13, kind: "spark", x: 50, y: 52, scale: 0.9, color: "#7f6fae" }],
      desc: "Buries the obsidian and tears it back out. Costs a blade, and it knocks down.",
      notation: "C  (1 Obsidian)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 156, elbowF: 24, weapon: 78, torso: -14, hipB: -26, kneeB: 40, offX: -4 }, "inOut"),
        kf(13, { ...STANCE, shoulderF: 44, elbowF: 20, weapon: -22, torso: 34, hipF: 40, kneeF: 24, hipB: -20, kneeB: 46, offX: 8 }, "out"),
        kf(20, { ...STANCE, shoulderF: 40, elbowF: 26, weapon: -18, torso: 28, offX: 6 }),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Claw",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 13,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [3, 12],
      hits: [hit(3, 5, bx(16, 18, 40, 20), 26, { guard: "low", blockstun: 9, hitstun: 12, pushX: 2.4 })],
      desc: "The fastest low in the game. Two of these into a special is his bread and butter.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 20, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, ...guard }, "out"),
        kf(3, { ...STANCE, crouch: 1, torso: 24, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderB: 104, elbowB: 10, offX: 4 }),
        kf(8, { ...STANCE, crouch: 1, torso: 22, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderB: 78, elbowB: 40 }, "inOut"),
        kf(13, { ...STANCE, crouch: 1, torso: 20, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, ...guard }),
      ],
    },
    {
      id: "2B",
      name: "Hamstring",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 23,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [8, 21],
      hits: [hit(8, 11, bx(22, 10, 68, 26), 52, { guard: "low", fx: "slash", pushX: 4.2 })],
      desc: "Cuts across the shin. Long low that cancels straight into a special.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 8, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderF: 14, elbowF: 96, weapon: 88 }),
        kf(8, { ...STANCE, crouch: 1, torso: 28, hipF: 42, kneeF: 80, hipB: -26, kneeB: 90, shoulderF: 66, elbowF: 22, weapon: -22, offX: 8 }, "out"),
        kf(14, { ...STANCE, crouch: 1, torso: 26, hipF: 40, kneeF: 78, hipB: -24, kneeB: 88, shoulderF: 62, elbowF: 26, weapon: -18, offX: 6 }),
        kf(23, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }),
      ],
    },
    {
      id: "2C",
      name: "Legsweep",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 28,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 24],
      hits: [
        hit(11, 15, bx(18, 4, 74, 24), 70, {
          guard: "low",
          knockdown: "sweep",
          fx: "slash",
          pushX: 5.6,
          shake: 1.1,
        }),
      ],
      desc: "Whips the blade along the floor. Knocks down, and he is fast enough to be right on top of them when they get up.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }, "out"),
        kf(5, { ...STANCE, crouch: 1, torso: 4, hipF: 30, kneeF: 72, hipB: -30, kneeB: 94, shoulderF: 10, elbowF: 60, weapon: 120 }),
        kf(11, { ...STANCE, crouch: 1, torso: 32, hipF: 46, kneeF: 86, hipB: -30, kneeB: 98, shoulderF: 92, elbowF: 34, weapon: -46, offX: 7 }, "out"),
        kf(18, { ...STANCE, crouch: 1, torso: 28, hipF: 42, kneeF: 82, hipB: -26, kneeB: 92, shoulderF: 88, elbowF: 30, weapon: -42 }),
        kf(28, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }),
      ],
    },
    {
      id: "6B",
      name: "Skull Crack",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "overhead"],
      priority: 10,
      duration: 28,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 25],
      hits: [
        hit(16, 19, bx(18, 40, 56, 62), 64, {
          guard: "overhead",
          fx: "slash",
          pushX: 5,
          hitstun: 22,
          shake: 1.2,
        }),
      ],
      desc: "A short chop from above. Overhead - the other half of the mix-up with his low.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 150, elbowF: 20, weapon: 70, torso: -10, offX: -2 }, "inOut"),
        kf(16, { ...STANCE, shoulderF: 56, elbowF: 24, weapon: -6, torso: 30, hipF: 34, kneeF: 22, offX: 6 }, "out"),
        kf(22, { ...STANCE, shoulderF: 52, elbowF: 30, weapon: -4, torso: 24, offX: 4 }),
        kf(28, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Upward Rip",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 30,
      cancelInto: ["special", "super"],
      cancelWindow: [11, 26],
      hits: [
        hit(9, 13, bx(14, 50, 56, 72), 66, {
          launch: [2, 13],
          knockdown: "launch",
          fx: "slash",
          hitstun: 24,
          shake: 1.2,
        }),
      ],
      desc: "Rips upward from the hip. Launches high enough for a double-jump juggle.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5, hipF: 24, kneeF: 46, hipB: -20, kneeB: 52 }, "out"),
        kf(5, { ...STANCE, crouch: 0.7, torso: 14, shoulderF: 8, elbowF: 100, weapon: -73 }),
        kf(9, { ...STANCE, torso: -16, shoulderF: 152, elbowF: 16, weapon: -17, hipF: 20, kneeF: 12, offY: 4 }, "out"),
        kf(16, { ...STANCE, torso: -12, shoulderF: 144, elbowF: 20, weapon: 60, hipF: 16, kneeF: 10 }),
        kf(24, { ...STANCE, torso: 6, shoulderF: 60, elbowF: 60 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      // Forward and back sets. Forward takes space, back gives it up to buy
      // range or a hard read.
      id: "6A",
      name: "Edge Rake",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 20,
      vel: [{ at: 2, x: 2.2 }],
      friction: 0.88,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [6, 18],
      hits: [hit(6, 8, bx(20, 60, 44, 26), 30, { guard: "high", fx: "slash", pushX: 3, hitstun: 13, hitstop: 5 })],
      desc: "Steps in and drags the obsidian across. Fast enough to start anything.",
      notation: "\u2192 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderF: 22, elbowF: 96, weapon: 24, torso: -2, offX: -2 }, "out"),
        kf(6, { ...STANCE, shoulderF: 80, elbowF: 20, weapon: -30, torso: 14, hipF: 26, kneeF: 18, offX: 8 }, "out"),
        kf(11, { ...STANCE, shoulderF: 62, elbowF: 46, weapon: -18, torso: 10, offX: 5 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Obsidian Charge",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 40,
      armor: [{ from: 8, to: 18, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 8, x: 5.4 }, { at: 26, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [20, 36],
      hits: [hit(16, 20, bx(18, 22, 64, 68), 94, { guard: "mid", fx: "slash", pushX: 18, hitstun: 24, hitstop: 12, knockdown: "wallbounce", shake: 2.4 })],
      desc: "Runs in behind the whole weight of it. Anything it catches goes into the wall.",
      notation: "\u2192 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 156, elbowF: -40, weapon: 129, torso: -14, hipB: -30, kneeB: 48, offX: -6 }, "out"),
        kf(16, { ...STANCE, shoulderF: 62, elbowF: 34, weapon: 22, torso: 34, hipF: 42, kneeF: 20, hipB: -26, kneeB: 26, offX: 12 }, "out"),
        kf(24, { ...STANCE, shoulderF: 54, elbowF: 44, weapon: -57, torso: 26, hipF: 30, kneeF: 26, offX: 8 }),
        kf(32, { ...STANCE, shoulderF: 44, elbowF: 66, weapon: -6, torso: 12, offX: 3 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Claw Swipe",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 22,
      vel: [{ at: 1, x: -2.6 }],
      friction: 0.86,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [8, 20],
      hits: [hit(8, 10, bx(16, 52, 42, 30), 36, { guard: "mid", fx: "blunt", pushX: 6, hitstun: 15, hitstop: 6 })],
      desc: "Gives ground and swipes across their guard. Punishes a step-in.",
      notation: "\u2190 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -6, shoulderF: 18, elbowF: 100, weapon: 20, hipB: -26, kneeB: 40, offX: -6 }, "out"),
        kf(8, { ...STANCE, torso: 10, shoulderF: 68, elbowF: 30, weapon: -26, hipF: 24, kneeF: 20, offX: -3 }, "out"),
        kf(14, { ...STANCE, torso: 2, shoulderF: 48, elbowF: 62, weapon: -16, offX: -4 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Backswing",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 30,
      vel: [{ at: 1, x: -3.4 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      hits: [hit(12, 15, bx(34, 52, 88, 24), 56, { guard: "mid", fx: "slash", pushX: 7, hitstun: 18, hitstop: 8 })],
      desc: "Steps out and brings it back across on the return. Long, and it keeps them out.",
      notation: "\u2190 + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 116, elbowF: -20, weapon: 74, torso: -12, hipB: -28, kneeB: 42, offX: -8 }, "inOut"),
        kf(12, { ...STANCE, shoulderF: 74, elbowF: 14, weapon: -22, torso: 6, hipF: 26, kneeF: 16, offX: -5 }, "out"),
        kf(17, { ...STANCE, shoulderF: 68, elbowF: 18, weapon: -20, torso: 4, offX: -6 }),
        kf(23, { ...STANCE, shoulderF: 44, elbowF: 60, weapon: -10, torso: 0, offX: -4 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Skull Rend",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 44,
      cancelInto: ["special", "super"],
      cancelWindow: [26, 40],
      hits: [hit(20, 23, bx(14, 20, 70, 86), 106, { guard: "overhead", fx: "slash", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 })],
      desc: "Overhead with both arms and all his weight. Blocked standing only.",
      notation: "\u2190 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 148, elbowF: -36, weapon: 74, torso: -10, offX: -5 }, "inOut"),
        kf(15, { ...STANCE, shoulderF: 180, elbowF: -10, weapon: 80, torso: -22, hipB: -26, kneeB: 38, offY: 3, offX: -3 }, "out"),
        kf(20, { ...STANCE, shoulderF: 84, elbowF: 16, weapon: -14, torso: 34, hipF: 36, kneeF: 20, hipB: -12, kneeB: 32, offX: 6 }, "out"),
        kf(26, { ...STANCE, shoulderF: 76, elbowF: 20, weapon: -12, torso: 26, offX: 4 }),
        kf(36, { ...STANCE, shoulderF: 46, elbowF: 66, weapon: -8, torso: 8 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Claw",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 17,
      airborne: true,
      landCancel: true,
      landRecovery: 2,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [4, 15],
      hits: [hit(4, 10, bx(14, 30, 44, 30), 32, { fx: "slash", pushX: 2.6, hitstun: 14 })],
      desc: "A quick swipe out of the jump. Fast enough to start an air string.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 34, kneeF: 46, hipB: -24, kneeB: 42 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderB: 112, elbowB: 18, torso: 18, hipF: 30, kneeF: 42 }),
        kf(11, { ...STANCE, free: 1, shoulderB: 74, elbowB: 50, torso: 12, hipF: 32, kneeF: 44 }, "inOut"),
        kf(17, { ...STANCE, free: 1, hipF: 34, kneeF: 46, hipB: -24, kneeB: 42 }),
      ],
    },
    {
      id: "jB",
      name: "Falling Cut",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 24,
      airborne: true,
      landCancel: true,
      landRecovery: 3,
      hits: [hit(6, 14, bx(18, 6, 64, 48), 58, { fx: "slash", pushX: 3.8, hitstun: 19 })],
      desc: "Swings down through the arc. Stays out long enough to cross up.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 30, kneeF: 42, hipB: -22, kneeB: 40 }, "out"),
        kf(3, { ...STANCE, free: 1, shoulderF: 150, elbowF: 22, weapon: 76, torso: -12 }),
        kf(6, { ...STANCE, free: 1, shoulderF: 60, elbowF: 22, weapon: 2, torso: 28, hipF: 40, kneeF: 36 }, "out"),
        kf(15, { ...STANCE, free: 1, shoulderF: 54, elbowF: 26, weapon: 0, torso: 24 }),
        kf(24, { ...STANCE, free: 1, hipF: 30, kneeF: 42, hipB: -22, kneeB: 40 }),
      ],
    },
    {
      id: "jC",
      name: "Pounce",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 28,
      airborne: true,
      landCancel: true,
      landRecovery: 7,
      vel: [{ at: 5, y: -3.5, mode: "add" }],
      hits: [
        hit(7, 18, bx(-2, -4, 56, 44), 78, {
          guard: "overhead",
          fx: "slash",
          knockdown: "soft",
          pushX: 4.4,
          shake: 1.4,
        }),
      ],
      desc: "Drops on them like the animal on the helmet. Crushes low blocks.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(4, { ...STANCE, free: 1, torso: -20, shoulderF: 158, elbowF: 14, shoulderB: 140, elbowB: 30, weapon: 82, hipF: 44, kneeF: 64, hipB: -32, kneeB: 62 }),
        kf(8, { ...STANCE, free: 1, torso: 34, shoulderF: 24, elbowF: 24, shoulderB: 34, elbowB: 30, weapon: -20, hipF: 20, kneeF: 20, hipB: -16, kneeB: 26 }, "out"),
        kf(28, { ...STANCE, free: 1, torso: 28, shoulderF: 28, elbowF: 28, weapon: -16 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Running Rend",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command"],
      priority: 12,
      duration: 30,
      vel: [
        { at: 3, x: 10.5 },
        { at: 15, x: 0 },
      ],
      friction: 0.88,
      hits: [
        hit(8, 14, bx(18, 26, 62, 58), 74, {
          fx: "slash",
          pushX: 7,
          knockdown: "soft",
          hitstun: 22,
          shake: 1.4,
        }),
      ],
      desc: "Closes the whole screen and swings on the way past. Knocks down.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 26, shoulderF: 6, elbowF: 96, weapon: 108, hipB: -34, kneeB: 46, offX: -2 }),
        kf(8, { ...STANCE, torso: 32, shoulderF: 82, elbowF: 16, weapon: -18, hipF: 44, kneeF: 24, hipB: -26, kneeB: 56, offX: 7 }, "out"),
        kf(20, { ...STANCE, torso: 26, shoulderF: 74, elbowF: 22, weapon: -14, hipF: 30, kneeF: 32 }),
        kf(30, { ...STANCE }),
      ],
    },

    // --------------------------------------------------------------- specials
    {
      id: "dart",
      name: "Atlatl Dart",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      priority: 20,
      duration: 32,
      resourceCost: 1,
      resourceMin: 1,
      meterGain: 6,
      projectiles: [
        {
          at: 11,
          kind: "dart",
          x: 36,
          y: 58,
          vx: 14,
          vy: 0.6,
          gravity: 0.04,
          life: 80,
          box: { x: -20, y: -6, w: 40, h: 12 },
          damage: 48,
          hitstun: 18,
          blockstun: 12,
          chip: 5,
          pushX: 5,
          clashes: true,
          fx: "pierce",
          color: "#7f6fae",
          trail: "#d9a441",
        },
      ],
      desc: "Throws a dart off the spear-thrower. His only ranged answer, and it eats a blade.",
      notation: "↓↘→ + B  (1 Obsidian)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderB: 160, elbowB: -30, torso: -18, hipB: -28, kneeB: 42, offX: -5 }, "inOut"),
        kf(11, { ...STANCE, shoulderB: 74, elbowB: -4, torso: 28, hipF: 40, kneeF: 22, hipB: -20, kneeB: 46, offX: 8 }, "out"),
        kf(20, { ...STANCE, shoulderB: 66, elbowB: 12, torso: 20, offX: 5 }),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "dartEx",
      name: "Dart Volley",
      input: { button: "S", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "projectile"],
      priority: 28,
      duration: 44,
      meterCost: 50,
      projectiles: [
        {
          at: 8,
          kind: "dart",
          x: 36,
          y: 72,
          vx: 14,
          vy: -0.6,
          gravity: 0.03,
          life: 80,
          box: { x: -20, y: -6, w: 40, h: 12 },
          damage: 36,
          hitstun: 16,
          blockstun: 11,
          chip: 3,
          pushX: 3.5,
          clashes: true,
          fx: "pierce",
          color: "#7f6fae",
        },
        {
          at: 15,
          kind: "dart",
          x: 36,
          y: 54,
          vx: 15,
          vy: 0,
          gravity: 0.03,
          life: 80,
          box: { x: -20, y: -6, w: 40, h: 12 },
          damage: 34,
          hitstun: 16,
          blockstun: 11,
          chip: 3,
          pushX: 3.5,
          clashes: true,
          fx: "pierce",
          color: "#7f6fae",
        },
        {
          at: 22,
          kind: "dart",
          x: 36,
          y: 36,
          vx: 16,
          vy: 0.3,
          gravity: 0.03,
          life: 80,
          box: { x: -20, y: -6, w: 40, h: 12 },
          damage: 44,
          hitstun: 20,
          blockstun: 13,
          chip: 4,
          pushX: 6,
          knockdown: "soft",
          clashes: true,
          fx: "pierce",
          color: "#7f6fae",
        },
      ],
      desc: "EX. Three darts at three heights, and it costs no obsidian - the meter pays for it.",
      notation: "↓↘→ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderB: 156, elbowB: -28, torso: -16, offX: -4 }, "inOut"),
        kf(8, { ...STANCE, shoulderB: 82, elbowB: -6, torso: 26, offX: 6 }, "out"),
        kf(12, { ...STANCE, shoulderB: 152, elbowB: -26, torso: -12, offX: -3 }, "inOut"),
        kf(15, { ...STANCE, shoulderB: 78, elbowB: -4, torso: 24, offX: 6 }, "out"),
        kf(19, { ...STANCE, shoulderB: 152, elbowB: -26, torso: -12, offX: -3 }, "inOut"),
        kf(22, { ...STANCE, shoulderB: 70, elbowB: 0, torso: 30, hipF: 38, kneeF: 24, offX: 8 }, "out"),
        kf(34, { ...STANCE, torso: 16 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "flurry",
      name: "Blade Storm",
      input: { button: "C", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 22,
      duration: 46,
      resourceCost: 2,
      resourceMin: 2,
      vel: [
        { at: 3, x: 4.5 },
        { at: 26, x: 0 },
      ],
      friction: 0.92,
      hits: [
        hit(8, 10, bx(20, 40, 62, 40), 30, { group: 1, fx: "slash", pushX: 1.2, hitstun: 14, hitstop: 4 }),
        hit(14, 16, bx(20, 30, 64, 48), 30, { group: 2, fx: "slash", pushX: 1.2, hitstun: 14, hitstop: 4 }),
        hit(20, 22, bx(20, 42, 64, 40), 30, { group: 3, fx: "slash", pushX: 1.2, hitstun: 14, hitstop: 4 }),
        hit(28, 33, bx(18, 24, 74, 64), 74, {
          group: 4,
          fx: "slash",
          pushX: 8,
          knockdown: "hard",
          hitstun: 24,
          shake: 1.8,
        }),
      ],
      desc: "Four swings without stopping, ending in a knockdown. Two blades, and worth both of them.",
      notation: "↓↘→ + C  (2 Obsidian)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 140, elbowF: 26, weapon: 66, torso: -10 }, "inOut"),
        kf(8, { ...STANCE, shoulderF: 70, elbowF: 20, weapon: -12, torso: 26, offX: 5 }, "out"),
        kf(12, { ...STANCE, shoulderF: 16, elbowF: 96, weapon: 100, torso: 6 }, "inOut"),
        kf(14, { ...STANCE, shoulderF: 88, elbowF: 26, weapon: -30, torso: 28, offX: 5 }, "out"),
        kf(18, { ...STANCE, shoulderF: 144, elbowF: 24, weapon: 68, torso: -8 }, "inOut"),
        kf(20, { ...STANCE, shoulderF: 66, elbowF: 18, weapon: -10, torso: 26, offX: 5 }, "out"),
        kf(25, { ...STANCE, shoulderF: 162, elbowF: 14, weapon: 84, torso: -20, hipB: -28, kneeB: 42, offX: -5 }, "inOut"),
        kf(28, { ...STANCE, shoulderF: 36, elbowF: 16, weapon: -26, torso: 38, hipF: 44, kneeF: 26, hipB: -22, kneeB: 50, offX: 10 }, "out"),
        kf(38, { ...STANCE, shoulderF: 44, elbowF: 44, torso: 20, offX: 5 }, "inOut"),
        kf(46, { ...STANCE }),
      ],
    },
    {
      id: "prowl",
      name: "Prowl",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "low"],
      priority: 22,
      duration: 34,
      invuln: [{ from: 4, to: 18, kind: "projectile" }],
      vel: [
        { at: 3, x: 9 },
        { at: 22, x: 0 },
      ],
      friction: 0.9,
      hits: [
        hit(12, 17, bx(16, 4, 60, 26), 62, {
          guard: "low",
          fx: "slash",
          knockdown: "sweep",
          pushX: 5,
          hitstun: 20,
          shake: 1.2,
        }),
      ],
      desc: "Slides in under fireballs on all fours and takes the legs out. Immune to projectiles on the way in.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 42, hipF: 12, kneeF: 92, hipB: -38, kneeB: 100, shoulderF: 8, elbowF: 40, shoulderB: 20, elbowB: 30, offY: -2 }, "out"),
        kf(12, { ...STANCE, crouch: 1, torso: 40, hipF: 62, kneeF: 40, hipB: -34, kneeB: 96, shoulderF: 78, elbowF: 26, weapon: -40, offX: 4 }, "out"),
        kf(20, { ...STANCE, crouch: 1, torso: 34, hipF: 46, kneeF: 66, hipB: -28, kneeB: 92, shoulderF: 64, elbowF: 38, weapon: -30 }),
        kf(34, { ...STANCE }),
      ],
    },
    {
      id: "rend",
      name: "Jaguar Rise",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 26,
      duration: 42,
      airborne: true,
      resourceCost: 1,
      resourceMin: 1,
      invuln: [{ from: 1, to: 7, kind: "strike" }],
      vel: [
        { at: 1, x: 2.6, y: 13 },
        { at: 24, y: -1, mode: "add" },
      ],
      hits: [
        hit(3, 8, bx(4, 54, 58, 78), 76, {
          launch: [2.2, 11.5],
          knockdown: "launch",
          fx: "slash",
          hitstun: 24,
          shake: 1.7,
        }),
        hit(9, 16, bx(2, 66, 54, 66), 36, { group: 2, launch: [1.6, 5.5], fx: "slash", hitstun: 16 }),
      ],
      desc: "Comes up off the floor cutting with both edges. Invincible on startup - his reversal.",
      notation: "→↓↘ + C  (1 Obsidian)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 22, kneeF: 50, hipB: -20, kneeB: 54 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -14, shoulderF: 158, elbowF: 12, weapon: 44, spin: -8, hipF: 32, kneeF: 30, hipB: -26, kneeB: 40 }, "out"),
        kf(12, { ...STANCE, free: 1, torso: -20, shoulderF: 172, elbowF: 6, weapon: 38, spin: -24, hipF: 26, kneeF: 26 }),
        kf(28, { ...STANCE, free: 1, torso: -2, shoulderF: 118, elbowF: 34, spin: -6, hipF: 30, kneeF: 42 }, "inOut"),
        kf(42, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "rendEx",
      name: "Jaguar Rise EX",
      input: { button: "S", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "launcher"],
      priority: 32,
      duration: 48,
      meterCost: 50,
      airborne: true,
      invuln: [{ from: 1, to: 15, kind: "strike" }],
      vel: [
        { at: 1, x: 3.2, y: 14.4 },
        { at: 28, y: -1, mode: "add" },
      ],
      hits: [
        hit(2, 8, bx(4, 52, 64, 84), 68, { launch: [2, 12.5], knockdown: "launch", fx: "slash", hitstun: 26, shake: 1.9 }),
        hit(9, 17, bx(2, 66, 58, 76), 34, { group: 2, launch: [1.4, 5], fx: "slash" }),
        hit(18, 26, bx(2, 76, 56, 68), 44, { group: 3, launch: [2, 4], fx: "slash", knockdown: "hard" }),
      ],
      desc: "EX. Fully invincible and it costs no blades. His get-out-of-anything button.",
      notation: "→↓↘ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 22, kneeF: 50 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -16, shoulderF: 162, elbowF: 10, weapon: 42, spin: -14 }, "out"),
        kf(15, { ...STANCE, free: 1, torso: -24, shoulderF: 176, elbowF: 4, weapon: 34, spin: -40 }),
        kf(32, { ...STANCE, free: 1, torso: -4, shoulderF: 120, elbowF: 32, spin: -8 }, "inOut"),
        kf(48, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "leap",
      name: "Killing Leap",
      input: { button: "C", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "overhead"],
      priority: 24,
      duration: 44,
      airborne: true,
      resourceCost: 1,
      resourceMin: 1,
      vel: [
        { at: 4, x: 8, y: 11 },
        { at: 22, y: -0.8, mode: "add" },
      ],
      hits: [
        hit(15, 24, bx(10, 6, 58, 56), 84, {
          guard: "overhead",
          fx: "slash",
          pushX: 6,
          knockdown: "hard",
          hitstun: 24,
          shake: 1.6,
        }),
      ],
      desc: "Springs over their guard and comes down blade-first. Overhead, and it puts them on the floor.",
      notation: "↓↙← + C  (1 Obsidian)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 22, kneeF: 46 }, "out"),
        kf(6, { ...STANCE, free: 1, torso: -18, shoulderF: 150, elbowF: 26, weapon: 74, hipF: -14, kneeF: 66, hipB: -34, kneeB: 58 }, "out"),
        kf(15, { ...STANCE, free: 1, torso: 30, shoulderF: 34, elbowF: 20, weapon: -22, hipF: 52, kneeF: 20, hipB: -22, kneeB: 44 }, "out"),
        kf(30, { ...STANCE, free: 1, torso: 24, shoulderF: 30, elbowF: 26, weapon: -18, hipF: 40, kneeF: 34 }, "inOut"),
        kf(44, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "reset",
      name: "Reset the Blades",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill"],
      priority: 18,
      duration: 40,
      resourceGain: 3,
      friction: 0.86,
      invuln: [{ from: 2, to: 10, kind: "projectile" }],
      vfx: [{ at: 26, kind: "spark", x: 20, y: 44, scale: 1.3, color: "#7f6fae" }],
      desc: "SKILL. Kneels and beds three fresh blades into the wood. Long, and completely helpless while he does it - buy the time first.",
      notation: "A + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, crouch: 0.85, torso: 30, hipF: 40, kneeF: 82, hipB: -26, kneeB: 94, shoulderF: 16, elbowF: 76, shoulderB: 30, elbowB: 74, weapon: 24 }, "inOut"),
        kf(20, { ...STANCE, crouch: 0.9, torso: 34, hipF: 40, kneeF: 84, hipB: -26, kneeB: 96, shoulderF: 12, elbowF: 82, shoulderB: 34, elbowB: 80, weapon: 18 }),
        kf(28, { ...STANCE, crouch: 0.88, torso: 32, hipF: 40, kneeF: 84, hipB: -26, kneeB: 96, shoulderF: 18, elbowF: 74, shoulderB: 28, elbowB: 72, weapon: 26 }),
        kf(40, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "Flower War",
      input: { button: "S", motion: "dd", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 92,
      meterCost: 100,
      superFreeze: 38,
      invuln: [{ from: 1, to: 12, kind: "strike" }],
      vel: [
        { at: 5, x: 11 },
        { at: 26, x: 6 },
        { at: 48, x: 3 },
        { at: 64, x: 0 },
      ],
      friction: 0.93,
      hits: [
        hit(10, 13, bx(20, 40, 68, 44), 44, { group: 1, fx: "slash", pushX: 1, hitstun: 18, hitstop: 5 }),
        hit(18, 21, bx(20, 20, 68, 46), 40, { group: 2, fx: "slash", pushX: 1, hitstun: 16, hitstop: 4 }),
        hit(26, 29, bx(20, 44, 68, 44), 40, { group: 3, fx: "slash", pushX: 1, hitstun: 16, hitstop: 4 }),
        hit(34, 37, bx(20, 24, 70, 50), 40, { group: 4, fx: "slash", pushX: 1, hitstun: 16, hitstop: 4 }),
        hit(42, 45, bx(20, 40, 70, 46), 40, { group: 5, fx: "slash", pushX: 1, hitstun: 16, hitstop: 4 }),
        hit(56, 62, bx(14, 16, 84, 88), 132, {
          group: 6,
          fx: "slash",
          pushX: 10,
          knockdown: "hard",
          launch: [5, 9],
          hitstop: 16,
          shake: 3,
        }),
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 48, scale: 2.3, color: "#ffd166" },
        { at: 56, kind: "explode", x: 50, y: 46, scale: 1.3 },
      ],
      desc: "SUPER. Takes them the way a captive is taken - five cuts to wear them down, then one to finish it. Costs no obsidian.",
      notation: "↓↓ + S  (100 meter)",
      frames: [
        kf(0, { ...STANCE, torso: -12, shoulderF: 20, elbowF: 96, weapon: 100, crouch: 0.4 }, "out"),
        kf(6, { ...STANCE, torso: 30, shoulderF: 74, elbowF: 18, weapon: -14, hipF: 40, kneeF: 22, offX: 6 }, "out"),
        kf(10, { ...STANCE, torso: 32, shoulderF: 70, elbowF: 14, weapon: -18, hipF: 42, kneeF: 20, offX: 8 }),
        kf(15, { ...STANCE, torso: 10, shoulderF: 14, elbowF: 98, weapon: 104 }, "inOut"),
        kf(18, { ...STANCE, torso: 32, shoulderF: 92, elbowF: 30, weapon: -38, offX: 7 }, "out"),
        kf(23, { ...STANCE, torso: 8, shoulderF: 146, elbowF: 22, weapon: 70 }, "inOut"),
        kf(26, { ...STANCE, torso: 30, shoulderF: 66, elbowF: 16, weapon: -12, offX: 7 }, "out"),
        kf(31, { ...STANCE, torso: 10, shoulderF: 16, elbowF: 96, weapon: 102 }, "inOut"),
        kf(34, { ...STANCE, torso: 32, shoulderF: 88, elbowF: 28, weapon: -34, offX: 7 }, "out"),
        kf(39, { ...STANCE, torso: 8, shoulderF: 148, elbowF: 20, weapon: 72 }, "inOut"),
        kf(42, { ...STANCE, torso: 30, shoulderF: 64, elbowF: 14, weapon: -10, offX: 7 }, "out"),
        kf(50, { ...STANCE, torso: -24, shoulderF: 172, elbowF: 6, shoulderB: 154, elbowB: 20, weapon: 90, hipB: -30, kneeB: 44, offX: -6 }, "inOut"),
        kf(56, { ...STANCE, torso: 40, shoulderF: 26, elbowF: 12, shoulderB: 34, elbowB: 16, weapon: -30, hipF: 48, kneeF: 28, hipB: -24, kneeB: 54, offX: 11 }, "out"),
        kf(74, { ...STANCE, torso: 26, shoulderF: 40, elbowF: 46, offX: 5 }, "inOut"),
        kf(92, { ...STANCE }),
      ],
    },
  ],
};
