/**
 * Te Rauparaha - Ngāti Toa.
 *
 * A taiaha is not a spear and not a staff: it is a two-handed weapon with a
 * blade at one end and a carved tongue at the other, and the whole art of it
 * is the switch - the long end holds the distance and the flat end takes the
 * head once the distance is gone. That is his fight. He controls a range
 * almost nobody else on the roster can reach into, and when someone finally
 * gets inside it he stops fencing and pulls the mere, which is a short flat
 * club of greenstone that ends the argument at arm's length.
 *
 * Mana fills when he holds ground rather than when he lands hits, because
 * the wero is a challenge issued before the fighting, not a reward after it.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const WOOD = "#4a3526";
const FLAX = "#c9a86a";
const POUNAMU = "#2f6b4f";
const SKIN_INK = "#1c1410";

const STANCE = {
  torso: 8,
  head: -2,
  hipF: 20,
  kneeF: 26,
  hipB: -22,
  kneeB: 34,
  // Both hands on the taiaha, held across the body at an angle - the guard a
  // taiaha is actually carried in, not a spear's one-handed point.
  shoulderF: 52,
  elbowF: 40,
  weapon: 42,
  shoulderB: 96,
  elbowB: 34,
  crouch: 0.2,
};

const IDLE_ARMS = { shoulderF: 52, elbowF: 40, weapon: 42, shoulderB: 96, elbowB: 34 };

export const MAORI: FighterDef = {
  id: "maori",
  name: "Te Rauparaha",
  title: "Chief of Ngāti Toa",
  era: "Kapiti Coast, 1820s",
  bio: "Ngāti Toa chief who took his people south out of Kāwhia when the country was being remade by muskets, and made Kapiti Island the base he ran a coast from. He is also the man who composed Ka Mate, which he is said to have put together after coming up out of a food pit alive when he had every reason not to.",
  archetype: "Footsies / Stance",
  difficulty: 3,
  strengths: ["Controls a range most of the roster cannot enter", "The mere makes close range a trap, not a loss", "Every heavy leaves him facing them"],
  weaknesses: ["Slow to start once he has been backed up", "Mana only fills while he holds his ground", "No answer to anything thrown at him"],
  winQuote: "You came inside the reach. That was the whole decision.",
  palette: {
    body: "#c98f63",
    outline: "#140d08",
    accent: POUNAMU,
    cloth: "#5c3a24",
    metal: "#d8d2c4",
    aura: "#6fd3a4",
  },
  stats: {
    health: 1010,
    walkF: 3.0,
    walkB: 2.7,
    dashSpeed: 8.6,
    dashFrames: 14,
    backdashFrames: 18,
    jumpVel: 12.1,
    jumpFwd: 4.8,
    gravity: 0.62,
    weight: 1.06,
    airMoves: 1,
    doubleJump: false,
    airDash: false,
    width: 19,
    standHeight: 102,
    crouchHeight: 62,
    scale: 1.01,
  },
  stance: STANCE,
  clips: guardClips({
    high: { torso: 2, head: -6, shoulderF: 34, elbowF: 96, weapon: 96, shoulderB: 74, elbowB: 70, crouch: 0.12, hipF: 18, kneeF: 28, hipB: -22, kneeB: 36, offX: -2 },
    low: { torso: 10, head: -5, shoulderF: 40, elbowF: 88, weapon: 92, shoulderB: 66, elbowB: 64, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88, offX: -2 },
  }),
  resource: {
    name: "Mana",
    max: 3,
    start: 1,
    regen: 0.007,
    regenIdleOnly: true,
    color: POUNAMU,
    pips: true,
  },
  props: [
    {
      id: "topknot",
      attach: "head",
      // Hair gathered up, with two feathers set in it. Kept plain on purpose:
      // a chief's moko is his own and is not decoration to invent.
      parts: [
        { geo: "poly", size: [-9, -4, -8, 6, 0, 10, 8, 5, 9, -4], pos: [0, 7], color: "#1d1410" },
        { geo: "poly", size: [-5, 4, 5, 3, 4, -5, -5, -4], pos: [-2, 13], color: "#1d1410" },
        { geo: "poly", size: [-1.6, 12, 1.6, 11, 1.2, -10, -1.6, -10], pos: [-3, 22], rot: 12, color: "#efe7d6" },
        { geo: "poly", size: [-1.4, 10, 1.4, 9, 1, -9, -1.4, -9], pos: [2, 21], rot: -14, color: "#2a221c" },
        // The line of the jaw, so the head reads as a face in profile.
        { geo: "box", size: [11, 1.4], pos: [4, -6], rot: -6, color: SKIN_INK, z: 0.4 },
      ],
    },
    {
      id: "korowai",
      attach: "torso",
      // Cloak over one shoulder, with a woven border along the hem.
      parts: [
        { geo: "poly", size: [-13, -16, 12, -15, 13, 6, 8, 16, -9, 16, -14, 5], pos: [0, 4], color: "#5c3a24" },
        { geo: "box", size: [20, 2.4], pos: [0, 12], color: FLAX },
        { geo: "box", size: [20, 2.4], pos: [0, -8], color: FLAX },
        { geo: "poly", size: [-3, 18, 3, 18, 3, -18, -3, -18], pos: [-5, 4], rot: 14, color: "#3d2617" },
      ],
      cloth: {
        segments: 4,
        segmentLength: 12,
        width: 24,
        endWidth: 18,
        color: "#4a2f1d",
        lining: "#c9a86a",
        gravity: 0.42,
        stiffness: 0.5,
        drift: -0.28,
      },
    },
    {
      id: "piupiu",
      attach: "pelvis",
      // Flax skirt: a band with the strands hanging off it.
      parts: [
        { geo: "poly", size: [-13, 4, 13, 3.5, 13, -4, -13, -4.5], pos: [0, 1], color: "#8a6a3a" },
        { geo: "box", size: [24, 2], pos: [0, 2], color: FLAX, z: 0.2 },
        { geo: "box", size: [3, 15], pos: [-8, -9], color: FLAX },
        { geo: "box", size: [3, 17], pos: [-2, -10], color: "#b8955c" },
        { geo: "box", size: [3, 15], pos: [4, -9], color: FLAX },
        { geo: "box", size: [3, 16], pos: [10, -9], color: "#b8955c" },
      ],
    },
    {
      id: "taiaha",
      attach: "handF",
      // Blade (rau) at one end, carved head with the tongue (arero) at the
      // other. Both ends are the weapon, which is the entire point of it.
      parts: [
        { geo: "cyl", size: [3, 96], pos: [10, 0], rot: 90, color: WOOD },
        // The rau: a long flattened blade running out from the grip.
        { geo: "poly", size: [-30, 5.5, 24, 4.5, 32, 0, 24, -4.5, -30, -5.5], pos: [78, 0], color: "#6b4a30" },
        { geo: "box", size: [46, 1.6], pos: [72, 1], color: "#9a7550" },
        // The carved head at the butt, with the tongue thrust out.
        { geo: "poly", size: [-7, 7, 4, 8, 7, 0, 4, -8, -7, -7], pos: [-42, 0], color: "#3a2819" },
        { geo: "poly", size: [0, 3.5, 10, 2, 13, 0, 10, -2, 0, -3.5], pos: [-32, 0], color: "#8a3f34" },
        { geo: "disc", size: [2], pos: [-45, 3], color: "#d8d2c4" },
        { geo: "disc", size: [2], pos: [-45, -3], color: "#d8d2c4" },
        // Dog-hair collar bound below the head.
        { geo: "box", size: [6, 11], pos: [-28, 0], color: "#efe7d6" },
      ],
    },
    {
      id: "mere",
      attach: "handB",
      conditional: true,
      // Mere pounamu: a short flat greenstone club, all edge and no point.
      parts: [
        { geo: "poly", size: [-4, 5, 14, 9, 24, 6, 26, 0, 24, -6, 14, -9, -4, -5], pos: [8, 0], color: POUNAMU },
        { geo: "poly", size: [-2, 7, 12, 6, 20, 3, 20, 1, 10, 2, -2, 4], pos: [10, 0], color: "#4f9a72" },
        { geo: "box", size: [10, 6], pos: [-6, 0], color: "#254f3c" },
        { geo: "box", size: [10, 1.6], pos: [-6, 1.8], color: FLAX },
        { geo: "ring", size: [3, 1.4], pos: [-13, 0], color: FLAX },
      ],
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 130,
      backThrowDamage: 142,
      throwRange: 60,
      rollSpeed: 7.6,
      weaponIdle: IDLE_ARMS,
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Butt Jab",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 13,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 12],
      followUps: [{ button: "A", move: "6A", from: 4, to: 10, string: "Both Ends" }],
      hits: [hit(4, 6, bx(20, 56, 50, 20), 26, { fx: "blunt", hitstun: 14, blockstun: 10, pushX: 2.6 })],
      desc: "Short punch off the carved end, without giving up the grip.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 74, elbowF: 12, weapon: 20, torso: 14, offX: 3 }),
        kf(8, { ...STANCE, shoulderF: 60, elbowF: 32, weapon: 34, torso: 10 }, "inOut"),
        kf(13, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Long Strike",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 22,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [8, 20],
      followUps: [{ button: "C", move: "6C", from: 8, to: 19, string: "Turn the Blade" }],
      hits: [hit(8, 11, bx(30, 48, 84, 26), 52, { fx: "blunt", pushX: 4.4, hitstun: 18 })],
      desc: "The blade end swung out at full extension. His longest quick button.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 26, elbowF: 66, weapon: 76, shoulderB: 64, elbowB: 58, torso: -8, offX: -3 }),
        kf(8, { ...STANCE, shoulderF: 88, elbowF: 4, weapon: 6, shoulderB: 118, elbowB: 8, torso: 20, hipF: 30, offX: 7 }, "out"),
        kf(15, { ...STANCE, shoulderF: 68, elbowF: 30, weapon: 30, torso: 12 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Overhead Rau",
      input: { button: "C", stance: "stand" },
      tags: ["heavy"],
      duration: 31,
      cancelInto: ["special", "super"],
      cancelWindow: [14, 27],
      hits: [
        hit(14, 18, bx(24, 34, 88, 54), 86, {
          fx: "blunt",
          pushX: 8,
          knockdown: "soft",
          hitstun: 23,
          shake: 1.8,
        }),
      ],
      desc: "Raises the blade over the head and brings it down the centre line.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderF: 8, elbowF: 84, weapon: 108, shoulderB: 40, elbowB: 76, torso: -14, hipB: -30, kneeB: 46, offX: -4 }, "inOut"),
        kf(14, { ...STANCE, shoulderF: 106, elbowF: 0, weapon: -18, shoulderB: 136, elbowB: 6, torso: 30, hipF: 38, kneeF: 22, offX: 8 }, "out"),
        kf(22, { ...STANCE, shoulderF: 84, elbowF: 20, weapon: 6, torso: 20, offX: 4 }),
        kf(31, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Tap",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 13,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 12],
      hits: [hit(4, 6, bx(18, 12, 48, 18), 24, { guard: "low", fx: "blunt", hitstun: 13, blockstun: 10, pushX: 2.2 })],
      desc: "Flicks the butt across the shin from a low guard.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 24, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88, shoulderF: 74, elbowF: 22, weapon: 10, offX: 4 }),
        kf(9, { ...STANCE, crouch: 1, torso: 20, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88, shoulderF: 58, elbowF: 40 }, "inOut"),
        kf(13, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88 }),
      ],
    },
    {
      id: "2B",
      name: "Ankle Sweep",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 23,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [9, 21],
      hits: [hit(8, 11, bx(24, 6, 78, 22), 50, { guard: "low", fx: "blunt", pushX: 3.8, hitstun: 17 })],
      desc: "The blade run flat along the ground at both his ankles.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 10, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88, shoulderF: 14, elbowF: 70, weapon: 70 }),
        kf(8, { ...STANCE, crouch: 1, torso: 28, hipF: 42, kneeF: 82, hipB: -24, kneeB: 88, shoulderF: 56, elbowF: 6, weapon: -30, offX: 7 }, "out"),
        kf(15, { ...STANCE, crouch: 1, torso: 20, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88, shoulderF: 46, elbowF: 34, weapon: 8 }, "inOut"),
        kf(23, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88 }),
      ],
    },
    {
      id: "2C",
      name: "Leg Reap",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 29,
      cancelInto: ["special", "super"],
      cancelWindow: [13, 25],
      hits: [hit(11, 15, bx(20, 2, 92, 22), 72, { guard: "low", knockdown: "sweep", fx: "blunt", pushX: 5.4 })],
      desc: "Turns the whole shaft through the floor. Knocks them down at a range they cannot answer from.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88 }, "out"),
        kf(5, { ...STANCE, crouch: 1, torso: 24, hipF: 12, kneeF: 96, hipB: -34, kneeB: 100, offX: -3 }),
        kf(11, { ...STANCE, crouch: 1, torso: 30, spin: -10, hipF: 86, kneeF: 6, hipB: -38, kneeB: 104, shoulderF: 40, elbowF: 12, weapon: -20, offX: 7 }, "out"),
        kf(20, { ...STANCE, crouch: 1, torso: 22, hipF: 50, kneeF: 52, hipB: -28, kneeB: 94 }, "inOut"),
        kf(29, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 78, hipB: -24, kneeB: 88 }),
      ],
    },
    {
      id: "6B",
      name: "Rising Butt",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "overhead"],
      priority: 10,
      duration: 32,
      vel: [{ at: 6, x: 2.8 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [18, 29],
      hits: [hit(17, 21, bx(20, 34, 60, 46), 56, { guard: "overhead", fx: "blunt", pushX: 4.6, hitstun: 20 })],
      desc: "Steps in and drives the carved end up over the guard. Blocked standing.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, crouch: 0.5, torso: 16, shoulderF: 30, elbowF: 60, weapon: 70 }),
        kf(13, { ...STANCE, free: 1, offY: 10, torso: -14, shoulderF: 10, elbowF: 80, weapon: 104, hipF: 96, kneeF: 20 }, "out"),
        kf(17, { ...STANCE, free: 1, offY: 3, torso: 28, shoulderF: 112, elbowF: 0, weapon: -22, hipF: 30, kneeF: 8, offX: 5 }, "out"),
        kf(24, { ...STANCE, offY: 0, torso: 14, hipF: 34, kneeF: 40 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Upward Rau",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 28],
      hits: [hit(10, 14, bx(16, 40, 58, 76), 68, { launch: [2, 12], knockdown: "launch", fx: "blunt", hitstun: 26 })],
      desc: "Blade up through the jaw from a low stance. Launches them for the follow-up.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 26, kneeF: 54 }, "out"),
        kf(5, { ...STANCE, crouch: 0.8, torso: 18, shoulderF: 16, elbowF: 62, weapon: 64 }),
        kf(10, { ...STANCE, torso: -16, shoulderF: 150, elbowF: -6, weapon: -46, shoulderB: 150, elbowB: 4, hipF: 20, kneeF: 14, offY: 4 }, "out"),
        kf(20, { ...STANCE, torso: -6, shoulderF: 110, elbowF: 18, weapon: -10 }),
        kf(26, { ...STANCE, torso: 2, shoulderF: 70, elbowF: 34, weapon: 24 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "6A",
      name: "Stepping Jab",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 21,
      vel: [{ at: 2, x: 2.2 }],
      friction: 0.88,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [7, 19],
      followUps: [{ button: "A", move: "5A", from: 7, to: 18, string: "Both Ends" }],
      hits: [hit(6, 8, bx(26, 54, 56, 24), 28, { guard: "high", fx: "blunt", pushX: 3, hitstun: 13, hitstop: 5 })],
      desc: "Slides in behind the point of the blade. Fast, and it keeps him at his range.",
      notation: "→ + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderF: 34, elbowF: 58, weapon: 62, torso: -2, offX: -2 }, "out"),
        kf(6, { ...STANCE, shoulderF: 84, elbowF: 2, weapon: 4, shoulderB: 116, elbowB: 6, torso: 16, hipF: 26, offX: 8 }, "out"),
        kf(12, { ...STANCE, shoulderF: 66, elbowF: 26, weapon: 28, torso: 10, offX: 5 }, "inOut"),
        kf(21, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Turning Blade",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 42,
      armor: [{ from: 9, to: 19, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 9, x: 5 }, { at: 27, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [22, 38],
      hits: [hit(17, 21, bx(20, 22, 84, 68), 92, { guard: "mid", fx: "blunt", pushX: 17, hitstun: 24, hitstop: 12, knockdown: "wallbounce", shake: 2.2 })],
      desc: "Walks through one hit and turns the whole weapon over into them. Puts them in the wall.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(9, { ...STANCE, shoulderF: 6, elbowF: 88, weapon: 96, torso: -16, hipB: -32, kneeB: 50, offX: -6 }, "out"),
        kf(17, { ...STANCE, shoulderF: 100, elbowF: 2, weapon: -16, shoulderB: 132, elbowB: 8, torso: 32, hipF: 44, kneeF: 22, offX: 12 }, "out"),
        kf(26, { ...STANCE, shoulderF: 86, elbowF: 18, weapon: 4, torso: 24, offX: 8 }),
        kf(34, { ...STANCE, shoulderF: 64, elbowF: 36, weapon: 28, torso: 10, offX: 3 }, "inOut"),
        kf(42, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Withdraw Jab",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 23,
      vel: [{ at: 1, x: -2.6 }],
      friction: 0.86,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [9, 21],
      hits: [hit(9, 11, bx(24, 50, 62, 28), 36, { guard: "mid", fx: "blunt", pushX: 6, hitstun: 15, hitstop: 6 })],
      desc: "Gives a step and leaves the blade where he was standing.",
      notation: "← + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -8, shoulderF: 22, elbowF: 64, weapon: 68, hipB: -28, kneeB: 42, offX: -6 }, "out"),
        kf(9, { ...STANCE, torso: 6, shoulderF: 82, elbowF: 6, weapon: 6, hipF: 24, kneeF: 22, offX: -3 }, "out"),
        kf(15, { ...STANCE, torso: 2, shoulderF: 62, elbowF: 30, weapon: 30, offX: -4 }, "inOut"),
        kf(23, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Back Kick",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 31,
      vel: [{ at: 1, x: -3.2 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [17, 28],
      hits: [hit(13, 16, bx(24, 44, 64, 30), 56, { guard: "mid", fx: "blunt", pushX: 7, hitstun: 18, hitstop: 8 })],
      desc: "Steps off the line and snaps the lead foot out at whatever followed him.",
      notation: "← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, hipF: 64, kneeF: 100, torso: -14, hipB: -34, kneeB: 48, offX: -8 }, "inOut"),
        kf(13, { ...STANCE, hipF: 94, kneeF: 12, hipB: -26, kneeB: 22, torso: -16, head: 6, offX: -4 }, "out"),
        kf(18, { ...STANCE, hipF: 88, kneeF: 16, torso: -14, offX: -6 }),
        kf(24, { ...STANCE, hipF: 44, kneeF: 54, torso: -2, offX: -4 }, "inOut"),
        kf(31, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Falling Blade",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 46,
      cancelInto: ["special", "super"],
      cancelWindow: [28, 42],
      hits: [hit(21, 24, bx(16, 20, 92, 86), 100, { guard: "overhead", fx: "blunt", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 })],
      desc: "Lifts the whole length overhead and drops it. Slow, and blocked standing only.",
      notation: "← + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(9, { ...STANCE, shoulderF: 4, elbowF: 92, weapon: 110, shoulderB: 34, elbowB: 80, torso: -14, offX: -5 }, "inOut"),
        kf(16, { ...STANCE, shoulderF: -12, elbowF: 100, weapon: 128, torso: -22, hipB: -28, kneeB: 40, offY: 4, offX: -3 }, "out"),
        kf(21, { ...STANCE, shoulderF: 116, elbowF: -4, weapon: -30, shoulderB: 140, elbowB: 4, torso: 34, hipF: 36, kneeF: 18, offX: 6 }, "out"),
        kf(28, { ...STANCE, shoulderF: 96, elbowF: 12, weapon: -6, torso: 26, offX: 4 }),
        kf(38, { ...STANCE, shoulderF: 62, elbowF: 36, weapon: 26, torso: 8 }, "inOut"),
        kf(46, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Tap",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 18,
      airborne: true,
      landCancel: true,
      landRecovery: 3,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [5, 16],
      hits: [hit(5, 10, bx(18, 30, 52, 28), 28, { fx: "blunt", hitstun: 14, pushX: 2.2 })],
      desc: "Short jab of the butt end on the way through the air.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 34, kneeF: 46, hipB: -24, kneeB: 46 }, "out"),
        kf(5, { ...STANCE, free: 1, shoulderF: 76, elbowF: 12, weapon: 16, torso: 12 }),
        kf(12, { ...STANCE, free: 1, shoulderF: 58, elbowF: 34, weapon: 34, torso: 6 }, "inOut"),
        kf(18, { ...STANCE, free: 1, hipF: 34, kneeF: 46, hipB: -24, kneeB: 46 }),
      ],
    },
    {
      id: "jB",
      name: "Air Sweep",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 24,
      airborne: true,
      landCancel: true,
      landRecovery: 5,
      cancelInto: ["heavy", "special"],
      hits: [hit(7, 14, bx(22, 16, 74, 40), 54, { fx: "blunt", pushX: 3.8, hitstun: 18 })],
      desc: "Swings the blade out flat underneath him.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 32, kneeF: 44, hipB: -22, kneeB: 42 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderF: 16, elbowF: 66, weapon: 72, torso: -8 }),
        kf(8, { ...STANCE, free: 1, shoulderF: 62, elbowF: 4, weapon: -24, torso: 20, hipF: 40 }, "out"),
        kf(16, { ...STANCE, free: 1, shoulderF: 56, elbowF: 30, weapon: 14, torso: 8 }, "inOut"),
        kf(24, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "jC",
      name: "Falling Rau",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 28,
      airborne: true,
      landCancel: true,
      landRecovery: 7,
      hits: [
        hit(8, 18, bx(8, 2, 64, 50), 76, {
          guard: "overhead",
          fx: "blunt",
          knockdown: "soft",
          pushX: 4.6,
          shake: 1.5,
        }),
      ],
      desc: "Brings the blade down the whole way to the floor. His jump-in.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, torso: -18, shoulderF: -6, elbowF: 96, weapon: 118, hipF: 40, kneeF: 56 }),
        kf(8, { ...STANCE, free: 1, torso: 30, shoulderF: 96, elbowF: 0, weapon: -50, hipF: 14, kneeF: 18 }, "out"),
        kf(28, { ...STANCE, free: 1, torso: 24, shoulderF: 88, elbowF: 6, weapon: -46 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Running Strike",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command"],
      priority: 12,
      duration: 32,
      vel: [
        { at: 3, x: 10 },
        { at: 16, x: 0 },
      ],
      friction: 0.9,
      hits: [hit(8, 13, bx(24, 26, 78, 46), 68, { fx: "blunt", pushX: 6.5, knockdown: "soft", hitstun: 21, shake: 1.4 })],
      desc: "Closes with the blade already coming round.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 26, crouch: 0.4, shoulderF: 12, elbowF: 76, weapon: 78, offX: -3 }),
        kf(8, { ...STANCE, torso: 32, crouch: 0.3, shoulderF: 92, elbowF: 2, weapon: -14, hipF: 46, kneeF: 24, offX: 8 }, "out"),
        kf(22, { ...STANCE, torso: 16, shoulderF: 64, elbowF: 34, weapon: 30, offX: 3 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },

    // -------------------------------------------------------- five specials
    {
      id: "longThrust",
      name: "Long Thrust",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 20,
      duration: 34,
      vel: [{ at: 8, x: 4.2 }, { at: 20, x: 0 }],
      friction: 0.92,
      hits: [hit(11, 15, bx(36, 46, 118, 24), 74, { fx: "pierce", pushX: 9, hitstun: 22, hitstop: 9, shake: 1.4 })],
      desc: "Drops the weight forward and puts the point out further than anyone expects. His whole game is making them respect this.",
      notation: "↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 22, elbowF: 62, weapon: 58, shoulderB: 60, elbowB: 62, torso: -12, offX: -5 }, "inOut"),
        // Arm and weapon unwind together so the shaft holds its line out.
        kf(11, { ...STANCE, shoulderF: 84, elbowF: 0, weapon: -4, shoulderB: 118, elbowB: 2, torso: 14, hipF: 40, kneeF: 18, offX: 9 }, "out"),
        kf(18, { ...STANCE, shoulderF: 82, elbowF: 2, weapon: -2, torso: 12, hipF: 34, offX: 7 }),
        kf(26, { ...STANCE, shoulderF: 64, elbowF: 30, weapon: 28, torso: 4, offX: 3 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },
    {
      id: "whiti",
      name: "Turn Through",
      input: { button: "C", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 22,
      duration: 40,
      hits: [
        hit(10, 13, bx(26, 40, 82, 34), 42, { group: 1, fx: "blunt", pushX: 2, hitstun: 18, hitstop: 5 }),
        hit(20, 24, bx(22, 24, 88, 56), 74, {
          group: 2,
          fx: "blunt",
          pushX: 9,
          knockdown: "hard",
          hitstun: 24,
          shake: 1.9,
        }),
      ],
      desc: "One end and then the other, turned through the middle. The second half knocks down.",
      notation: "↓↘→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderF: 20, elbowF: 66, weapon: 70, torso: -10, offX: -3 }),
        kf(10, { ...STANCE, shoulderF: 92, elbowF: 2, weapon: -8, torso: 20, hipF: 30, offX: 6 }, "out"),
        kf(16, { ...STANCE, spin: -12, shoulderF: 30, elbowF: 60, weapon: 80, torso: -6, offX: 2 }, "inOut"),
        kf(20, { ...STANCE, spin: -22, shoulderF: 112, elbowF: -6, weapon: -34, shoulderB: 140, elbowB: 4, torso: 30, hipF: 40, kneeF: 20, offX: 9 }, "out"),
        kf(30, { ...STANCE, spin: -8, shoulderF: 74, elbowF: 26, weapon: 22, torso: 14, offX: 4 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "mereDraw",
      name: "Mere Pounamu",
      input: { button: "A", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 24,
      duration: 26,
      resourceCost: 1,
      resourceMin: 1,
      showProps: ["mere"],
      hits: [
        hit(5, 8, bx(10, 46, 44, 32), 58, { group: 1, fx: "blunt", pushX: 3, hitstun: 20, hitstop: 8 }),
        hit(9, 12, bx(8, 40, 46, 40), 62, {
          group: 2,
          fx: "blunt",
          pushX: 7,
          knockdown: "hard",
          hitstun: 24,
          hitstop: 11,
          shake: 1.7,
        }),
      ],
      desc: "Lets the taiaha hang and takes them at arm's length with the greenstone instead. Five frames, and it does not care that they are inside his reach. Costs one Mana.",
      notation: "↓↙← + A",
      frames: [
        kf(0, { ...STANCE, crouch: 0.3 }, "out"),
        kf(5, { ...STANCE, shoulderB: 34, elbowB: 6, weaponBack: -20, shoulderF: 40, elbowF: 62, torso: 22, hipF: 30, offX: 5 }, "out"),
        kf(9, { ...STANCE, shoulderB: 96, elbowB: -6, weaponBack: -40, shoulderF: 36, elbowF: 66, torso: 30, hipF: 36, kneeF: 20, offX: 8 }, "out"),
        kf(16, { ...STANCE, shoulderB: 62, elbowB: 30, weaponBack: -4, torso: 16, offX: 4 }, "inOut"),
        kf(26, { ...STANCE }),
      ],
    },
    {
      // Not "parry" - that id belongs to the universal deflect every fighter
      // carries, and two moves answering to one id is a real bug waiting.
      id: "turnBlade",
      name: "Turn the Blade",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 26,
      duration: 30,
      parryWindow: [3, 12],
      friction: 0.84,
      resourceGain: 1,
      vfx: [{ at: 3, kind: "spark", x: 30, y: 52, scale: 0.9, color: "#6fd3a4" }],
      desc: "Catches what is coming on the shaft and turns it off the line. Deflects, and the read is worth one Mana.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderF: 62, elbowF: 58, weapon: 86, shoulderB: 84, elbowB: 52, torso: 4, crouch: 0.3, offX: -3 }, "out"),
        kf(12, { ...STANCE, shoulderF: 44, elbowF: 70, weapon: 96, torso: -6, offX: -5 }, "inOut"),
        kf(20, { ...STANCE, shoulderF: 56, elbowF: 46, weapon: 56, torso: 2 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "leapStrike",
      name: "Leaping Rau",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 26,
      duration: 46,
      airborne: true,
      invuln: [{ from: 1, to: 7, kind: "strike" }],
      vel: [
        { at: 1, x: 3, y: 12.2 },
        { at: 26, y: -1, mode: "add" },
      ],
      hits: [
        hit(4, 10, bx(12, 40, 62, 80), 82, { launch: [2, 11], knockdown: "launch", fx: "blunt", hitstun: 26, shake: 1.8 }),
        hit(11, 18, bx(10, 56, 56, 66), 34, { group: 2, launch: [1.6, 5.5], fx: "blunt", hitstun: 18 }),
      ],
      desc: "Comes up off the back foot with the blade leading. Invincible for the first frames - his only real reversal.",
      notation: "→↓↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.7, hipF: 26, kneeF: 54 }, "out"),
        kf(4, { ...STANCE, free: 1, torso: -18, shoulderF: 150, elbowF: -8, weapon: -46, shoulderB: 152, elbowB: 4, hipF: 46, kneeF: 62, hipB: -32, kneeB: 44 }, "out"),
        kf(16, { ...STANCE, free: 1, torso: -22, shoulderF: 162, elbowF: -12, weapon: -52, hipF: 36, kneeF: 74 }),
        kf(32, { ...STANCE, free: 1, torso: -4, shoulderF: 108, elbowF: 20, weapon: -6, hipF: 32, kneeF: 48 }, "inOut"),
        kf(46, { ...STANCE, free: 1 }),
      ],
    },

    // ----------------------------------------------------------------- skill
    {
      id: "wero",
      name: "Wero",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill"],
      priority: 18,
      duration: 34,
      friction: 0.8,
      resourceGain: 1,
      meterGain: 22,
      vfx: [{ at: 4, kind: "spark", x: 16, y: 60, scale: 1.1, color: "#6fd3a4" }],
      desc: "SKILL. The challenge, thrown down before anything starts. Stands his ground, takes back one Mana and builds meter - and tells them exactly where the line is.",
      notation: "A + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, crouch: 0.55, torso: 16, head: 4, shoulderF: 34, elbowF: 40, weapon: 76, shoulderB: 74, elbowB: 40, hipF: 40, kneeF: 46, hipB: -38, kneeB: 52, offX: -2 }, "out"),
        kf(14, { ...STANCE, crouch: 0.5, torso: 22, head: 6, shoulderF: 96, elbowF: 10, weapon: 6, shoulderB: 120, elbowB: 12, hipF: 44, kneeF: 44, hipB: -40, kneeB: 50, offX: 4 }, "out"),
        kf(24, { ...STANCE, crouch: 0.4, torso: 14, head: 2, shoulderF: 60, elbowF: 34, weapon: 46 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "The Whole Length",
      input: { button: "S", motion: "dd", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 104,
      meterCost: 100,
      superFreeze: 42,
      invuln: [{ from: 1, to: 14, kind: "strike" }],
      vel: [
        { at: 6, x: 9 },
        { at: 30, x: 5 },
        { at: 56, x: 4 },
        { at: 74, x: 0 },
      ],
      friction: 0.93,
      hits: [
        hit(13, 17, bx(26, 42, 92, 34), 52, { group: 1, fx: "blunt", pushX: 1, hitstun: 20, hitstop: 5 }),
        hit(25, 29, bx(24, 22, 92, 34), 44, { group: 2, guard: "low", fx: "blunt", pushX: 1, hitstun: 18, hitstop: 4 }),
        hit(37, 41, bx(24, 44, 88, 40), 44, { group: 3, fx: "blunt", pushX: 1, hitstun: 18, hitstop: 4 }),
        hit(49, 53, bx(22, 34, 92, 50), 48, { group: 4, fx: "blunt", pushX: 1, hitstun: 18, hitstop: 5 }),
        hit(64, 70, bx(16, 14, 96, 84), 136, {
          group: 5,
          fx: "blunt",
          pushX: 12,
          knockdown: "hard",
          launch: [6, 8.5],
          hitstop: 17,
          shake: 3,
        }),
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 50, scale: 2.4, color: "#6fd3a4" },
        { at: 64, kind: "explode", x: 54, y: 46, scale: 1.3 },
      ],
      desc: "SUPER. High, low, high, and then the length of it brought down through the middle.",
      notation: "↓↓ + S (100 meter)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5, torso: -10 }, "out"),
        kf(7, { ...STANCE, shoulderF: 16, elbowF: 70, weapon: 74, torso: -12, offX: -4 }, "out"),
        kf(13, { ...STANCE, shoulderF: 96, elbowF: 0, weapon: -12, torso: 24, hipF: 38, offX: 8 }, "out"),
        kf(20, { ...STANCE, crouch: 0.5, shoulderF: 24, elbowF: 62, weapon: 66, torso: 8 }, "inOut"),
        kf(25, { ...STANCE, crouch: 0.7, shoulderF: 54, elbowF: 8, weapon: -26, torso: 30, hipF: 46, kneeF: 40, offX: 7 }, "out"),
        kf(33, { ...STANCE, shoulderF: 20, elbowF: 66, weapon: 72, torso: -8 }, "inOut"),
        kf(37, { ...STANCE, spin: -10, shoulderF: 104, elbowF: -2, weapon: -20, torso: 26, offX: 7 }, "out"),
        kf(45, { ...STANCE, shoulderF: 26, elbowF: 60, weapon: 68, torso: -6 }, "inOut"),
        kf(49, { ...STANCE, spin: 10, shoulderF: 88, elbowF: 4, weapon: -10, torso: 28, hipF: 40, offX: 8 }, "out"),
        kf(58, { ...STANCE, shoulderF: -14, elbowF: 100, weapon: 130, torso: -24, hipB: -32, kneeB: 48, offX: -6 }, "inOut"),
        kf(64, { ...STANCE, shoulderF: 120, elbowF: -6, weapon: -36, shoulderB: 144, elbowB: 2, torso: 36, hipF: 46, kneeF: 24, hipB: -24, kneeB: 54, offX: 12 }, "out"),
        kf(84, { ...STANCE, shoulderF: 74, elbowF: 26, weapon: 22, torso: 14, offX: 4 }, "inOut"),
        kf(104, { ...STANCE }),
      ],
    },
  ],
};
