/**
 * Batu Khenbish - horse archer.
 *
 * The roster's true zoner. She holds a charge in her back leg the whole match
 * and cashes it in as an arrow that goes through anything, and the floor in
 * front of her is never really safe to stand on. Her Quiver is finite: six
 * arrows, refilled slowly while she is not shooting, so the pressure on her is
 * to make each one worth the walk backwards it cost.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const FELT = "#5c6f4a";
const DEEL = "#7d5a2e";
const TRIM = "#c8a24a";
const HORN = "#3b2a1c";
const SHAFT = "#d8c79b";

const STANCE = {
  torso: 2,
  head: -2,
  hipF: 14,
  kneeF: 18,
  hipB: -22,
  kneeB: 34,
  // Bow arm out front, string hand back by the jaw.
  shoulderF: 90,
  elbowF: 0,
  shoulderB: 58,
  elbowB: 92,
  weapon: 0,
};

/** Keeps the bow out of her ribs during the universal moves. */
const IDLE_ARMS = { shoulderF: 86, elbowF: 6, weapon: 0 };

export const MONGOL: FighterDef = {
  id: "mongol",
  name: "Subutai",
  title: "Orlok of the Right Hand",
  era: "Kalka River, 1223",
  bio: "Rose from a blacksmith's son to Genghis Khan's finest field commander. Broke the Rus and the Cumans at the Kalka, then twenty years later broke Hungary at Mohi. Manoeuvres you into a place you chose yourself.",
  archetype: "Zoner / Charge",
  difficulty: 4,
  strengths: ["Controls the full screen", "Charged arrow goes through projectiles", "Caltrops make the floor hers"],
  weaknesses: ["Almost nothing up close", "Six arrows and no more", "Must hold back to threaten"],
  winQuote: "You went where I wanted. You always were going to.",
  palette: {
    body: "#e8d5b4",
    outline: "#161009",
    accent: TRIM,
    cloth: DEEL,
    metal: "#b9c2cc",
    aura: "#9be0a0",
  },
  stats: {
    health: 950,
    walkF: 2.55,
    walkB: 3.0,
    dashSpeed: 8.2,
    dashFrames: 15,
    backdashFrames: 20,
    jumpVel: 12.1,
    jumpFwd: 4.6,
    gravity: 0.62,
    weight: 1,
    airMoves: 1,
    doubleJump: false,
    airDash: false,
    width: 19,
    standHeight: 103,
    crouchHeight: 63,
    scale: 1,
  },
  stance: STANCE,
  // Nothing to block with but the bow, so the stave comes up across the face.
  clips: guardClips({
    high: { torso: -2, head: -6, shoulderF: 24, elbowF: 118, weapon: 6, shoulderB: 14, elbowB: 132, hipF: 12, kneeF: 22, hipB: -20, kneeB: 34, offX: -2 },
    low: { torso: 8, head: -5, shoulderF: 30, elbowF: 110, weapon: 6, shoulderB: 20, elbowB: 126, hipF: 32, kneeF: 74, hipB: -22, kneeB: 84, offX: -2 },
  }),
  resource: {
    name: "Quiver",
    // A hundred arrows - a campaign quiver rather than a handful. He is a
    // horse archer; running dry mid-round is not the thing that beats him.
    max: 100,
    start: 100,
    // Spent shafts get picked up between exchanges, slowly.
    regen: 0.02,
    regenIdleOnly: true,
    color: SHAFT,
    pips: true,
  },
  props: [
    {
      id: "hat",
      attach: "head",
      // Fur-trimmed cap with the upturned brim split at the front.
      parts: [
        { geo: "cone", size: [12, 17], pos: [0, 9], color: FELT },
        { geo: "poly", size: [-8, 5, 8, 4, 6, -5, -6, -5], pos: [0, 7], color: "#4a5b3c" },
        { geo: "poly", size: [-14, 4, -6, 6, 6, 6, 14, 4, 12, -4, -12, -4], pos: [0, 2], color: "#3c3226" },
        { geo: "box", size: [26, 2], pos: [0, 5], color: "#6a5c46" },
        { geo: "disc", size: [3.2], pos: [0, 18], color: TRIM },
        // Ear flaps tied up behind.
        { geo: "poly", size: [-4, 6, 4, 5, 3, -7, -4, -6], pos: [-12, -2], rot: 14, color: "#3c3226", behind: true },
      ],
    },
    {
      id: "deel",
      attach: "torso",
      // Deel wrapped right over left, with a lamellar plate laced over the
      // chest and the sash holding the whole thing shut.
      parts: [
        { geo: "poly", size: [-14, -17, 14, -17, 15, 6, 10, 17, -10, 17, -15, 6], pos: [0, 3], color: DEEL },
        { geo: "poly", size: [-3, 18, 12, 15, 13, -14, -4, -16], pos: [5, 3], rot: -4, color: "#8f6a38" },
        { geo: "poly", size: [-5, 18, 3, 17, 2, -16, -6, -15], pos: [-8, 3], color: "#6a4a26" },
        // Lamellar scales, laced in a lighter iron so they read against the deel.
        { geo: "poly", size: [-10, -6, 10, -6, 11, 4, 6, 8, -6, 8, -11, 4], pos: [-1, 8], color: "#9aa2ab" },
        { geo: "box", size: [20, 1.6], pos: [-1, 10], color: "#5a636d" },
        { geo: "box", size: [20, 1.6], pos: [-1, 5], color: "#5a636d" },
        { geo: "box", size: [1.6, 15], pos: [-6, 8], color: "#5a636d" },
        { geo: "box", size: [1.6, 15], pos: [3, 8], color: "#5a636d" },
        { geo: "poly", size: [-15, 3, 15, 4, 15, -4, -15, -3], pos: [0, -13], color: TRIM },
        { geo: "disc", size: [2.4], pos: [8, -13], color: "#8f6a24", z: 0.3 },
      ],
    },
    {
      id: "quiver",
      attach: "back",
      // Birch quiver slung at the hip, arrows nock-up.
      parts: [
        { geo: "poly", size: [-7, 18, 7, 17, 6, -17, -7, -18], pos: [-6, 6], rot: -16, color: HORN, behind: true },
        { geo: "box", size: [15, 4], pos: [-3, 22], rot: -16, color: TRIM, behind: true },
        { geo: "box", size: [15, 4], pos: [-9, -10], rot: -16, color: TRIM, behind: true },
        // Fletchings poking out of the top.
        { geo: "box", size: [2.4, 17], pos: [-7, 29], rot: -22, color: SHAFT, behind: true },
        { geo: "poly", size: [-2, 7, 2, 6, 2, -7, -2, -6], pos: [-8, 36], rot: -22, color: "#b04a3a", behind: true },
        { geo: "box", size: [2.4, 17], pos: [-3, 30], rot: -14, color: SHAFT, behind: true },
        { geo: "poly", size: [-2, 7, 2, 6, 2, -7, -2, -6], pos: [-3, 37], rot: -14, color: "#dfe4e9", behind: true },
        { geo: "box", size: [2.4, 16], pos: [1, 29], rot: -8, color: SHAFT, behind: true },
        { geo: "poly", size: [-2, 6, 2, 6, 2, -6, -2, -6], pos: [2, 36], rot: -8, color: "#b04a3a", behind: true },
      ],
    },
    {
      id: "sash",
      attach: "pelvis",
      parts: [
        { geo: "poly", size: [-14, 5, 14, 4, 14, -5, -14, -6], pos: [0, -2], color: TRIM },
        { geo: "poly", size: [-4, 4, 4, 4, 4, -4, -4, -4], pos: [-10, -3], color: "#9a7a2f" },
        { geo: "box", size: [8, 3], pos: [8, -4], color: "#9a7a2f" },
      ],
      cloth: {
        segments: 4,
        segmentLength: 11,
        width: 16,
        endWidth: 7,
        color: TRIM,
        lining: "#8f6a24",
        gravity: 0.46,
        stiffness: 0.55,
        drift: -0.3,
      },
    },
    {
      id: "bow",
      attach: "handF",
      // Recurve, built out of straight segments that kink outwards: grip,
      // two limbs, two reflexed tips, and the string chorded across them.
      parts: [
        { geo: "poly", size: [-4, 7, 3, 6, 3, -6, -4, -7], pos: [-4, 0], color: HORN },
        { geo: "poly", size: [-3, 11, 2, 10, 3, -10, -2, -11], pos: [-7, 15], rot: 12, color: "#4e3823" },
        { geo: "poly", size: [-3, 11, 2, 10, 3, -10, -2, -11], pos: [-7, -15], rot: -12, color: "#4e3823" },
        // Reflexed tips, kicked back the other way.
        { geo: "poly", size: [-2, 7, 2, 6, 2, -6, -2, -7], pos: [-4, 28], rot: -34, color: TRIM },
        { geo: "poly", size: [-2, 7, 2, 6, 2, -6, -2, -7], pos: [-4, -28], rot: 34, color: TRIM },
        // Sinew binding at the grip.
        { geo: "box", size: [8, 2], pos: [-4, 5], color: "#8f7a58" },
        { geo: "box", size: [8, 2], pos: [-4, -5], color: "#8f7a58" },
        // The string chords straight across the belly of the bow.
        { geo: "box", size: [1.6, 62], pos: [2, 0], color: "#efe8d6" },
      ],
    },
    {
      id: "nocked",
      attach: "handF",
      conditional: true,
      parts: [
        { geo: "box", size: [46, 2.6], pos: [22, 0], color: SHAFT },
        { geo: "poly", size: [0, 0, -8, 4, -8, -4], pos: [50, 0], color: "#b9c2cc" },
        { geo: "poly", size: [-2, 5, 2, 4, 2, -5, -2, -4], pos: [2, 0], color: "#b04a3a" },
      ],
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 118,
      backThrowDamage: 132,
      throwRange: 58,
      rollSpeed: 8,
      weaponIdle: IDLE_ARMS,
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Bow Jab",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 12,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 11],
      // Stave Work string continues into 6A.
      followUps: [
        { button: "A", move: "6A", from: 4, to: 9, string: "Stave Work" },
      ],
      hits: [hit(4, 6, bx(18, 54, 46, 20), 26, { fx: "blunt", hitstun: 14, blockstun: 10, pushX: 2.4 })],
      desc: "Pokes the bow tip into their face. Her only fast button, and she needs it.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 92, elbowF: 2, weapon: -30, torso: 10, offX: 3 }),
        kf(8, { ...STANCE, shoulderF: 84, elbowF: 20, torso: 4 }, "inOut"),
        kf(12, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Bow Sweep",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 22,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [8, 20],
      // Bow Sweep string continues into 4C.
      followUps: [
        { button: "C", move: "4C", from: 8, to: 19, string: "Bow Sweep" },
      ],
      hits: [hit(8, 12, bx(20, 44, 62, 34), 50, { fx: "blunt", pushX: 4.6, hitstun: 18 })],
      desc: "Swings the horn limb across at chest height to make room.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 146, elbowF: 40, weapon: 60, torso: -10, offX: -3 }),
        kf(8, { ...STANCE, shoulderF: 60, elbowF: 6, weapon: -50, torso: 20, hipF: 24, offX: 6 }, "out"),
        kf(15, { ...STANCE, shoulderF: 76, elbowF: 22, torso: 8 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Point Blank",
      input: { button: "C", stance: "stand" },
      tags: ["heavy"],
      duration: 32,
      resourceCost: 1,
      resourceMin: 1,
      showProps: ["nocked"],
      cancelInto: ["special", "super"],
      cancelWindow: [14, 28],
      projectiles: [
        {
          at: 13,
          kind: "arrow",
          x: 40,
          y: 62,
          vx: 26,
          vy: 0,
          life: 44,
          box: { x: -14, y: -4, w: 28, h: 9 },
          damage: 78,
          hitstun: 22,
          blockstun: 14,
          chip: 6,
          pushX: 5,
          clashes: true,
          fx: "pierce",
          color: SHAFT,
          trail: "#efe3c2",
        },
      ],
      desc: "Draws and looses without aiming. Costs an arrow, and at this range it does not miss.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderF: 88, elbowF: 4, shoulderB: 78, elbowB: 128, torso: -6, offX: -2 }, "inOut"),
        kf(13, { ...STANCE, shoulderF: 90, elbowF: 0, shoulderB: 40, elbowB: 40, torso: 10, offX: 3 }, "out"),
        kf(22, { ...STANCE, shoulderF: 84, elbowF: 12, shoulderB: 56, elbowB: 84, torso: 4 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Poke",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 13,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 12],
      hits: [hit(4, 6, bx(16, 12, 46, 18), 24, { guard: "low", fx: "blunt", hitstun: 13, blockstun: 10, pushX: 2.2 })],
      desc: "Bow tip along the floor from a crouch.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 14, hipF: 32, kneeF: 76, hipB: -24, kneeB: 88 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 20, hipF: 32, kneeF: 76, hipB: -24, kneeB: 88, shoulderF: 44, elbowF: 6, weapon: -70, offX: 4 }),
        kf(9, { ...STANCE, crouch: 1, torso: 16, hipF: 32, kneeF: 76, hipB: -24, kneeB: 88, shoulderF: 62, elbowF: 24 }, "inOut"),
        kf(13, { ...STANCE, crouch: 1, torso: 14, hipF: 32, kneeF: 76, hipB: -24, kneeB: 88 }),
      ],
    },
    {
      id: "2B",
      name: "Shin Kick",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 22,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [9, 20],
      hits: [hit(8, 11, bx(18, 6, 64, 24), 48, { guard: "low", fx: "blunt", pushX: 4, hitstun: 17 })],
      desc: "Boot to the ankle. Her low confirm into everything.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 14, hipF: 32, kneeF: 76, hipB: -24, kneeB: 88 }, "out"),
        kf(5, { ...STANCE, crouch: 1, torso: 10, hipF: 10, kneeF: 92, hipB: -30, kneeB: 94 }),
        kf(8, { ...STANCE, crouch: 1, torso: 22, hipF: 76, kneeF: 10, hipB: -32, kneeB: 96, offX: 6 }, "out"),
        kf(16, { ...STANCE, crouch: 1, torso: 16, hipF: 46, kneeF: 52, hipB: -26, kneeB: 90 }, "inOut"),
        kf(22, { ...STANCE, crouch: 1, torso: 14, hipF: 32, kneeF: 76, hipB: -24, kneeB: 88 }),
      ],
    },
    {
      id: "2C",
      name: "Stirrup Sweep",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 30,
      cancelInto: ["special", "super"],
      cancelWindow: [13, 26],
      hits: [hit(11, 15, bx(16, 2, 78, 22), 68, { guard: "low", knockdown: "sweep", fx: "blunt", pushX: 5.2 })],
      desc: "Takes their legs and buys her the two seconds she needs to back up.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 14, hipF: 32, kneeF: 76, hipB: -24, kneeB: 88 }, "out"),
        kf(6, { ...STANCE, crouch: 1, torso: 20, hipF: 8, kneeF: 96, hipB: -34, kneeB: 100, offX: -2 }),
        kf(11, { ...STANCE, crouch: 1, torso: 26, hipF: 86, kneeF: 4, hipB: -38, kneeB: 104, shoulderF: 30, elbowF: 20, offX: 5 }, "out"),
        kf(20, { ...STANCE, crouch: 1, torso: 18, hipF: 50, kneeF: 50, hipB: -28, kneeB: 94 }, "inOut"),
        kf(30, { ...STANCE, crouch: 1, torso: 14, hipF: 32, kneeF: 76, hipB: -24, kneeB: 88 }),
      ],
    },
    {
      id: "6B",
      name: "Horn Strike",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "overhead"],
      priority: 10,
      duration: 32,
      vel: [{ at: 6, x: 2.6 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 29],
      hits: [hit(16, 20, bx(18, 38, 54, 44), 56, { guard: "overhead", fx: "blunt", pushX: 4.6, hitstun: 20 })],
      desc: "Brings the top limb of the bow down over their guard. Overhead.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 168, elbowF: 20, weapon: 40, torso: -14, offX: -3 }, "inOut"),
        kf(16, { ...STANCE, shoulderF: 52, elbowF: 4, weapon: -60, torso: 26, hipF: 26, offX: 6 }, "out"),
        kf(24, { ...STANCE, shoulderF: 70, elbowF: 20, torso: 10 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Uppercut Nock",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 28],
      hits: [hit(10, 14, bx(12, 42, 50, 72), 64, { launch: [1.8, 12], knockdown: "launch", fx: "blunt", hitstun: 26 })],
      desc: "Rips the bow up through their chin. Launches - and she has an air arrow waiting.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 50 }, "out"),
        kf(5, { ...STANCE, crouch: 0.8, torso: 16, shoulderF: 30, elbowF: 30, weapon: -70 }),
        kf(10, { ...STANCE, torso: -16, shoulderF: 172, elbowF: 4, weapon: 30, hipF: 18, kneeF: 12, offY: 4 }, "out"),
        kf(20, { ...STANCE, torso: -6, shoulderF: 124, elbowF: 20 }),
        kf(26, { ...STANCE, torso: 0, shoulderF: 92, elbowF: 16 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },
    {
      // Forward and back sets. Forward takes space, back gives it up to buy
      // range or a hard read.
      id: "6A",
      name: "Limb Jab",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 20,
      vel: [{ at: 2, x: 2.2 }],
      friction: 0.88,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [7, 18],
      // Stave Work string continues into 6C.
      followUps: [
        { button: "C", move: "6C", from: 7, to: 17, string: "Stave Work" },
      ],
      hits: [hit(7, 9, bx(20, 60, 44, 26), 32, { guard: "high", fx: "blunt", pushX: 3, hitstun: 14, hitstop: 5 })],
      desc: "Steps in and jabs with the tip of the bow. Buys him the room to draw again.",
      notation: "\u2192 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 56, elbowF: 34, weapon: 40, torso: -2, offX: -2 }, "out"),
        kf(7, { ...STANCE, shoulderF: 92, elbowF: 2, weapon: 0, torso: 14, hipF: 24, kneeF: 18, offX: 7 }, "out"),
        kf(12, { ...STANCE, shoulderF: 84, elbowF: 14, weapon: 16, torso: 10, offX: 5 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Stave Swing",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 40,
      armor: [{ from: 8, to: 18, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 8, x: 5.4 }, { at: 26, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [20, 36],
      hits: [hit(16, 20, bx(18, 22, 64, 68), 86, { guard: "mid", fx: "blunt", pushX: 17, hitstun: 24, hitstop: 12, knockdown: "wallbounce", shake: 2.2 })],
      desc: "Swings the bow like a club and rides it forward. Not what it was made for; it works.",
      notation: "\u2192 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 156, elbowF: -50, weapon: 92, torso: -12, hipB: -30, kneeB: 48, offX: -6 }, "out"),
        kf(16, { ...STANCE, shoulderF: 70, elbowF: 24, weapon: 30, torso: 32, hipF: 40, kneeF: 20, hipB: -26, kneeB: 26, offX: 12 }, "out"),
        kf(24, { ...STANCE, shoulderF: 62, elbowF: 32, weapon: 26, torso: 24, hipF: 28, kneeF: 26, offX: 8 }),
        kf(32, { ...STANCE, shoulderF: 78, elbowF: 12, weapon: 12, torso: 10, offX: 3 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "String Snap",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 22,
      vel: [{ at: 1, x: -2.6 }],
      friction: 0.86,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [8, 20],
      // Loose At Range string continues into 5C.
      followUps: [
        { button: "C", move: "5C", from: 8, to: 19, string: "Loose At Range" },
      ],
      hits: [hit(8, 10, bx(16, 52, 42, 30), 36, { guard: "mid", fx: "blunt", pushX: 6, hitstun: 15, hitstop: 6 })],
      desc: "Steps off and whips the string hand back across their face.",
      notation: "\u2190 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -6, shoulderB: 30, elbowB: 110, hipB: -28, kneeB: 42, offX: -6 }, "out"),
        kf(8, { ...STANCE, torso: 8, shoulderB: 86, elbowB: 26, hipF: 22, kneeF: 20, offX: -3 }, "out"),
        kf(14, { ...STANCE, torso: 2, shoulderB: 66, elbowB: 62, offX: -4 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Held Draw",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 30,
      vel: [{ at: 1, x: -3.4 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      hits: [hit(12, 15, bx(40, 52, 96, 24), 56, { guard: "mid", fx: "blunt", pushX: 7, hitstun: 18, hitstop: 8 })],
      desc: "Backs away with the bow at full extension and lets the tip do the work.",
      notation: "\u2190 + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 64, elbowF: 26, weapon: 44, torso: -12, hipB: -28, kneeB: 42, offX: -8 }, "inOut"),
        kf(12, { ...STANCE, shoulderF: 92, elbowF: -2, weapon: 0, torso: 4, hipF: 24, kneeF: 14, offX: -5 }, "out"),
        kf(17, { ...STANCE, shoulderF: 90, elbowF: 0, weapon: 0, torso: 2, offX: -6 }),
        kf(23, { ...STANCE, shoulderF: 80, elbowF: 14, weapon: 18, torso: 0, offX: -4 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Overhead Stave",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 44,
      cancelInto: ["special", "super"],
      cancelWindow: [26, 40],
      hits: [hit(20, 23, bx(14, 20, 70, 86), 96, { guard: "overhead", fx: "blunt", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 })],
      desc: "Raises the bow in both hands and brings it down. Blocked standing only.",
      notation: "\u2190 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 144, elbowF: -46, weapon: 84, torso: -10, offX: -5 }, "inOut"),
        kf(15, { ...STANCE, shoulderF: 178, elbowF: -18, weapon: 90, torso: -20, hipB: -26, kneeB: 38, offY: 3, offX: -3 }, "out"),
        kf(20, { ...STANCE, shoulderF: 88, elbowF: 8, weapon: 62, torso: 32, hipF: 34, kneeF: 20, hipB: -12, kneeB: 32, offX: 6 }, "out"),
        kf(26, { ...STANCE, shoulderF: 80, elbowF: 12, weapon: 58, torso: 26, offX: 4 }),
        kf(36, { ...STANCE, shoulderF: 84, elbowF: 6, weapon: 20, torso: 8 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Poke",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 17,
      airborne: true,
      landCancel: true,
      landRecovery: 3,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [4, 15],
      hits: [hit(4, 9, bx(14, 32, 46, 26), 28, { fx: "blunt", hitstun: 14, pushX: 2.2 })],
      desc: "Bow tip out in front of her on the way past.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 32, kneeF: 44, hipB: -24, kneeB: 44 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderF: 92, elbowF: 0, weapon: -34, torso: 12 }),
        kf(11, { ...STANCE, free: 1, shoulderF: 78, elbowF: 20, torso: 4 }, "inOut"),
        kf(17, { ...STANCE, free: 1, hipF: 32, kneeF: 44, hipB: -24, kneeB: 44 }),
      ],
    },
    {
      id: "jB",
      name: "Air Kick",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 24,
      airborne: true,
      landCancel: true,
      landRecovery: 4,
      cancelInto: ["heavy", "special"],
      hits: [hit(6, 14, bx(16, 16, 54, 42), 52, { fx: "blunt", pushX: 3.8, hitstun: 18 })],
      desc: "Straight boot out at whoever tried to follow her up.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 32, kneeF: 42, hipB: -22, kneeB: 40 }, "out"),
        kf(4, { ...STANCE, free: 1, hipF: 14, kneeF: 88, torso: 10 }),
        kf(7, { ...STANCE, free: 1, hipF: 88, kneeF: 8, hipB: -30, kneeB: 60, torso: 14 }, "out"),
        kf(16, { ...STANCE, free: 1, hipF: 54, kneeF: 40, torso: 6 }, "inOut"),
        kf(24, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "jC",
      name: "Falling Shot",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air"],
      duration: 28,
      airborne: true,
      landCancel: true,
      landRecovery: 8,
      resourceCost: 1,
      resourceMin: 1,
      showProps: ["nocked"],
      projectiles: [
        {
          at: 9,
          kind: "arrow",
          x: 30,
          y: 24,
          vx: 15,
          vy: -9,
          gravity: 0.2,
          life: 60,
          box: { x: -14, y: -4, w: 28, h: 9 },
          damage: 62,
          hitstun: 20,
          blockstun: 13,
          chip: 5,
          knockdown: "soft",
          clashes: true,
          fx: "pierce",
          color: SHAFT,
          trail: "#efe3c2",
        },
      ],
      desc: "Shoots down at the floor from the top of the jump. Her air-to-ground answer.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, torso: 14, shoulderF: 62, elbowF: 4, shoulderB: 56, elbowB: 126, hipF: 40, kneeF: 56 }, "inOut"),
        kf(9, { ...STANCE, free: 1, torso: 20, shoulderF: 60, elbowF: 0, shoulderB: 24, elbowB: 34, hipF: 30, kneeF: 40 }, "out"),
        kf(28, { ...STANCE, free: 1, torso: 12, shoulderF: 70, elbowF: 14, shoulderB: 50, elbowB: 80 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Riding Shoulder",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command"],
      priority: 12,
      duration: 32,
      vel: [
        { at: 3, x: 9.6 },
        { at: 16, x: 0 },
      ],
      friction: 0.9,
      hits: [hit(8, 13, bx(16, 30, 56, 46), 64, { fx: "blunt", pushX: 7, knockdown: "soft", hitstun: 20, shake: 1.4 })],
      desc: "Puts her shoulder through them to reset the spacing. Not elegant. Effective.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 24, crouch: 0.4, shoulderF: 40, elbowF: 60, offX: -3 }),
        kf(8, { ...STANCE, torso: 34, crouch: 0.3, shoulderF: 20, elbowF: 40, hipF: 44, kneeF: 24, offX: 8 }, "out"),
        kf(22, { ...STANCE, torso: 14, offX: 3 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },

    // -------------------------------------------------------- five specials
    {
      id: "powerShot",
      name: "Heartseeker",
      input: { button: "B", motion: "chargeB", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      priority: 22,
      duration: 40,
      resourceCost: 1,
      resourceMin: 1,
      showProps: ["nocked"],
      friction: 0.9,
      projectiles: [
        {
          at: 14,
          kind: "arrow",
          x: 44,
          y: 62,
          vx: 31,
          vy: 0,
          life: 60,
          box: { x: -18, y: -5, w: 36, h: 11 },
          damage: 94,
          hitstun: 26,
          blockstun: 16,
          chip: 8,
          pushX: 7,
          knockdown: "hard",
          // Goes through fireballs and keeps going: three things stop it.
          hits: 3,
          clashes: false,
          fx: "pierce",
          scale: 1.15,
          color: "#fff4d2",
          trail: "#9be0a0",
        },
      ],
      vfx: [{ at: 14, kind: "spark", x: 46, y: 62, scale: 1.2, color: "#9be0a0" }],
      desc: "Hold back to draw, then forward to loose. Full-screen, ignores other projectiles and knocks them flat.",
      notation: "hold ← then → + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 90, elbowF: 0, shoulderB: 84, elbowB: 138, torso: -10, hipB: -30, offX: -3 }, "inOut"),
        kf(14, { ...STANCE, shoulderF: 90, elbowF: 0, shoulderB: 30, elbowB: 30, torso: 12, hipF: 22, offX: 4 }, "out"),
        kf(26, { ...STANCE, shoulderF: 86, elbowF: 8, shoulderB: 50, elbowB: 70, torso: 4 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "volley",
      name: "Rolling Volley",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      duration: 42,
      resourceCost: 2,
      resourceMin: 2,
      showProps: ["nocked"],
      projectiles: [
        {
          at: 9,
          kind: "arrow",
          x: 40,
          y: 66,
          vx: 22,
          vy: 0,
          life: 56,
          box: { x: -13, y: -4, w: 26, h: 9 },
          damage: 40,
          hitstun: 17,
          blockstun: 12,
          chip: 3,
          clashes: true,
          fx: "pierce",
          color: SHAFT,
          trail: "#efe3c2",
        },
        {
          at: 19,
          kind: "arrow",
          x: 40,
          y: 56,
          vx: 22,
          vy: 0,
          life: 56,
          box: { x: -13, y: -4, w: 26, h: 9 },
          damage: 34,
          hitstun: 17,
          blockstun: 12,
          chip: 3,
          clashes: true,
          fx: "pierce",
          color: SHAFT,
          trail: "#efe3c2",
        },
        {
          at: 29,
          kind: "arrow",
          x: 40,
          y: 46,
          vx: 22,
          vy: 0,
          life: 56,
          box: { x: -13, y: -4, w: 26, h: 9 },
          damage: 34,
          hitstun: 17,
          blockstun: 12,
          chip: 3,
          pushX: 4,
          clashes: true,
          fx: "pierce",
          color: SHAFT,
          trail: "#efe3c2",
        },
      ],
      desc: "Three arrows down a staircase, chest to knee. Two from the quiver - it is the cheap way to hold a corner.",
      notation: "↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderB: 76, elbowB: 130, torso: -6 }, "inOut"),
        kf(9, { ...STANCE, shoulderF: 84, elbowF: 0, shoulderB: 36, elbowB: 40, torso: 8, offX: 3 }, "out"),
        kf(15, { ...STANCE, shoulderB: 74, elbowB: 128, torso: -4 }, "inOut"),
        kf(19, { ...STANCE, shoulderF: 90, elbowF: 0, shoulderB: 34, elbowB: 38, torso: 8, offX: 3 }, "out"),
        kf(25, { ...STANCE, shoulderB: 72, elbowB: 126, torso: -4 }, "inOut"),
        kf(29, { ...STANCE, shoulderF: 98, elbowF: 0, shoulderB: 32, elbowB: 36, torso: 8, offX: 3 }, "out"),
        kf(36, { ...STANCE, shoulderF: 82, elbowF: 14, torso: 2 }, "inOut"),
        kf(42, { ...STANCE }),
      ],
    },
    {
      id: "skyArrow",
      name: "Sky Arrow",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "projectile", "overhead"],
      priority: 18,
      duration: 36,
      resourceCost: 1,
      resourceMin: 1,
      showProps: ["nocked"],
      projectiles: [
        {
          at: 11,
          kind: "arrow",
          x: 26,
          y: 82,
          vx: 9.5,
          vy: 15,
          gravity: 0.44,
          life: 90,
          box: { x: -6, y: -14, w: 12, h: 28 },
          damage: 58,
          hitstun: 22,
          blockstun: 15,
          chip: 5,
          // It comes down on their head, so it has to be blocked standing.
          guard: "overhead",
          knockdown: "soft",
          clashes: false,
          fx: "pierce",
          spin: -6,
          color: SHAFT,
          trail: "#efe3c2",
        },
      ],
      desc: "Loosed almost straight up and it lands on them a second later. Overhead - crouching does nothing about it.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 150, elbowF: 6, weapon: 30, shoulderB: 130, elbowB: 130, torso: -16 }, "inOut"),
        kf(11, { ...STANCE, shoulderF: 156, elbowF: 2, weapon: 34, shoulderB: 96, elbowB: 34, torso: -20, offY: 2 }, "out"),
        kf(22, { ...STANCE, shoulderF: 120, elbowF: 12, torso: -6 }, "inOut"),
        kf(36, { ...STANCE }),
      ],
    },
    {
      id: "caltrops",
      name: "Caltrops",
      input: { button: "A", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "projectile", "low"],
      priority: 18,
      duration: 34,
      projectiles: [
        {
          at: 10,
          kind: "caltrop",
          x: 24,
          y: 44,
          vx: 6.5,
          vy: 3,
          gravity: 0.5,
          life: 150,
          box: { x: -12, y: 0, w: 24, h: 14 },
          damage: 34,
          hitstun: 20,
          blockstun: 14,
          chip: 3,
          guard: "low",
          knockdown: "sweep",
          bounce: 0.24,
          bounces: 2,
          drag: 0.96,
          hits: 1,
          clashes: false,
          fx: "spark",
          color: "#b9c2cc",
        },
        {
          at: 13,
          kind: "caltrop",
          x: 24,
          y: 44,
          vx: 10.5,
          vy: 4.5,
          gravity: 0.5,
          life: 150,
          box: { x: -12, y: 0, w: 24, h: 14 },
          damage: 30,
          hitstun: 20,
          blockstun: 14,
          chip: 3,
          guard: "low",
          knockdown: "sweep",
          bounce: 0.24,
          bounces: 2,
          drag: 0.96,
          hits: 1,
          clashes: false,
          fx: "spark",
          color: "#b9c2cc",
        },
      ],
      desc: "Scatters iron on the floor between them. It sits there. Whoever walks into it goes down, and it costs her no arrows.",
      notation: "↓↙← + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, crouch: 0.5, torso: 18, shoulderB: 20, elbowB: 100 }),
        kf(10, { ...STANCE, crouch: 0.4, torso: 22, shoulderB: 62, elbowB: 20, offX: 3 }, "out"),
        kf(13, { ...STANCE, crouch: 0.35, torso: 20, shoulderB: 76, elbowB: 14, offX: 4 }, "out"),
        kf(22, { ...STANCE, crouch: 0.2, torso: 10, shoulderB: 60, elbowB: 60 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },
    {
      id: "hoofKick",
      name: "Hoof Kick",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 24,
      duration: 42,
      airborne: true,
      invuln: [{ from: 1, to: 8, kind: "strike" }],
      vel: [
        { at: 1, x: 2.2, y: 11.6 },
        { at: 22, y: -0.9, mode: "add" },
      ],
      hits: [
        hit(3, 10, bx(12, 40, 54, 70), 78, { launch: [2, 10], knockdown: "launch", fx: "blunt", hitstun: 25, shake: 1.7 }),
        hit(11, 18, bx(10, 52, 48, 58), 30, { group: 2, launch: [1.2, 4], fx: "blunt" }),
      ],
      desc: "Backwards off an imaginary saddle, both heels through their jaw. Invincible on the way up - it is the only button she has that says no.",
      notation: "→↓↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.7, hipF: 22, kneeF: 52 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -30, spin: -14, hipF: 106, kneeF: 16, hipB: 74, kneeB: 24, shoulderF: 150, elbowF: 30, shoulderB: 140, elbowB: 40 }, "out"),
        kf(16, { ...STANCE, free: 1, torso: -36, spin: -22, hipF: 116, kneeF: 10, hipB: 86, kneeB: 16 }),
        kf(30, { ...STANCE, free: 1, torso: -10, spin: -6, hipF: 50, kneeF: 50, hipB: -10, kneeB: 40 }, "inOut"),
        kf(42, { ...STANCE, free: 1 }),
      ],
    },

    // ----------------------------------------------------------------- skill
    {
      id: "nock",
      name: "Restring",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill"],
      priority: 18,
      duration: 46,
      resourceGain: 25,
      meterGain: 12,
      friction: 0.9,
      desc: "SKILL. Pulls three arrows from the quiver and holds them in the bow hand. Long, and completely defenceless - do it from across the screen.",
      notation: "A + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(10, { ...STANCE, torso: -14, shoulderB: 150, elbowB: 60, shoulderF: 60, elbowF: 40, head: 8 }, "inOut"),
        kf(24, { ...STANCE, torso: -4, shoulderB: 100, elbowB: 110, shoulderF: 70, elbowF: 30 }, "inOut"),
        kf(34, { ...STANCE, torso: 6, shoulderB: 62, elbowB: 96, shoulderF: 86, elbowF: 10 }, "out"),
        kf(46, { ...STANCE }),
      ],
    },

    // ------------------------------------------------------------------- EX
    {
      id: "powerShotEx",
      name: "Heartseeker EX",
      input: { button: "S", motion: "chargeB", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "projectile"],
      priority: 28,
      duration: 44,
      meterCost: 50,
      showProps: ["nocked"],
      friction: 0.9,
      projectiles: [
        {
          at: 12,
          kind: "arrow",
          x: 44,
          y: 62,
          vx: 36,
          vy: 0,
          life: 60,
          box: { x: -22, y: -8, w: 44, h: 17 },
          damage: 118,
          hitstun: 32,
          blockstun: 18,
          chip: 12,
          pushX: 10,
          knockdown: "wallbounce",
          hits: 6,
          clashes: false,
          fx: "pierce",
          scale: 1.4,
          color: "#ffffff",
          trail: "#9be0a0",
          hitstop: 14,
        },
      ],
      vfx: [{ at: 12, kind: "spark", x: 48, y: 62, scale: 2, color: "#9be0a0" }],
      desc: "EX. Costs no arrows, goes through everything on the screen including them, and peels them off the far wall.",
      notation: "hold ← then → + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderF: 90, elbowF: 0, shoulderB: 88, elbowB: 146, torso: -14, hipB: -34, offX: -4 }, "inOut"),
        kf(12, { ...STANCE, shoulderF: 90, elbowF: 0, shoulderB: 26, elbowB: 26, torso: 16, hipF: 26, offX: 5 }, "out"),
        kf(28, { ...STANCE, shoulderF: 86, elbowF: 10, shoulderB: 50, elbowB: 70, torso: 4 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "hoofKickEx",
      name: "Hoof Kick EX",
      input: { button: "S", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "launcher"],
      priority: 30,
      duration: 52,
      meterCost: 50,
      airborne: true,
      invuln: [{ from: 1, to: 18, kind: "strike" }],
      vel: [
        { at: 1, x: 3, y: 13.2 },
        { at: 30, y: -1, mode: "add" },
      ],
      hits: [
        hit(3, 10, bx(12, 38, 58, 78), 66, { launch: [2, 12], knockdown: "launch", fx: "blunt", hitstun: 28, shake: 2 }),
        hit(11, 20, bx(10, 52, 52, 66), 32, { group: 2, launch: [1.2, 5], fx: "blunt" }),
        hit(21, 30, bx(10, 62, 52, 62), 50, { group: 3, launch: [1.6, 4], fx: "blunt", knockdown: "hard" }),
      ],
      desc: "EX. Invincible the whole way up and it carries them with her.",
      notation: "→↓↘ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.7, hipF: 22, kneeF: 52 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -32, spin: -18, hipF: 112, kneeF: 12, hipB: 82, kneeB: 18 }, "out"),
        kf(20, { ...STANCE, free: 1, torso: -40, spin: -30, hipF: 122, kneeF: 8, hipB: 94, kneeB: 12 }),
        kf(38, { ...STANCE, free: 1, torso: -12, spin: -8, hipF: 50, kneeF: 50 }, "inOut"),
        kf(52, { ...STANCE, free: 1 }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "Arrow Storm",
      input: { button: "S", motion: "dd", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 118,
      meterCost: 100,
      superFreeze: 46,
      invuln: [{ from: 1, to: 18, kind: "strike" }],
      friction: 0.9,
      projectiles: [
        // Six flat arrows, faster and faster, then the one she aimed.
        {
          at: 24,
          kind: "arrow",
          x: 44,
          y: 70,
          vx: 26,
          vy: 0,
          life: 60,
          box: { x: -16, y: -6, w: 32, h: 13 },
          damage: 40,
          hitstun: 26,
          blockstun: 15,
          chip: 5,
          hits: 3,
          clashes: false,
          fx: "pierce",
          color: "#fff4d2",
          trail: "#9be0a0",
        },
        {
          at: 32,
          kind: "arrow",
          x: 44,
          y: 62,
          vx: 27,
          vy: 0,
          life: 60,
          box: { x: -16, y: -6, w: 32, h: 13 },
          damage: 36,
          hitstun: 26,
          blockstun: 15,
          chip: 5,
          hits: 3,
          clashes: false,
          fx: "pierce",
          color: "#fff4d2",
          trail: "#9be0a0",
        },
        {
          at: 40,
          kind: "arrow",
          x: 44,
          y: 54,
          vx: 28,
          vy: 0,
          life: 60,
          box: { x: -16, y: -6, w: 32, h: 13 },
          damage: 36,
          hitstun: 26,
          blockstun: 15,
          chip: 5,
          hits: 3,
          clashes: false,
          fx: "pierce",
          color: "#fff4d2",
          trail: "#9be0a0",
        },
        {
          at: 48,
          kind: "arrow",
          x: 44,
          y: 46,
          vx: 29,
          vy: 0,
          life: 60,
          box: { x: -16, y: -6, w: 32, h: 13 },
          damage: 34,
          hitstun: 26,
          blockstun: 15,
          chip: 5,
          hits: 3,
          clashes: false,
          fx: "pierce",
          color: "#fff4d2",
          trail: "#9be0a0",
        },
        {
          at: 56,
          kind: "arrow",
          x: 44,
          y: 38,
          vx: 30,
          vy: 0,
          life: 60,
          box: { x: -16, y: -6, w: 32, h: 13 },
          damage: 34,
          hitstun: 26,
          blockstun: 15,
          chip: 5,
          hits: 3,
          clashes: false,
          fx: "pierce",
          color: "#fff4d2",
          trail: "#9be0a0",
        },
        {
          at: 66,
          kind: "arrow",
          x: 46,
          y: 58,
          vx: 34,
          vy: 0,
          life: 70,
          box: { x: -26, y: -12, w: 52, h: 25 },
          damage: 150,
          hitstun: 40,
          blockstun: 22,
          chip: 16,
          pushX: 12,
          knockdown: "wallbounce",
          hits: 6,
          clashes: false,
          fx: "pierce",
          scale: 1.6,
          hitstop: 20,
          color: "#ffffff",
          trail: "#9be0a0",
        },
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 52, scale: 2.4, color: "#9be0a0" },
        { at: 66, kind: "spark", x: 50, y: 58, scale: 2.4, color: "#ffffff" },
      ],
      desc: "SUPER. She empties the quiver down one line and then puts the last arrow through the hole the others made.",
      notation: "↓↓ + S (with 100 meter)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.4, torso: -10 }, "out"),
        kf(18, { ...STANCE, shoulderF: 90, elbowF: 0, shoulderB: 86, elbowB: 140, torso: -12, offX: -3 }, "inOut"),
        kf(24, { ...STANCE, shoulderF: 90, elbowF: 0, shoulderB: 34, elbowB: 34, torso: 10, offX: 3 }, "out"),
        kf(32, { ...STANCE, shoulderF: 92, elbowF: 0, shoulderB: 30, elbowB: 32, torso: 10, offX: 3 }, "out"),
        kf(40, { ...STANCE, shoulderF: 96, elbowF: 0, shoulderB: 28, elbowB: 30, torso: 8, offX: 4 }, "out"),
        kf(48, { ...STANCE, shoulderF: 104, elbowF: 0, shoulderB: 26, elbowB: 28, torso: 6, offX: 4 }, "out"),
        kf(56, { ...STANCE, shoulderF: 112, elbowF: 0, shoulderB: 24, elbowB: 26, torso: 4, offX: 4 }, "out"),
        kf(62, { ...STANCE, shoulderF: 92, elbowF: 0, shoulderB: 92, elbowB: 150, torso: -18, hipB: -36, offX: -5 }, "inOut"),
        kf(66, { ...STANCE, shoulderF: 92, elbowF: 0, shoulderB: 20, elbowB: 20, torso: 20, hipF: 30, offX: 8 }, "out"),
        kf(92, { ...STANCE, shoulderF: 86, elbowF: 10, shoulderB: 48, elbowB: 72, torso: 4 }, "inOut"),
        kf(118, { ...STANCE }),
      ],
    },
  ],
};
