/**
 * Nai Khanom Tom - Muay Boran fighter.
 *
 * Nothing in her hands but the wraps and cords already on them: elbows,
 * knees and shins, thrown from a stance that never stops bouncing. Her
 * Rhythm bar fills as she lands, and her best tools only open up once she
 * is already winning the exchange.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const SILK = "#c8352f";
const GOLD = "#e0b13a";
const ROPE = "#e8dfc8";

const STANCE = {
  torso: 4,
  head: -3,
  hipF: 12,
  kneeF: 14,
  hipB: -16,
  kneeB: 26,
  // High guard: elbows in, fists at cheek height rather than on top of her
  // own head, so the face and the mongkhon still read.
  shoulderF: 34,
  elbowF: 118,
  shoulderB: 16,
  elbowB: 118,
};

export const MUAYTHAI: FighterDef = {
  id: "muaythai",
  name: "Nai Khanom Tom",
  title: "The Ten Bouts",
  era: "Ava, 1774",
  bio: "Taken prisoner when Ayutthaya fell and made to fight before the Burmese court. Beat the first champion, then nine more in succession without leaving the ring, and was freed for it.",
  archetype: "Rushdown / Clinch",
  difficulty: 3,
  strengths: ["Fastest normals in the roster", "Clinch converts anywhere", "Rhythm rewards pressure"],
  weaknesses: ["Shortest reach", "No projectile at all", "Must earn every inch"],
  winQuote: "That was one. Line up the other nine.",
  palette: {
    body: "#f2e5d0",
    outline: "#191310",
    accent: SILK,
    cloth: SILK,
    metal: GOLD,
    aura: "#ffca6b",
  },
  stats: {
    health: 940,
    walkF: 3.3,
    walkB: 2.6,
    dashSpeed: 9.2,
    dashFrames: 13,
    backdashFrames: 18,
    jumpVel: 12.3,
    jumpFwd: 5,
    gravity: 0.63,
    weight: 0.95,
    airMoves: 2,
    doubleJump: false,
    airDash: false,
    width: 19,
    standHeight: 102,
    crouchHeight: 64,
    scale: 0.99,
  },
  stance: STANCE,
  // Thai high guard: forearms vertical, fists at the cheeks, elbows in
  // front of the ribs.
  clips: guardClips({
    high: { torso: -2, head: -7, shoulderF: 34, elbowF: 142, shoulderB: 18, elbowB: 146, hipF: 12, kneeF: 22, hipB: -16, kneeB: 32, offX: -2 },
    low: { torso: 8, head: -5, shoulderF: 40, elbowF: 132, shoulderB: 24, elbowB: 138, hipF: 32, kneeF: 74, hipB: -20, kneeB: 84, offX: -2 },
  }),
  resource: {
    name: "Rhythm",
    max: 100,
    start: 0,
    gainOnHit: 9,
    gainOnBlocked: 4,
    gainOnTakeHit: 3,
    color: "#ffca6b",
  },
  props: [
    {
      id: "mongkhon",
      attach: "head",
      // The mongkhon: a blessed cord worn into the ring and never touched by
      // anyone but her, with the tail hanging down behind.
      parts: [
        // Worn high on the crown like a headband, not slung round the face.
        { geo: "ring", size: [10, 2.6], pos: [0, 5], color: GOLD },
        { geo: "poly", size: [-4, 2.5, 4, 2, 3.5, -2.5, -3.5, -3], pos: [1, 12], color: SILK },
        { geo: "disc", size: [2], pos: [1, 14], color: "#f0d68e", z: 0.2 },
        // Hair knotted at the back, under the cord.
        { geo: "poly", size: [-6, 5, 2, 7, 3, -6, -5, -5], pos: [-7, 0], color: "#2b1d16", behind: true },
        // Tail of the cord, hanging down the back of her head.
        { geo: "poly", size: [-2.5, 7, 2.5, 6, 2, -7, -2.5, -6], pos: [-9, -3], rot: 14, color: GOLD, behind: true },
        { geo: "poly", size: [-2.5, 4, 2.5, 3, 2, -4, -2, -4], pos: [-12, -14], rot: 14, color: SILK, behind: true },
      ],
    },
    {
      id: "handwrapF",
      attach: "handF",
      parts: [
        // Taped fist: rounded over the knuckles, with the wrap crossing it.
        { geo: "poly", size: [-6, 3, -4, 6, 3, 6.5, 7, 3, 7, -3, 3, -6.5, -4, -6, -6, -3], pos: [1, 0], color: ROPE },
        { geo: "box", size: [2, 12], pos: [-1, 0], rot: 8, color: "#d6c9ab" },
        { geo: "box", size: [2, 12], pos: [3, 0], rot: 8, color: "#d6c9ab" },
        { geo: "poly", size: [-3, 5, 3, 4, 3, -4, -3, -5], pos: [-5, 0], color: "#c8bb9c" },
      ],
    },
    {
      id: "handwrapB",
      attach: "handB",
      parts: [
        // Taped fist: rounded over the knuckles, with the wrap crossing it.
        { geo: "poly", size: [-6, 3, -4, 6, 3, 6.5, 7, 3, 7, -3, 3, -6.5, -4, -6, -6, -3], pos: [1, 0], color: "#dcd3bd" },
        { geo: "box", size: [2, 12], pos: [-1, 0], rot: 8, color: "#d6c9ab" },
        { geo: "box", size: [2, 12], pos: [3, 0], rot: 8, color: "#d6c9ab" },
        { geo: "poly", size: [-3, 5, 3, 4, 3, -4, -3, -5], pos: [-5, 0], color: "#c8bb9c" },
      ],
    },
    {
      // The prajioud: a braided armband per arm, blessed the same day as the
      // mongkhon. Hung off the forearms so they travel with the guard.
      id: "prajioudF",
      attach: "forearmF",
      parts: [
        { geo: "poly", size: [-5, 4, 5, 3.5, 5, -3.5, -5, -4], pos: [-6, 0], color: SILK },
        { geo: "box", size: [2, 9], pos: [-4, 0], color: GOLD },
      ],
    },
    {
      id: "prajioudB",
      attach: "forearmB",
      parts: [
        { geo: "poly", size: [-5, 4, 5, 3.5, 5, -3.5, -5, -4], pos: [-6, 0], color: "#a82a25" },
        { geo: "box", size: [2, 9], pos: [-4, 0], color: "#b8912f" },
      ],
    },
    {
      id: "anklesF",
      attach: "footF",
      parts: [{ geo: "poly", size: [-5, 2, -3, 4.5, 3, 4, 5, 1.5, 4, -3, -4, -3.5], pos: [-1, 5], color: ROPE }],
    },
    {
      id: "anklesB",
      attach: "footB",
      parts: [{ geo: "poly", size: [-5, 2, -3, 4.5, 3, 4, 5, 1.5, 4, -3, -4, -3.5], pos: [-1, 5], color: "#c8bb9c" }],
    },
    {
      id: "shorts",
      attach: "pelvis",
      // Satin shorts, high-cut at the hip so the knees come up clean.
      parts: [
        { geo: "poly", size: [-12, 8, 12, 8, 10, -9, -10, -9], pos: [0, -4], color: SILK },
        { geo: "poly", size: [-12, 2.5, 12, 2, 12, -2.5, -12, -2], pos: [0, 3], color: GOLD },
        { geo: "poly", size: [-6, 3, 6, 2.5, 5, -3, -5, -2.5], pos: [1, -11], color: GOLD },
        { geo: "box", size: [2.2, 16], pos: [0, -4], color: "#a82a25" },
      ],
      cloth: {
        segments: 3,
        segmentLength: 8,
        width: 26,
        endWidth: 22,
        color: "#a82a25",
        gravity: 0.5,
        stiffness: 0.62,
        drift: -0.18,
      },
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 128,
      backThrowDamage: 136,
      throwRange: 58,
      rollSpeed: 8.4,
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Jab",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 11,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [3, 10],
      // Hands string continues into 5A, Hands string continues into 5B.
      followUps: [
        { button: "A", move: "5A", from: 3, to: 8, string: "Hands" },
        { button: "B", move: "5B", from: 3, to: 8, string: "Hands" },
      ],
      hits: [hit(3, 5, bx(16, 56, 42, 20), 28, { fx: "blunt", hitstun: 14, blockstun: 10, pushX: 2.6 })],
      desc: "The fastest button in the game. Three frames, cancels into everything.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderF: 96, elbowF: 4, torso: 10, offX: 3 }),
        kf(7, { ...STANCE, shoulderF: 118, elbowF: 62, torso: 6 }, "inOut"),
        kf(11, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Cross Elbow",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 20,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [7, 18],
      // Elbow Chain string continues into 4C.
      followUps: [
        { button: "C", move: "4C", from: 7, to: 17, string: "Elbow Chain" },
      ],
      hits: [hit(7, 10, bx(18, 52, 50, 30), 54, { fx: "blunt", pushX: 4.4, hitstun: 18 })],
      desc: "Turns the hips over and drives the taped elbow through. Short, and it hurts.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderB: 150, elbowB: 130, torso: -10, offX: -3 }),
        kf(7, { ...STANCE, shoulderB: 74, elbowB: 118, torso: 22, hipF: 26, offX: 6 }, "out"),
        kf(13, { ...STANCE, shoulderB: 104, elbowB: 112, torso: 12 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Roundhouse",
      input: { button: "C", stance: "stand" },
      tags: ["heavy"],
      duration: 30,
      cancelInto: ["special", "super"],
      cancelWindow: [13, 26],
      hits: [
        hit(13, 17, bx(20, 40, 82, 40), 88, {
          fx: "blunt",
          pushX: 8,
          knockdown: "hard",
          hitstun: 24,
          shake: 1.9,
        }),
      ],
      desc: "Full shin, full hip rotation. The single best button she has and the one you will block.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, torso: -12, hipB: -40, kneeB: 60, shoulderF: 150, elbowF: 70, offX: -4 }, "inOut"),
        kf(13, { ...STANCE, torso: 26, spin: -12, hipB: 86, kneeB: 10, hipF: 30, kneeF: 16, shoulderF: 60, elbowF: 40, shoulderB: 160, elbowB: 60, offX: 7 }, "out"),
        kf(21, { ...STANCE, torso: 18, spin: -6, hipB: 40, kneeB: 40, offX: 4 }),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Jab",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 12,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [3, 11],
      hits: [hit(3, 5, bx(14, 14, 42, 20), 26, { guard: "low", fx: "blunt", hitstun: 13, blockstun: 10, pushX: 2.4 })],
      desc: "Quick low from a crouch. Her opener.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(3, { ...STANCE, crouch: 1, torso: 22, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderF: 92, elbowF: 38, offX: 4 }),
        kf(8, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderF: 116, elbowF: 84 }, "inOut"),
        kf(12, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "2B",
      name: "Low Kick",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 22,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [8, 20],
      hits: [hit(8, 11, bx(18, 6, 66, 26), 52, { guard: "low", fx: "blunt", pushX: 4.2, hitstun: 17 })],
      desc: "Shin to the thigh. Must be blocked low and it chips away at their stance.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(5, { ...STANCE, crouch: 1, torso: 12, hipF: 10, kneeF: 92, hipB: -30, kneeB: 92 }),
        kf(8, { ...STANCE, crouch: 1, torso: 24, hipF: 74, kneeF: 12, hipB: -32, kneeB: 96, offX: 6 }, "out"),
        kf(16, { ...STANCE, crouch: 1, torso: 18, hipF: 46, kneeF: 52, hipB: -26, kneeB: 88 }, "inOut"),
        kf(22, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "2C",
      name: "Sweep Kick",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 28,
      cancelInto: ["special", "super"],
      cancelWindow: [11, 24],
      hits: [hit(10, 14, bx(16, 2, 78, 24), 72, { guard: "low", knockdown: "sweep", fx: "blunt", pushX: 5.6 })],
      desc: "Takes the leg out from under them. Her knockdown.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(6, { ...STANCE, crouch: 1, torso: 20, hipF: 8, kneeF: 96, hipB: -34, kneeB: 100, offX: -2 }),
        kf(10, { ...STANCE, crouch: 1, torso: 26, hipF: 84, kneeF: 4, hipB: -36, kneeB: 104, offX: 5 }, "out"),
        kf(18, { ...STANCE, crouch: 1, torso: 20, hipF: 50, kneeF: 48, hipB: -30, kneeB: 92 }, "inOut"),
        kf(28, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "6B",
      name: "Jump Elbow",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "overhead"],
      priority: 10,
      duration: 30,
      vel: [{ at: 5, x: 3.6 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [14, 26],
      hits: [hit(13, 17, bx(18, 40, 52, 44), 60, { guard: "overhead", fx: "blunt", pushX: 5, hitstun: 20 })],
      desc: "Hops in and drops the point of the elbow. Overhead - it beats a low block.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, crouch: 0.45, torso: 12, hipF: 18, kneeF: 58 }),
        kf(10, { ...STANCE, free: 1, offY: 14, torso: -8, shoulderB: 176, elbowB: 96, hipF: -20, kneeF: 74, hipB: -28, kneeB: 56 }, "out"),
        kf(13, { ...STANCE, free: 1, offY: 6, torso: 30, shoulderB: 48, elbowB: 130, hipF: 40, kneeF: 40, offX: 5 }, "out"),
        kf(20, { ...STANCE, offY: 0, torso: 18, shoulderB: 90, elbowB: 118 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Rising Knee",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 30,
      cancelInto: ["special", "super"],
      cancelWindow: [11, 26],
      hits: [hit(8, 12, bx(12, 46, 54, 70), 70, { launch: [2, 12], knockdown: "launch", fx: "blunt", hitstun: 26 })],
      desc: "Drives the knee up through their chin. Launches into a juggle.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5, hipF: 24, kneeF: 46 }, "out"),
        kf(5, { ...STANCE, crouch: 0.7, hipF: 10, kneeF: 70, torso: 10 }),
        kf(8, { ...STANCE, torso: -14, hipF: 118, kneeF: 118, hipB: -14, kneeB: 20, shoulderF: 150, elbowF: 60, offY: 5 }, "out"),
        kf(16, { ...STANCE, torso: -8, hipF: 96, kneeF: 100 }),
        kf(24, { ...STANCE, torso: 2, hipF: 40, kneeF: 44 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      // Forward and back sets. Forward takes space, back gives it up to buy
      // range or a hard read.
      id: "6A",
      name: "Teep",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 20,
      vel: [{ at: 2, x: 2.2 }],
      friction: 0.88,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [6, 18],
      // Long Legs string continues into 6C.
      followUps: [
        { button: "C", move: "6C", from: 6, to: 17, string: "Long Legs" },
      ],
      hits: [hit(6, 8, bx(24, 44, 56, 26), 28, { guard: "high", fx: "blunt", pushX: 14, hitstun: 13, hitstop: 6 })],
      desc: "Push kick to the belly. Not damage - it stops them walking in and resets the round.",
      notation: "\u2192 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        // Knee chambered to the chest, then the leg locks out flat.
        kf(3, { ...STANCE, hipF: 76, kneeF: 108, torso: -8, offX: -2 }, "out"),
        kf(6, { ...STANCE, hipF: 104, kneeF: 8, hipB: -28, kneeB: 22, torso: -20, head: 8, offX: 5 }, "out"),
        kf(11, { ...STANCE, hipF: 58, kneeF: 52, torso: -6, offX: 3 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Switch Roundhouse",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 40,
      armor: [{ from: 8, to: 18, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 8, x: 5.4 }, { at: 26, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [20, 36],
      hits: [hit(16, 20, bx(16, 22, 52, 68), 94, { guard: "mid", fx: "blunt", pushX: 18, hitstun: 24, hitstop: 12, knockdown: "wallbounce", shake: 2.4 })],
      desc: "Switches the feet and turns the shin all the way through them.",
      notation: "\u2192 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        // Switch step, then the hip turns over and the shin follows it.
        kf(8, { ...STANCE, hipF: -24, kneeF: 40, hipB: 30, kneeB: 62, torso: -18, shoulderF: 60, elbowF: 90, offX: -6 }, "out"),
        kf(16, { ...STANCE, hipB: 96, kneeB: 16, hipF: 22, kneeF: 18, torso: 30, shoulderF: 20, elbowF: 40, shoulderB: 128, elbowB: 30, offX: 11 }, "out"),
        kf(24, { ...STANCE, hipB: 70, kneeB: 40, torso: 22, offX: 7 }),
        kf(32, { ...STANCE, hipB: 10, kneeB: 44, torso: 8, offX: 3 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Check Elbow",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 22,
      vel: [{ at: 1, x: -2.6 }],
      friction: 0.86,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [8, 20],
      // Elbow Chain string continues into 5B.
      followUps: [
        { button: "B", move: "5B", from: 8, to: 19, string: "Elbow Chain" },
      ],
      hits: [hit(8, 10, bx(16, 52, 42, 30), 36, { guard: "mid", fx: "blunt", pushX: 6, hitstun: 15, hitstop: 6 })],
      desc: "Steps out and cuts back with the taped point of the elbow. Short and it opens skin.",
      notation: "\u2190 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -8, shoulderF: 20, elbowF: 140, hipB: -26, kneeB: 40, offX: -6 }, "out"),
        // Elbow leads, hand stays tight to the head.
        kf(8, { ...STANCE, torso: 10, shoulderF: 96, elbowF: 132, hipF: 22, kneeF: 16, offX: -3 }, "out"),
        kf(14, { ...STANCE, torso: 2, shoulderF: 52, elbowF: 128, offX: -4 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Long Knee",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 30,
      vel: [{ at: 1, x: -3.4 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      hits: [hit(12, 15, bx(22, 46, 60, 40), 56, { guard: "mid", fx: "blunt", pushX: 7, hitstun: 18, hitstop: 8 })],
      desc: "Gives ground and spears the knee up into them as they follow.",
      notation: "\u2190 + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, hipB: -40, kneeB: 60, torso: -14, shoulderF: 40, elbowF: 128, hipF: 8, kneeF: 30, offX: -8 }, "inOut"),
        // Hips driven through, knee point leading, hands pulling down.
        kf(12, { ...STANCE, hipF: 96, kneeF: 106, torso: -12, head: 6, shoulderF: 74, elbowF: 116, shoulderB: 60, elbowB: 118, hipB: -26, kneeB: 18, offX: -4 }, "out"),
        kf(17, { ...STANCE, hipF: 88, kneeF: 100, torso: -10, shoulderF: 70, elbowF: 116, offX: -6 }),
        kf(23, { ...STANCE, hipF: 40, kneeF: 62, torso: -2, offX: -4 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Downward Elbow",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 44,
      cancelInto: ["special", "super"],
      cancelWindow: [26, 40],
      hits: [hit(20, 23, bx(12, 20, 58, 86), 98, { guard: "overhead", fx: "slash", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 })],
      desc: "Steps back, then drops the wrapped elbow through the top of their guard. Blocked standing only.",
      notation: "\u2190 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 120, elbowF: 130, torso: -12, offX: -5 }, "inOut"),
        // Elbow lifted above the head, forearm folded flat.
        kf(15, { ...STANCE, shoulderF: 172, elbowF: 138, torso: -20, hipB: -26, kneeB: 38, offY: 3, offX: -3 }, "out"),
        kf(20, { ...STANCE, shoulderF: 88, elbowF: 126, torso: 34, hipF: 34, kneeF: 16, hipB: -12, kneeB: 32, offX: 6 }, "out"),
        kf(26, { ...STANCE, shoulderF: 80, elbowF: 124, torso: 26, offX: 4 }),
        kf(36, { ...STANCE, shoulderF: 46, elbowF: 122, torso: 8 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Jab",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 17,
      airborne: true,
      landCancel: true,
      landRecovery: 2,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [4, 15],
      hits: [hit(4, 9, bx(14, 34, 44, 28), 30, { fx: "blunt", hitstun: 14, pushX: 2.4 })],
      desc: "Quick air punch to stuff anyone rising into her.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 32, kneeF: 42, hipB: -22, kneeB: 40 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderF: 100, elbowF: 8, torso: 12 }),
        kf(11, { ...STANCE, free: 1, shoulderF: 124, elbowF: 74, torso: 6 }, "inOut"),
        kf(17, { ...STANCE, free: 1, hipF: 32, kneeF: 42, hipB: -22, kneeB: 40 }),
      ],
    },
    {
      id: "jB",
      name: "Air Knee",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 24,
      airborne: true,
      landCancel: true,
      landRecovery: 4,
      cancelInto: ["heavy", "special"],
      hits: [hit(6, 13, bx(16, 20, 54, 44), 56, { fx: "blunt", pushX: 4, hitstun: 18 })],
      desc: "Knee driven forward in the air. Beats most jump-ins outright.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 30, kneeF: 40, hipB: -22, kneeB: 38 }, "out"),
        kf(4, { ...STANCE, free: 1, hipF: 10, kneeF: 88, torso: 10 }),
        kf(7, { ...STANCE, free: 1, hipF: 96, kneeF: 108, hipB: -24, kneeB: 44, torso: 20 }, "out"),
        kf(16, { ...STANCE, free: 1, hipF: 60, kneeF: 70, torso: 10 }, "inOut"),
        kf(24, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "jC",
      name: "Falling Elbow",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 28,
      airborne: true,
      landCancel: true,
      landRecovery: 7,
      vel: [{ at: 5, y: -3.5, mode: "add" }],
      hits: [
        hit(7, 18, bx(2, 0, 54, 46), 80, {
          guard: "overhead",
          fx: "blunt",
          knockdown: "soft",
          pushX: 5,
          shake: 1.5,
        }),
      ],
      desc: "Drops elbow-first out of the sky. Her jump-in.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, torso: -20, shoulderB: 178, elbowB: 100, hipF: 40, kneeF: 56 }),
        kf(8, { ...STANCE, free: 1, torso: 32, shoulderB: 40, elbowB: 128, hipF: 16, kneeF: 20 }, "out"),
        kf(28, { ...STANCE, free: 1, torso: 26, shoulderB: 44, elbowB: 124 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Blitz Knee",
      input: { button: "C", dir: "f", stance: "stand", whileDashing: true },
      tags: ["command"],
      priority: 12,
      duration: 32,
      vel: [
        { at: 3, x: 10.5 },
        { at: 16, x: 0 },
      ],
      friction: 0.9,
      hits: [hit(8, 14, bx(18, 30, 60, 52), 74, { fx: "blunt", pushX: 7.5, knockdown: "soft", hitstun: 22, shake: 1.5 })],
      desc: "Sprints in behind a knee. Her fastest way through neutral.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 26, hipB: -34, kneeB: 50, offX: -3 }),
        kf(8, { ...STANCE, torso: 30, hipF: 100, kneeF: 100, hipB: -26, kneeB: 40, shoulderF: 140, elbowF: 70, offX: 8 }, "out"),
        kf(22, { ...STANCE, torso: 18, hipF: 50, kneeF: 50, offX: 4 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },

    // -------------------------------------------------------- five specials
    {
      id: "teep",
      name: "Teep",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      duration: 30,
      vel: [{ at: 6, x: 2.5 }],
      friction: 0.88,
      hits: [
        hit(8, 12, bx(22, 40, 74, 30), 52, {
          fx: "blunt",
          pushX: 17,
          hitstun: 20,
          knockdown: "wallbounce",
          shake: 1.4,
        }),
      ],
      desc: "Push kick straight to the sternum. Almost no damage, enormous pushback - it resets the fight to her range.",
      notation: "↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, hipF: 6, kneeF: 88, torso: -8, offX: -3 }),
        kf(8, { ...STANCE, hipF: 92, kneeF: 6, hipB: -26, kneeB: 34, torso: 18, shoulderF: 150, elbowF: 60, offX: 6 }, "out"),
        kf(16, { ...STANCE, hipF: 60, kneeF: 30, torso: 10 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "flyingKnee",
      name: "Flying Knee",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 24,
      duration: 44,
      airborne: true,
      invuln: [{ from: 1, to: 8, kind: "strike" }],
      vel: [
        { at: 1, x: 4.6, y: 11.8 },
        { at: 24, y: -0.9, mode: "add" },
      ],
      hits: [
        hit(3, 9, bx(10, 44, 60, 74), 84, { launch: [2.4, 10], knockdown: "launch", fx: "blunt", hitstun: 26, shake: 1.9 }),
        hit(10, 18, bx(8, 56, 54, 64), 34, { group: 2, launch: [1.4, 5], fx: "blunt" }),
      ],
      desc: "Invincible knee that travels. Reversal, anti-air, and it crosses ground doing it.",
      notation: "→↓↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 48 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -12, hipF: 116, kneeF: 116, hipB: -34, kneeB: 30, shoulderF: 156, elbowF: 50, shoulderB: 120, elbowB: 60 }, "out"),
        kf(16, { ...STANCE, free: 1, torso: -18, hipF: 124, kneeF: 124, hipB: -40, kneeB: 24 }),
        kf(32, { ...STANCE, free: 1, torso: -2, hipF: 60, kneeF: 60, hipB: -20, kneeB: 40 }, "inOut"),
        kf(44, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "clinch",
      name: "Clinch",
      input: { button: "B", motion: "hcf", stance: ["stand", "crouch"] },
      tags: ["special", "throw"],
      priority: 26,
      duration: 30,
      // The whole character is paid out through this grab - everything else he
      // owns is bottom-third damage - and it was reaching 64 units when his own
      // jab reaches 90, so he had to be closer to take the neck than to punch.
      // Measured under AI control it was thrown 1.8 times a round and connected
      // 0.2 of them: his win condition happened once every five rounds.
      vel: [{ at: 2, x: 7.5 }],
      friction: 0.92,
      throwDef: { from: 6, to: 16, range: 82, success: "clinchKnees" },
      desc: "Steps in and takes the neck. Command grab - it beats blocking entirely, and it closes the last of the gap itself.",
      notation: "←↙↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: 16, shoulderF: 96, elbowF: 30, shoulderB: 90, elbowB: 34, hipF: 26, offX: 4 }),
        kf(10, { ...STANCE, torso: 20, shoulderF: 86, elbowF: 18, shoulderB: 80, elbowB: 22, offX: 6 }),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "clinchKnees",
      name: "Clinch Knees",
      input: { stance: "stand" },
      tags: ["special", "throw"],
      internal: true,
      duration: 66,
      grabOffset: [36, 4],
      throwPayload: {
        at: 52,
        damage: 62,
        launch: [7, 8.5],
        knockdown: "hard",
        hitstop: 12,
        fx: "blunt",
        // Four knees on the way, then the throw off.
        ticks: [
          { at: 12, damage: 26, fx: "blunt" },
          { at: 22, damage: 24, fx: "blunt" },
          { at: 32, damage: 24, fx: "blunt" },
          { at: 42, damage: 26, fx: "blunt" },
        ],
      },
      desc: "",
      frames: [
        kf(0, { ...STANCE, torso: 16, shoulderF: 86, elbowF: 16, shoulderB: 80, elbowB: 20 }, "out"),
        kf(12, { ...STANCE, torso: 22, shoulderF: 84, elbowF: 14, shoulderB: 78, elbowB: 18, hipF: 108, kneeF: 108, offX: 3 }, "out"),
        kf(18, { ...STANCE, torso: 16, shoulderF: 86, elbowF: 16, hipF: 30, kneeF: 30 }, "inOut"),
        kf(22, { ...STANCE, torso: 22, shoulderF: 84, elbowF: 14, hipB: 104, kneeB: 104, offX: 3 }, "out"),
        kf(28, { ...STANCE, torso: 16, hipB: -20, kneeB: 30 }, "inOut"),
        kf(32, { ...STANCE, torso: 22, hipF: 110, kneeF: 110, offX: 3 }, "out"),
        kf(38, { ...STANCE, torso: 16, hipF: 30, kneeF: 30 }, "inOut"),
        kf(42, { ...STANCE, torso: 24, hipB: 108, kneeB: 108, offX: 4 }, "out"),
        kf(52, { ...STANCE, torso: 30, shoulderF: 130, elbowF: 20, shoulderB: 124, elbowB: 16, hipF: 40, kneeF: 24, offX: 6 }, "out"),
        kf(66, { ...STANCE }),
      ],
    },
    {
      id: "spinElbow",
      name: "Spinning Elbow",
      input: { button: "C", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 22,
      duration: 38,
      resourceCost: 30,
      resourceMin: 30,
      // The armoured way in. One hit absorbed over eight frames was not enough
      // to walk through anybody's poke, so this covered no ground it did not
      // already have. Longer window and further travel makes it the answer to
      // being held out - which is the only problem he has.
      vel: [{ at: 6, x: 7.5 }],
      friction: 0.9,
      armor: [{ from: 5, to: 20, hits: 1, damageScale: 0.3 }],
      hits: [
        hit(14, 19, bx(16, 44, 62, 40), 96, {
          fx: "blunt",
          pushX: 9,
          knockdown: "hard",
          hitstun: 28,
          hitstop: 13,
          shake: 2.3,
        }),
      ],
      vfx: [{ at: 14, kind: "blunt", x: 44, y: 60, scale: 1.4 }],
      desc: "Turns her back to them and comes round with the elbow. Absorbs a hit on the turn. Costs Rhythm.",
      notation: "↓↙← + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, spin: -110, torso: 10, shoulderF: 130, elbowF: 90, shoulderB: 140, elbowB: 80 }, "linear"),
        kf(11, { ...STANCE, spin: -240, torso: 6, shoulderB: 150, elbowB: 120 }, "linear"),
        kf(14, { ...STANCE, spin: -330, torso: 20, shoulderB: 70, elbowB: 128, hipF: 32, kneeF: 20, offX: 6 }, "out"),
        kf(24, { ...STANCE, spin: -360, torso: 14, shoulderB: 100, elbowB: 118, offX: 3 }, "inOut"),
        kf(38, { ...STANCE, spin: -360 }),
      ],
    },
    {
      id: "cartwheel",
      name: "Cartwheel Kick",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "overhead"],
      priority: 20,
      duration: 42,
      airborne: true,
      // He is upside down and off the ground, so nothing at chest height is
      // where he is. This is the one tool he has that can cross a gap through
      // something rather than around it, and without the invulnerability it
      // was a slow overhead that traded with everything on the way in.
      invuln: [{ from: 5, to: 18, kind: "strike" }],
      vel: [
        { at: 4, x: 7.4, y: 9.5 },
        { at: 22, y: -0.8, mode: "add" },
      ],
      hits: [
        hit(12, 22, bx(8, 8, 62, 62), 76, {
          guard: "overhead",
          fx: "blunt",
          pushX: 6,
          knockdown: "hard",
          hitstun: 24,
          shake: 1.7,
        }),
      ],
      desc: "Flips over and brings the heel down. Overhead, and it travels the gap.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5, hipF: 24, kneeF: 46 }, "out"),
        kf(6, { ...STANCE, free: 1, spin: -80, torso: -10, hipF: 60, kneeF: 30, hipB: -60, kneeB: 30, shoulderF: -40, elbowF: 20, shoulderB: -50, elbowB: 20 }, "linear"),
        kf(14, { ...STANCE, free: 1, spin: -200, hipF: 40, kneeF: 20, hipB: -70, kneeB: 20 }, "linear"),
        kf(24, { ...STANCE, free: 1, spin: -330, hipF: 70, kneeF: 20, hipB: -30, kneeB: 40 }, "linear"),
        kf(32, { ...STANCE, free: 1, spin: -360, torso: 12, hipF: 40, kneeF: 40 }, "inOut"),
        kf(42, { ...STANCE, free: 1, spin: -360 }),
      ],
    },

    // ----------------------------------------------------------------- skill
    {
      id: "wai",
      name: "Wai Khru",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill"],
      priority: 18,
      duration: 42,
      resourceGain: 40,
      meterGain: 16,
      friction: 0.9,
      armor: [{ from: 6, to: 30, hits: 1, damageScale: 0.35 }],
      desc: "SKILL. The ritual bow. Builds Rhythm and meter, and she can eat one hit doing it - but only one.",
      notation: "A + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(10, { ...STANCE, torso: 18, head: 14, shoulderF: 60, elbowF: 90, shoulderB: 56, elbowB: 94, hipF: 10, kneeF: 24 }, "inOut"),
        kf(26, { ...STANCE, torso: 22, head: 18, shoulderF: 54, elbowF: 96, shoulderB: 50, elbowB: 100 }),
        kf(36, { ...STANCE, torso: 6, head: 4, shoulderF: 110, elbowF: 92 }, "inOut"),
        kf(42, { ...STANCE }),
      ],
    },

    // ------------------------------------------------------------------ EX
    {
      id: "teepEx",
      name: "Teep EX",
      input: { button: "S", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "ex"],
      priority: 26,
      duration: 40,
      meterCost: 50,
      invuln: [{ from: 1, to: 10, kind: "strike" }],
      vel: [{ at: 5, x: 4 }],
      friction: 0.88,
      hits: [
        hit(7, 10, bx(20, 44, 70, 30), 40, { group: 1, fx: "blunt", pushX: 3, hitstun: 18, hitstop: 6 }),
        hit(16, 21, bx(22, 38, 80, 36), 74, {
          group: 2,
          fx: "blunt",
          pushX: 24,
          knockdown: "wallbounce",
          hitstun: 28,
          hitstop: 14,
          shake: 2.4,
        }),
      ],
      desc: "EX. Invincible on the way in, two kicks, and the second sends them off the far wall.",
      notation: "↓↘→ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, hipF: 8, kneeF: 84, torso: -6, offX: -2 }),
        kf(7, { ...STANCE, hipF: 88, kneeF: 8, torso: 16, offX: 5 }, "out"),
        kf(13, { ...STANCE, hipF: 20, kneeF: 70, torso: -8, offX: -3 }, "inOut"),
        kf(16, { ...STANCE, hipF: 98, kneeF: 2, hipB: -30, kneeB: 30, torso: 22, shoulderF: 150, elbowF: 50, offX: 8 }, "out"),
        kf(28, { ...STANCE, hipF: 50, kneeF: 40, torso: 10 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "flyingKneeEx",
      name: "Flying Knee EX",
      input: { button: "S", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "launcher"],
      priority: 30,
      duration: 52,
      meterCost: 50,
      airborne: true,
      invuln: [{ from: 1, to: 16, kind: "strike" }],
      vel: [
        { at: 1, x: 5.6, y: 13.6 },
        { at: 30, y: -1, mode: "add" },
      ],
      hits: [
        hit(3, 9, bx(10, 42, 66, 82), 68, { launch: [2.4, 12], knockdown: "launch", fx: "blunt", hitstun: 28, shake: 2 }),
        hit(10, 18, bx(8, 56, 60, 74), 34, { group: 2, launch: [1.4, 5], fx: "blunt" }),
        hit(19, 28, bx(8, 66, 58, 68), 52, { group: 3, launch: [2, 4], fx: "blunt", knockdown: "hard" }),
      ],
      desc: "EX. Fully invincible, crosses more ground, and carries them all the way up.",
      notation: "→↓↘ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 48 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -14, spin: -6, hipF: 120, kneeF: 120, hipB: -36, kneeB: 26 }, "out"),
        kf(18, { ...STANCE, free: 1, torso: -22, spin: -16, hipF: 128, kneeF: 128, hipB: -42, kneeB: 20 }),
        kf(36, { ...STANCE, free: 1, torso: -4, spin: -4, hipF: 60, kneeF: 60 }, "inOut"),
        kf(52, { ...STANCE, free: 1 }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "Nine Strikes",
      input: { button: "S", motion: "dd", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 112,
      meterCost: 100,
      superFreeze: 42,
      invuln: [{ from: 1, to: 12, kind: "strike" }],
      vel: [
        { at: 6, x: 9 },
        { at: 30, x: 4 },
        { at: 60, x: 2 },
        { at: 72, x: 0 },
      ],
      friction: 0.92,
      hits: [
        hit(12, 15, bx(16, 50, 54, 28), 40, { group: 1, fx: "blunt", pushX: 0.8, hitstun: 20, hitstop: 5 }),
        hit(18, 21, bx(16, 46, 54, 30), 34, { group: 2, fx: "blunt", pushX: 0.8, hitstun: 18, hitstop: 4 }),
        hit(24, 27, bx(16, 40, 58, 34), 34, { group: 3, fx: "blunt", pushX: 0.8, hitstun: 18, hitstop: 4 }),
        hit(30, 33, bx(16, 34, 62, 38), 36, { group: 4, fx: "blunt", pushX: 0.8, hitstun: 18, hitstop: 4 }),
        hit(38, 41, bx(16, 44, 60, 40), 36, { group: 5, fx: "blunt", pushX: 0.8, hitstun: 18, hitstop: 4 }),
        hit(46, 49, bx(16, 30, 66, 44), 38, { group: 6, fx: "blunt", pushX: 0.8, hitstun: 18, hitstop: 4 }),
        hit(54, 57, bx(14, 40, 68, 44), 38, { group: 7, fx: "blunt", pushX: 0.8, hitstun: 18, hitstop: 5 }),
        hit(62, 68, bx(12, 20, 84, 68), 142, {
          group: 8,
          fx: "blunt",
          pushX: 13,
          knockdown: "wallbounce",
          launch: [8, 7],
          hitstop: 18,
          shake: 3,
        }),
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 50, scale: 2.5, color: "#ffca6b" },
        { at: 62, kind: "explode", x: 50, y: 46, scale: 1.1 },
      ],
      desc: "SUPER. Every limb she has, in order, ending on the elbow that puts them through the wall.",
      notation: "↓↓ + S (with 100 meter)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.3, torso: -8 }, "out"),
        kf(12, { ...STANCE, torso: 20, shoulderF: 96, elbowF: 4, offX: 5 }, "out"),
        kf(18, { ...STANCE, torso: 18, shoulderB: 92, elbowB: 6, offX: 5 }, "out"),
        kf(24, { ...STANCE, torso: 22, shoulderF: 70, elbowF: 116, offX: 6 }, "out"),
        kf(30, { ...STANCE, torso: 24, shoulderB: 66, elbowB: 120, offX: 6 }, "out"),
        kf(38, { ...STANCE, torso: 20, hipF: 100, kneeF: 100, offX: 5 }, "out"),
        kf(46, { ...STANCE, torso: 22, hipB: 96, kneeB: 96, offX: 5 }, "out"),
        kf(54, { ...STANCE, torso: 26, spin: -14, hipB: 84, kneeB: 12, offX: 6 }, "out"),
        kf(58, { ...STANCE, spin: -180, torso: 10, shoulderB: 150, elbowB: 110 }, "linear"),
        kf(62, { ...STANCE, spin: -340, torso: 30, shoulderB: 56, elbowB: 130, hipF: 42, kneeF: 24, offX: 10 }, "out"),
        kf(84, { ...STANCE, spin: -360, torso: 16, offX: 4 }, "inOut"),
        kf(112, { ...STANCE, spin: -360 }),
      ],
    },
  ],
};
