/**
 * Akali Phula Singh (1761-1823) - Nihang Sikh, jathedar of the Akal Takht,
 * and the commander Ranjit Singh could give orders to but not control.
 *
 * Led the Akali Nihangs at Kasur, Multan and Peshawar, and died leading the
 * charge at Nowshera in 1823. Famously once summoned the Maharaja himself to
 * the Akal Takht to answer for his conduct - and the Maharaja came.
 *
 * The Nihang dress is the character: a towering blue dumalla with steel quoits
 * stacked around it, and those quoits are the weapon. A chakram is thrown flat
 * and edge-on; he carries five, and every one he throws is one he no longer
 * has. When they run out he still has the tulwar, and he is much less happy
 * about it.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const NIHANG_BLUE = "#1f3f7a";
const DEEP_BLUE = "#152c57";
const STEEL = "#c9d2da";
const SAFFRON = "#e08c2a";
const GOLD = "#d8b452";

/** Tulwar low in the right hand, left hand up by the turban and the quoits. */
const STANCE = {
  torso: 7,
  head: -3,
  hipF: 16,
  kneeF: 19,
  hipB: -18,
  kneeB: 30,
  shoulderF: 36,
  elbowF: 66,
  shoulderB: 62,
  elbowB: 62,
  weapon: 30,
};

const guard = { shoulderB: 74, elbowB: 66 };

export const NIHANG: FighterDef = {
  id: "nihang",
  name: "Akali Phula Singh",
  title: "Jathedar of the Akal Takht",
  era: "Punjab, 1807",
  bio: "Commanded the Akali Nihangs through Kasur, Multan and Peshawar for Ranjit Singh, and once summoned the Maharaja to the Akal Takht to answer for himself. Died at the front of the charge at Nowshera.",
  archetype: "Zoner / Resource",
  difficulty: 4,
  strengths: ["Controls the whole screen", "Thrown quoits come back", "Strong wake-up pressure"],
  weaknesses: ["Helpless once the quoits are gone", "Mediocre close-range normals", "Slow to recover them"],
  winQuote: "The quoits return to me. You do not have to.",
  palette: {
    body: "#a9764c",
    outline: "#12131a",
    accent: SAFFRON,
    cloth: NIHANG_BLUE,
    metal: STEEL,
    aura: "#6fa8ff",
  },
  stats: {
    health: 980,
    walkF: 2.6,
    walkB: 2.4,
    dashSpeed: 7.8,
    dashFrames: 16,
    backdashFrames: 20,
    jumpVel: 12.4,
    jumpFwd: 4.4,
    gravity: 0.62,
    weight: 1,
    airMoves: 2,
    doubleJump: false,
    airDash: false,
    width: 21,
    standHeight: 106,
    crouchHeight: 68,
    scale: 1.02,
  },
  stance: STANCE,
  // Tulwar in a hanging guard with the chakram hand tucked in under it.
  clips: guardClips({
    high: { torso: 0, head: -6, shoulderF: 136, elbowF: 28, weapon: -104, shoulderB: 24, elbowB: 122, hipF: 16, kneeF: 22, hipB: -18, kneeB: 34, offX: -2 },
    low: { torso: 8, head: -5, shoulderF: 128, elbowF: 32, weapon: -98, shoulderB: 30, elbowB: 116, hipF: 34, kneeF: 76, hipB: -20, kneeB: 86, offX: -2 },
  }),
  resource: {
    name: "Chakram",
    max: 5,
    start: 5,
    // A thrown quoit is picked up, or a new one comes off the turban. Either
    // way it is slow, and landing hits speeds it up.
    regen: 0.009,
    gainOnHit: 0.2,
    color: STEEL,
    pips: true,
  },
  props: [
    {
      id: "dumalla",
      attach: "head",
      // Dumalla: a tall conical turban wound over a bamboo frame, with the
      // chakrams stacked up it and a khanda pinned at the front. This is the
      // silhouette people recognise a Nihang by from across a battlefield.
      parts: [
        // The tower of cloth, widening as it goes up.
        { geo: "poly", size: [-11, -4, -12, 6, -10, 16, -6, 24, 0, 28, 6, 24, 10, 16, 12, 6, 11, -4], pos: [0, 4], color: NIHANG_BLUE },
        // Wound courses of cloth showing across it.
        { geo: "poly", size: [-12, 1.6, 12, 1.6, 11, -1.6, -11, -1.6], pos: [0, 8], color: DEEP_BLUE, z: 0.1 },
        { geo: "poly", size: [-10, 1.6, 10, 1.6, 9, -1.6, -9, -1.6], pos: [0, 16], color: DEEP_BLUE, z: 0.1 },
        { geo: "poly", size: [-7, 1.6, 7, 1.6, 6, -1.6, -6, -1.6], pos: [0, 24], color: DEEP_BLUE, z: 0.1 },
        // Chakrams: flat steel rings stacked around the cone, largest at the
        // bottom. These are ammunition, not decoration.
        { geo: "ring", size: [12, 2.4], pos: [0, 10], color: STEEL, z: 0.4 },
        { geo: "ring", size: [9.5, 2.2], pos: [0, 19], color: STEEL, z: 0.4 },
        { geo: "ring", size: [7, 2], pos: [0, 26], color: "#e2e9ef", z: 0.4 },
        // Khanda badge pinned at the brow: straight sword, flanked by two
        // curved ones, inside a circle.
        { geo: "disc", size: [3.4], pos: [7, 6], color: GOLD, z: 0.6 },
        { geo: "box", size: [1.6, 9], pos: [7, 7], color: "#f2dd9a", z: 0.65 },
        { geo: "box", size: [7, 1.4], pos: [7, 4], color: "#f2dd9a", z: 0.65 },
        // Saffron under-scarf showing at the temple.
        { geo: "poly", size: [-8, 3, 8, 2, 7, -2, -8, -3], pos: [0, 0], color: SAFFRON, z: 0.3 },
        // The beard, which for a Nihang is never cut.
        { geo: "poly", size: [-8, 5, 4, 4, 8, -3, 5, -12, -3, -14, -9, -6], pos: [2, -9], color: "#2b2118", z: 0.55 },
      ],
    },
    {
      id: "tulwar",
      attach: "handF",
      // Tulwar: a deeply curved single-edged blade, disc-pommel hilt with a
      // short knuckle bow. The disc is what stops the hand sliding off.
      parts: [
        // Blade, curving up away from the grip and broadening near the tip.
        { geo: "poly", size: [0, -4, 16, -6, 32, -7, 48, -5, 58, 2, 47, 2, 32, -1, 16, -1, 0, 3], pos: [16, 0], color: "#dde5ec" },
        { geo: "poly", size: [0, -1.5, 16, -3, 32, -4, 46, -2.5, 52, 0.5, 44, 0.5, 30, -2, 15, -2.5, 0, 0.5], pos: [16, 0], color: "#f2f7fb", z: 0.1 },
        // Langets and the straight quillons.
        { geo: "box", size: [5, 5], pos: [12, 0], color: GOLD },
        { geo: "poly", size: [-2, -9, 2, -9, 2.6, 0, 2, 9, -2, 9, -2.6, 0], pos: [9, 0], color: GOLD },
        // Knuckle bow curving back to the pommel.
        { geo: "poly", size: [0, -1.6, 8, -8, 8, -10.5, -1, -2.6], pos: [4, 0], color: GOLD },
        { geo: "box", size: [12, 1.8], pos: [-4, -9], color: GOLD },
        // Grip and the flat disc pommel.
        { geo: "box", size: [13, 5.5], pos: [0, 0], color: "#3f2c1c" },
        { geo: "disc", size: [5], pos: [-9, 0], color: GOLD },
        { geo: "disc", size: [2], pos: [-9, 0], color: "#8f7530" },
      ],
    },
    {
      id: "chakram",
      attach: "handB",
      // A quoit held ready in the off hand, spun on one finger. Hidden while
      // he is throwing it.
      parts: [
        { geo: "ring", size: [11, 2.6], pos: [10, 0], color: STEEL },
        { geo: "ring", size: [11, 1], pos: [10, 0], color: "#f2f7fb", z: 0.1 },
      ],
    },
    {
      id: "chola",
      attach: "torso",
      // Chola: the loose blue battle robe, with an iron chest disc and the
      // bandolier of a man who expects to be shot at.
      parts: [
        { geo: "poly", size: [-13, -16, 12, -16, 14, 6, 6, 16, -8, 16, -14, 5], pos: [0, 3], color: NIHANG_BLUE },
        // The robe crossing over at the chest.
        { geo: "poly", size: [-14, 10, 4, 16, 12, 6, 10, 0, -13, -2], pos: [0, 4], color: DEEP_BLUE, z: 0.2 },
        // Iron chest disc, buckled on over the robe.
        { geo: "disc", size: [5.5], pos: [3, 4], color: STEEL, z: 0.4 },
        { geo: "disc", size: [2.2], pos: [3, 4], color: "#8d959e", z: 0.45 },
        // Bandolier of iron shot.
        { geo: "poly", size: [-14, 4, 12, -10, 11, -13, -15, 1], pos: [0, 8], color: "#4a3220", z: 0.3 },
        { geo: "disc", size: [1.2], pos: [-9, 5], color: STEEL, z: 0.35 },
        { geo: "disc", size: [1.2], pos: [-3, 2], color: STEEL, z: 0.35 },
        { geo: "disc", size: [1.2], pos: [4, -2], color: STEEL, z: 0.35 },
        // Saffron collar.
        { geo: "poly", size: [-10, 2.5, 10, 2.5, 9, -2.5, -9, -2.5], pos: [0, 16], color: SAFFRON, z: 0.5 },
      ],
    },
    {
      id: "kamarkasa",
      attach: "pelvis",
      // Waist sash with a katar tucked into it and the robe skirt below.
      parts: [
        { geo: "box", size: [28, 9], pos: [0, 2], color: SAFFRON },
        { geo: "box", size: [28, 2], pos: [0, 5], color: "#f0b45a" },
        // Katar pushed through the sash, hilt forward.
        { geo: "poly", size: [0, 3, 11, 1.5, 14, 0, 11, -1.5, 0, -3], pos: [8, -2], color: STEEL, z: 0.3 },
        { geo: "box", size: [4, 7], pos: [1, -2], color: GOLD, z: 0.35 },
        // Skirt of the chola.
        { geo: "poly", size: [-12, 4, 12, 4, 9, -20, -9, -20], pos: [0, -6], color: NIHANG_BLUE, behind: true },
        { geo: "poly", size: [-9, 2, 9, 2, 7, -8, -7, -8], pos: [0, -24], color: DEEP_BLUE, behind: true },
      ],
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 118,
      backThrowDamage: 128,
      throwRange: 60,
      rollSpeed: 7.6,
      weaponIdle: { weapon: STANCE.weapon },
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Quoit Slash",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 13,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [3, 12],
      // Chakram Work string continues into 6A.
      followUps: [
        { button: "A", move: "6A", from: 4, to: 10, string: "Chakram Work" },
      ],
      hits: [hit(4, 6, bx(18, 52, 44, 22), 30, { blockstun: 10, hitstun: 14, fx: "slash", pushX: 2.8 })],
      desc: "Rakes the held quoit across their face without letting go of it. Fast, and it chains.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderB: 96, elbowB: 12, torso: 12, offX: 3 }),
        kf(8, { ...STANCE, shoulderB: 74, elbowB: 46, torso: 8 }, "inOut"),
        kf(13, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Tulwar Cut",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 22,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [8, 20],
      // Tulwar Kata string continues into 5C.
      followUps: [
        { button: "C", move: "5C", from: 8, to: 19, string: "Tulwar Kata" },
      ],
      hits: [hit(8, 11, bx(24, 42, 68, 40), 58, { fx: "slash", pushX: 4.6, hitstun: 18 })],
      desc: "A drawing cut with the curve of the blade. His most honest button.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 136, elbowF: 26, weapon: 70, torso: -10, offX: -3 }),
        kf(8, { ...STANCE, shoulderF: 62, elbowF: 16, weapon: -12, torso: 24, hipF: 32, kneeF: 20, offX: 7 }, "out"),
        kf(14, { ...STANCE, shoulderF: 56, elbowF: 22, weapon: -8, torso: 18, offX: 5 }),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Full Draw",
      input: { button: "C", stance: "stand" },
      tags: ["heavy"],
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [15, 28],
      // Tulwar Kata string continues into 4C.
      followUps: [
        { button: "C", move: "4C", from: 14, to: 29, string: "Tulwar Kata" },
      ],
      hits: [
        hit(14, 18, bx(20, 30, 78, 64), 88, {
          fx: "slash",
          knockdown: "soft",
          pushX: 6.5,
          shake: 1.5,
        }),
      ],
      desc: "Turns the whole body through a long cut. Knocks down and gives him room to throw again.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderF: 162, elbowF: 16, weapon: 84, torso: -18, hipB: -26, kneeB: 40, offX: -4 }, "inOut"),
        kf(14, { ...STANCE, shoulderF: 44, elbowF: 12, weapon: -24, torso: 32, hipF: 40, kneeF: 24, hipB: -20, kneeB: 46, offX: 8 }, "out"),
        kf(22, { ...STANCE, shoulderF: 40, elbowF: 18, weapon: -20, torso: 26, offX: 5 }),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Quoit",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 14,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 13],
      hits: [hit(4, 6, bx(16, 16, 42, 20), 26, { guard: "low", blockstun: 10, hitstun: 13, pushX: 2.4 })],
      desc: "Rakes the quoit along the floor. Must be blocked crouching.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, ...guard }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 22, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderB: 108, elbowB: 6, offX: 4 }),
        kf(9, { ...STANCE, crouch: 1, torso: 20, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderB: 82, elbowB: 38 }, "inOut"),
        kf(14, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, ...guard }),
      ],
    },
    {
      id: "2B",
      name: "Low Cut",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 25,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [9, 23],
      hits: [hit(9, 12, bx(22, 10, 68, 26), 54, { guard: "low", fx: "slash", pushX: 4.4 })],
      desc: "Cuts across the shins with the tip of the curve. Long low.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }, "out"),
        kf(5, { ...STANCE, crouch: 1, torso: 8, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderF: 16, elbowF: 88, weapon: 92 }),
        kf(9, { ...STANCE, crouch: 1, torso: 26, hipF: 42, kneeF: 80, hipB: -26, kneeB: 90, shoulderF: 70, elbowF: 22, weapon: -26, offX: 8 }, "out"),
        kf(15, { ...STANCE, crouch: 1, torso: 24, hipF: 40, kneeF: 78, hipB: -24, kneeB: 88, shoulderF: 66, elbowF: 26, weapon: -22, offX: 6 }),
        kf(25, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }),
      ],
    },
    {
      id: "2C",
      name: "Heel Sweep",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 31,
      cancelInto: ["special", "super"],
      cancelWindow: [13, 27],
      hits: [
        hit(12, 16, bx(18, 2, 74, 24), 72, {
          guard: "low",
          knockdown: "sweep",
          fx: "slash",
          pushX: 5.8,
          shake: 1.2,
        }),
      ],
      desc: "Sweeps the blade along the ground. Knocks down - his best way to buy time for quoits.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }, "out"),
        kf(6, { ...STANCE, crouch: 1, torso: 4, hipF: 30, kneeF: 72, hipB: -30, kneeB: 94, shoulderF: 10, elbowF: 58, weapon: 116 }),
        kf(12, { ...STANCE, crouch: 1, torso: 30, hipF: 46, kneeF: 86, hipB: -30, kneeB: 98, shoulderF: 94, elbowF: 32, weapon: -50, offX: 7 }, "out"),
        kf(20, { ...STANCE, crouch: 1, torso: 26, hipF: 42, kneeF: 82, hipB: -26, kneeB: 92, shoulderF: 88, elbowF: 28, weapon: -44 }),
        kf(31, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }),
      ],
    },
    {
      id: "6B",
      name: "Overhand Quoit",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "overhead"],
      priority: 10,
      duration: 28,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 25],
      hits: [
        hit(16, 19, bx(16, 44, 52, 56), 58, {
          guard: "overhead",
          fx: "slash",
          pushX: 4.6,
          hitstun: 21,
          shake: 1.1,
        }),
      ],
      desc: "Chops down with the edge of the held quoit. Overhead - the partner to his low.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderB: 160, elbowB: 14, torso: -14, offX: -3 }, "inOut"),
        kf(16, { ...STANCE, shoulderB: 46, elbowB: 30, torso: 30, hipF: 34, kneeF: 22, offX: 6 }, "out"),
        kf(22, { ...STANCE, shoulderB: 52, elbowB: 36, torso: 24, offX: 4 }),
        kf(28, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Rising Tulwar",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 28],
      hits: [
        hit(10, 14, bx(14, 52, 58, 74), 68, {
          launch: [2, 12.5],
          knockdown: "launch",
          fx: "slash",
          hitstun: 25,
          shake: 1.3,
        }),
      ],
      desc: "Rips the curve of the blade upward. Launches - and puts them in the air where the quoits live.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5, hipF: 24, kneeF: 46, hipB: -20, kneeB: 52 }, "out"),
        kf(5, { ...STANCE, crouch: 0.7, torso: 12, shoulderF: 8, elbowF: 92, weapon: -64 }),
        kf(10, { ...STANCE, torso: -16, shoulderF: 150, elbowF: 12, weapon: -11, hipF: 20, kneeF: 12, offY: 4 }, "out"),
        kf(17, { ...STANCE, torso: -12, shoulderF: 142, elbowF: 16, weapon: 66, hipF: 16, kneeF: 10 }),
        kf(25, { ...STANCE, torso: 4, shoulderF: 58, elbowF: 52 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },
    {
      // Forward and back sets. Forward takes space, back gives it up to buy
      // range or a hard read.
      id: "6A",
      name: "Quoit Flick",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 20,
      vel: [{ at: 2, x: 2.2 }],
      friction: 0.88,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [7, 18],
      // Chakram Work string continues into 6B.
      followUps: [
        { button: "B", move: "6B", from: 7, to: 17, string: "Chakram Work" },
      ],
      hits: [hit(7, 9, bx(20, 60, 44, 26), 32, { guard: "high", fx: "slash", pushX: 3, hitstun: 14, hitstop: 5 })],
      desc: "Steps in and snaps the chakram edge across. Fast, and it keeps them honest.",
      notation: "\u2192 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderB: 30, elbowB: 78, weaponBack: 40, torso: -2, offX: -2 }, "out"),
        kf(7, { ...STANCE, shoulderB: 86, elbowB: 10, weaponBack: 4, torso: 14, hipF: 24, kneeF: 16, offX: 7 }, "out"),
        kf(12, { ...STANCE, shoulderB: 72, elbowB: 32, weaponBack: 24, torso: 10, offX: 5 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Charging Cut",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 40,
      armor: [{ from: 8, to: 18, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 8, x: 5.4 }, { at: 26, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [20, 36],
      hits: [hit(16, 20, bx(18, 22, 64, 68), 92, { guard: "mid", fx: "slash", pushX: 17, hitstun: 24, hitstop: 12, knockdown: "wallbounce", shake: 2.2 })],
      desc: "Comes forward with the whole arc behind the tulwar. Puts them in the wall.",
      notation: "\u2192 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 152, elbowF: -46, weapon: 138, torso: -12, hipB: -30, kneeB: 48, offX: -6 }, "out"),
        kf(16, { ...STANCE, shoulderF: 60, elbowF: 36, weapon: 23, torso: 32, hipF: 40, kneeF: 18, hipB: -26, kneeB: 24, offX: 12 }, "out"),
        kf(24, { ...STANCE, shoulderF: 52, elbowF: 44, weapon: -54, torso: 24, hipF: 28, kneeF: 24, offX: 8 }),
        kf(32, { ...STANCE, shoulderF: 46, elbowF: 52, weapon: 30, torso: 10, offX: 3 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Hilt Rap",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 22,
      vel: [{ at: 1, x: -2.6 }],
      friction: 0.86,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [8, 20],
      hits: [hit(8, 10, bx(16, 52, 42, 30), 36, { guard: "mid", fx: "blunt", pushX: 6, hitstun: 15, hitstop: 6 })],
      desc: "Steps off and raps the hilt across their guard. Buys him the space back.",
      notation: "\u2190 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -6, shoulderF: 22, elbowF: 78, weapon: 62, hipB: -26, kneeB: 40, offX: -6 }, "out"),
        kf(8, { ...STANCE, torso: 8, shoulderF: 70, elbowF: 22, weapon: 88, hipF: 22, kneeF: 18, offX: -3 }, "out"),
        kf(14, { ...STANCE, torso: 2, shoulderF: 54, elbowF: 44, weapon: 56, offX: -4 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Draw Cut",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 30,
      vel: [{ at: 1, x: -3.4 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      // Draw Cut string continues into 3C.
      followUps: [
        { button: "C", move: "3C", from: 12, to: 27, string: "Draw Cut" },
      ],
      hits: [hit(12, 15, bx(34, 52, 88, 24), 56, { guard: "mid", fx: "slash", pushX: 7, hitstun: 18, hitstop: 8 })],
      desc: "Retreats and lets the curve of the blade do the work on the way out.",
      notation: "\u2190 + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 112, elbowF: -26, weapon: 92, torso: -12, hipB: -28, kneeB: 42, offX: -8 }, "inOut"),
        // Edge laid on and pulled back - a draw, not a chop.
        kf(12, { ...STANCE, shoulderF: 76, elbowF: 10, weapon: 12, torso: 6, hipF: 26, kneeF: 14, offX: -5 }, "out"),
        kf(17, { ...STANCE, shoulderF: 68, elbowF: 16, weapon: 10, torso: 4, offX: -6 }),
        kf(23, { ...STANCE, shoulderF: 50, elbowF: 40, weapon: 34, torso: 0, offX: -4 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Overhand Tulwar",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 44,
      cancelInto: ["special", "super"],
      cancelWindow: [26, 40],
      hits: [hit(20, 23, bx(14, 20, 70, 86), 102, { guard: "overhead", fx: "slash", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 })],
      desc: "Takes it high and cuts straight down the centre. Blocked standing only.",
      notation: "\u2190 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 144, elbowF: -42, weapon: 92, torso: -10, offX: -5 }, "inOut"),
        kf(15, { ...STANCE, shoulderF: 176, elbowF: -14, weapon: 98, torso: -20, hipB: -26, kneeB: 38, offY: 3, offX: -3 }, "out"),
        kf(20, { ...STANCE, shoulderF: 84, elbowF: 12, weapon: 66, torso: 32, hipF: 34, kneeF: 18, hipB: -12, kneeB: 32, offX: 6 }, "out"),
        kf(26, { ...STANCE, shoulderF: 76, elbowF: 16, weapon: 62, torso: 26, offX: 4 }),
        kf(36, { ...STANCE, shoulderF: 52, elbowF: 44, weapon: 44, torso: 8 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Quoit",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 18,
      airborne: true,
      landCancel: true,
      landRecovery: 2,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [5, 16],
      hits: [hit(5, 11, bx(14, 32, 46, 30), 32, { fx: "slash", pushX: 2.6, hitstun: 14 })],
      desc: "Quick quoit rake out of a jump.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 34, kneeF: 46, hipB: -24, kneeB: 42 }, "out"),
        kf(5, { ...STANCE, free: 1, shoulderB: 114, elbowB: 14, torso: 14, hipF: 30, kneeF: 42 }),
        kf(12, { ...STANCE, free: 1, shoulderB: 82, elbowB: 46, torso: 8, hipF: 32, kneeF: 44 }, "inOut"),
        kf(18, { ...STANCE, free: 1, hipF: 34, kneeF: 46, hipB: -24, kneeB: 42 }),
      ],
    },
    {
      id: "jB",
      name: "Air Cut",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 25,
      airborne: true,
      landCancel: true,
      landRecovery: 4,
      hits: [hit(6, 14, bx(18, 8, 62, 46), 58, { fx: "slash", pushX: 3.8, hitstun: 19 })],
      desc: "Cuts down through the jump arc.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 30, kneeF: 42, hipB: -22, kneeB: 40 }, "out"),
        kf(3, { ...STANCE, free: 1, shoulderF: 148, elbowF: 18, weapon: 76, torso: -12 }),
        kf(6, { ...STANCE, free: 1, shoulderF: 58, elbowF: 18, weapon: -6, torso: 26, hipF: 38, kneeF: 34 }, "out"),
        kf(16, { ...STANCE, free: 1, shoulderF: 52, elbowF: 22, weapon: -4, torso: 22 }),
        kf(25, { ...STANCE, free: 1, hipF: 30, kneeF: 42, hipB: -22, kneeB: 40 }),
      ],
    },
    {
      id: "jC",
      name: "Air Chakram",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "projectile"],
      duration: 30,
      airborne: true,
      resourceCost: 1,
      resourceMin: 1,
      hideProps: ["chakram"],
      projectiles: [
        {
          at: 8,
          kind: "chakram",
          x: 26,
          y: 26,
          vx: 11,
          vy: -3.5,
          gravity: 0.16,
          life: 80,
          box: { x: -13, y: -13, w: 26, h: 26 },
          damage: 56,
          hitstun: 20,
          blockstun: 13,
          chip: 5,
          pushX: 6,
          clashes: true,
          fx: "slash",
          spin: 26,
          color: "#c9d2da",
          trail: "#6fa8ff",
        },
      ],
      desc: "Throws a quoit down at an angle from the air. Controls the ground under his jump.",
      notation: "(air) C  (1 Chakram)",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 30, kneeF: 42, hipB: -22, kneeB: 40 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderB: 158, elbowB: -26, torso: -16, hipF: 34, kneeF: 48 }),
        kf(8, { ...STANCE, free: 1, shoulderB: 58, elbowB: 4, torso: 26, hipF: 40, kneeF: 36 }, "out"),
        kf(18, { ...STANCE, free: 1, shoulderB: 52, elbowB: 18, torso: 18 }),
        kf(30, { ...STANCE, free: 1, hipF: 30, kneeF: 42, hipB: -22, kneeB: 40 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Charging Cut",
      input: { button: "C", dir: "f", stance: "stand", whileDashing: true },
      tags: ["command"],
      priority: 12,
      duration: 32,
      vel: [
        { at: 4, x: 9 },
        { at: 17, x: 0 },
      ],
      friction: 0.89,
      hits: [
        hit(9, 15, bx(18, 26, 64, 60), 76, {
          fx: "slash",
          pushX: 8,
          knockdown: "soft",
          hitstun: 22,
          shake: 1.5,
        }),
      ],
      desc: "Runs in behind the tulwar. Knocks down and lets him reset the spacing.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: 22, shoulderF: 10, elbowF: 92, weapon: 104, hipB: -32, kneeB: 46, offX: -2 }),
        kf(9, { ...STANCE, torso: 30, shoulderF: 78, elbowF: 14, weapon: -18, hipF: 42, kneeF: 24, hipB: -26, kneeB: 56, offX: 8 }, "out"),
        kf(21, { ...STANCE, torso: 24, shoulderF: 72, elbowF: 20, weapon: -14, hipF: 30, kneeF: 32 }),
        kf(32, { ...STANCE }),
      ],
    },

    // --------------------------------------------------------------- specials
    {
      id: "throw",
      name: "Chakram Throw",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      priority: 20,
      duration: 32,
      resourceCost: 2,
      resourceMin: 2,
      meterGain: 6,
      hideProps: ["chakram"],
      projectiles: [
        {
          at: 11,
          kind: "chakram",
          x: 36,
          y: 56,
          vx: 12.5,
          vy: 0,
          life: 100,
          box: { x: -14, y: -14, w: 28, h: 28 },
          damage: 54,
          hitstun: 19,
          blockstun: 13,
          chip: 6,
          pushX: 5,
          clashes: true,
          fx: "slash",
          spin: 30,
          color: "#c9d2da",
          trail: "#6fa8ff",
        },
      ],
      desc: "Spins a quoit off the fingers, flat and edge-on. Spends two - and he only carries five.",
      notation: "↓↘→ + B  (2 Chakram)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderB: 150, elbowB: -34, torso: -16, hipB: -28, kneeB: 42, offX: -5 }, "inOut"),
        kf(11, { ...STANCE, shoulderB: 70, elbowB: -2, torso: 26, hipF: 38, kneeF: 22, hipB: -20, kneeB: 46, offX: 8 }, "out"),
        kf(20, { ...STANCE, shoulderB: 64, elbowB: 14, torso: 18, offX: 5 }),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "throwEx",
      name: "Chakram Fan",
      input: { button: "S", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "projectile"],
      priority: 28,
      duration: 46,
      meterCost: 50,
      hideProps: ["chakram"],
      projectiles: [
        {
          at: 9,
          kind: "chakram",
          x: 36,
          y: 74,
          vx: 12,
          vy: -1.2,
          gravity: 0.04,
          life: 100,
          box: { x: -14, y: -14, w: 28, h: 28 },
          damage: 38,
          hitstun: 17,
          blockstun: 12,
          chip: 4,
          pushX: 3.5,
          clashes: true,
          fx: "slash",
          spin: 30,
          color: "#c9d2da",
        },
        {
          at: 16,
          kind: "chakram",
          x: 36,
          y: 54,
          vx: 13,
          vy: 0,
          life: 100,
          box: { x: -14, y: -14, w: 28, h: 28 },
          damage: 36,
          hitstun: 17,
          blockstun: 12,
          chip: 4,
          pushX: 3.5,
          clashes: true,
          fx: "slash",
          spin: 30,
          color: "#c9d2da",
        },
        {
          at: 23,
          kind: "chakram",
          x: 36,
          y: 30,
          vx: 13.5,
          vy: 0.8,
          gravity: 0.02,
          life: 100,
          box: { x: -14, y: -14, w: 28, h: 28 },
          damage: 46,
          hitstun: 21,
          blockstun: 14,
          chip: 5,
          pushX: 7,
          knockdown: "soft",
          clashes: true,
          fx: "slash",
          spin: 30,
          color: "#c9d2da",
          trail: "#6fa8ff",
        },
      ],
      desc: "EX. Three quoits at three heights, and the meter pays for them instead of the belt.",
      notation: "↓↘→ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderB: 146, elbowB: -30, torso: -14, offX: -4 }, "inOut"),
        kf(9, { ...STANCE, shoulderB: 80, elbowB: -4, torso: 24, offX: 6 }, "out"),
        kf(13, { ...STANCE, shoulderB: 146, elbowB: -30, torso: -12, offX: -3 }, "inOut"),
        kf(16, { ...STANCE, shoulderB: 74, elbowB: -2, torso: 24, offX: 6 }, "out"),
        kf(20, { ...STANCE, shoulderB: 148, elbowB: -30, torso: -12, offX: -3 }, "inOut"),
        kf(23, { ...STANCE, shoulderB: 64, elbowB: 2, torso: 28, hipF: 38, kneeF: 24, offX: 8 }, "out"),
        kf(36, { ...STANCE, torso: 14 }, "inOut"),
        kf(46, { ...STANCE }),
      ],
    },
    {
      id: "skip",
      name: "Skipping Quoit",
      input: { button: "C", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile", "low"],
      priority: 22,
      duration: 40,
      resourceCost: 2,
      resourceMin: 2,
      hideProps: ["chakram"],
      projectiles: [
        {
          at: 13,
          kind: "chakram",
          x: 34,
          y: 16,
          vx: 10,
          vy: 2,
          gravity: 0.34,
          bounce: 0.72,
          bounces: 3,
          life: 120,
          box: { x: -14, y: -14, w: 28, h: 28 },
          damage: 60,
          hitstun: 22,
          blockstun: 14,
          guard: "low",
          chip: 6,
          pushX: 6,
          knockdown: "sweep",
          clashes: true,
          fx: "slash",
          spin: 34,
          color: "#c9d2da",
          trail: "#6fa8ff",
        },
      ],
      vfx: [{ at: 13, kind: "dust", x: 32, y: 2, scale: 1.2 }],
      desc: "Skims a quoit off the ground so it skips at them. Must be blocked low, and it sweeps.",
      notation: "↓↘→ + C  (2 Chakram)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, crouch: 0.5, shoulderB: 130, elbowB: -20, torso: -8, offX: -4 }, "inOut"),
        kf(13, { ...STANCE, crouch: 0.85, shoulderB: 22, elbowB: 30, torso: 34, hipF: 42, kneeF: 78, hipB: -26, kneeB: 90, offX: 6 }, "out"),
        kf(24, { ...STANCE, crouch: 0.6, shoulderB: 40, elbowB: 40, torso: 24 }),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "guardBreak",
      name: "Circle the Blade",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 22,
      duration: 42,
      vel: [
        { at: 4, x: 5 },
        { at: 22, x: 0 },
      ],
      friction: 0.9,
      hits: [
        hit(10, 13, bx(20, 36, 62, 50), 34, { group: 1, fx: "slash", pushX: 1.5, hitstun: 15, hitstop: 4 }),
        hit(17, 20, bx(20, 26, 64, 58), 34, { group: 2, fx: "slash", pushX: 1.5, hitstun: 15, hitstop: 4 }),
        hit(26, 32, bx(18, 22, 72, 68), 76, {
          group: 3,
          fx: "slash",
          pushX: 9,
          knockdown: "hard",
          hitstun: 25,
          shake: 1.9,
        }),
      ],
      desc: "Three cuts round the same circle, each from a different angle. Costs no quoits - his answer when the belt is empty.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 140, elbowF: 24, weapon: 72, torso: -10, offX: -3 }, "inOut"),
        kf(10, { ...STANCE, shoulderF: 68, elbowF: 14, weapon: -14, torso: 24, offX: 6 }, "out"),
        kf(14, { ...STANCE, shoulderF: 14, elbowF: 92, weapon: 104, torso: 6 }, "inOut"),
        kf(17, { ...STANCE, shoulderF: 92, elbowF: 28, weapon: -36, torso: 26, offX: 6 }, "out"),
        kf(22, { ...STANCE, shoulderF: 166, elbowF: 10, weapon: 88, torso: -20, hipB: -28, kneeB: 42, offX: -5 }, "inOut"),
        kf(26, { ...STANCE, shoulderF: 38, elbowF: 10, weapon: -28, torso: 36, hipF: 44, kneeF: 26, hipB: -22, kneeB: 50, offX: 10 }, "out"),
        kf(36, { ...STANCE, shoulderF: 46, elbowF: 40, torso: 18, offX: 5 }, "inOut"),
        kf(42, { ...STANCE }),
      ],
    },
    {
      id: "returning",
      name: "Returning Quoit",
      input: { button: "C", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      priority: 24,
      duration: 48,
      resourceCost: 2,
      resourceMin: 2,
      // The quoit is thrown flat and caught again on the way past, so the belt
      // ends the move exactly where it started. It is the only throw he can
      // afford to spam - and it is slow enough that he pays for it in frames.
      resourceGain: 1,
      hideProps: ["chakram"],
      friction: 0.9,
      projectiles: [
        {
          at: 14,
          kind: "chakram",
          x: 34,
          y: 58,
          vx: 8,
          vy: 0,
          drag: 0.965,
          life: 96,
          box: { x: -16, y: -16, w: 32, h: 32 },
          damage: 48,
          hitstun: 20,
          blockstun: 14,
          chip: 5,
          pushX: 4,
          hits: 2,
          clashes: true,
          fx: "slash",
          spin: 38,
          color: "#c9d2da",
          trail: "#6fa8ff",
          scale: 1.25,
        },
      ],
      desc: "A heavy quoit thrown flat, slowing as it goes and hitting twice. He catches it again, so the belt costs him nothing.",
      notation: "↓↙← + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderB: 140, elbowB: -34, torso: -18, hipB: -30, kneeB: 44, offX: -6 }, "inOut"),
        kf(14, { ...STANCE, shoulderB: 62, elbowB: -6, torso: 30, hipF: 40, kneeF: 22, hipB: -20, kneeB: 46, offX: 9 }, "out"),
        kf(26, { ...STANCE, shoulderB: 58, elbowB: 10, torso: 20, offX: 5 }),
        kf(38, { ...STANCE, shoulderB: 88, elbowB: 24, torso: 8 }, "inOut"),
        kf(48, { ...STANCE }),
      ],
    },
    {
      id: "rise",
      name: "Akal Rise",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 26,
      duration: 44,
      airborne: true,
      invuln: [{ from: 1, to: 8, kind: "strike" }],
      vel: [
        { at: 1, x: 2.2, y: 12.4 },
        { at: 26, y: -1, mode: "add" },
      ],
      hits: [
        hit(3, 8, bx(4, 54, 58, 78), 78, {
          launch: [2, 11],
          knockdown: "launch",
          fx: "slash",
          hitstun: 25,
          shake: 1.8,
        }),
        hit(9, 16, bx(2, 66, 54, 66), 36, { group: 2, launch: [1.6, 5.5], fx: "slash", hitstun: 17 }),
      ],
      desc: "Comes up off the back foot with the tulwar leading. Invincible on startup - his reversal.",
      notation: "→↓↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 22, kneeF: 50, hipB: -20, kneeB: 54 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -14, shoulderF: 152, elbowF: 14, weapon: 40, hipF: 32, kneeF: 30, hipB: -26, kneeB: 40 }, "out"),
        kf(12, { ...STANCE, free: 1, torso: -20, shoulderF: 168, elbowF: 8, weapon: 34, hipF: 26, kneeF: 26 }),
        kf(30, { ...STANCE, free: 1, torso: -2, shoulderF: 116, elbowF: 32, hipF: 30, kneeF: 42 }, "inOut"),
        kf(44, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "riseEx",
      name: "Akal Rise EX",
      input: { button: "S", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "launcher"],
      priority: 32,
      duration: 50,
      meterCost: 50,
      airborne: true,
      invuln: [{ from: 1, to: 16, kind: "strike" }],
      vel: [
        { at: 1, x: 2.8, y: 13.8 },
        { at: 30, y: -1, mode: "add" },
      ],
      hits: [
        hit(2, 8, bx(4, 52, 64, 84), 70, { launch: [2, 12.5], knockdown: "launch", fx: "slash", hitstun: 27, shake: 2 }),
        hit(9, 17, bx(2, 66, 58, 76), 34, { group: 2, launch: [1.4, 5], fx: "slash" }),
        hit(18, 26, bx(2, 76, 56, 68), 46, { group: 3, launch: [2, 4], fx: "slash", knockdown: "hard" }),
      ],
      desc: "EX. Fully invincible, higher, and it carries them up with him.",
      notation: "→↓↘ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 22, kneeF: 50 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -16, shoulderF: 158, elbowF: 12, weapon: 38, spin: -10 }, "out"),
        kf(16, { ...STANCE, free: 1, torso: -24, shoulderF: 174, elbowF: 4, weapon: 30, spin: -30 }),
        kf(34, { ...STANCE, free: 1, torso: -4, shoulderF: 118, elbowF: 30, spin: -6 }, "inOut"),
        kf(50, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "recover",
      name: "Call Them Back",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill"],
      priority: 18,
      duration: 38,
      resourceGain: 3,
      friction: 0.86,
      armor: [{ from: 4, to: 20, hits: 1, damageScale: 0.45 }],
      vfx: [{ at: 22, kind: "spark", x: 0, y: 78, scale: 1.4, color: "#c9d2da" }],
      desc: "SKILL. Takes three fresh quoits down off the dumalla. Absorbs one hit while he does it, which is the only reason it is safe at all.",
      notation: "A + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, torso: -6, shoulderB: 152, elbowB: 26, shoulderF: 40, elbowF: 60, head: 6, crouch: 0.2 }, "inOut"),
        kf(20, { ...STANCE, torso: -8, shoulderB: 164, elbowB: 14, shoulderF: 44, elbowF: 56, head: 8, crouch: 0.22 }),
        kf(28, { ...STANCE, torso: -2, shoulderB: 110, elbowB: 40, shoulderF: 38, elbowF: 62, head: 2 }, "inOut"),
        kf(38, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "Nowshera",
      input: { button: "S", motion: "dd", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 100,
      meterCost: 100,
      superFreeze: 40,
      invuln: [{ from: 1, to: 13, kind: "strike" }],
      hideProps: ["chakram"],
      vel: [
        { at: 40, x: 10 },
        { at: 66, x: 0 },
      ],
      friction: 0.93,
      projectiles: [
        {
          at: 10,
          kind: "chakram",
          x: 34,
          y: 76,
          vx: 13,
          vy: -1,
          gravity: 0.03,
          life: 110,
          box: { x: -14, y: -14, w: 28, h: 28 },
          damage: 42,
          hitstun: 18,
          blockstun: 12,
          chip: 4,
          pushX: 3,
          clashes: true,
          fx: "slash",
          spin: 34,
          color: "#c9d2da",
          trail: "#6fa8ff",
        },
        {
          at: 16,
          kind: "chakram",
          x: 34,
          y: 56,
          vx: 14,
          vy: 0,
          life: 110,
          box: { x: -14, y: -14, w: 28, h: 28 },
          damage: 40,
          hitstun: 18,
          blockstun: 12,
          chip: 4,
          pushX: 3,
          clashes: true,
          fx: "slash",
          spin: 34,
          color: "#c9d2da",
        },
        {
          at: 22,
          kind: "chakram",
          x: 34,
          y: 34,
          vx: 14,
          vy: 0.4,
          life: 110,
          box: { x: -14, y: -14, w: 28, h: 28 },
          damage: 40,
          hitstun: 18,
          blockstun: 12,
          chip: 4,
          pushX: 3,
          clashes: true,
          fx: "slash",
          spin: 34,
          color: "#c9d2da",
        },
        {
          at: 28,
          kind: "chakram",
          x: 34,
          y: 14,
          vx: 13,
          vy: 0.2,
          life: 110,
          box: { x: -14, y: -14, w: 28, h: 28 },
          damage: 44,
          hitstun: 20,
          blockstun: 13,
          guard: "low",
          chip: 5,
          pushX: 4,
          clashes: true,
          fx: "slash",
          spin: 34,
          color: "#c9d2da",
        },
      ],
      hits: [
        hit(56, 64, bx(14, 12, 88, 92), 140, {
          fx: "slash",
          pushX: 12,
          knockdown: "hard",
          launch: [5, 9],
          hitstop: 18,
          shake: 3.1,
        }),
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 50, scale: 2.4, color: "#6fa8ff" },
        { at: 56, kind: "explode", x: 54, y: 46, scale: 1.4 },
      ],
      desc: "SUPER. Empties the dumalla - four quoits across four heights - and then rides in behind them with the tulwar, the way he went in at Nowshera.",
      notation: "↓↓ + S  (100 meter)",
      frames: [
        kf(0, { ...STANCE, torso: -14, shoulderB: 150, elbowB: -30, crouch: 0.35 }, "out"),
        kf(10, { ...STANCE, torso: 24, shoulderB: 78, elbowB: -4, offX: 5 }, "out"),
        kf(14, { ...STANCE, torso: -10, shoulderB: 152, elbowB: -30, offX: -3 }, "inOut"),
        kf(16, { ...STANCE, torso: 24, shoulderB: 74, elbowB: -2, offX: 5 }, "out"),
        kf(20, { ...STANCE, torso: -10, shoulderB: 152, elbowB: -30, offX: -3 }, "inOut"),
        kf(22, { ...STANCE, torso: 26, shoulderB: 68, elbowB: 0, offX: 5 }, "out"),
        kf(26, { ...STANCE, torso: -8, shoulderB: 140, elbowB: -24, crouch: 0.4, offX: -3 }, "inOut"),
        kf(28, { ...STANCE, torso: 30, shoulderB: 30, elbowB: 26, crouch: 0.6, offX: 5 }, "out"),
        kf(40, { ...STANCE, torso: 30, shoulderF: 20, elbowF: 88, weapon: 96, hipB: -34, kneeB: 48, offX: 2 }, "out"),
        kf(50, { ...STANCE, torso: -22, shoulderF: 172, elbowF: 8, weapon: 90, hipB: -30, kneeB: 44, offX: -5 }, "inOut"),
        kf(56, { ...STANCE, torso: 40, shoulderF: 28, elbowF: 6, weapon: -30, hipF: 48, kneeF: 28, hipB: -24, kneeB: 56, offX: 12 }, "out"),
        kf(80, { ...STANCE, torso: 24, shoulderF: 44, elbowF: 44, offX: 5 }, "inOut"),
        kf(100, { ...STANCE }),
      ],
    },
  ],
};
