/**
 * Hyo Kagemori - shinobi.
 *
 * Built out of mix-ups rather than damage: a kunai to make them block, a
 * teleport to appear on the other side of it, an overhead and a low that look
 * the same for the first six frames. Her Kage bar is the fuel for the
 * disappearing act, and it only refills while she is standing still - so the
 * more she cheats, the more honestly she has to fight.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const CLOTH = "#2b3350";
const DARK = "#1b2138";
const STEEL = "#c9d2de";
const SASH = "#a8324a";

const STANCE = {
  torso: 6,
  head: -2,
  hipF: 16,
  kneeF: 20,
  hipB: -20,
  kneeB: 32,
  // Low, coiled, blade hand back and ready.
  shoulderF: 68,
  elbowF: 62,
  shoulderB: 30,
  elbowB: 66,
  crouch: 0.18,
  // Reverse grip: the blade lies back along her forearm until she swings.
  weaponBack: 168,
};

/** Arm carriage the universal moves keep so the tanto stays out of her body. */
const IDLE_ARMS = { shoulderB: 30, elbowB: 66, weaponBack: 168 };

export const NINJA: FighterDef = {
  id: "ninja",
  name: "Hattori Hanzō",
  title: "Captain of the Iga Men",
  era: "Iga Crossing, 1582",
  bio: "Iga-born retainer of Tokugawa Ieyasu. When Nobunaga was killed at Honnō-ji he took his lord back across Iga through hostile country on nothing but the goodwill of men he had grown up with.",
  archetype: "Mix-up / Mobility",
  difficulty: 4,
  strengths: ["Teleport crosses up anything", "Fastest walk speed", "Overhead and low off the same startup"],
  weaknesses: ["Lowest health in the roster", "Damage needs three correct guesses", "Kage only refills while idle"],
  winQuote: "You never saw the road we took. That was the point of it.",
  palette: {
    body: "#e6d8c0",
    outline: "#0f1220",
    accent: SASH,
    cloth: CLOTH,
    metal: STEEL,
    aura: "#7fd4ff",
  },
  stats: {
    health: 900,
    walkF: 3.4,
    walkB: 3.05,
    dashSpeed: 9.6,
    dashFrames: 13,
    backdashFrames: 17,
    jumpVel: 12.9,
    jumpFwd: 5.4,
    gravity: 0.62,
    weight: 1.08,
    airMoves: 2,
    doubleJump: true,
    airDash: true,
    width: 18,
    standHeight: 100,
    crouchHeight: 60,
    scale: 0.975,
  },
  stance: STANCE,
  // The reverse grip already lays the tanto along her forearm, so guarding
  // is just raising the arm and letting the blade cover it.
  clips: guardClips({
    high: { torso: 0, head: -6, shoulderB: 16, elbowB: 144, weaponBack: 168, shoulderF: 30, elbowF: 122, crouch: 0.1, hipF: 16, kneeF: 24, hipB: -20, kneeB: 34, offX: -2 },
    low: { torso: 8, head: -5, shoulderB: 24, elbowB: 134, weaponBack: 168, shoulderF: 36, elbowF: 114, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, offX: -2 },
  }),
  resource: {
    name: "Kage",
    max: 3,
    start: 2,
    // Two seconds of standing still buys one teleport back.
    regen: 0.0085,
    regenIdleOnly: true,
    color: "#7fd4ff",
    pips: true,
  },
  props: [
    {
      id: "hood",
      attach: "head",
      // Cowl over the crown, a bare strip for the eyes, mask over the jaw -
      // the pale band is what makes the head read as a face and not a lump.
      parts: [
        { geo: "poly", size: [-12, -6, -12, 4, -7, 9, 0, 11, 7, 9, 12, 3, 12, -6], pos: [0, 6], color: CLOTH },
        { geo: "box", size: [24, 3.5], pos: [0, 13], color: DARK },
        { geo: "poly", size: [-11, 7, 10, 6, 11, -5, 3, -7, -10, -6], pos: [3, -8], color: CLOTH },
        { geo: "box", size: [22, 3], pos: [3, -14], color: DARK },
        // Knot and tail of the hood hanging off the back.
        { geo: "poly", size: [-4, 4, 4, 3, 3, -4, -4, -4], pos: [-12, 4], color: DARK, behind: true },
        { geo: "poly", size: [0, 5, -5, -6, -11, -12, -9, 2], pos: [-14, 1], rot: 8, color: DARK, behind: true },
      ],
    },
    {
      id: "scarf",
      attach: "neck",
      parts: [{ geo: "poly", size: [-10, 4, 10, 3, 9, -4, -10, -4], pos: [-2, -1], color: SASH }],
      cloth: {
        segments: 5,
        segmentLength: 13,
        width: 13,
        endWidth: 4,
        color: SASH,
        lining: "#7a2337",
        gravity: 0.34,
        stiffness: 0.5,
        drift: -0.5,
      },
    },
    {
      id: "vest",
      attach: "torso",
      // Quilted jacket with a chest plate laced under the cross straps, and a
      // row of throwing spikes along the strap.
      parts: [
        { geo: "poly", size: [-13, -16, 13, -16, 14, 6, 9, 16, -9, 16, -14, 6], pos: [0, 4], color: CLOTH },
        { geo: "poly", size: [-9, -10, 9, -10, 10, 4, 5, 10, -5, 10, -10, 4], pos: [0, 4], color: "#232b46" },
        { geo: "box", size: [19, 1.6], pos: [0, 8], color: "#39436a" },
        { geo: "box", size: [19, 1.6], pos: [0, 1], color: "#39436a" },
        { geo: "box", size: [19, 1.6], pos: [0, -6], color: "#39436a" },
        { geo: "poly", size: [-12, 3, 12, 4, 12, -3, -12, -4], pos: [0, -10], color: SASH },
        // Cross straps - a shade lighter than the jacket, or they vanish.
        { geo: "poly", size: [-3, 19, 3, 19, 3, -19, -3, -19], pos: [-4, 4], rot: 12, color: "#454f74" },
        { geo: "poly", size: [-2.5, 17, 2.5, 17, 2.5, -17, -2.5, -17], pos: [6, 4], rot: -14, color: "#3a4462" },
        // Spikes tucked into the strap.
        { geo: "poly", size: [0, 4, 5, 1, 5, -1, 0, -4], pos: [-6, 12], rot: 12, color: STEEL, z: 0.3 },
        { geo: "poly", size: [0, 4, 5, 1, 5, -1, 0, -4], pos: [-4, 4], rot: 12, color: STEEL, z: 0.3 },
        { geo: "poly", size: [0, 4, 5, 1, 5, -1, 0, -4], pos: [-2, -4], rot: 12, color: STEEL, z: 0.3 },
      ],
    },
    {
      id: "pouch",
      attach: "pelvis",
      parts: [
        { geo: "poly", size: [-12, 4, 12, 3.5, 12, -4, -12, -4.5], pos: [0, 1], color: DARK },
        { geo: "poly", size: [-5, 6, 5, 5, 4, -7, -5, -6], pos: [-11, -5], color: CLOTH },
        { geo: "box", size: [9, 2], pos: [-11, 0], color: "#3a4462", z: 0.2 },
        { geo: "poly", size: [-4, 3, 4, 2, 4, -3, -4, -3], pos: [10, -2], color: SASH },
      ],
    },
    {
      id: "tanto",
      attach: "handB",
      // Tanto: short, straight, with a squared guard and a wrapped grip.
      parts: [
        { geo: "poly", size: [-6, 3.4, 6, 3, 6, -3, -6, -3.4], pos: [-2, 0], color: DARK },
        { geo: "box", size: [2, 5], pos: [-4, 0], rot: 45, color: "#8b7d5c" },
        { geo: "box", size: [2, 5], pos: [-1, 0], rot: 45, color: "#8b7d5c" },
        { geo: "box", size: [3, 11], pos: [5, 0], color: "#8b7d5c" },
        { geo: "blade", size: [26, 5.5, 0.3], pos: [18, 0], color: "#98a3b2" },
        { geo: "box", size: [22, 1.4], pos: [17, 1.4], color: "#eef2f6" },
      ],
    },
    {
      id: "kunai",
      attach: "handF",
      conditional: true,
      parts: [
        { geo: "box", size: [11, 5], pos: [-2, 0], color: DARK },
        { geo: "ring", size: [4.5, 1.8], pos: [-9, 0], color: DARK },
        { geo: "poly", size: [-4, 5, 10, 3, 18, 0, 10, -3, -4, -5], pos: [12, 0], color: STEEL },
      ],
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 122,
      backThrowDamage: 138,
      throwRange: 56,
      rollSpeed: 9.2,
      weaponIdle: IDLE_ARMS,
      // Reversed grip: the tanto points down at rest and would dig in.
      rollCarry: { back: 86 },
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Palm Strike",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 12,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 11],
      // Kunai Flurry string continues into 4A.
      followUps: [
        { button: "A", move: "4A", from: 4, to: 9, string: "Kunai Flurry" },
      ],
      hits: [hit(4, 6, bx(16, 56, 44, 20), 26, { fx: "blunt", hitstun: 14, blockstun: 10, pushX: 2.4 })],
      desc: "Open hand off the front shoulder. Four frames and it cancels into everything.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 92, elbowF: 6, torso: 12, offX: 3 }),
        kf(8, { ...STANCE, shoulderF: 74, elbowF: 44, torso: 8 }, "inOut"),
        kf(12, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Tanto Slash",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 19,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [7, 17],
      // Tanto Work string continues into 6C.
      followUps: [
        { button: "C", move: "6C", from: 6, to: 16, string: "Tanto Work" },
      ],
      hits: [hit(6, 9, bx(18, 46, 58, 34), 50, { fx: "slash", pushX: 4, hitstun: 18 })],
      desc: "Short blade across the middle. Fast for a weapon button.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderB: 12, elbowB: 96, torso: -6, weaponBack: 90, offX: -2 }),
        kf(6, { ...STANCE, shoulderB: 96, elbowB: 22, torso: 18, weaponBack: 10, hipF: 26, offX: 6 }, "out"),
        kf(12, { ...STANCE, shoulderB: 62, elbowB: 52, torso: 10, weaponBack: 26 }, "inOut"),
        kf(19, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Crescent Kick",
      input: { button: "C", stance: "stand" },
      tags: ["heavy"],
      duration: 29,
      cancelInto: ["special", "super"],
      cancelWindow: [13, 25],
      // Shadow Kicks string continues into 4B.
      followUps: [
        { button: "B", move: "4B", from: 12, to: 26, string: "Shadow Kicks" },
      ],
      hits: [
        hit(12, 16, bx(20, 44, 76, 40), 82, {
          fx: "blunt",
          pushX: 7.5,
          knockdown: "soft",
          hitstun: 23,
          shake: 1.7,
        }),
      ],
      desc: "Hooks the heel over and brings it down across their guard.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, torso: -10, hipB: -40, kneeB: 66, offX: -3 }, "inOut"),
        kf(12, { ...STANCE, torso: 22, spin: -8, hipB: 104, kneeB: 16, hipF: 24, kneeF: 18, shoulderF: 130, elbowF: 40, offX: 6 }, "out"),
        kf(20, { ...STANCE, torso: 14, hipB: 40, kneeB: 46, offX: 3 }),
        kf(29, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Jab",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 12,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 11],
      hits: [hit(4, 6, bx(14, 14, 42, 18), 24, { guard: "low", fx: "blunt", hitstun: 13, blockstun: 10, pushX: 2.2 })],
      desc: "Knuckles to the shin from a crouch. Her check button.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 22, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderF: 84, elbowF: 32, offX: 4 }),
        kf(8, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderF: 66, elbowF: 60 }, "inOut"),
        kf(12, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }),
      ],
    },
    {
      id: "2B",
      name: "Low Cut",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 21,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [8, 19],
      hits: [hit(7, 10, bx(18, 8, 62, 24), 48, { guard: "low", fx: "slash", pushX: 3.8, hitstun: 17 })],
      desc: "Blade dragged across the ankle. Blocked low, cancels into everything she has.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 10, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderB: -4, elbowB: 90, weaponBack: 80 }),
        kf(7, { ...STANCE, crouch: 1, torso: 26, hipF: 40, kneeF: 80, hipB: -22, kneeB: 86, shoulderB: 44, elbowB: 12, weaponBack: -30, offX: 6 }, "out"),
        kf(14, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderB: 30, elbowB: 50, weaponBack: 10 }, "inOut"),
        kf(21, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }),
      ],
    },
    {
      id: "2C",
      name: "Scythe Sweep",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 28,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 24],
      hits: [hit(10, 14, bx(16, 2, 80, 22), 70, { guard: "low", knockdown: "sweep", fx: "blunt", pushX: 5.4 })],
      desc: "Spins the back leg through the floor. Knocks them down for free pressure.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }, "out"),
        kf(5, { ...STANCE, crouch: 1, torso: 22, hipF: 12, kneeF: 96, hipB: -34, kneeB: 100, offX: -2 }),
        kf(10, { ...STANCE, crouch: 1, torso: 28, spin: -10, hipF: 88, kneeF: 4, hipB: -38, kneeB: 106, shoulderF: 30, elbowF: 20, offX: 6 }, "out"),
        kf(19, { ...STANCE, crouch: 1, torso: 20, hipF: 50, kneeF: 50, hipB: -28, kneeB: 94 }, "inOut"),
        kf(28, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }),
      ],
    },
    {
      id: "6B",
      name: "Hook Kick",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "overhead"],
      priority: 10,
      duration: 30,
      vel: [{ at: 6, x: 3 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      hits: [hit(15, 19, bx(18, 34, 56, 46), 56, { guard: "overhead", fx: "blunt", pushX: 4.6, hitstun: 20 })],
      desc: "Steps in and chops the heel down. Overhead - it starts exactly like her low cut.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, crouch: 0.5, torso: 14, hipF: 16, kneeF: 62 }),
        kf(11, { ...STANCE, free: 1, offY: 12, torso: -12, hipF: 112, kneeF: 12, hipB: -30, kneeB: 60 }, "out"),
        kf(15, { ...STANCE, free: 1, offY: 4, torso: 26, hipF: 30, kneeF: 4, hipB: -18, kneeB: 40, offX: 5 }, "out"),
        kf(22, { ...STANCE, offY: 0, torso: 14, hipF: 34, kneeF: 40 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Rising Cut",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 30,
      cancelInto: ["special", "super"],
      cancelWindow: [11, 26],
      hits: [hit(9, 13, bx(14, 40, 52, 74), 66, { launch: [2, 12.5], knockdown: "launch", fx: "slash", hitstun: 26 })],
      desc: "Blade up through the chin. Launches, and she can follow them all the way up.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 50 }, "out"),
        kf(5, { ...STANCE, crouch: 0.8, torso: 16, shoulderB: -10, elbowB: 84, weaponBack: 74 }),
        kf(9, { ...STANCE, torso: -14, shoulderB: 168, elbowB: 8, weaponBack: -14, hipF: 18, kneeF: 12, offY: 4 }, "out"),
        kf(18, { ...STANCE, torso: -6, shoulderB: 120, elbowB: 34, weaponBack: 10 }),
        kf(24, { ...STANCE, torso: 2, shoulderB: 60, elbowB: 60 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      // Forward and back sets. Forward takes space, back gives it up to buy
      // range or a hard read.
      id: "6A",
      name: "Kunai Flick",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 20,
      vel: [{ at: 2, x: 2.2 }],
      friction: 0.88,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [6, 18],
      // Kunai Flurry string continues into 5A.
      followUps: [
        { button: "A", move: "5A", from: 6, to: 17, string: "Kunai Flurry" },
      ],
      hits: [hit(6, 8, bx(20, 60, 44, 26), 28, { guard: "high", fx: "slash", pushX: 3, hitstun: 13, hitstop: 5 })],
      desc: "Steps in and flicks the kunai across. Her fastest button by a wide margin.",
      notation: "\u2192 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderF: 42, elbowF: 74, weapon: 40, torso: -2, offX: -2 }, "out"),
        kf(6, { ...STANCE, shoulderF: 88, elbowF: 6, weapon: 2, torso: 14, hipF: 26, kneeF: 18, offX: 8 }, "out"),
        kf(11, { ...STANCE, shoulderF: 74, elbowF: 28, weapon: 22, torso: 10, offX: 5 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Running Cut",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 40,
      armor: [{ from: 8, to: 18, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 8, x: 5.4 }, { at: 26, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [20, 36],
      // Tanto Work string continues into 4C.
      followUps: [
        { button: "C", move: "4C", from: 16, to: 37, string: "Tanto Work" },
      ],
      hits: [hit(16, 20, bx(16, 22, 52, 68), 88, { guard: "mid", fx: "slash", pushX: 17, hitstun: 24, hitstop: 12, knockdown: "wallbounce", shake: 2.2 })],
      desc: "Closes and drags the blade through on the way past. Puts them in the wall.",
      notation: "\u2192 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        // Reverse grip: the blade lies back along the forearm, so the cut
        // comes from the elbow opening out, not from a swing.
        kf(8, { ...STANCE, shoulderB: 14, elbowB: 118, weaponBack: 168, torso: -14, hipB: -30, kneeB: 48, offX: -6 }, "out"),
        kf(16, { ...STANCE, shoulderB: 92, elbowB: 18, weaponBack: 152, torso: 32, hipF: 42, kneeF: 20, hipB: -26, kneeB: 26, offX: 12 }, "out"),
        kf(24, { ...STANCE, shoulderB: 82, elbowB: 26, weaponBack: 154, torso: 24, hipF: 30, kneeF: 26, offX: 8 }),
        kf(32, { ...STANCE, shoulderB: 44, elbowB: 58, weaponBack: 166, torso: 10, offX: 3 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Backhand Cut",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 22,
      vel: [{ at: 1, x: -2.6 }],
      friction: 0.86,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [8, 20],
      hits: [hit(8, 10, bx(16, 52, 42, 30), 36, { guard: "mid", fx: "slash", pushX: 6, hitstun: 15, hitstop: 6 })],
      desc: "Slips back and opens the elbow so the blade rakes across on the way out.",
      notation: "\u2190 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -6, shoulderB: 6, elbowB: 110, weaponBack: 168, hipB: -26, kneeB: 40, offX: -6 }, "out"),
        kf(8, { ...STANCE, torso: 8, shoulderB: 70, elbowB: 26, weaponBack: 156, hipF: 22, kneeF: 20, offX: -3 }, "out"),
        kf(14, { ...STANCE, torso: 2, shoulderB: 42, elbowB: 56, weaponBack: 164, offX: -4 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Retreating Kick",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 30,
      vel: [{ at: 1, x: -3.4 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      hits: [hit(12, 15, bx(26, 46, 68, 30), 56, { guard: "mid", fx: "blunt", pushX: 7, hitstun: 18, hitstop: 8 })],
      desc: "Gives ground and snaps the lead leg out at whatever follows.",
      notation: "\u2190 + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, hipF: 66, kneeF: 104, torso: -14, hipB: -34, kneeB: 46, offX: -8 }, "inOut"),
        kf(12, { ...STANCE, hipF: 96, kneeF: 10, hipB: -26, kneeB: 20, torso: -18, head: 6, offX: -4 }, "out"),
        kf(17, { ...STANCE, hipF: 90, kneeF: 14, torso: -16, offX: -6 }),
        kf(23, { ...STANCE, hipF: 44, kneeF: 54, torso: -2, offX: -4 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Falling Tanto",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 44,
      cancelInto: ["special", "super"],
      cancelWindow: [26, 40],
      hits: [hit(20, 23, bx(12, 20, 58, 86), 96, { guard: "overhead", fx: "pierce", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 })],
      desc: "Jumps the blade up and drives it straight down, point first. Blocked standing only.",
      notation: "\u2190 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderB: 100, elbowB: 46, weaponBack: 168, torso: -12, offX: -5 }, "inOut"),
        // Reverse grip drives point-down from above, which is exactly what
        // this grip is for.
        kf(15, { ...STANCE, shoulderB: 172, elbowB: 20, weaponBack: 172, torso: -20, hipB: -26, kneeB: 38, offY: 4, offX: -3 }, "out"),
        kf(20, { ...STANCE, shoulderB: 92, elbowB: 4, weaponBack: 176, torso: 34, hipF: 36, kneeF: 18, hipB: -12, kneeB: 32, offX: 6 }, "out"),
        kf(26, { ...STANCE, shoulderB: 84, elbowB: 8, weaponBack: 174, torso: 26, offX: 4 }),
        kf(36, { ...STANCE, shoulderB: 44, elbowB: 58, weaponBack: 168, torso: 8 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Slice",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 17,
      airborne: true,
      landCancel: true,
      landRecovery: 2,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [4, 15],
      hits: [hit(4, 9, bx(14, 32, 44, 28), 28, { fx: "slash", hitstun: 14, pushX: 2.2 })],
      desc: "Quick blade flick in the air. Keeps a juggle alive.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 34, kneeF: 44, hipB: -24, kneeB: 44 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderB: 78, elbowB: 14, weaponBack: 8, torso: 12 }),
        kf(11, { ...STANCE, free: 1, shoulderB: 46, elbowB: 56, weaponBack: 30, torso: 6 }, "inOut"),
        kf(17, { ...STANCE, free: 1, hipF: 34, kneeF: 44, hipB: -24, kneeB: 44 }),
      ],
    },
    {
      id: "jB",
      name: "Air Knee",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 23,
      airborne: true,
      landCancel: true,
      landRecovery: 4,
      cancelInto: ["heavy", "special"],
      hits: [hit(6, 13, bx(16, 18, 52, 42), 52, { fx: "blunt", pushX: 3.8, hitstun: 18 })],
      desc: "Knee out in front of her on the way in.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 32, kneeF: 42, hipB: -22, kneeB: 40 }, "out"),
        kf(4, { ...STANCE, free: 1, hipF: 12, kneeF: 90, torso: 10 }),
        kf(7, { ...STANCE, free: 1, hipF: 98, kneeF: 106, hipB: -26, kneeB: 46, torso: 18 }, "out"),
        kf(15, { ...STANCE, free: 1, hipF: 58, kneeF: 68, torso: 8 }, "inOut"),
        kf(23, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "jC",
      name: "Falling Blade",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 27,
      airborne: true,
      landCancel: true,
      landRecovery: 6,
      hits: [
        hit(7, 17, bx(6, 4, 52, 48), 74, {
          guard: "overhead",
          fx: "slash",
          knockdown: "soft",
          pushX: 4.6,
          shake: 1.4,
        }),
      ],
      desc: "Point-down blade all the way to the floor. Her jump-in.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, torso: -18, shoulderB: 172, elbowB: 20, weaponBack: 20, hipF: 40, kneeF: 56 }),
        kf(8, { ...STANCE, free: 1, torso: 30, shoulderB: 40, elbowB: 10, weaponBack: -70, hipF: 14, kneeF: 18 }, "out"),
        kf(27, { ...STANCE, free: 1, torso: 24, shoulderB: 34, elbowB: 14, weaponBack: -70 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Shadow Rush",
      input: { button: "C", dir: "f", stance: "stand", whileDashing: true },
      tags: ["command"],
      priority: 12,
      duration: 30,
      vel: [
        { at: 3, x: 11 },
        { at: 15, x: 0 },
      ],
      friction: 0.9,
      hits: [hit(7, 12, bx(18, 26, 62, 46), 68, { fx: "slash", pushX: 6.5, knockdown: "soft", hitstun: 21, shake: 1.4 })],
      desc: "Runs the blade forward at chest height. Closes the screen in a hurry.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 26, crouch: 0.4, shoulderB: 4, elbowB: 80, weaponBack: 70, offX: -3 }),
        kf(7, { ...STANCE, torso: 32, crouch: 0.3, shoulderB: 74, elbowB: 10, weaponBack: -6, hipF: 46, kneeF: 24, offX: 8 }, "out"),
        kf(20, { ...STANCE, torso: 16, shoulderB: 48, elbowB: 46, offX: 3 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },

    // -------------------------------------------------------- five specials
    {
      id: "kunaiThrow",
      name: "Kunai",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      duration: 28,
      showProps: ["kunai"],
      projectiles: [
        {
          at: 10,
          kind: "kunai",
          x: 34,
          y: 62,
          vx: 17,
          vy: 0.6,
          gravity: 0.04,
          life: 70,
          box: { x: -9, y: -4, w: 18, h: 9 },
          damage: 42,
          hitstun: 17,
          blockstun: 12,
          chip: 3,
          pushX: 3,
          clashes: true,
          fx: "pierce",
          spin: 22,
          color: STEEL,
          trail: "#8fa4c4",
        },
      ],
      desc: "Thrown flat and fast. Not much damage - it exists so they have to hold still.",
      notation: "↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderF: 146, elbowF: 96, torso: -12, offX: -3 }),
        kf(10, { ...STANCE, shoulderF: 78, elbowF: 4, torso: 20, hipF: 26, offX: 6 }, "out"),
        kf(18, { ...STANCE, shoulderF: 66, elbowF: 44, torso: 10 }, "inOut"),
        kf(28, { ...STANCE }),
      ],
    },
    {
      id: "kunaiAir",
      name: "Air Kunai",
      input: { button: "B", motion: "qcf", stance: "air" },
      tags: ["special", "projectile", "air"],
      variant: "kunaiThrow",
      priority: 20,
      duration: 26,
      airborne: true,
      showProps: ["kunai"],
      projectiles: [
        {
          at: 8,
          kind: "kunai",
          x: 30,
          y: 20,
          vx: 14,
          vy: -6,
          gravity: 0.16,
          life: 70,
          box: { x: -9, y: -4, w: 18, h: 9 },
          damage: 38,
          hitstun: 16,
          blockstun: 11,
          chip: 3,
          pushX: 3,
          clashes: true,
          fx: "pierce",
          spin: 26,
          color: STEEL,
          trail: "#8fa4c4",
        },
      ],
      desc: "The same knife thrown down at an angle. Controls the space she just jumped out of.",
      notation: "(air) ↓↘→ + B",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderF: 150, elbowF: 90, torso: -14 }),
        kf(8, { ...STANCE, free: 1, shoulderF: 58, elbowF: 6, torso: 26, hipF: 30, kneeF: 40 }, "out"),
        kf(16, { ...STANCE, free: 1, shoulderF: 62, elbowF: 50, torso: 10 }, "inOut"),
        kf(26, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "shadowStep",
      name: "Shadow Step",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "movement"],
      priority: 22,
      duration: 26,
      resourceCost: 1,
      resourceMin: 1,
      // Fully gone for the middle of it - she can pass straight through a
      // fireball and land on the far side of whoever threw it.
      invuln: [{ from: 4, to: 18, kind: "full" }],
      vel: [
        { at: 4, x: 17 },
        { at: 17, x: 0 },
      ],
      friction: 0.7,
      noTurn: true,
      vfx: [
        { at: 3, kind: "smoke", x: 0, y: 46, scale: 1.3, color: "#7fd4ff" },
        { at: 18, kind: "smoke", x: 0, y: 46, scale: 1.3, color: "#7fd4ff" },
      ],
      desc: "Vanishes and reappears past them. Invincible through the middle - the cheapest way she has to change sides. Costs one Kage.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5 }, "out"),
        kf(4, { ...STANCE, crouch: 1, squash: 0.5, torso: 24, offY: -4 }, "linear"),
        kf(10, { ...STANCE, free: 1, crouch: 1, squash: 0.3, torso: 30, hipF: 70, kneeF: 90, hipB: -50, kneeB: 96 }, "linear"),
        kf(18, { ...STANCE, crouch: 0.8, squash: 0.7, torso: 20, hipF: 40, kneeF: 60 }, "out"),
        kf(26, { ...STANCE }),
      ],
    },
    {
      id: "smokeBomb",
      name: "Smoke Bomb",
      input: { button: "A", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      priority: 18,
      duration: 34,
      projectiles: [
        {
          at: 9,
          kind: "smokebomb",
          x: 26,
          y: 66,
          vx: 8.5,
          vy: 4.5,
          gravity: 0.42,
          life: 46,
          box: { x: -7, y: -7, w: 14, h: 14 },
          damage: 0,
          hitstun: 0,
          blockstun: 0,
          hits: 1,
          bounce: 0.3,
          bounces: 1,
          drag: 0.99,
          fx: "burn",
          // Bursts into a cloud that has to be blocked low and buys her the
          // frames to be somewhere else.
          detonate: {
            radius: 54,
            damage: 46,
            hitstun: 26,
            blockstun: 20,
            knockdown: "none",
            guard: "low",
            chip: 5,
          },
          scale: 0.9,
          color: "#8f97a8",
        },
      ],
      desc: "Lobbed short and bursts into a cloud on the floor. Blocked low, and the cloud lasts long enough for her to be behind them.",
      notation: "↓↙← + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderF: 140, elbowF: 110, torso: -10, offX: -3 }),
        kf(9, { ...STANCE, shoulderF: 66, elbowF: 20, torso: 22, hipF: 24, offX: 5 }, "out"),
        kf(20, { ...STANCE, shoulderF: 60, elbowF: 54, torso: 8 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },
    {
      id: "risingBlade",
      name: "Rising Blade",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 24,
      duration: 44,
      airborne: true,
      invuln: [{ from: 1, to: 7, kind: "strike" }],
      vel: [
        { at: 1, x: 2.6, y: 12.6 },
        { at: 22, y: -0.9, mode: "add" },
      ],
      hits: [
        hit(3, 9, bx(10, 40, 52, 78), 80, { launch: [2, 10.5], knockdown: "launch", fx: "slash", hitstun: 26, shake: 1.8 }),
        hit(10, 17, bx(8, 54, 48, 66), 32, { group: 2, launch: [1.2, 4.5], fx: "slash" }),
      ],
      desc: "Invincible on frame one, straight up with the blade leading. Her reversal and her anti-air.",
      notation: "→↓↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.7, hipF: 24, kneeF: 50, shoulderB: 0, elbowB: 90, weaponBack: 80 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -16, spin: -10, shoulderB: 172, elbowB: 6, weaponBack: -10, hipF: 50, kneeF: 66, hipB: -34, kneeB: 40 }, "out"),
        kf(16, { ...STANCE, free: 1, torso: -20, spin: -18, shoulderB: 178, elbowB: 4, weaponBack: -12, hipF: 40, kneeF: 76 }),
        kf(32, { ...STANCE, free: 1, torso: -4, spin: -6, shoulderB: 100, elbowB: 40, hipF: 34, kneeF: 48 }, "inOut"),
        kf(44, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "swallowDive",
      name: "Swallow Dive",
      input: { button: "C", motion: "qcf", stance: "air" },
      tags: ["special", "overhead", "air"],
      priority: 24,
      duration: 34,
      airborne: true,
      landCancel: true,
      landRecovery: 8,
      vel: [{ at: 4, x: 9, y: -13 }],
      hits: [
        hit(6, 24, bx(6, 0, 50, 48), 78, {
          guard: "overhead",
          fx: "slash",
          pushX: 5,
          knockdown: "hard",
          hitstun: 24,
          shake: 1.6,
        }),
      ],
      desc: "Folds up and drops on a diagonal, blade first. Overhead, and it changes her jump arc mid-air.",
      notation: "(air) ↓↘→ + C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(4, { ...STANCE, free: 1, torso: -24, spin: -14, shoulderB: 176, elbowB: 16, weaponBack: 10, hipF: 60, kneeF: 80 }, "out"),
        kf(7, { ...STANCE, free: 1, torso: 34, spin: 16, shoulderB: 30, elbowB: 8, weaponBack: -80, hipF: 10, kneeF: 14, hipB: -14, kneeB: 20 }, "out"),
        kf(34, { ...STANCE, free: 1, torso: 30, spin: 12, shoulderB: 28, elbowB: 10, weaponBack: -80 }),
      ],
    },

    // ----------------------------------------------------------------- skill
    {
      id: "kawarimi",
      name: "Kawarimi",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill"],
      priority: 18,
      duration: 30,
      parryWindow: [2, 9],
      friction: 0.82,
      resourceGain: 1,
      vfx: [{ at: 2, kind: "smoke", x: 0, y: 46, scale: 1, color: "#7fd4ff" }],
      desc: "SKILL. The substitution. Deflects anything that lands in the first frames and hands her a Kage back for it.",
      notation: "A + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, crouch: 0.7, squash: 0.7, torso: 20, shoulderF: 40, elbowF: 90, shoulderB: 10, elbowB: 96, offY: -2 }, "out"),
        kf(9, { ...STANCE, crouch: 0.5, torso: -8, shoulderF: 96, elbowF: 40, shoulderB: 60, elbowB: 60, offX: -4 }, "inOut"),
        kf(18, { ...STANCE, torso: 4, shoulderF: 70, elbowF: 56 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },

    // ------------------------------------------------------------------- EX
    {
      id: "kunaiEx",
      name: "Kunai EX",
      input: { button: "S", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "projectile"],
      priority: 26,
      duration: 34,
      meterCost: 50,
      showProps: ["kunai"],
      projectiles: [
        {
          at: 9,
          kind: "kunai",
          x: 34,
          y: 74,
          vx: 18,
          vy: 1.4,
          gravity: 0.05,
          life: 70,
          box: { x: -9, y: -4, w: 18, h: 9 },
          damage: 34,
          hitstun: 18,
          blockstun: 12,
          chip: 3,
          clashes: true,
          fx: "pierce",
          spin: 24,
          color: "#dff2ff",
          trail: "#7fd4ff",
        },
        {
          at: 12,
          kind: "kunai",
          x: 34,
          y: 60,
          vx: 18,
          vy: 0,
          gravity: 0.05,
          life: 70,
          box: { x: -9, y: -4, w: 18, h: 9 },
          damage: 30,
          hitstun: 18,
          blockstun: 12,
          chip: 3,
          clashes: true,
          fx: "pierce",
          spin: 24,
          color: "#dff2ff",
          trail: "#7fd4ff",
        },
        {
          at: 15,
          kind: "kunai",
          x: 34,
          y: 46,
          vx: 18,
          vy: -1.4,
          gravity: 0.05,
          life: 70,
          box: { x: -9, y: -4, w: 18, h: 9 },
          damage: 30,
          hitstun: 18,
          blockstun: 12,
          chip: 3,
          knockdown: "soft",
          clashes: true,
          fx: "pierce",
          spin: 24,
          color: "#dff2ff",
          trail: "#7fd4ff",
        },
      ],
      desc: "EX. Three knives in a fan. Covers every height at once and there is no jumping over it.",
      notation: "↓↘→ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderF: 150, elbowF: 100, torso: -14, offX: -4 }),
        kf(9, { ...STANCE, shoulderF: 96, elbowF: 6, torso: 16, offX: 5 }, "out"),
        kf(12, { ...STANCE, shoulderF: 78, elbowF: 4, torso: 22, offX: 6 }, "out"),
        kf(15, { ...STANCE, shoulderF: 58, elbowF: 6, torso: 26, hipF: 28, offX: 7 }, "out"),
        kf(24, { ...STANCE, shoulderF: 64, elbowF: 50, torso: 8 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },
    {
      id: "shadowStepEx",
      name: "Shadow Step EX",
      input: { button: "S", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "ex"],
      priority: 28,
      duration: 40,
      meterCost: 50,
      invuln: [{ from: 1, to: 22, kind: "full" }],
      vel: [
        { at: 3, x: 18 },
        { at: 18, x: 0 },
      ],
      friction: 0.7,
      noTurn: true,
      hits: [
        hit(22, 28, bx(-16, 30, 64, 56), 88, {
          fx: "slash",
          pushX: 6,
          knockdown: "hard",
          hitstun: 26,
          hitstop: 12,
          shake: 2.1,
        }),
      ],
      vfx: [
        { at: 2, kind: "smoke", x: 0, y: 46, scale: 1.5, color: "#7fd4ff" },
        { at: 20, kind: "smoke", x: 0, y: 46, scale: 1.5, color: "#7fd4ff" },
      ],
      desc: "EX. Costs no Kage, stays gone twice as long, and comes out of the smoke behind them with the blade already moving.",
      notation: "↓↙← + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5 }, "out"),
        kf(3, { ...STANCE, crouch: 1, squash: 0.4, torso: 24, offY: -4 }, "linear"),
        kf(12, { ...STANCE, free: 1, crouch: 1, squash: 0.25, torso: 30, hipF: 70, kneeF: 90, hipB: -50, kneeB: 96 }, "linear"),
        kf(20, { ...STANCE, crouch: 0.7, squash: 0.8, torso: -14, shoulderB: 0, elbowB: 96, weaponBack: 86 }, "out"),
        kf(22, { ...STANCE, torso: -22, spin: 8, shoulderB: 168, elbowB: 10, weaponBack: -20, offX: -8 }, "out"),
        kf(30, { ...STANCE, torso: -6, shoulderB: 80, elbowB: 46, offX: -4 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "Hundred Shadows",
      input: { button: "S", motion: "dd", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 116,
      meterCost: 100,
      superFreeze: 44,
      invuln: [{ from: 1, to: 20, kind: "full" }],
      noTurn: true,
      vel: [
        { at: 8, x: 14 },
        { at: 26, x: -11 },
        { at: 44, x: 13 },
        { at: 62, x: -9 },
        { at: 80, x: 6 },
        { at: 92, x: 0 },
      ],
      friction: 0.9,
      hits: [
        hit(14, 18, bx(-10, 34, 66, 52), 44, { group: 1, fx: "slash", pushX: 0.6, hitstun: 22, hitstop: 5 }),
        hit(30, 34, bx(-10, 34, 66, 52), 38, { group: 2, fx: "slash", pushX: 0.6, hitstun: 20, hitstop: 4 }),
        hit(48, 52, bx(-10, 30, 66, 56), 38, { group: 3, fx: "slash", pushX: 0.6, hitstun: 20, hitstop: 4 }),
        hit(66, 70, bx(-10, 30, 66, 56), 38, { group: 4, fx: "slash", pushX: 0.6, hitstun: 20, hitstop: 4 }),
        hit(82, 86, bx(-8, 26, 62, 62), 40, { group: 5, fx: "slash", pushX: 0.6, hitstun: 20, hitstop: 5 }),
        hit(92, 98, bx(4, 14, 78, 74), 138, {
          group: 6,
          fx: "slash",
          pushX: 12,
          knockdown: "hard",
          launch: [6.5, 8],
          hitstop: 18,
          shake: 3,
        }),
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 50, scale: 2.4, color: "#7fd4ff" },
        { at: 14, kind: "smoke", x: 0, y: 46, scale: 1.2, color: "#7fd4ff" },
        { at: 30, kind: "smoke", x: 0, y: 46, scale: 1.2, color: "#7fd4ff" },
        { at: 48, kind: "smoke", x: 0, y: 46, scale: 1.2, color: "#7fd4ff" },
        { at: 66, kind: "smoke", x: 0, y: 46, scale: 1.2, color: "#7fd4ff" },
        { at: 92, kind: "slash", x: 40, y: 50, scale: 1.6, color: "#dff2ff" },
      ],
      desc: "SUPER. She is on both sides of them at once and neither one is the real her, until the last cut - which is.",
      notation: "↓↓ + S (with 100 meter)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, torso: -10 }, "out"),
        kf(8, { ...STANCE, free: 1, crouch: 1, squash: 0.4, torso: 30 }, "linear"),
        kf(14, { ...STANCE, torso: -18, spin: -6, shoulderB: 156, elbowB: 12, weaponBack: -14, offX: -6 }, "out"),
        kf(24, { ...STANCE, free: 1, squash: 0.4, torso: 24 }, "linear"),
        kf(30, { ...STANCE, torso: -16, spin: 8, shoulderB: 150, elbowB: 16, weaponBack: -10, offX: -5 }, "out"),
        kf(42, { ...STANCE, free: 1, squash: 0.4, torso: 26 }, "linear"),
        kf(48, { ...STANCE, torso: 20, spin: -8, shoulderB: 60, elbowB: 14, weaponBack: -40, offX: 5 }, "out"),
        kf(60, { ...STANCE, free: 1, squash: 0.4, torso: 22 }, "linear"),
        kf(66, { ...STANCE, torso: -14, spin: 10, shoulderB: 148, elbowB: 18, weaponBack: -8, offX: -5 }, "out"),
        kf(78, { ...STANCE, free: 1, squash: 0.5, torso: 24 }, "linear"),
        kf(82, { ...STANCE, torso: 24, spin: -10, hipF: 96, kneeF: 90, offX: 5 }, "out"),
        kf(88, { ...STANCE, crouch: 0.8, torso: -20, shoulderB: -12, elbowB: 96, weaponBack: 92, offX: -4 }, "out"),
        kf(92, { ...STANCE, torso: 34, spin: -18, shoulderB: 78, elbowB: 4, weaponBack: -66, hipF: 40, kneeF: 22, offX: 10 }, "out"),
        kf(104, { ...STANCE, torso: 12, shoulderB: 50, elbowB: 44, offX: 4 }, "inOut"),
        kf(116, { ...STANCE }),
      ],
    },
  ],
};
