/**
 * "Blackrock" Nell - pirate captain.
 *
 * Fast, aggressive, all mix-up: cutlass rekkas, a flintlock, a grappling hook
 * that drags you into her range, and a dive kick that ruins jump-outs.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const COAT = "#2b3a67";
const GOLD = "#e0b13a";
const STEEL = "#d5dbe2";

const STANCE = {
  torso: 7,
  head: -4,
  hipF: 17,
  kneeF: 18,
  hipB: -19,
  kneeB: 30,
  shoulderF: 44,
  elbowF: 34,
  shoulderB: -18,
  elbowB: 40,
  weapon: 42,
};

export const PIRATE: FighterDef = {
  id: "pirate",
  name: "Anne Bonny",
  title: "Of Rackham's Company",
  era: "Negril Point, 1720",
  bio: "Sailed with Calico Jack Rackham until the sloop was taken off Negril Point. The court record says that when the boarders came over the rail, she and Mary Read were the only two who fought.",
  archetype: "Rushdown / Mix-up",
  difficulty: 3,
  strengths: ["Fastest walk speed", "Double jump and dive kick", "Rekka pressure"],
  weaknesses: ["Low health", "Short normals", "Needs powder for zoning"],
  winQuote: "The rest of them were below decks with the rum. As usual.",
  palette: {
    body: "#efe7d8",
    outline: "#17181c",
    accent: GOLD,
    cloth: COAT,
    metal: STEEL,
    aura: "#4fd1c5",
  },
  stats: {
    health: 950,
    walkF: 3.15,
    walkB: 2.5,
    dashSpeed: 8.6,
    dashFrames: 14,
    backdashFrames: 19,
    jumpVel: 12.1,
    jumpFwd: 5.2,
    gravity: 0.6,
    weight: 0.94,
    airMoves: 3,
    doubleJump: true,
    airDash: false,
    width: 19,
    standHeight: 102,
    crouchHeight: 64,
    scale: 0.99,
  },
  stance: STANCE,
  // Cutlass in a hanging guard, pistol hand tucked in behind the elbow.
  clips: guardClips({
    high: { torso: 0, head: -6, shoulderF: 132, elbowF: 28, weapon: -96, shoulderB: 20, elbowB: 126, hipF: 16, kneeF: 22, hipB: -18, kneeB: 32, offX: -2 },
    low: { torso: 8, head: -5, shoulderF: 124, elbowF: 32, weapon: -90, shoulderB: 26, elbowB: 120, hipF: 33, kneeF: 74, hipB: -20, kneeB: 84, offX: -2 },
  }),
  resource: {
    name: "Powder",
    max: 2,
    start: 2,
    regen: 0.0035,
    color: "#ffd479",
    pips: true,
  },
  props: [
    {
      id: "hat",
      attach: "head",
      // Tricorn: three corners pinned up around a crown, with a plume.
      parts: [
        { geo: "poly", size: [-19, -1, -13, 5, 0, 7, 13, 5, 19, -1, 12, -5, 0, -6, -12, -5], pos: [1, 8], rot: -6, color: "#1d2545" },
        { geo: "poly", size: [-11, -3, -8, 8, 0, 13, 8, 8, 11, -3], pos: [0, 10], color: "#243056" },
        { geo: "box", size: [22, 3], pos: [0, 9], rot: -6, color: GOLD },
        // Skull badge on the front corner.
        { geo: "disc", size: [3.4], pos: [9, 10], color: "#e8e2d2", z: 0.3 },
        { geo: "box", size: [7, 2], pos: [9, 7], color: "#e8e2d2", z: 0.3 },
        // Plume off the back.
        { geo: "poly", size: [0, 0, -7, 8, -16, 11, -20, 7, -12, 2, -5, -2], pos: [-14, 6], color: "#b03a4a", behind: true },
      ],
    },
    {
      id: "patch",
      attach: "head",
      parts: [
        { geo: "poly", size: [-4, 4, 4, 3, 4, -4, -4, -3], pos: [5, 1], color: "#101215", z: 0.9 },
        { geo: "box", size: [17, 1.6], pos: [0, 4], rot: -8, color: "#101215", z: 0.9 },
        // Scar under the good eye.
        { geo: "box", size: [1.4, 7], pos: [-3, -5], rot: 12, color: "#a5665a", z: 0.9 },
      ],
    },
    {
      id: "cutlass",
      attach: "handF",
      // Cutlass: a broad curved blade with a knuckle bow round the grip.
      parts: [
        { geo: "blade", size: [60, 8, 0.45], pos: [36, 4], rot: 8, color: STEEL },
        { geo: "poly", size: [-28, 2, 28, 1, 26, -2, -28, -1], pos: [36, 6], rot: 8, color: "#f2f6fa" },
        // Knuckle bow sweeping from the guard to the pommel.
        { geo: "poly", size: [1, 9, 8, 6, 9, -6, 2, -10, 1, -6, 6, -4, 5, 4, 0, 6], pos: [1, -1], color: GOLD },
        { geo: "box", size: [5, 20], pos: [3, 1], color: "#c99a2f" },
        { geo: "cyl", size: [2.6, 13], pos: [-7, -1], rot: 90, color: "#5a3b21" },
        { geo: "box", size: [12, 1.6], pos: [-7, 1], rot: 90, color: "#7d5730" },
        { geo: "disc", size: [3.2], pos: [-14, -1], color: GOLD },
      ],
    },
    {
      id: "pistol",
      attach: "handB",
      conditional: true,
      // Flintlock: octagonal barrel, lock plate, cock and a curled walnut butt.
      parts: [
        { geo: "poly", size: [-13, 2.6, 15, 2, 15, -2, -13, -2.6], pos: [12, 2], color: "#3f444b" },
        { geo: "box", size: [8, 2], pos: [22, 3], color: "#5a6068" },
        { geo: "poly", size: [-5, 4, 5, 5, 6, -4, -5, -5], pos: [3, 0], color: "#4a4f57" },
        { geo: "poly", size: [0, 0, 3, 5, 6, 4, 5, -2], pos: [4, 4], color: "#6a707a" },
        { geo: "disc", size: [2], pos: [7, 3], color: GOLD },
        { geo: "poly", size: [4, 4, -2, 2, -8, -6, -4, -9, 2, -4], pos: [-3, -4], color: "#5a3b21" },
        { geo: "box", size: [4, 3], pos: [-9, -11], color: GOLD },
      ],
    },
    {
      id: "hook",
      attach: "handB",
      conditional: true,
      parts: [
        { geo: "cyl", size: [1.6, 26], pos: [12, 0], rot: 90, color: "#8a8f98" },
        { geo: "poly", size: [-4, 6, 4, 5, 5, -5, -4, -6], pos: [24, 0], color: "#6a707a" },
        // The claw itself, curling back on the point.
        { geo: "poly", size: [0, 4, 10, 2, 16, -6, 12, -13, 8, -10, 11, -5, 7, -2, 0, -3], pos: [28, 0], color: STEEL },
      ],
    },
    {
      id: "coat",
      attach: "torso",
      // Naval coat: wide lapels, a double row of buttons, and a bandolier.
      parts: [
        { geo: "poly", size: [-13, -16, 13, -16, 14, 8, 9, 17, -9, 17, -14, 8], pos: [0, 3], color: COAT },
        { geo: "poly", size: [-8, 14, 2, 16, 4, 2, -6, -2], pos: [-5, 6], color: "#33447a" },
        { geo: "poly", size: [8, 14, -2, 16, -4, 2, 6, -2], pos: [6, 6], color: "#3a4d88" },
        { geo: "box", size: [26, 3], pos: [0, -12], color: "#1a2445" },
        // Bandolier across the chest.
        { geo: "box", size: [7, 40], pos: [-1, 2], rot: 24, color: "#6b4a2c" },
        { geo: "disc", size: [1.9], pos: [-6, 12], color: GOLD, z: 0.3 },
        { geo: "disc", size: [1.9], pos: [-3, 4], color: GOLD, z: 0.3 },
        { geo: "disc", size: [1.9], pos: [0, -4], color: GOLD, z: 0.3 },
        { geo: "poly", size: [-7, 16, 3, 14, 5, -12, -6, -14], pos: [-9, -6], rot: 6, color: "#22305c", behind: true },
      ],
      cloth: {
        segments: 4,
        segmentLength: 10,
        width: 17,
        endWidth: 9,
        color: COAT,
        gravity: 0.44,
        stiffness: 0.42,
        drift: -0.4,
      },
    },
    {
      id: "sash",
      attach: "pelvis",
      parts: [
        { geo: "poly", size: [-12, 4, 12, 5, 12, -4, -12, -5], pos: [0, 2], rot: -8, color: "#a32d3a" },
        { geo: "poly", size: [-5, 5, 5, 4, 4, -5, -4, -6], pos: [1, 2], color: GOLD },
        { geo: "poly", size: [-3, 7, 4, 6, 3, -7, -3, -7], pos: [-9, -5], rot: 10, color: "#8f2532", behind: true },
      ],
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 115,
      backThrowDamage: 128,
      throwRange: 58,
      rollSpeed: 8.4,
      weaponIdle: { weapon: STANCE.weapon },
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Quick Slash",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 12,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [3, 11],
      // Cutlass Rush string continues into 5B.
      followUps: [
        { button: "B", move: "5B", from: 3, to: 9, string: "Cutlass Rush" },
      ],
      hits: [hit(3, 5, bx(18, 54, 46, 20), 30, { fx: "slash", hitstun: 14, blockstun: 10, pushX: 2.8 })],
      desc: "Three-frame-fast cutlass flick. Chains into itself twice.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE, weapon: 160 }, "out"),
        kf(3, { ...STANCE, shoulderF: 88, elbowF: 6, weapon: 32, torso: 12, offX: 3 }),
        kf(8, { ...STANCE, shoulderF: 60, elbowF: 26, weapon: -39, torso: 8 }, "inOut"),
        kf(12, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Cross Cut",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 20,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [7, 18],
      // Cutlass Rush string continues into 6C.
      followUps: [
        { button: "C", move: "6C", from: 7, to: 17, string: "Cutlass Rush" },
      ],
      hits: [hit(7, 10, bx(22, 44, 66, 40), 54, { fx: "slash", pushX: 4.4, hitstun: 17 })],
      desc: "Diagonal slash across the chest. Solid confirm into rekkas.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: -30, elbowF: 70, weapon: 203, torso: -8, offX: -3 }),
        kf(7, { ...STANCE, shoulderF: 96, elbowF: 10, weapon: 18, torso: 18, hipF: 28, offX: 6 }, "out"),
        kf(13, { ...STANCE, shoulderF: 80, elbowF: 22, weapon: -56, torso: 12 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Boarding Cleave",
      input: { button: "C", stance: "stand" },
      tags: ["heavy"],
      duration: 30,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 26],
      // Boarding Steel string continues into 4C.
      followUps: [
        { button: "C", move: "4C", from: 12, to: 27, string: "Boarding Steel" },
      ],
      hits: [
        hit(12, 16, bx(16, 26, 76, 74), 86, {
          fx: "slash",
          pushX: 6.4,
          knockdown: "soft",
          hitstun: 22,
          shake: 1.4,
        }),
      ],
      desc: "Big overhead-to-floor cleave. Knocks down and leaves you next to them.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 176, elbowF: -20, weapon: 70, torso: -18, hipB: -26, kneeB: 40, offX: -4 }, "inOut"),
        kf(12, { ...STANCE, shoulderF: 40, elbowF: 14, weapon: -34, torso: 32, hipF: 36, kneeF: 26, hipB: -20, kneeB: 44, offX: 7 }, "out"),
        kf(20, { ...STANCE, shoulderF: 34, elbowF: 20, weapon: -30, torso: 28, offX: 5 }),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Ankle Nick",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 13,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [3, 12],
      hits: [hit(3, 5, bx(16, 12, 44, 20), 28, { guard: "low", fx: "slash", hitstun: 13, blockstun: 10, pushX: 2.6 })],
      desc: "Fastest low in the game. Great for opening up a blocking opponent.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(3, { ...STANCE, crouch: 1, torso: 22, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderF: 96, elbowF: 42, weapon: -34, offX: 4 }),
        kf(8, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderF: 70, elbowF: 40, weapon: 10 }, "inOut"),
        kf(13, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "2B",
      name: "Deck Slice",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 22,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [8, 20],
      hits: [hit(8, 11, bx(20, 8, 66, 26), 50, { guard: "low", fx: "slash", pushX: 4, hitstun: 16 })],
      desc: "Low horizontal slice. Cancels straight into the flintlock.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(5, { ...STANCE, crouch: 1, torso: 6, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderF: -10, elbowF: 76, weapon: 80 }),
        kf(8, { ...STANCE, crouch: 1, torso: 26, hipF: 38, kneeF: 78, hipB: -24, kneeB: 88, shoulderF: 104, elbowF: 40, weapon: -40, offX: 7 }, "out"),
        kf(16, { ...STANCE, crouch: 1, torso: 20, hipF: 36, kneeF: 76, hipB: -22, kneeB: 86, shoulderF: 80, elbowF: 38, weapon: -6 }, "inOut"),
        kf(22, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "2C",
      name: "Boot Sweep",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 28,
      cancelInto: ["special", "super"],
      cancelWindow: [11, 24],
      hits: [hit(10, 14, bx(18, 2, 78, 24), 72, { guard: "low", knockdown: "sweep", fx: "blunt", pushX: 5.6 })],
      desc: "Low sweeping kick. Knockdown into your okizeme game.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(6, { ...STANCE, crouch: 1, torso: 20, hipF: 10, kneeF: 90, hipB: -30, kneeB: 96, offX: -2 }),
        kf(10, { ...STANCE, crouch: 1, torso: 26, hipF: 78, kneeF: 10, hipB: -34, kneeB: 100, shoulderF: 20, elbowF: 40, offX: 4 }, "out"),
        kf(18, { ...STANCE, crouch: 1, torso: 22, hipF: 50, kneeF: 50, hipB: -30, kneeB: 92 }, "inOut"),
        kf(28, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "6B",
      name: "Keelhaul Kick",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "overhead"],
      priority: 10,
      duration: 32,
      vel: [{ at: 6, x: 3.4 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [14, 28],
      hits: [
        hit(14, 18, bx(22, 40, 60, 46), 62, {
          guard: "overhead",
          fx: "blunt",
          pushX: 5,
          hitstun: 20,
        }),
      ],
      desc: "Hopping overhead boot. Slow enough to react to, fast enough to catch crouchers.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, crouch: 0.5, torso: 14, hipF: 20, kneeF: 60, hipB: -16, kneeB: 60 }),
        kf(11, { ...STANCE, free: 1, offY: 14, torso: -6, hipF: -20, kneeF: 80, hipB: -30, kneeB: 60, shoulderF: -20, elbowF: 60 }, "out"),
        kf(14, { ...STANCE, free: 1, offY: 10, torso: 22, hipF: 86, kneeF: 6, hipB: -26, kneeB: 70, shoulderF: 30, elbowF: 30, offX: 4 }, "out"),
        kf(20, { ...STANCE, free: 1, offY: 4, torso: 18, hipF: 60, kneeF: 30, hipB: -20, kneeB: 60 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Rising Steel",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [11, 28],
      hits: [
        hit(8, 12, bx(12, 50, 58, 72), 70, {
          launch: [2.2, 12],
          knockdown: "launch",
          fx: "slash",
          hitstun: 26,
        }),
      ],
      desc: "Upward slash that launches. Jump-cancel into air combos.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5, hipF: 26, kneeF: 46 }, "out"),
        kf(5, { ...STANCE, crouch: 0.7, shoulderF: -20, elbowF: 80, weapon: -25, torso: 14 }),
        kf(8, { ...STANCE, torso: -16, shoulderF: 150, elbowF: -14, weapon: 15, hipF: 22, kneeF: 12, offY: 3 }, "out"),
        kf(16, { ...STANCE, torso: -10, shoulderF: 140, elbowF: -8, weapon: 91 }),
        kf(24, { ...STANCE, torso: 2, shoulderF: 70, elbowF: 20 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },
    {
      // Forward and back sets. Forward takes space, back gives it up to buy
      // range or a hard read.
      id: "6A",
      name: "Point Jab",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 20,
      vel: [{ at: 2, x: 2.2 }],
      friction: 0.88,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [6, 18],
      // Boarding Steel string continues into 5C.
      followUps: [
        { button: "C", move: "5C", from: 6, to: 17, string: "Boarding Steel" },
      ],
      hits: [hit(6, 8, bx(20, 60, 44, 26), 30, { guard: "high", fx: "slash", pushX: 3, hitstun: 13, hitstop: 5 })],
      desc: "Steps in and flicks the point at the face. Quickest thing she has.",
      notation: "\u2192 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderF: 30, elbowF: 58, weapon: 62, torso: -2, offX: -2 }, "out"),
        kf(6, { ...STANCE, shoulderF: 86, elbowF: 6, weapon: 6, torso: 14, hipF: 24, kneeF: 16, offX: 8 }, "out"),
        kf(11, { ...STANCE, shoulderF: 70, elbowF: 24, weapon: 30, torso: 10, offX: 5 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Boarding Rush",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 40,
      armor: [{ from: 8, to: 18, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 8, x: 5.4 }, { at: 26, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [20, 36],
      hits: [hit(16, 20, bx(16, 22, 52, 68), 90, { guard: "mid", fx: "slash", pushX: 17, hitstun: 24, hitstop: 12, knockdown: "wallbounce", shake: 2.2 })],
      desc: "Runs onto them swinging. Ends against the wall more often than not.",
      notation: "\u2192 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 150, elbowF: -40, weapon: 134, torso: -12, hipB: -30, kneeB: 48, offX: -6 }, "out"),
        kf(16, { ...STANCE, shoulderF: 58, elbowF: 40, weapon: 21, torso: 32, hipF: 42, kneeF: 16, hipB: -26, kneeB: 24, offX: 12 }, "out"),
        kf(24, { ...STANCE, shoulderF: 50, elbowF: 46, weapon: -54, torso: 24, hipF: 30, kneeF: 22, offX: 8 }),
        kf(32, { ...STANCE, shoulderF: 48, elbowF: 38, weapon: 34, torso: 10, offX: 3 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Pistol Butt",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 22,
      vel: [{ at: 1, x: -2.6 }],
      friction: 0.86,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [8, 20],
      // Powder Burn string continues into 5A.
      followUps: [
        { button: "A", move: "5A", from: 8, to: 19, string: "Powder Burn" },
      ],
      hits: [hit(8, 10, bx(16, 52, 42, 30), 36, { guard: "mid", fx: "blunt", pushX: 6, hitstun: 15, hitstop: 6 })],
      desc: "Backs off and clubs them with the pistol butt. Cheap, fast, effective.",
      notation: "\u2190 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -6, shoulderB: 20, elbowB: 84, weaponBack: 40, hipB: -26, kneeB: 40, offX: -6 }, "out"),
        kf(8, { ...STANCE, torso: 10, shoulderB: 72, elbowB: 22, weaponBack: 84, hipF: 22, kneeF: 16, offX: -3 }, "out"),
        kf(14, { ...STANCE, torso: 2, shoulderB: 40, elbowB: 46, weaponBack: 60, offX: -4 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Backhand Cut",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 30,
      vel: [{ at: 1, x: -3.4 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      hits: [hit(12, 15, bx(34, 52, 88, 24), 56, { guard: "mid", fx: "slash", pushX: 7, hitstun: 18, hitstop: 8 })],
      desc: "Steps out and drags the edge back across them. Keeps her at her range, not theirs.",
      notation: "\u2190 + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 108, elbowF: -22, weapon: 96, torso: -12, hipB: -28, kneeB: 42, offX: -8 }, "inOut"),
        // Edge turned out and pulled back through the line.
        kf(12, { ...STANCE, shoulderF: 74, elbowF: 12, weapon: 10, torso: 6, hipF: 24, kneeF: 14, offX: -5 }, "out"),
        kf(17, { ...STANCE, shoulderF: 68, elbowF: 16, weapon: 8, torso: 4, offX: -6 }),
        kf(23, { ...STANCE, shoulderF: 52, elbowF: 34, weapon: 34, torso: 0, offX: -4 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Boarding Cleave",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 44,
      cancelInto: ["special", "super"],
      cancelWindow: [26, 40],
      hits: [hit(20, 23, bx(14, 20, 70, 86), 100, { guard: "overhead", fx: "slash", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 })],
      desc: "Both hands on the grip and straight down through the collarbone. Blocked standing only.",
      notation: "\u2190 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 140, elbowF: -38, weapon: 96, torso: -10, offX: -5 }, "inOut"),
        kf(15, { ...STANCE, shoulderF: 174, elbowF: -12, weapon: 100, torso: -20, hipB: -26, kneeB: 38, offY: 3, offX: -3 }, "out"),
        kf(20, { ...STANCE, shoulderF: 82, elbowF: 14, weapon: 68, torso: 32, hipF: 34, kneeF: 16, hipB: -12, kneeB: 32, offX: 6 }, "out"),
        kf(26, { ...STANCE, shoulderF: 74, elbowF: 18, weapon: 64, torso: 26, offX: 4 }),
        kf(36, { ...STANCE, shoulderF: 52, elbowF: 36, weapon: 46, torso: 8 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Flick",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 18,
      airborne: true,
      landCancel: true,
      landRecovery: 2,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [4, 16],
      hits: [hit(4, 9, bx(16, 32, 48, 30), 34, { fx: "slash", hitstun: 14, pushX: 2.6 })],
      desc: "Fast air slash. Use it to start air strings after a launcher.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 32, kneeF: 40, hipB: -22, kneeB: 40 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderF: 92, elbowF: 16, weapon: 6, torso: 12, hipF: 30, kneeF: 44 }),
        kf(11, { ...STANCE, free: 1, shoulderF: 64, elbowF: 30, weapon: 30, torso: 8 }, "inOut"),
        kf(18, { ...STANCE, free: 1, hipF: 32, kneeF: 40, hipB: -22, kneeB: 40 }),
      ],
    },
    {
      id: "jB",
      name: "Air Cross",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 24,
      airborne: true,
      landCancel: true,
      landRecovery: 4,
      cancelInto: ["heavy", "special"],
      cancelWindow: [8, 22],
      hits: [hit(6, 12, bx(18, 18, 64, 52), 56, { fx: "slash", pushX: 4, hitstun: 18 })],
      desc: "Wide air slash with a generous hitbox in front and below.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 30, kneeF: 40, hipB: -22, kneeB: 38 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderF: -34, elbowF: 80, weapon: 90, torso: -10 }),
        kf(7, { ...STANCE, free: 1, shoulderF: 104, elbowF: 24, weapon: -30, torso: 20, hipF: 36, kneeF: 34 }, "out"),
        kf(16, { ...STANCE, free: 1, shoulderF: 84, elbowF: 30, weapon: -6, torso: 14 }, "inOut"),
        kf(24, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "jC",
      name: "Anchor Drop",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 28,
      airborne: true,
      landCancel: true,
      landRecovery: 7,
      hits: [
        hit(9, 18, bx(6, -4, 62, 48), 80, {
          guard: "overhead",
          fx: "slash",
          knockdown: "soft",
          pushX: 5,
          shake: 1.4,
        }),
      ],
      desc: "Downward cleave. The jump-in that starts most of her pressure.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, torso: -20, shoulderF: 168, elbowF: -24, weapon: 66, hipF: 40, kneeF: 56 }),
        kf(9, { ...STANCE, free: 1, torso: 28, shoulderF: 26, elbowF: 20, weapon: -40, hipF: 18, kneeF: 22, hipB: -14, kneeB: 26 }, "out"),
        kf(28, { ...STANCE, free: 1, torso: 22, shoulderF: 30, elbowF: 24, weapon: -34 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Boarding Rush",
      input: { button: "C", dir: "f", stance: "stand", whileDashing: true },
      tags: ["command"],
      priority: 12,
      duration: 32,
      vel: [
        { at: 3, x: 10 },
        { at: 16, x: 0 },
      ],
      friction: 0.9,
      hits: [
        hit(8, 14, bx(20, 30, 66, 56), 76, {
          fx: "slash",
          pushX: 7,
          knockdown: "soft",
          hitstun: 22,
          shake: 1.4,
        }),
      ],
      desc: "Sprinting shoulder-and-blade rush that covers half the screen.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 26, shoulderF: -20, elbowF: 70, weapon: 80, hipB: -34, kneeB: 50, offX: -3 }),
        kf(8, { ...STANCE, torso: 30, shoulderF: 108, elbowF: 18, weapon: -30, hipF: 44, kneeF: 24, hipB: -28, kneeB: 56, offX: 8 }, "out"),
        kf(20, { ...STANCE, torso: 22, shoulderF: 76, elbowF: 26, weapon: 8, offX: 4 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },

    // --------------------------------------------------------------- specials
    {
      id: "flintlock",
      name: "Flintlock Shot",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      duration: 34,
      resourceCost: 1,
      resourceMin: 1,
      showProps: ["pistol"],
      projectiles: [
        {
          at: 11,
          kind: "shot",
          x: 42,
          y: 60,
          vx: 19,
          vy: 0,
          life: 60,
          box: { x: -12, y: -5, w: 24, h: 10 },
          damage: 58,
          hitstun: 18,
          blockstun: 13,
          chip: 5,
          pushX: 5,
          clashes: true,
          fx: "shot",
          color: "#ffd479",
          trail: "#ffb648",
        },
      ],
      vfx: [{ at: 11, kind: "shot", x: 46, y: 60, scale: 1.1, color: "#ffd479" }],
      desc: "Fires the flintlock straight ahead. Costs a powder charge.",
      notation: "↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderB: 60, elbowB: 40, weaponBack: -20, torso: -6 }),
        kf(11, { ...STANCE, shoulderB: 92, elbowB: -4, weaponBack: 0, torso: 8, offX: -2 }, "out"),
        kf(18, { ...STANCE, shoulderB: 108, elbowB: -14, weaponBack: 16, torso: -6, offX: -4 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },
    {
      id: "flintlockEx",
      name: "Double Barrel",
      input: { button: "S", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "projectile"],
      priority: 20,
      duration: 44,
      meterCost: 50,
      showProps: ["pistol"],
      projectiles: [
        {
          at: 9,
          kind: "shot",
          x: 42,
          y: 64,
          vx: 20,
          vy: 0,
          life: 60,
          box: { x: -12, y: -5, w: 24, h: 10 },
          damage: 44,
          hitstun: 20,
          blockstun: 14,
          chip: 4,
          pushX: 3,
          clashes: true,
          fx: "shot",
          color: "#ffd479",
          trail: "#ffb648",
        },
        {
          at: 17,
          kind: "shot",
          x: 42,
          y: 52,
          vx: 20,
          vy: 0,
          life: 60,
          box: { x: -12, y: -5, w: 24, h: 10 },
          damage: 52,
          hitstun: 24,
          blockstun: 15,
          chip: 5,
          pushX: 9,
          knockdown: "hard",
          clashes: true,
          fx: "shot",
          color: "#ffd479",
          trail: "#ffb648",
        },
      ],
      vfx: [
        { at: 9, kind: "shot", x: 46, y: 64, scale: 1.2, color: "#ffd479" },
        { at: 17, kind: "shot", x: 46, y: 52, scale: 1.4, color: "#ffd479" },
      ],
      desc: "EX. Two shots, no powder needed - the second one knocks down.",
      notation: "↓↘→ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderB: 66, elbowB: 30, weaponBack: -16, torso: -4 }),
        kf(9, { ...STANCE, shoulderB: 96, elbowB: -6, weaponBack: 4, torso: 10, offX: -2 }, "out"),
        kf(14, { ...STANCE, shoulderB: 110, elbowB: -16, weaponBack: 18, torso: -8, offX: -5 }, "inOut"),
        kf(17, { ...STANCE, shoulderB: 88, elbowB: -2, weaponBack: 2, torso: 12, offX: -1 }, "out"),
        kf(26, { ...STANCE, shoulderB: 104, elbowB: -12, weaponBack: 14, torso: -6, offX: -4 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "hook",
      name: "Grapple Hook",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      priority: 18,
      duration: 40,
      resourceCost: 1,
      resourceMin: 1,
      showProps: ["hook"],
      projectiles: [
        {
          at: 12,
          kind: "hook",
          armAfter: 0,
          x: 36,
          y: 58,
          vx: 14,
          vy: 0,
          life: 26,
          box: { x: -18, y: -8, w: 36, h: 16 },
          damage: 44,
          hitstun: 30,
          blockstun: 16,
          pushX: -13,
          chip: 3,
          fx: "pierce",
          color: "#9aa4b1",
        },
      ],
      desc: "Throws the hook - on hit it drags them into point-blank range for a mix-up.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderB: -70, elbowB: 30, torso: -14, offX: -4 }, "inOut"),
        kf(12, { ...STANCE, shoulderB: 96, elbowB: 6, weaponBack: -10, torso: 20, offX: 5 }, "out"),
        kf(24, { ...STANCE, shoulderB: 60, elbowB: 40, torso: 10 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "hookEx",
      name: "Grapple Hook EX",
      input: { button: "S", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "projectile"],
      priority: 26,
      duration: 40,
      meterCost: 50,
      showProps: ["hook"],
      invuln: [{ from: 1, to: 10, kind: "projectile" }],
      projectiles: [
        {
          at: 8,
          kind: "hook",
          x: 36,
          y: 58,
          vx: 18,
          vy: 0,
          life: 30,
          box: { x: -20, y: -10, w: 40, h: 20 },
          damage: 62,
          hitstun: 40,
          blockstun: 18,
          pushX: -18,
          chip: 4,
          fx: "pierce",
          color: "#4fd1c5",
          trail: "#4fd1c5",
        },
      ],
      desc: "EX. Faster hook that ignores fireballs on the way out and yanks them to your feet.",
      notation: "↓↙← + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderB: -80, elbowB: 26, torso: -16, offX: -5 }, "inOut"),
        kf(8, { ...STANCE, shoulderB: 100, elbowB: 4, weaponBack: -12, torso: 22, offX: 6 }, "out"),
        kf(22, { ...STANCE, shoulderB: 56, elbowB: 44, torso: 8 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "rekka1",
      name: "Cutlass Rekka",
      input: { button: "C", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 22,
      duration: 28,
      vel: [{ at: 4, x: 5 }],
      friction: 0.9,
      followUps: [{ button: "C", move: "rekka2", from: 8, to: 26 }],
      hits: [hit(8, 11, bx(20, 42, 62, 38), 52, { fx: "slash", pushX: 3.4, hitstun: 18 })],
      desc: "Rushing slash. Press Heavy again for the follow-up.",
      notation: "↓↘→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: -24, elbowF: 74, weapon: 84, torso: 10, offX: -2 }),
        kf(8, { ...STANCE, shoulderF: 100, elbowF: 14, weapon: -24, torso: 24, hipF: 36, kneeF: 22, offX: 6 }, "out"),
        kf(16, { ...STANCE, shoulderF: 78, elbowF: 26, weapon: 4, torso: 16 }, "inOut"),
        kf(28, { ...STANCE }),
      ],
    },
    {
      id: "rekka2",
      name: "Rekka - Second",
      input: { stance: "stand" },
      tags: ["special"],
      internal: true,
      duration: 26,
      vel: [{ at: 2, x: 5.5 }],
      friction: 0.9,
      followUps: [
        { button: "C", move: "rekka3", from: 7, to: 24 },
        { button: "B", move: "rekka3low", from: 7, to: 24 },
      ],
      hits: [hit(6, 9, bx(22, 36, 66, 44), 46, { fx: "slash", pushX: 3.2, hitstun: 18 })],
      desc: "",
      frames: [
        kf(0, { ...STANCE, shoulderF: 100, elbowF: 14, weapon: -24, torso: 20 }, "out"),
        kf(3, { ...STANCE, shoulderF: 150, elbowF: -20, weapon: 60, torso: -10 }, "inOut"),
        kf(6, { ...STANCE, shoulderF: 46, elbowF: 30, weapon: -40, torso: 30, hipF: 34, offX: 5 }, "out"),
        kf(14, { ...STANCE, shoulderF: 64, elbowF: 30, weapon: -10, torso: 18 }, "inOut"),
        kf(26, { ...STANCE }),
      ],
    },
    {
      id: "rekka3",
      name: "Rekka - Finish",
      input: { stance: "stand" },
      tags: ["special"],
      internal: true,
      duration: 34,
      vel: [{ at: 2, x: 6 }],
      friction: 0.88,
      hits: [
        hit(7, 12, bx(20, 26, 74, 64), 78, {
          fx: "slash",
          pushX: 9,
          knockdown: "hard",
          hitstun: 26,
          shake: 1.8,
        }),
      ],
      desc: "",
      frames: [
        kf(0, { ...STANCE, shoulderF: 60, elbowF: 30, weapon: -20, torso: 22 }, "out"),
        kf(4, { ...STANCE, shoulderF: 170, elbowF: -26, weapon: 70, torso: -20, offX: -3 }, "inOut"),
        kf(7, { ...STANCE, shoulderF: 34, elbowF: 22, weapon: -46, torso: 34, hipF: 40, kneeF: 26, hipB: -22, kneeB: 48, offX: 8 }, "out"),
        kf(20, { ...STANCE, shoulderF: 46, elbowF: 26, weapon: -24, torso: 24, offX: 4 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },
    {
      id: "rekka3low",
      name: "Rekka - Low Finish",
      input: { stance: "stand" },
      tags: ["special", "low"],
      internal: true,
      duration: 32,
      vel: [{ at: 2, x: 4.5 }],
      friction: 0.88,
      hits: [
        hit(8, 12, bx(18, 2, 72, 26), 64, {
          guard: "low",
          fx: "slash",
          knockdown: "sweep",
          pushX: 6,
          hitstun: 22,
        }),
      ],
      desc: "",
      frames: [
        kf(0, { ...STANCE, shoulderF: 60, elbowF: 30, weapon: -20, torso: 22 }, "out"),
        kf(4, { ...STANCE, crouch: 0.8, shoulderF: 10, elbowF: 60, weapon: 70, torso: 20 }, "inOut"),
        kf(8, { ...STANCE, crouch: 1, shoulderF: 96, elbowF: 46, weapon: -50, torso: 32, hipF: 44, kneeF: 82, hipB: -26, kneeB: 92, offX: 7 }, "out"),
        kf(20, { ...STANCE, crouch: 0.9, shoulderF: 70, elbowF: 40, weapon: -10, torso: 24 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "risingCutlass",
      name: "Rising Cutlass",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 24,
      duration: 44,
      airborne: true,
      invuln: [{ from: 1, to: 7, kind: "strike" }],
      vel: [
        { at: 1, x: 2.8, y: 12.2 },
        { at: 24, y: -0.8, mode: "add" },
      ],
      hits: [
        hit(3, 8, bx(8, 50, 60, 80), 80, { launch: [2, 10.5], knockdown: "launch", fx: "slash", hitstun: 26, shake: 1.7 }),
        hit(9, 16, bx(6, 62, 54, 70), 36, { group: 2, launch: [1.6, 5], fx: "slash" }),
      ],
      desc: "Invincible spinning rise. Her reversal - punish anything unsafe.",
      notation: "→↓↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 48 }, "out"),
        kf(3, { ...STANCE, free: 1, spin: -20, torso: -10, shoulderF: 150, elbowF: -10, weapon: 30, hipF: 30, kneeF: 30 }, "out"),
        kf(14, { ...STANCE, free: 1, spin: -180, torso: -16, shoulderF: 168, elbowF: -6, weapon: 24, hipF: 26, kneeF: 26 }, "linear"),
        kf(26, { ...STANCE, free: 1, spin: -340, torso: -8, shoulderF: 140, elbowF: -10, weapon: 32 }, "linear"),
        kf(34, { ...STANCE, free: 1, spin: -360, torso: 0, shoulderF: 90, elbowF: 20, weapon: 40 }, "inOut"),
        kf(44, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "diveKick",
      name: "Plunder Dive",
      input: { button: "B", motion: "qcb", stance: "air" },
      tags: ["special", "air", "overhead"],
      priority: 26,
      duration: 40,
      airborne: true,
      landCancel: true,
      landRecovery: 8,
      vel: [{ at: 3, x: 8, y: -11 }],
      hits: [
        hit(5, 30, bx(14, 6, 54, 46), 62, {
          guard: "overhead",
          fx: "blunt",
          pushX: 4,
          hitstun: 22,
          knockdown: "soft",
        }),
      ],
      desc: "Air-only diagonal dive kick. Changes your jump arc and crosses people up.",
      notation: "(air) ↓↙← + B",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: 24, hipF: 74, kneeF: 4, hipB: -30, kneeB: 40, shoulderF: -30, elbowF: 50, shoulderB: -40, elbowB: 40 }, "out"),
        kf(30, { ...STANCE, free: 1, torso: 26, hipF: 78, kneeF: 2, hipB: -32, kneeB: 38 }),
        kf(40, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "swig",
      name: "Swig of Rum",
      input: { buttons: ["A", "C"], stance: "stand" },
      tags: ["skill"],
      priority: 18,
      duration: 46,
      resourceGain: 2,
      meterGain: 18,
      friction: 0.9,
      desc: "SKILL. Reloads both powder charges and builds meter - but you are wide open while she drinks.",
      notation: "A + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(10, { ...STANCE, shoulderB: -140, elbowB: 120, torso: -20, head: -18 }, "inOut"),
        kf(26, { ...STANCE, shoulderB: -150, elbowB: 128, torso: -26, head: -24, offY: 2 }),
        kf(36, { ...STANCE, shoulderB: -60, elbowB: 60, torso: -6, head: -4 }, "inOut"),
        kf(46, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "Broadside",
      input: { button: "S", motion: "hcf", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 110,
      meterCost: 100,
      superFreeze: 40,
      invuln: [{ from: 1, to: 10, kind: "strike" }],
      showProps: ["pistol"],
      friction: 0.92,
      projectiles: [
        {
          at: 20,
          kind: "cannon",
          armAfter: 0,
          x: 40,
          y: 30,
          vx: 11,
          vy: 0.2,
          life: 100,
          box: { x: -16, y: -14, w: 32, h: 28 },
          damage: 60,
          hitstun: 26,
          blockstun: 16,
          chip: 8,
          pushX: 5,
          fx: "explode",
          scale: 1.4,
          color: "#2c2f36",
          trail: "#8a8f98",
        },
        {
          at: 34,
          kind: "cannon",
          armAfter: 0,
          x: 40,
          y: 62,
          vx: 12,
          vy: 0,
          life: 100,
          box: { x: -16, y: -14, w: 32, h: 28 },
          damage: 55,
          hitstun: 26,
          blockstun: 16,
          chip: 7,
          pushX: 5,
          fx: "explode",
          scale: 1.4,
          color: "#2c2f36",
          trail: "#8a8f98",
        },
        {
          at: 48,
          kind: "cannon",
          armAfter: 0,
          x: 40,
          y: 44,
          vx: 13,
          vy: 0.1,
          life: 100,
          box: { x: -18, y: -16, w: 36, h: 32 },
          damage: 90,
          hitstun: 34,
          blockstun: 18,
          chip: 10,
          pushX: 12,
          knockdown: "hard",
          fx: "explode",
          scale: 1.8,
          color: "#2c2f36",
          trail: "#ffb648",
          detonate: { radius: 70, damage: 60, hitstun: 30, blockstun: 16, knockdown: "hard", chip: 6 },
        },
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 50, scale: 2.4, color: "#4fd1c5" },
        { at: 20, kind: "explode", x: 44, y: 30, scale: 0.9 },
        { at: 34, kind: "explode", x: 44, y: 62, scale: 0.9 },
        { at: 48, kind: "explode", x: 44, y: 44, scale: 1.2 },
      ],
      desc: "SUPER. Calls in a broadside from the ship offshore - three cannonballs, the last one explodes.",
      notation: "←↙↓↘→ + S  (100 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(10, { ...STANCE, shoulderF: 150, elbowF: -20, weapon: 60, torso: -16, offX: -4 }, "inOut"),
        kf(18, { ...STANCE, shoulderF: 172, elbowF: -10, weapon: 40, torso: -22, head: -14, offY: 2 }, "out"),
        kf(30, { ...STANCE, shoulderF: 166, elbowF: -12, weapon: 44, torso: -18, head: -10 }),
        kf(48, { ...STANCE, shoulderF: 150, elbowF: -18, weapon: 52, torso: -10, head: -6 }, "inOut"),
        kf(70, { ...STANCE, shoulderF: 90, elbowF: 20, weapon: 40, torso: 6 }, "inOut"),
        kf(110, { ...STANCE }),
      ],
    },
  ],
};
