/**
 * Marcus Aquila - Roman legionary.
 *
 * Long spear pokes, a shield that eats hits, and pilum throws. Slow to move,
 * brutal at his own range.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const RED = "#c0392b";
const BRONZE = "#d9a441";
const STEEL = "#c9d1d9";

/** Spear in the front hand, shield across the back arm. */
const STANCE = {
  torso: 5,
  head: -3,
  hipF: 15,
  kneeF: 14,
  hipB: -17,
  kneeB: 26,
  shoulderF: 64,
  elbowF: -26,
  shoulderB: 34,
  elbowB: 66,
  weapon: 52,
};

const guard = { shoulderB: 58, elbowB: 74 };

export const ROMAN: FighterDef = {
  id: "roman",
  name: "Lucius Vorenus",
  title: "Centurion, Legio XI",
  era: "Nervii Country, 54 BC",
  bio: "Named by Caesar in the Gallic War for the running feud with Titus Pullo that sent them both over the rampart at the Nervii siege. Holds the line with a scutum and punishes everything that steps inside it.",
  archetype: "Zoner / Wall",
  difficulty: 2,
  strengths: ["Longest normals in the roster", "Shield armour", "Strong anti-airs"],
  weaknesses: ["Slow walk speed", "Weak up close", "Long recovery on whiffs"],
  winQuote: "Pullo would have gone first. That is the only thing he ever beat me at.",
  palette: {
    body: "#e8e6e3",
    outline: "#1c1a17",
    accent: RED,
    cloth: "#8c2f22",
    metal: BRONZE,
    aura: "#ffb648",
  },
  stats: {
    health: 1050,
    walkF: 2.35,
    walkB: 1.95,
    dashSpeed: 7.2,
    dashFrames: 16,
    backdashFrames: 22,
    jumpVel: 12.4,
    jumpFwd: 4.4,
    gravity: 0.62,
    weight: 1.1,
    airMoves: 2,
    doubleJump: false,
    airDash: false,
    width: 21,
    standHeight: 104,
    crouchHeight: 68,
    scale: 1.02,
  },
  stance: STANCE,
  // The scutum does the work. Shield up and square, gladius withdrawn to
  // the hip where it can come out again without moving the shield.
  clips: guardClips({
    high: { torso: 3, head: -8, shoulderB: -12, elbowB: 102, shoulderF: 26, elbowF: -14, weapon: 164, hipF: 13, kneeF: 20, hipB: -18, kneeB: 32, offX: -3 },
    low: { torso: 9, head: -6, shoulderB: -26, elbowB: 110, shoulderF: 30, elbowF: -18, weapon: 160, hipF: 32, kneeF: 72, hipB: -20, kneeB: 82, offX: -3 },
  }),
  resource: {
    name: "Pila",
    max: 3,
    start: 3,
    regen: 0.006,
    color: BRONZE,
    pips: true,
  },
  props: [
    {
      id: "helmet",
      attach: "head",
      // Galea: bowl, neck guard, hinged cheek pieces and a fore-and-aft crest.
      parts: [
        // Bowl: rounded over the crown, flaring out to the browband.
        { geo: "poly", size: [-11, -3, -10.5, 3, -8, 8, -4, 11, 4, 11, 8, 8, 10.5, 3, 11, -3, 7, -5, -7, -5], pos: [0, 2], color: BRONZE },
        { geo: "poly", size: [-12, 2.5, 12, 2, 11, -2.5, -11, -3], pos: [0, -2], color: "#b8862f" },
        // Neck guard sweeping back and down.
        { geo: "poly", size: [0, 0, -3, -9, -11, -12, -12, -3], pos: [-8, -3], color: "#a8762a", behind: true },
        // Cheek piece hinged over the jaw.
        { geo: "poly", size: [0, 4, 5, 2, 6, -6, 2, -10, -2, -8], pos: [6, -6], color: BRONZE, z: 0.9 },
        // Crest rail and the horsehair plume laid fore and aft along it: a low
        // ridge that sweeps up over the crown, not a block sitting on top.
        { geo: "box", size: [19, 3], pos: [-1, 11], color: "#8a6a2f" },
        { geo: "poly", size: [-14, -1, -13, 3, -8, 6, 0, 7, 7, 5, 11, 1, 12, -2], pos: [-1, 12], color: RED },
        { geo: "poly", size: [-11, -1, -10, 2, -5, 4, 2, 4, 7, 2, 9, -1], pos: [-1, 13], color: "#e05a48" },
        // Tail of the plume falling down the back of the helmet.
        { geo: "poly", size: [0, 4, -4, -10, -8, -14, -7, 3], pos: [-13, 8], color: "#a52d1f", behind: true },
      ],
    },
    {
      id: "spear",
      attach: "handF",
      // Pilum: a long shaft, an iron shank, a pyramid head and a bronze butt.
      parts: [
        { geo: "cyl", size: [2.6, 118], pos: [18, 0], rot: 90, color: "#7a5230" },
        { geo: "cyl", size: [1.7, 26], pos: [84, 0], rot: 90, color: "#8f97a1" },
        // Socket collar where the shank enters the wood.
        { geo: "box", size: [9, 6.5], pos: [72, 0], color: BRONZE },
        { geo: "box", size: [4, 5], pos: [64, 0], color: "#b8862f" },
        // Pyramid head, barbed.
        { geo: "poly", size: [0, 0, -8, 5, -13, 2, -13, -2, -8, -5], pos: [110, 0], color: STEEL },
        // Grip binding.
        { geo: "box", size: [12, 6], pos: [4, 0], color: "#5c3d22" },
        { geo: "box", size: [12, 2], pos: [4, 2], color: "#7a5230" },
        { geo: "cone", size: [3.4, 10], pos: [-42, 0], rot: -90, color: BRONZE },
      ],
    },
    {
      id: "shield",
      attach: "forearmB",
      // Scutum: a tall curved rectangle, bronze rim, iron boss and lightning wings.
      parts: [
        { geo: "poly", size: [-9, -28, 9, -28, 10, -18, 10, 18, 9, 28, -9, 28, -10, 18, -10, -18], pos: [14, 0], color: BRONZE, z: 0.55 },
        { geo: "poly", size: [-7, -25, 7, -25, 8, -16, 8, 16, 7, 25, -7, 25, -8, 16, -8, -16], pos: [14, 0], color: RED, z: 0.6 },
        // Painted wings either side of the boss.
        { geo: "poly", size: [0, 0, -6, 7, -2, 8, 2, 3, 2, -3, -2, -8, -6, -7], pos: [14, 12], color: "#e8c46a", z: 0.7 },
        { geo: "poly", size: [0, 0, -6, -7, -2, -8, 2, -3, 2, 3, -2, 8, -6, 7], pos: [14, -12], color: "#e8c46a", z: 0.7 },
        { geo: "box", size: [3.5, 34], pos: [14, 0], color: "#a52d1f", z: 0.7 },
        // Iron boss over the hand grip.
        { geo: "disc", size: [6.5], pos: [14, 0], color: STEEL, z: 0.8 },
        { geo: "disc", size: [3], pos: [14, 1], color: "#eef2f6", z: 0.85 },
        { geo: "box", size: [19, 3], pos: [14, 26], color: BRONZE, z: 0.8 },
        { geo: "box", size: [19, 3], pos: [14, -26], color: BRONZE, z: 0.8 },
      ],
    },
    {
      id: "lorica",
      attach: "torso",
      // Lorica segmentata: banded iron plates over the chest, shoulder guards
      // on top, all buckled down the centre.
      parts: [
        { geo: "poly", size: [-13, -15, 13, -15, 14, 6, 11, 15, -11, 15, -14, 6], pos: [0, 3], color: "#b9bfc6" },
        { geo: "box", size: [27, 3.5], pos: [0, 12], color: "#8d959e" },
        { geo: "box", size: [27, 3.5], pos: [0, 5], color: "#8d959e" },
        { geo: "box", size: [26, 3.5], pos: [0, -2], color: "#8d959e" },
        { geo: "box", size: [25, 3.5], pos: [0, -9], color: "#8d959e" },
        // Shoulder guards.
        { geo: "poly", size: [-9, 0, -7, 6, 6, 7, 9, 1, 6, -3, -7, -3], pos: [-4, 16], color: "#cdd3d9" },
        { geo: "poly", size: [-8, 0, -6, 5, 6, 6, 8, 0, 5, -3, -6, -3], pos: [4, 18], color: "#dfe4e9", z: 0.2 },
        // Buckles down the front.
        { geo: "disc", size: [2], pos: [7, 10], color: BRONZE, z: 0.3 },
        { geo: "disc", size: [2], pos: [7, 0], color: BRONZE, z: 0.3 },
        { geo: "disc", size: [2], pos: [7, -10], color: BRONZE, z: 0.3 },
      ],
    },
    {
      id: "skirt",
      attach: "pelvis",
      // Pteruges: leather straps with bronze studs on the ends.
      parts: [
        { geo: "box", size: [28, 7], pos: [0, 2], color: "#6f4a2a" },
        { geo: "poly", size: [-3.5, 8, 3.5, 8, 2.5, -8, -2.5, -8], pos: [-9, -6], color: "#8c2f22", behind: true },
        { geo: "poly", size: [-3.5, 9, 3.5, 9, 2.5, -9, -2.5, -9], pos: [-1, -7], color: "#a5382a", behind: true },
        { geo: "poly", size: [-3.5, 8, 3.5, 8, 2.5, -8, -2.5, -8], pos: [7, -6], color: "#8c2f22", behind: true },
        { geo: "disc", size: [1.6], pos: [-9, -13], color: BRONZE, behind: true },
        { geo: "disc", size: [1.6], pos: [-1, -15], color: BRONZE, behind: true },
        { geo: "disc", size: [1.6], pos: [7, -13], color: BRONZE, behind: true },
      ],
    },
    {
      id: "cape",
      attach: "neck",
      parts: [
        { geo: "box", size: [22, 6], pos: [-4, -2], color: "#7d1f1f", behind: true },
        { geo: "disc", size: [3], pos: [7, -1], color: BRONZE },
      ],
      cloth: {
        segments: 4,
        segmentLength: 11,
        width: 19,
        endWidth: 11,
        color: "#8f2222",
        gravity: 0.5,
        stiffness: 0.5,
        drift: -0.34,
      },
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 125,
      backThrowDamage: 135,
      throwRange: 64,
      rollSpeed: 6.8,
      weaponIdle: { weapon: STANCE.weapon },
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Shield Jab",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 14,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 13],
      // Testudo string continues into 6A.
      followUps: [
        { button: "A", move: "6A", from: 4, to: 11, string: "Testudo" },
      ],
      hits: [hit(4, 6, bx(20, 52, 46, 22), 34, { blockstun: 11, hitstun: 15, fx: "blunt", pushX: 3.4 })],
      desc: "Fast shield punch. Your best button up close and it chains into everything.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderB: 82, elbowB: 20, torso: 10, offX: 2 }),
        kf(6, { ...STANCE, shoulderB: 88, elbowB: 8, torso: 12, offX: 5 }),
        kf(10, { ...STANCE, shoulderB: 60, elbowB: 46, torso: 8 }, "inOut"),
        kf(14, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Spear Thrust",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 24,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [8, 22],
      // Pilum Drill string continues into 5C.
      followUps: [
        { button: "C", move: "5C", from: 8, to: 21, string: "Pilum Drill" },
      ],
      hits: [hit(8, 11, bx(34, 54, 84, 20), 62, { fx: "pierce", pushX: 5, hitstun: 18 })],
      desc: "Straight thrust with huge reach. The backbone of his zoning game.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        // The shaft stays level the whole way. `weapon` unwinds as the shoulder
        // and elbow open, so the point tracks straight down the line instead of
        // being swung round with the arm - it used to drop to 38 degrees below
        // horizontal and come up 39 above, which is a windmill, not a thrust.
        kf(5, { ...STANCE, shoulderF: 52, elbowF: -60, torso: -6, offX: -4, weapon: 100 }),
        kf(8, { ...STANCE, shoulderF: 84, elbowF: -2, torso: 14, offX: 8, weapon: 3, hipF: 30, kneeF: 20 }, "out"),
        kf(13, { ...STANCE, shoulderF: 82, elbowF: 0, torso: 12, offX: 7, weapon: 4, hipF: 28, kneeF: 18 }),
        kf(19, { ...STANCE, shoulderF: 70, elbowF: -18, torso: 8, offX: 2, weapon: 35 }, "inOut"),
        kf(24, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Overhead Chop",
      input: { button: "C", stance: "stand" },
      tags: ["heavy", "overhead"],
      duration: 34,
      cancelInto: ["special", "super"],
      cancelWindow: [14, 30],
      // Pilum Drill string continues into 4C.
      followUps: [
        { button: "C", move: "4C", from: 16, to: 31, string: "Pilum Drill" },
      ],
      hits: [
        hit(16, 19, bx(24, 30, 78, 76), 92, {
          guard: "overhead",
          fx: "slash",
          knockdown: "soft",
          pushX: 6.5,
          shake: 1.4,
        }),
      ],
      desc: "Two-handed downward smash. Must be blocked standing and knocks down.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 168, elbowF: -34, shoulderB: 150, elbowB: -20, torso: -16, weapon: 96, hipB: -24, kneeB: 34 }, "inOut"),
        kf(16, { ...STANCE, shoulderF: 46, elbowF: 8, shoulderB: 50, elbowB: 10, torso: 30, weapon: 8, hipF: 34, kneeF: 26, hipB: -18, kneeB: 40, offX: 6 }, "out"),
        kf(22, { ...STANCE, shoulderF: 40, elbowF: 12, shoulderB: 46, elbowB: 14, torso: 28, weapon: 4, offX: 5 }),
        kf(30, { ...STANCE, shoulderF: 58, elbowF: -10, torso: 14 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Shield Poke",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 15,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 14],
      hits: [hit(4, 6, bx(18, 20, 44, 22), 30, { guard: "low", blockstun: 11, hitstun: 14, pushX: 3 })],
      desc: "Quick low. Must be blocked crouching and links into itself.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, ...guard }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 22, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderB: 100, elbowB: 8, offX: 4 }),
        kf(9, { ...STANCE, crouch: 1, torso: 20, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderB: 76, elbowB: 40 }, "inOut"),
        kf(15, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, ...guard }),
      ],
    },
    {
      id: "2B",
      name: "Crouching Spear",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 26,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [9, 24],
      hits: [hit(9, 12, bx(30, 14, 86, 26), 58, { guard: "low", fx: "pierce", pushX: 4.6 })],
      desc: "Low thrust along the ground. Long, safe-ish poke that must be blocked low.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(5, { ...STANCE, crouch: 1, torso: 10, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderF: 40, elbowF: -70, weapon: 78 }),
        kf(9, { ...STANCE, crouch: 1, torso: 26, hipF: 40, kneeF: 78, hipB: -26, kneeB: 88, shoulderF: 74, elbowF: -8, weapon: 30, offX: 8 }, "out"),
        kf(15, { ...STANCE, crouch: 1, torso: 24, hipF: 38, kneeF: 76, hipB: -24, kneeB: 86, shoulderF: 72, elbowF: -10, weapon: 30, offX: 7 }),
        kf(26, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "2C",
      name: "Shaft Sweep",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [13, 28],
      hits: [
        hit(12, 16, bx(20, 6, 92, 26), 78, {
          guard: "low",
          knockdown: "sweep",
          fx: "slash",
          pushX: 6,
          shake: 1.2,
        }),
      ],
      desc: "Sweeping shaft strike. Knocks down on hit - your main knockdown starter.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(7, { ...STANCE, crouch: 1, torso: 4, hipF: 30, kneeF: 70, hipB: -30, kneeB: 92, shoulderF: 20, elbowF: -30, weapon: 110 }),
        kf(13, { ...STANCE, crouch: 1, torso: 30, hipF: 46, kneeF: 84, hipB: -30, kneeB: 96, shoulderF: 100, elbowF: 30, weapon: -30, offX: 6 }, "out"),
        kf(20, { ...STANCE, crouch: 1, torso: 26, hipF: 42, kneeF: 80, hipB: -26, kneeB: 90, shoulderF: 96, elbowF: 26, weapon: -26 }),
        kf(32, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "6B",
      name: "Scutum Bash",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command"],
      priority: 10,
      duration: 30,
      armor: [{ from: 3, to: 13, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 6, x: 4.5 }],
      friction: 0.86,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 26],
      // Shield Wall string continues into 6C.
      followUps: [
        { button: "C", move: "6C", from: 10, to: 27, string: "Shield Wall" },
      ],
      hits: [
        hit(10, 14, bx(24, 34, 56, 52), 70, {
          fx: "blunt",
          pushX: 7,
          hitstun: 22,
          knockdown: "crumple",
          shake: 1.5,
        }),
      ],
      desc: "Armoured shield charge - absorbs one hit on the way in and crumples on contact.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, torso: -8, shoulderB: 70, elbowB: 40, hipB: -28, kneeB: 44, offX: -4 }),
        kf(10, { ...STANCE, torso: 24, shoulderB: 92, elbowB: 4, hipF: 36, kneeF: 22, hipB: -20, kneeB: 46, offX: 8 }, "out"),
        kf(16, { ...STANCE, torso: 20, shoulderB: 88, elbowB: 8, hipF: 32, kneeF: 20, offX: 6 }),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Skyward Guard",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 34,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 30],
      hits: [
        hit(9, 14, bx(16, 56, 62, 74), 74, {
          launch: [2.4, 12.5],
          knockdown: "launch",
          fx: "pierce",
          hitstun: 26,
          shake: 1.3,
        }),
      ],
      desc: "Angled anti-air thrust that launches. Follow it into a jump attack for damage.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5, hipF: 26, kneeF: 44, hipB: -20, kneeB: 52 }, "out"),
        kf(6, { ...STANCE, crouch: 0.7, torso: 12, shoulderF: 40, elbowF: -20, weapon: 40 }),
        kf(9, { ...STANCE, torso: -14, shoulderF: 140, elbowF: -16, weapon: -60, hipF: 22, kneeF: 12, offY: 4 }, "out"),
        kf(16, { ...STANCE, torso: -10, shoulderF: 132, elbowF: -12, weapon: -20, hipF: 18, kneeF: 10 }),
        kf(26, { ...STANCE, torso: 4, shoulderF: 80, elbowF: -22 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },
    {
      // Forward and back sets. A is the scutum, B is the spear, C commits.
      id: "6A",
      name: "Boss Punch",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 20,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [7, 18],
      vel: [{ at: 2, x: 2.2 }],
      friction: 0.88,
      // Testudo string continues into 6B.
      followUps: [
        { button: "B", move: "6B", from: 7, to: 17, string: "Testudo" },
      ],
      hits: [hit(7, 9, bx(20, 60, 44, 26), 32, { fx: "blunt", guard: "high", pushX: 3, hitstun: 14, hitstop: 5 })],
      desc: "Punches with the iron boss of the scutum. His fastest button and where pressure starts.",
      notation: "\u2192 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderB: 22, elbowB: 86, torso: -2, offX: -2 }, "out"),
        kf(7, { ...STANCE, shoulderB: 62, elbowB: 24, torso: 14, hipF: 26, kneeF: 16, offX: 7 }, "out"),
        kf(12, { ...STANCE, shoulderB: 48, elbowB: 48, torso: 10, offX: 5 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Legion Advance",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 40,
      armor: [{ from: 8, to: 18, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 8, x: 5.4 }, { at: 26, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [20, 36],
      hits: [
        hit(16, 20, bx(19, 22, 70, 68), 88, { fx: "blunt", guard: "mid", pushX: 17, hitstun: 24, hitstop: 12, knockdown: "wallbounce", shake: 2.2 }),
      ],
      desc: "Walks forward behind the shield and does not stop. Carries them into the wall.",
      notation: "\u2192 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, torso: -10, shoulderB: 18, elbowB: 92, hipB: -32, kneeB: 52, crouch: 0.28, offX: -6 }, "out"),
        kf(16, { ...STANCE, torso: 32, shoulderB: 54, elbowB: 44, hipF: 42, kneeF: 18, hipB: -28, kneeB: 24, crouch: 0.14, offX: 12 }, "out"),
        kf(24, { ...STANCE, torso: 24, shoulderB: 46, elbowB: 52, hipF: 30, kneeF: 24, offX: 8 }),
        kf(32, { ...STANCE, torso: 10, offX: 3 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Rim Chop",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 22,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [8, 20],
      vel: [{ at: 1, x: -2.6 }],
      friction: 0.86,
      hits: [hit(8, 10, bx(16, 50, 42, 32), 36, { fx: "blunt", guard: "mid", pushX: 6, hitstun: 15, hitstop: 6 })],
      desc: "Gives ground and chops down with the shield rim. Catches a step-in behind a whiff.",
      notation: "\u2190 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -6, shoulderB: 6, elbowB: 96, hipB: -26, kneeB: 38, offX: -6 }, "out"),
        kf(8, { ...STANCE, torso: 8, shoulderB: 56, elbowB: 40, hipF: 22, kneeF: 18, offX: -3 }, "out"),
        kf(14, { ...STANCE, torso: 2, shoulderB: 42, elbowB: 58, offX: -4 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Long Guard",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 30,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      vel: [{ at: 1, x: -3.4 }],
      friction: 0.88,
      // He leaves, the point stays. Longest button on the roster.
      hits: [hit(12, 15, bx(46, 52, 108, 22), 56, { fx: "pierce", guard: "mid", pushX: 7, hitstun: 18, hitstop: 8 })],
      desc: "Steps off the line and holds the point out. Nothing walks into this for free.",
      notation: "\u2190 + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 46, elbowF: -12, weapon: 60, torso: -10, hipB: -28, kneeB: 42, offX: -8 }, "inOut"),
        // Arm locks out and the weapon angle unwinds with it, so the shaft
        // stays level instead of sweeping up as the elbow opens.
        kf(12, { ...STANCE, shoulderF: 86, elbowF: 0, weapon: 6, torso: 4, hipF: 28, kneeF: 12, hipB: -22, kneeB: 32, offX: -5 }, "out"),
        kf(17, { ...STANCE, shoulderF: 84, elbowF: 2, weapon: 6, torso: 2, hipF: 26, kneeF: 12, offX: -6 }),
        kf(23, { ...STANCE, shoulderF: 70, elbowF: -16, weapon: 36, torso: 0, offX: -4 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Haft Drop",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 44,
      cancelInto: ["special", "super"],
      cancelWindow: [26, 40],
      hits: [
        hit(20, 23, bx(16, 20, 92, 86), 100, { fx: "blunt", guard: "overhead", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 }),
      ],
      desc: "Raises the spear two-handed and brings the shaft down on their head. Blocked standing only.",
      notation: "\u2190 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 128, elbowF: -46, weapon: 96, torso: -12, offX: -5 }, "inOut"),
        // Shaft vertical above the head, then driven straight down.
        kf(15, { ...STANCE, shoulderF: 168, elbowF: -20, weapon: 112, torso: -20, hipB: -26, kneeB: 38, offY: 3, offX: -3 }, "out"),
        kf(20, { ...STANCE, shoulderF: 96, elbowF: 6, weapon: 84, torso: 30, hipF: 34, kneeF: 18, hipB: -12, kneeB: 32, offX: 6 }, "out"),
        kf(26, { ...STANCE, shoulderF: 88, elbowF: 10, weapon: 80, torso: 24, offX: 4 }),
        kf(36, { ...STANCE, shoulderF: 76, elbowF: -18, weapon: 62, torso: 8 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Shield",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 20,
      airborne: true,
      landCancel: true,
      landRecovery: 2,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [5, 18],
      hits: [hit(5, 10, bx(16, 34, 48, 32), 38, { fx: "blunt", pushX: 3, hitstun: 15 })],
      desc: "Quick air shield swat. Fast enough to beat other jump-ins.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 34, kneeF: 44, hipB: -24, kneeB: 40 }, "out"),
        kf(5, { ...STANCE, free: 1, shoulderB: 108, elbowB: 20, torso: 14, hipF: 30, kneeF: 40, hipB: -20, kneeB: 36 }),
        kf(12, { ...STANCE, free: 1, shoulderB: 70, elbowB: 50, torso: 8, hipF: 32, kneeF: 42, hipB: -22, kneeB: 38 }, "inOut"),
        kf(20, { ...STANCE, free: 1, hipF: 34, kneeF: 44, hipB: -24, kneeB: 40 }),
      ],
    },
    {
      id: "jB",
      name: "Diving Spear",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 26,
      airborne: true,
      landCancel: true,
      landRecovery: 4,
      hits: [hit(7, 14, bx(24, 10, 74, 46), 64, { fx: "pierce", pushX: 4.4, hitstun: 20 })],
      desc: "Downward-angled air thrust with the reach to hit from anywhere in a jump arc.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 30, kneeF: 40, hipB: -22, kneeB: 38 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderF: 30, elbowF: -50, weapon: 84, torso: -8 }),
        kf(7, { ...STANCE, free: 1, shoulderF: 96, elbowF: 6, weapon: 14, torso: 24, hipF: 40, kneeF: 34, hipB: -14, kneeB: 30 }, "out"),
        kf(16, { ...STANCE, free: 1, shoulderF: 92, elbowF: 8, weapon: 12, torso: 22 }),
        kf(26, { ...STANCE, free: 1, hipF: 30, kneeF: 40, hipB: -22, kneeB: 38 }),
      ],
    },
    {
      id: "jC",
      name: "Shield Drop",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 30,
      airborne: true,
      landCancel: true,
      landRecovery: 8,
      vel: [{ at: 6, y: -4, mode: "add" }],
      hits: [
        hit(8, 18, bx(-6, -6, 60, 46), 84, {
          guard: "overhead",
          fx: "blunt",
          knockdown: "soft",
          pushX: 5,
          shake: 1.6,
        }),
      ],
      desc: "Slams the scutum straight down. Heavy jump-in that crushes low blocks.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, torso: -22, shoulderB: 150, elbowB: -10, hipF: 40, kneeF: 60, hipB: -30, kneeB: 60 }),
        kf(9, { ...STANCE, free: 1, torso: 30, shoulderB: 26, elbowB: 16, hipF: 20, kneeF: 20, hipB: -16, kneeB: 24 }, "out"),
        kf(30, { ...STANCE, free: 1, torso: 24, shoulderB: 30, elbowB: 20 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Legion Charge",
      input: { button: "C", dir: "f", stance: "stand", whileDashing: true },
      tags: ["command"],
      priority: 12,
      duration: 36,
      vel: [
        { at: 4, x: 9 },
        { at: 18, x: 0 },
      ],
      friction: 0.9,
      armor: [{ from: 3, to: 17, hits: 1, damageScale: 0.5 }],
      hits: [
        hit(10, 18, bx(20, 26, 70, 60), 88, {
          fx: "pierce",
          pushX: 9,
          knockdown: "hard",
          hitstun: 24,
          shake: 1.8,
        }),
      ],
      desc: "Running spear charge with armour. Closes ground and knocks down hard.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: 16, shoulderF: 46, elbowF: -40, weapon: 66, hipB: -30, kneeB: 44, offX: -3 }),
        kf(10, { ...STANCE, torso: 26, shoulderF: 78, elbowF: -6, weapon: 40, hipF: 40, kneeF: 24, hipB: -26, kneeB: 54, offX: 6 }, "out"),
        kf(24, { ...STANCE, torso: 22, shoulderF: 74, elbowF: -8, weapon: 40, hipF: 30, kneeF: 30 }),
        kf(36, { ...STANCE }),
      ],
    },

    // --------------------------------------------------------------- specials
    {
      id: "pilum",
      name: "Pilum Throw",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      duration: 38,
      resourceCost: 1,
      resourceMin: 1,
      meterGain: 6,
      projectiles: [
        {
          at: 13,
          kind: "pilum",
          x: 40,
          y: 62,
          vx: 12,
          vy: 0.4,
          gravity: 0.03,
          life: 90,
          box: { x: -26, y: -7, w: 52, h: 14 },
          damage: 66,
          hitstun: 20,
          blockstun: 14,
          chip: 6,
          pushX: 6,
          clashes: true,
          fx: "pierce",
          scale: 1,
          color: "#c9d1d9",
        },
      ],
      desc: "Hurls a javelin across the screen. Uses one pilum - they come back slowly.",
      notation: "↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 158, elbowF: -44, weapon: 70, torso: -18, hipB: -28, kneeB: 40, offX: -5 }, "inOut"),
        kf(13, { ...STANCE, shoulderF: 76, elbowF: -4, weapon: 34, torso: 26, hipF: 40, kneeF: 22, hipB: -20, kneeB: 46, offX: 8 }, "out"),
        kf(22, { ...STANCE, shoulderF: 70, elbowF: -8, torso: 20, offX: 5 }),
        kf(38, { ...STANCE }),
      ],
    },
    {
      id: "pilumEx",
      name: "Pilum Volley",
      input: { button: "S", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "projectile"],
      priority: 20,
      duration: 52,
      meterCost: 50,
      projectiles: [
        {
          at: 10,
          kind: "pilum",
          x: 40,
          y: 76,
          vx: 13,
          vy: -0.5,
          gravity: 0.02,
          life: 90,
          box: { x: -26, y: -7, w: 52, h: 14 },
          damage: 46,
          hitstun: 18,
          blockstun: 12,
          chip: 4,
          pushX: 4,
          clashes: true,
          fx: "pierce",
        },
        {
          at: 18,
          kind: "pilum",
          x: 40,
          y: 60,
          vx: 14,
          vy: 0,
          gravity: 0.02,
          life: 90,
          box: { x: -26, y: -7, w: 52, h: 14 },
          damage: 42,
          hitstun: 18,
          blockstun: 12,
          chip: 4,
          pushX: 4,
          clashes: true,
          fx: "pierce",
        },
        {
          at: 26,
          kind: "pilum",
          x: 40,
          y: 44,
          vx: 15,
          vy: 0.3,
          gravity: 0.02,
          life: 90,
          box: { x: -26, y: -7, w: 52, h: 14 },
          damage: 52,
          hitstun: 22,
          blockstun: 14,
          chip: 5,
          pushX: 7,
          knockdown: "soft",
          clashes: true,
          fx: "pierce",
        },
      ],
      desc: "EX. Three javelins at three heights - a wall the opponent has to jump into.",
      notation: "↓↘→ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 154, elbowF: -40, weapon: 66, torso: -16, offX: -5 }, "inOut"),
        kf(10, { ...STANCE, shoulderF: 84, elbowF: -6, weapon: 30, torso: 24, offX: 7 }, "out"),
        kf(14, { ...STANCE, shoulderF: 150, elbowF: -38, weapon: 62, torso: -12, offX: -3 }, "inOut"),
        kf(18, { ...STANCE, shoulderF: 80, elbowF: -6, weapon: 32, torso: 22, offX: 7 }, "out"),
        kf(22, { ...STANCE, shoulderF: 150, elbowF: -38, weapon: 62, torso: -12, offX: -3 }, "inOut"),
        kf(26, { ...STANCE, shoulderF: 72, elbowF: -2, weapon: 36, torso: 28, hipF: 38, kneeF: 24, offX: 9 }, "out"),
        kf(38, { ...STANCE, torso: 12 }, "inOut"),
        kf(52, { ...STANCE }),
      ],
    },
    {
      id: "phalanx",
      name: "Phalanx Advance",
      input: { button: "B", motion: "hcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 22,
      duration: 54,
      vel: [
        { at: 1, x: 3.4 },
        { at: 14, x: 3.2 },
        { at: 28, x: 3.6 },
        { at: 40, x: 0 },
      ],
      friction: 0.94,
      hits: [
        hit(8, 11, bx(30, 50, 76, 22), 34, { group: 1, fx: "pierce", pushX: 1.6, hitstun: 16, hitstop: 5 }),
        hit(20, 23, bx(30, 50, 80, 22), 34, { group: 2, fx: "pierce", pushX: 1.6, hitstun: 16, hitstop: 5 }),
        hit(32, 36, bx(30, 46, 88, 26), 62, {
          group: 3,
          fx: "pierce",
          pushX: 8,
          knockdown: "hard",
          hitstun: 24,
          shake: 1.6,
        }),
      ],
      desc: "Marches forward with three thrusts. The last one knocks down.",
      notation: "←↙↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        // Recock keeps the elbow tucked rather than winding it wide, and the
        // weapon angle unwinds against the shoulder/elbow opening on the way
        // to full extension - the shaft holds its line instead of swinging.
        kf(5, { ...STANCE, shoulderF: 52, elbowF: -32, weapon: 54, torso: 4 }),
        kf(8, { ...STANCE, shoulderF: 80, elbowF: -4, weapon: 4, torso: 20, hipF: 34, kneeF: 20, offX: 5 }, "out"),
        kf(16, { ...STANCE, shoulderF: 52, elbowF: -32, weapon: 54, torso: 6, hipF: 18, kneeF: 30 }, "inOut"),
        kf(20, { ...STANCE, shoulderF: 82, elbowF: -4, weapon: 4, torso: 22, hipF: 36, kneeF: 20, offX: 5 }, "out"),
        kf(28, { ...STANCE, shoulderF: 50, elbowF: -36, weapon: 58, torso: 4, hipF: 16, kneeF: 32 }, "inOut"),
        kf(32, { ...STANCE, shoulderF: 88, elbowF: 0, weapon: -2, torso: 28, hipF: 42, kneeF: 22, hipB: -24, kneeB: 50, offX: 9 }, "out"),
        kf(44, { ...STANCE, torso: 14 }, "inOut"),
        kf(54, { ...STANCE }),
      ],
    },
    {
      id: "skyward",
      name: "Skyward Spear",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 24,
      duration: 46,
      airborne: true,
      invuln: [{ from: 1, to: 8, kind: "strike" }],
      vel: [
        { at: 1, x: 2.4, y: 12.6 },
        { at: 26, y: -1, mode: "add" },
      ],
      hits: [
        hit(4, 8, bx(6, 60, 62, 76), 82, {
          launch: [2, 11],
          knockdown: "launch",
          fx: "pierce",
          hitstun: 26,
          shake: 1.8,
        }),
        hit(9, 16, bx(4, 70, 56, 66), 40, { group: 2, launch: [1.6, 6], fx: "pierce", hitstun: 18 }),
      ],
      desc: "Invincible rising thrust. Your reversal and your anti-air of last resort.",
      notation: "→↓↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 50, hipB: -20, kneeB: 54 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -16, shoulderF: 156, elbowF: -22, weapon: -30, hipF: 30, kneeF: 30, hipB: -26, kneeB: 40 }, "out"),
        kf(12, { ...STANCE, free: 1, torso: -22, shoulderF: 172, elbowF: -4, weapon: -34, hipF: 26, kneeF: 26, hipB: -22, kneeB: 34 }),
        kf(30, { ...STANCE, free: 1, torso: -4, shoulderF: 120, elbowF: -20, weapon: 48, hipF: 30, kneeF: 40, hipB: -20, kneeB: 40 }, "inOut"),
        kf(46, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "skywardEx",
      name: "Skyward Spear EX",
      input: { button: "S", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "launcher"],
      priority: 30,
      duration: 52,
      meterCost: 50,
      airborne: true,
      invuln: [{ from: 1, to: 14, kind: "strike" }],
      vel: [
        { at: 1, x: 3, y: 14 },
        { at: 30, y: -1, mode: "add" },
      ],
      hits: [
        hit(3, 8, bx(6, 58, 68, 84), 74, { launch: [2, 12], knockdown: "launch", fx: "pierce", hitstun: 28, shake: 2 }),
        hit(10, 18, bx(4, 70, 62, 78), 34, { group: 2, launch: [1.4, 5], fx: "pierce" }),
        hit(19, 26, bx(4, 80, 60, 70), 46, { group: 3, launch: [2, 4], fx: "pierce", knockdown: "hard" }),
      ],
      desc: "EX. Fully invincible, higher, and it carries them up with you.",
      notation: "→↓↘ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 50 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -18, shoulderF: 160, elbowF: -20, weapon: 38, spin: -6 }, "out"),
        kf(14, { ...STANCE, free: 1, torso: -26, shoulderF: 172, elbowF: -14, weapon: 32, spin: -16 }),
        kf(34, { ...STANCE, free: 1, torso: -6, shoulderF: 124, elbowF: -18, weapon: 46, spin: 0 }, "inOut"),
        kf(52, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "testudo",
      name: "Testudo",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill", "stance"],
      priority: 18,
      duration: 30,
      armor: [{ from: 4, to: 24, hits: 2, damageScale: 0.25 }],
      friction: 0.9,
      holdLoop: { from: 10, to: 20, button: "S", maxFrames: 90 },
      holdRelease: "testudoBash",
      // Bracing is where he re-arms: a Roman line passed fresh pila forward to
      // the front rank, and behind the scutum is the only moment he has both
      // hands free. Only the brace gives them back - hold Guard and release
      // into the bash and you have spent the moment attacking instead, which
      // is the choice the stance is for.
      resourceGain: 2,
      desc: "SKILL. Shield stance - absorbs two hits and comes up with fresh pila, then bashes out of it. Hold Guard to stay in the shell longer.",
      notation: "A + C, hold S",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -4, shoulderB: 92, elbowB: 10, shoulderF: 30, elbowF: 30, crouch: 0.35, hipF: 22, kneeF: 44, hipB: -18, kneeB: 48, weapon: 10 }),
        kf(10, { ...STANCE, torso: -6, shoulderB: 96, elbowB: 6, shoulderF: 28, elbowF: 32, crouch: 0.4, hipF: 22, kneeF: 46, hipB: -18, kneeB: 50, weapon: 8 }),
        kf(20, { ...STANCE, torso: -4, shoulderB: 94, elbowB: 8, shoulderF: 30, elbowF: 30, crouch: 0.38, hipF: 22, kneeF: 44, hipB: -18, kneeB: 48, weapon: 10 }),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "testudoBash",
      name: "Testudo Bash",
      input: { stance: "stand" },
      tags: ["skill"],
      internal: true,
      duration: 30,
      vel: [{ at: 3, x: 6 }],
      friction: 0.88,
      hits: [
        hit(6, 10, bx(22, 30, 62, 58), 78, {
          fx: "blunt",
          pushX: 8,
          knockdown: "hard",
          hitstun: 24,
          shake: 1.7,
        }),
      ],
      desc: "",
      frames: [
        kf(0, { ...STANCE, torso: -6, shoulderB: 96, elbowB: 6, crouch: 0.4 }, "out"),
        kf(6, { ...STANCE, torso: 26, shoulderB: 92, elbowB: 0, hipF: 38, kneeF: 22, hipB: -22, kneeB: 48, offX: 8 }, "out"),
        kf(14, { ...STANCE, torso: 20, shoulderB: 80, elbowB: 16, offX: 5 }),
        kf(30, { ...STANCE }),
      ],
    },

    {
      id: "stomp",
      name: "Aquila Stomp",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "projectile", "low"],
      priority: 20,
      duration: 42,
      resourceCost: 1,
      resourceMin: 1,
      friction: 0.9,
      projectiles: [
        {
          at: 14,
          kind: "shock",
          armAfter: 0,
          x: 34,
          y: 8,
          vx: 8.5,
          vy: 0,
          life: 60,
          box: { x: -18, y: -8, w: 36, h: 30 },
          damage: 54,
          hitstun: 22,
          blockstun: 14,
          guard: "low",
          chip: 5,
          pushX: 6,
          knockdown: "sweep",
          fx: "blunt",
          color: "#d9a441",
          trail: "#8a744f",
          scale: 1,
        },
      ],
      vfx: [{ at: 14, kind: "dust", x: 30, y: 2, scale: 1.6 }],
      desc: "Drives the spear butt into the ground and sends a shockwave along the floor. Must be blocked low.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 150, elbowF: -40, weapon: 96, torso: -16, hipB: -26, kneeB: 38, offX: -4 }, "inOut"),
        kf(14, { ...STANCE, crouch: 0.85, shoulderF: 20, elbowF: 34, weapon: -66, torso: 34, hipF: 42, kneeF: 76, hipB: -26, kneeB: 90, offX: 5 }, "out"),
        kf(24, { ...STANCE, crouch: 0.6, shoulderF: 34, elbowF: 20, weapon: -40, torso: 26 }),
        kf(42, { ...STANCE }),
      ],
    },
    {
      id: "vault",
      name: "Spear Vault",
      input: { button: "C", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "overhead"],
      priority: 22,
      duration: 46,
      airborne: true,
      vel: [
        { at: 4, x: 7, y: 10.5 },
        { at: 22, y: -0.6, mode: "add" },
      ],
      hits: [
        hit(16, 24, bx(14, 8, 62, 54), 84, {
          guard: "overhead",
          fx: "blunt",
          pushX: 7,
          knockdown: "hard",
          hitstun: 24,
          shake: 1.7,
        }),
      ],
      desc: "Vaults over the spear and comes down boots first. Overhead - crushes crouching blocks.",
      notation: "↓↙← + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5, hipF: 22, kneeF: 44 }, "out"),
        kf(6, { ...STANCE, free: 1, torso: 16, shoulderF: 30, elbowF: 10, weapon: -70, hipF: -20, kneeF: 70, hipB: -34, kneeB: 60 }, "out"),
        kf(16, { ...STANCE, free: 1, torso: 26, shoulderF: 10, elbowF: 30, weapon: -80, hipF: 86, kneeF: 10, hipB: -30, kneeB: 48 }, "out"),
        kf(30, { ...STANCE, free: 1, torso: 20, shoulderF: 26, elbowF: 24, weapon: -60, hipF: 60, kneeF: 30, hipB: -24, kneeB: 44 }, "inOut"),
        kf(46, { ...STANCE, free: 1 }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "Legion's Wrath",
      input: { button: "S", motion: "dd", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 96,
      meterCost: 100,
      superFreeze: 40,
      invuln: [{ from: 1, to: 12, kind: "strike" }],
      vel: [
        { at: 6, x: 8 },
        { at: 30, x: 5 },
        { at: 54, x: 3 },
        { at: 70, x: 0 },
      ],
      friction: 0.94,
      hits: [
        hit(12, 16, bx(24, 40, 84, 46), 60, { group: 1, fx: "pierce", pushX: 1, hitstun: 22, hitstop: 6 }),
        hit(24, 28, bx(24, 40, 88, 46), 46, { group: 2, fx: "pierce", pushX: 1, hitstun: 20, hitstop: 5 }),
        hit(36, 40, bx(24, 34, 92, 52), 46, { group: 3, fx: "pierce", pushX: 1, hitstun: 20, hitstop: 5 }),
        hit(48, 52, bx(24, 34, 92, 52), 46, { group: 4, fx: "pierce", pushX: 1, hitstun: 20, hitstop: 5 }),
        hit(62, 68, bx(18, 20, 96, 78), 130, {
          group: 5,
          fx: "slash",
          pushX: 11,
          knockdown: "hard",
          launch: [6, 9],
          hitstop: 16,
          shake: 3,
        }),
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 50, scale: 2.4, color: "#ffb648" },
        { at: 62, kind: "explode", x: 60, y: 50, scale: 1.4 },
      ],
      desc: "SUPER. Charges the length of the arena with a storm of thrusts, ending in a shield-driven finisher.",
      notation: "↓↓ + S  (100 meter)",
      frames: [
        kf(0, { ...STANCE, torso: -14, shoulderF: 46, elbowF: -30, weapon: 54, crouch: 0.4 }, "out"),
        kf(8, { ...STANCE, torso: 24, shoulderF: 84, elbowF: -4, weapon: 0, hipF: 40, kneeF: 22, offX: 6 }, "out"),
        kf(12, { ...STANCE, torso: 26, shoulderF: 88, elbowF: 0, weapon: -4, hipF: 42, kneeF: 20, offX: 8 }),
        kf(20, { ...STANCE, torso: 16, shoulderF: 52, elbowF: -30, weapon: 56, hipF: 20, kneeF: 34 }, "inOut"),
        kf(24, { ...STANCE, torso: 26, shoulderF: 88, elbowF: 0, weapon: 0, hipF: 42, kneeF: 20, offX: 8 }, "out"),
        kf(32, { ...STANCE, torso: 16, shoulderF: 52, elbowF: -30, weapon: 58, hipF: 20, kneeF: 34 }, "inOut"),
        kf(36, { ...STANCE, torso: 28, shoulderF: 92, elbowF: 2, weapon: -4, hipF: 44, kneeF: 20, offX: 9 }, "out"),
        kf(44, { ...STANCE, torso: 16, shoulderF: 56, elbowF: -22, weapon: 50, hipF: 20, kneeF: 34 }, "inOut"),
        kf(48, { ...STANCE, torso: 28, shoulderF: 92, elbowF: 2, weapon: -14, hipF: 44, kneeF: 20, offX: 9 }, "out"),
        kf(58, { ...STANCE, torso: -20, shoulderF: 150, elbowF: -30, shoulderB: 130, elbowB: -10, weapon: 80, hipB: -30, kneeB: 46, offX: -4 }, "inOut"),
        kf(62, { ...STANCE, torso: 34, shoulderF: 30, elbowF: 16, shoulderB: 40, elbowB: 12, weapon: -6, hipF: 46, kneeF: 26, hipB: -24, kneeB: 54, offX: 10 }, "out"),
        kf(78, { ...STANCE, torso: 24, shoulderF: 44, elbowF: 4, offX: 6 }, "inOut"),
        kf(96, { ...STANCE }),
      ],
    },
  ],
};
