/**
 * Kaede Rin - ronin.
 *
 * Everything is about the draw. Her katana spends most of the round in its
 * scabbard, and the moves that matter are the ones that take it out: long,
 * committal, and devastating if you guess right. Spends Ki to do it.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const STEEL = "#e2e8f0";
const LACQUER = "#1d2733";
const CRIMSON = "#b3323c";
const GOLD = "#d9b25a";

const STANCE = {
  torso: 3,
  head: -2,
  hipF: 13,
  kneeF: 13,
  hipB: -18,
  kneeB: 28,
  // Left hand rests on the scabbard, right hand hovers at the hilt.
  shoulderF: 44,
  elbowF: 36,
  shoulderB: 34,
  elbowB: 40,
  weapon: 26,
};

export const SAMURAI: FighterDef = {
  id: "samurai",
  name: "Tomoe Gozen",
  title: "Of Yoshinaka's Household",
  era: "Awazu, 1184",
  bio: "The Heike Monogatari calls her a match for a thousand, fit to meet god or demon, and has her taking a head at Awazu before Yoshinaka sent her away so he could die alone.",
  archetype: "Footsies / Counter",
  difficulty: 5,
  strengths: ["Enormous sword reach", "Counter stance beats anything", "Highest single-hit damage"],
  weaknesses: ["Ki-hungry specials", "Punishable whiffs", "No real projectile"],
  winQuote: "He told me to go. He did not tell me to stop.",
  palette: {
    body: "#f0ece2",
    outline: "#161a20",
    accent: CRIMSON,
    cloth: LACQUER,
    metal: STEEL,
    aura: "#9fe8ff",
  },
  stats: {
    health: 960,
    walkF: 2.85,
    walkB: 2.45,
    dashSpeed: 8.2,
    dashFrames: 15,
    backdashFrames: 20,
    jumpVel: 12.6,
    jumpFwd: 4.9,
    gravity: 0.63,
    weight: 0.97,
    airMoves: 2,
    doubleJump: false,
    airDash: false,
    width: 19,
    standHeight: 104,
    crouchHeight: 66,
    scale: 1,
  },
  stance: STANCE,
  // Hilt above the head, blade angled down across the line - a receiving
  // guard, not a static block.
  clips: guardClips({
    high: { torso: 0, head: -6, shoulderF: 134, elbowF: 26, weapon: 96, shoulderB: 108, elbowB: 44, hipF: 13, kneeF: 20, hipB: -18, kneeB: 32, offX: -2 },
    low: { torso: 8, head: -5, shoulderF: 126, elbowF: 30, weapon: 88, shoulderB: 102, elbowB: 46, hipF: 32, kneeF: 72, hipB: -20, kneeB: 82, offX: -2 },
  }),
  resource: {
    name: "Ki",
    max: 3,
    start: 3,
    regen: 0.0045,
    color: "#9fe8ff",
    pips: true,
  },
  props: [
    {
      id: "kabuto",
      attach: "head",
      // Kabuto: lacquered bowl, a flared neck guard, a gold crescent maedate
      // and a demon mask over the lower face.
      parts: [
        { geo: "poly", size: [-11, -4, -11, 4, -6, 11, 0, 13, 6, 11, 11, 4, 11, -4], pos: [0, 2], color: LACQUER },
        { geo: "box", size: [2.5, 16], pos: [0, 4], color: "#33465c" },
        { geo: "box", size: [24, 4], pos: [0, -3], rot: -4, color: "#33465c" },
        // Shikoro: the lamellar neck guard flaring out behind.
        { geo: "poly", size: [4, 2, -4, -4, -14, -9, -16, -1, -8, 4], pos: [-8, -5], color: LACQUER, behind: true },
        { geo: "box", size: [16, 2], pos: [-14, -9], rot: 18, color: CRIMSON, behind: true },
        // Maedate: a gilt crescent standing off the brow.
        { geo: "poly", size: [0, 0, -6, 10, -3, 18, 0, 12, 3, 18, 6, 10], pos: [1, 12], color: GOLD },
        { geo: "poly", size: [0, 0, -3, 7, 0, 11, 3, 7], pos: [1, 13], color: "#f0d68e" },
        // Mempo: the snarling half-mask.
        { geo: "poly", size: [-5, 6, 6, 5, 8, -3, 3, -8, -5, -6], pos: [6, -6], color: CRIMSON, z: 0.9 },
        { geo: "box", size: [9, 1.6], pos: [7, -6], color: "#e8e2d2", z: 0.92 },
      ],
    },
    {
      id: "katana",
      attach: "handF",
      // Katana: a long shallow curve with a hardened edge, a round tsuba and a
      // wrapped tsuka.
      parts: [
        { geo: "blade", size: [86, 6, 0.3], pos: [50, 3], rot: 4, color: "#9aa7b5" },
        { geo: "poly", size: [-42, 2.4, 42, 1.6, 44, -0.6, -42, -0.8], pos: [50, 4], rot: 4, color: STEEL },
        { geo: "disc", size: [5.4], pos: [4, 0], color: GOLD },
        { geo: "disc", size: [3], pos: [4, 0], color: "#8a6a2f", z: 0.1 },
        { geo: "cyl", size: [2.4, 22], pos: [-10, -1], rot: 90, color: LACQUER },
        // Ito wrap: diamonds down the grip.
        { geo: "poly", size: [-3, 3, 3, 3, 3, -3, -3, -3], pos: [-4, -1], rot: 45, color: "#4a5c72" },
        { geo: "poly", size: [-3, 3, 3, 3, 3, -3, -3, -3], pos: [-11, -1], rot: 45, color: "#4a5c72" },
        { geo: "poly", size: [-3, 3, 3, 3, 3, -3, -3, -3], pos: [-18, -1], rot: 45, color: "#4a5c72" },
        { geo: "box", size: [4, 7], pos: [-22, -1], color: GOLD },
      ],
    },
    {
      id: "saya",
      attach: "pelvis",
      parts: [
        { geo: "cyl", size: [3.4, 76], pos: [-16, 4], rot: 74, color: LACQUER, behind: true },
        { geo: "box", size: [8, 5], pos: [4, 12], rot: 74, color: GOLD, behind: true },
        { geo: "box", size: [6, 4], pos: [-32, -8], rot: 74, color: GOLD, behind: true },
        // Obi with the knot at the hip.
        { geo: "poly", size: [-12, 4, 12, 3, 12, -4, -12, -3], pos: [-2, 0], rot: -8, color: CRIMSON },
        { geo: "poly", size: [-5, 5, 5, 4, 4, -5, -5, -4], pos: [-11, -1], color: "#8f2530" },
      ],
    },
    {
      id: "sode",
      attach: "torso",
      // Do-maru: lacquered lamellar laced in crimson, with a big shoulder plate.
      parts: [
        { geo: "poly", size: [-13, -16, 13, -16, 14, 6, 10, 16, -10, 16, -14, 6], pos: [0, 3], color: LACQUER },
        { geo: "box", size: [26, 2], pos: [0, 12], color: CRIMSON },
        { geo: "box", size: [26, 2], pos: [0, 6], color: CRIMSON },
        { geo: "box", size: [25, 2], pos: [0, 0], color: CRIMSON },
        { geo: "box", size: [24, 2], pos: [0, -6], color: CRIMSON },
        { geo: "box", size: [23, 2], pos: [0, -12], color: CRIMSON },
        { geo: "box", size: [2, 32], pos: [-4, 0], color: "#33465c" },
        { geo: "box", size: [2, 32], pos: [4, 0], color: "#33465c" },
        // Sode: the rectangular shoulder guard hanging off a cord.
        { geo: "poly", size: [-10, 12, 10, 13, 11, -10, -11, -11], pos: [-7, 14], rot: 8, color: LACQUER },
        { geo: "box", size: [21, 2.5], pos: [-7, 20], rot: 8, color: GOLD },
        { geo: "box", size: [20, 2], pos: [-7, 13], rot: 8, color: CRIMSON },
        { geo: "poly", size: [-9, 17, 9, 15, 7, -17, -8, -16], pos: [-11, -12], rot: 4, color: "#2b3948", behind: true },
      ],
    },
    {
      id: "hakama",
      attach: "pelvis",
      parts: [
        { geo: "poly", size: [-6, 12, 6, 12, 5, -12, -5, -12], pos: [-8, -11], rot: 4, color: "#2b3948", behind: true },
        { geo: "poly", size: [-6, 12, 6, 12, 5, -12, -5, -12], pos: [7, -11], rot: -4, color: "#33465c", behind: true },
      ],
      cloth: {
        segments: 3,
        segmentLength: 9,
        width: 19,
        endWidth: 13,
        color: "#2b3948",
        gravity: 0.5,
        stiffness: 0.55,
        drift: -0.24,
      },
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 118,
      backThrowDamage: 130,
      throwRange: 60,
      rollSpeed: 8.2,
      weaponIdle: { weapon: STANCE.weapon },
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Tsuka Strike",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 13,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 12],
      hits: [hit(4, 6, bx(18, 52, 44, 22), 32, { fx: "blunt", hitstun: 14, blockstun: 10, pushX: 3 })],
      desc: "Jab with the sword hilt - the blade never leaves the scabbard. Fast and cancellable.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderB: 88, elbowB: 8, torso: 12, offX: 3 }),
        kf(9, { ...STANCE, shoulderB: 46, elbowB: 34, torso: 6 }, "inOut"),
        kf(13, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Kesa Cut",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 22,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [8, 20],
      hits: [hit(8, 11, bx(24, 44, 78, 42), 56, { fx: "slash", pushX: 4.6, hitstun: 18 })],
      desc: "Diagonal shoulder-to-hip cut with real reach. Her main poke.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderF: 168, elbowF: -26, weapon: 30, torso: -10, offX: -3 }),
        kf(8, { ...STANCE, shoulderF: 62, elbowF: 6, weapon: -18, torso: 22, hipF: 28, offX: 7 }, "out"),
        kf(15, { ...STANCE, shoulderF: 54, elbowF: 16, weapon: -26, torso: 14 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Overhead Split",
      input: { button: "C", stance: "stand" },
      tags: ["heavy"],
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [14, 28],
      hits: [
        hit(14, 18, bx(18, 24, 84, 78), 94, {
          fx: "slash",
          pushX: 6.5,
          knockdown: "hard",
          hitstun: 24,
          shake: 1.8,
        }),
      ],
      desc: "Two-handed vertical cut, straight down. Huge damage, huge commitment.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderF: 184, elbowF: -12, shoulderB: 172, elbowB: -8, weapon: 20, torso: -18, hipB: -26, kneeB: 40, offX: -4 }, "inOut"),
        kf(14, { ...STANCE, shoulderF: 34, elbowF: 10, shoulderB: 40, elbowB: 8, weapon: -30, torso: 32, hipF: 36, kneeF: 26, hipB: -20, kneeB: 44, offX: 7 }, "out"),
        kf(22, { ...STANCE, shoulderF: 30, elbowF: 14, weapon: -26, torso: 28, offX: 5 }),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Hilt",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 13,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 12],
      hits: [hit(4, 6, bx(16, 14, 44, 22), 28, { guard: "low", fx: "blunt", hitstun: 13, blockstun: 10, pushX: 2.8 })],
      desc: "Quick low knock with the pommel. Opens up a standing guard.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 24, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderB: 84, elbowB: 24, offX: 4 }),
        kf(9, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderB: 40, elbowB: 40 }, "inOut"),
        kf(13, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "2B",
      name: "Grass Cutter",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 24,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [9, 22],
      hits: [hit(9, 12, bx(20, 6, 82, 26), 54, { guard: "low", fx: "slash", pushX: 4.4, hitstun: 17 })],
      desc: "Long low sweep of the blade. Must be blocked crouching.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(5, { ...STANCE, crouch: 1, torso: 8, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderF: -22, elbowF: 84, weapon: 40 }),
        kf(9, { ...STANCE, crouch: 1, torso: 26, hipF: 40, kneeF: 78, hipB: -26, kneeB: 88, shoulderF: 100, elbowF: 40, weapon: -54, offX: 8 }, "out"),
        kf(17, { ...STANCE, crouch: 1, torso: 20, hipF: 36, kneeF: 76, hipB: -22, kneeB: 86, shoulderF: 74, elbowF: 46, weapon: -30 }, "inOut"),
        kf(24, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "2C",
      name: "Ankle Reap",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 30,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 26],
      hits: [hit(11, 15, bx(18, 2, 88, 24), 76, { guard: "low", knockdown: "sweep", fx: "slash", pushX: 6 })],
      desc: "Full-extension sweep. Knockdown into her okizeme.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(6, { ...STANCE, crouch: 1, torso: 4, hipF: 30, kneeF: 70, hipB: -30, kneeB: 92, shoulderF: -34, elbowF: 92, weapon: 56 }),
        kf(11, { ...STANCE, crouch: 1, torso: 30, hipF: 46, kneeF: 84, hipB: -30, kneeB: 96, shoulderF: 108, elbowF: 36, weapon: -64, offX: 8 }, "out"),
        kf(20, { ...STANCE, crouch: 1, torso: 24, hipF: 42, kneeF: 80, hipB: -26, kneeB: 90, shoulderF: 82, elbowF: 42, weapon: -36 }, "inOut"),
        kf(30, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "6B",
      name: "Rising Knee",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "overhead"],
      priority: 10,
      duration: 30,
      vel: [{ at: 5, x: 3.2 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [14, 26],
      hits: [hit(13, 17, bx(20, 36, 54, 48), 58, { guard: "overhead", fx: "blunt", pushX: 5, hitstun: 20 })],
      desc: "Hopping knee that must be blocked standing. Her only fast overhead.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, crouch: 0.45, torso: 12, hipF: 18, kneeF: 58 }),
        kf(10, { ...STANCE, free: 1, offY: 14, torso: -4, hipF: -22, kneeF: 76, hipB: -30, kneeB: 58 }, "out"),
        kf(13, { ...STANCE, free: 1, offY: 8, torso: 20, hipF: 90, kneeF: 96, hipB: -26, kneeB: 66, offX: 4 }, "out"),
        kf(20, { ...STANCE, offY: 0, torso: 14, hipF: 44, kneeF: 48 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Rising Moon",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [11, 28],
      hits: [hit(8, 12, bx(12, 48, 62, 76), 72, { launch: [2, 12.5], knockdown: "launch", fx: "slash", hitstun: 26 })],
      desc: "Upward arc that launches. Follow into air normals for the juggle.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5, hipF: 26, kneeF: 46 }, "out"),
        kf(5, { ...STANCE, crouch: 0.7, shoulderF: -26, elbowF: 88, weapon: -27, torso: 14 }),
        kf(8, { ...STANCE, torso: -18, shoulderF: 156, elbowF: -14, weapon: 9, hipF: 22, kneeF: 12, offY: 4 }, "out"),
        kf(16, { ...STANCE, torso: -12, shoulderF: 144, elbowF: -10, weapon: 90 }),
        kf(24, { ...STANCE, torso: 2, shoulderF: 60, elbowF: 30, weapon: -30 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },
    {
      // Forward and back sets. Forward takes space, back gives it up to buy
      // range or a hard read.
      id: "6A",
      name: "Tsuki",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 20,
      vel: [{ at: 2, x: 2.2 }],
      friction: 0.88,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [7, 18],
      hits: [hit(7, 9, bx(20, 60, 44, 26), 32, { guard: "high", fx: "pierce", pushX: 3, hitstun: 14, hitstop: 5 })],
      desc: "A short step and a straight thrust off the hip. Her quickest opening.",
      notation: "\u2192 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 30, elbowF: 62, weapon: 56, torso: -2, offX: -2 }, "out"),
        // Point driven straight down the line; the weapon angle unwinds with
        // the elbow so the blade stays level rather than swinging up.
        kf(7, { ...STANCE, shoulderF: 84, elbowF: 4, weapon: 4, torso: 14, hipF: 24, kneeF: 14, offX: 7 }, "out"),
        kf(12, { ...STANCE, shoulderF: 68, elbowF: 24, weapon: 24, torso: 10, offX: 5 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Kesa Giri",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 40,
      armor: [{ from: 8, to: 18, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 8, x: 5.4 }, { at: 26, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [20, 36],
      hits: [hit(16, 20, bx(18, 22, 64, 68), 92, { guard: "mid", fx: "slash", pushX: 17, hitstun: 24, hitstop: 12, knockdown: "wallbounce", shake: 2.2 })],
      desc: "Steps through with the full diagonal cut, collarbone to hip.",
      notation: "\u2192 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 158, elbowF: -44, weapon: 130, torso: -12, hipB: -30, kneeB: 48, offX: -6 }, "out"),
        kf(16, { ...STANCE, shoulderF: 62, elbowF: 34, weapon: 23, torso: 32, hipF: 40, kneeF: 16, hipB: -26, kneeB: 24, offX: 12 }, "out"),
        kf(24, { ...STANCE, shoulderF: 54, elbowF: 42, weapon: -54, torso: 24, hipF: 28, kneeF: 22, offX: 8 }),
        kf(32, { ...STANCE, shoulderF: 50, elbowF: 40, weapon: 30, torso: 10, offX: 3 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Tsuka Check",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 22,
      vel: [{ at: 1, x: -2.6 }],
      friction: 0.86,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [8, 20],
      hits: [hit(8, 10, bx(16, 52, 42, 30), 36, { guard: "mid", fx: "blunt", pushX: 6, hitstun: 15, hitstop: 6 })],
      desc: "Slips back and cracks them with the hilt. Made for punishing a whiff.",
      notation: "\u2190 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -6, shoulderF: 24, elbowF: 80, weapon: 74, hipB: -26, kneeB: 40, offX: -6 }, "out"),
        kf(8, { ...STANCE, torso: 8, shoulderF: 70, elbowF: 24, weapon: 96, hipF: 22, kneeF: 16, offX: -3 }, "out"),
        kf(14, { ...STANCE, torso: 2, shoulderF: 56, elbowF: 44, weapon: 60, offX: -4 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Kiriage",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 30,
      vel: [{ at: 1, x: -3.4 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      hits: [hit(12, 15, bx(26, 44, 82, 46), 56, { guard: "mid", fx: "slash", pushX: 7, hitstun: 18, hitstop: 8 })],
      desc: "Draws back and cuts upward from low guard. Her counter to anything reaching in.",
      notation: "\u2190 + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        // Blade dropped to gedan, then the rising cut.
        kf(6, { ...STANCE, shoulderF: 16, elbowF: 44, weapon: -46, torso: -12, hipB: -28, kneeB: 42, offX: -8 }, "inOut"),
        kf(12, { ...STANCE, shoulderF: 104, elbowF: -14, weapon: 32, torso: 4, hipF: 24, kneeF: 12, offX: -5 }, "out"),
        kf(17, { ...STANCE, shoulderF: 110, elbowF: -18, weapon: 36, torso: 2, offX: -6 }),
        kf(23, { ...STANCE, shoulderF: 72, elbowF: 22, weapon: 34, torso: 0, offX: -4 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Men Uchi",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 44,
      cancelInto: ["special", "super"],
      cancelWindow: [26, 40],
      hits: [hit(20, 23, bx(14, 20, 70, 86), 104, { guard: "overhead", fx: "slash", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 })],
      desc: "Raises to jodan and cuts straight down through the head. Blocked standing only.",
      notation: "\u2190 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 146, elbowF: -40, weapon: 90, torso: -10, offX: -5 }, "inOut"),
        // Jodan: both hands above the brow, blade vertical.
        kf(15, { ...STANCE, shoulderF: 178, elbowF: -14, weapon: 94, torso: -20, hipB: -26, kneeB: 38, offY: 3, offX: -3 }, "out"),
        kf(20, { ...STANCE, shoulderF: 84, elbowF: 12, weapon: 66, torso: 32, hipF: 34, kneeF: 16, hipB: -12, kneeB: 32, offX: 6 }, "out"),
        kf(26, { ...STANCE, shoulderF: 76, elbowF: 16, weapon: 62, torso: 26, offX: 4 }),
        kf(36, { ...STANCE, shoulderF: 56, elbowF: 40, weapon: 40, torso: 8 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Slice",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 18,
      airborne: true,
      landCancel: true,
      landRecovery: 2,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [4, 16],
      hits: [hit(4, 9, bx(16, 32, 52, 30), 34, { fx: "slash", hitstun: 14, pushX: 2.8 })],
      desc: "Quick air cut. Starts air strings after a launcher.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, weapon: 159, free: 1, hipF: 32, kneeF: 42, hipB: -22, kneeB: 40 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderF: 96, elbowF: 10, weapon: 20, torso: 12 }),
        kf(11, { ...STANCE, free: 1, shoulderF: 54, elbowF: 40, weapon: -46, torso: 6 }, "inOut"),
        kf(18, { ...STANCE, free: 1, hipF: 32, kneeF: 42, hipB: -22, kneeB: 40 }),
      ],
    },
    {
      id: "jB",
      name: "Air Kesa",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 24,
      airborne: true,
      landCancel: true,
      landRecovery: 4,
      cancelInto: ["heavy", "special"],
      cancelWindow: [8, 22],
      hits: [hit(6, 12, bx(18, 14, 74, 52), 58, { fx: "slash", pushX: 4, hitstun: 18 })],
      desc: "Wide diagonal cut with the reach to catch anyone in the air.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 30, kneeF: 40, hipB: -22, kneeB: 38 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderF: 172, elbowF: -20, weapon: 34, torso: -12 }),
        kf(7, { ...STANCE, free: 1, shoulderF: 74, elbowF: 12, weapon: -34, torso: 22, hipF: 36, kneeF: 34 }, "out"),
        kf(16, { ...STANCE, free: 1, shoulderF: 60, elbowF: 24, weapon: -40, torso: 14 }, "inOut"),
        kf(24, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "jC",
      name: "Falling Crane",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 28,
      airborne: true,
      landCancel: true,
      landRecovery: 7,
      hits: [
        hit(8, 18, bx(2, -4, 66, 50), 82, {
          guard: "overhead",
          fx: "slash",
          knockdown: "soft",
          pushX: 5,
          shake: 1.5,
        }),
      ],
      desc: "Blade held straight down through the whole descent. Her jump-in.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, torso: -20, shoulderF: 178, elbowF: -14, weapon: 26, hipF: 40, kneeF: 56 }),
        kf(9, { ...STANCE, free: 1, torso: 28, shoulderF: 24, elbowF: 14, weapon: -40, hipF: 16, kneeF: 22 }, "out"),
        kf(28, { ...STANCE, free: 1, torso: 22, shoulderF: 28, elbowF: 18, weapon: -36 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Running Cut",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command"],
      priority: 12,
      duration: 34,
      vel: [
        { at: 3, x: 10.5 },
        { at: 16, x: 0 },
      ],
      friction: 0.9,
      hits: [hit(9, 15, bx(20, 28, 74, 58), 76, { fx: "slash", pushX: 7.5, knockdown: "soft", hitstun: 22, shake: 1.5 })],
      desc: "Sprints past with the blade extended. Covers half the screen.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 26, shoulderF: -30, elbowF: 90, weapon: 60, hipB: -34, kneeB: 50, offX: -3 }),
        kf(9, { ...STANCE, torso: 30, shoulderF: 96, elbowF: 16, weapon: -46, hipF: 44, kneeF: 24, hipB: -28, kneeB: 56, offX: 8 }, "out"),
        kf(22, { ...STANCE, torso: 20, shoulderF: 64, elbowF: 30, weapon: -30, offX: 4 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },

    // -------------------------------------------------------- five specials
    {
      id: "iai",
      name: "Iai Draw",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      duration: 40,
      resourceCost: 1,
      resourceMin: 1,
      vel: [
        { at: 10, x: 7.5 },
        { at: 22, x: 0 },
      ],
      friction: 0.88,
      invuln: [{ from: 8, to: 14, kind: "projectile" }],
      hits: [
        hit(12, 16, bx(16, 20, 118, 64), 96, {
          fx: "slash",
          pushX: 8,
          knockdown: "hard",
          hitstun: 26,
          hitstop: 12,
          shake: 2,
        }),
      ],
      vfx: [{ at: 12, kind: "slash", x: 70, y: 52, scale: 1.6, color: "#9fe8ff" }],
      desc: "Steps through the opponent and draws in one motion. Enormous range, cuts through fireballs.",
      notation: "↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, torso: -12, shoulderF: 6, elbowF: 84, shoulderB: -10, elbowB: 70, weapon: -78, offX: -4 }, "inOut"),
        kf(12, { ...STANCE, torso: 26, shoulderF: 104, elbowF: -12, shoulderB: 40, elbowB: 20, weapon: -30, hipF: 42, kneeF: 22, hipB: -26, kneeB: 54, offX: 10 }, "out"),
        kf(22, { ...STANCE, torso: 18, shoulderF: 88, elbowF: -4, weapon: -20, offX: 6 }),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "tsubame",
      name: "Swallow Cut",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 24,
      duration: 46,
      resourceCost: 1,
      resourceMin: 1,
      airborne: true,
      invuln: [{ from: 1, to: 8, kind: "strike" }],
      vel: [
        { at: 1, x: 2.6, y: 13 },
        { at: 26, y: -0.9, mode: "add" },
      ],
      hits: [
        hit(3, 8, bx(8, 50, 62, 84), 78, { launch: [2, 11], knockdown: "launch", fx: "slash", hitstun: 26, shake: 1.8 }),
        hit(9, 16, bx(6, 64, 58, 72), 38, { group: 2, launch: [1.6, 5], fx: "slash" }),
      ],
      desc: "Invincible rising cut. Reversal, anti-air and juggle starter.",
      notation: "→↓↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 48 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -14, shoulderF: 150, elbowF: -16, weapon: 20, hipF: 30, kneeF: 30 }, "out"),
        kf(14, { ...STANCE, free: 1, torso: -22, shoulderF: 174, elbowF: -8, weapon: 12, hipF: 26, kneeF: 26 }),
        kf(32, { ...STANCE, free: 1, torso: -4, shoulderF: 110, elbowF: 4, weapon: -20 }, "inOut"),
        kf(46, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "kamae",
      name: "Kamae Stance",
      input: { button: "C", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "stance"],
      priority: 22,
      duration: 34,
      friction: 0.9,
      parryWindow: [3, 22],
      holdLoop: { from: 12, to: 22, button: "C", maxFrames: 80 },
      holdRelease: "kamaeCut",
      desc: "Reads the attack instead of blocking it. Any strike caught here is deflected - release Heavy for the answer.",
      notation: "↓↙← + C (hold)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: -6, shoulderF: 128, elbowF: -40, shoulderB: 96, elbowB: -20, weapon: 30, hipF: 18, kneeF: 30, hipB: -22, kneeB: 42 }),
        kf(12, { ...STANCE, torso: -8, shoulderF: 132, elbowF: -44, shoulderB: 100, elbowB: -24, weapon: 32, hipF: 18, kneeF: 32, hipB: -22, kneeB: 44 }),
        kf(22, { ...STANCE, torso: -6, shoulderF: 128, elbowF: -40, shoulderB: 96, elbowB: -20, weapon: 30 }),
        kf(34, { ...STANCE }),
      ],
    },
    {
      id: "kamaeCut",
      name: "Kamae - Answer",
      input: { stance: "stand" },
      tags: ["special"],
      internal: true,
      duration: 32,
      vel: [{ at: 2, x: 8 }],
      friction: 0.86,
      hits: [
        hit(5, 10, bx(18, 22, 96, 60), 104, {
          fx: "slash",
          pushX: 9,
          knockdown: "hard",
          hitstun: 28,
          hitstop: 13,
          shake: 2.2,
        }),
      ],
      desc: "",
      frames: [
        kf(0, { ...STANCE, torso: -8, shoulderF: 130, elbowF: -42, weapon: 32 }, "out"),
        kf(5, { ...STANCE, torso: 30, shoulderF: 52, elbowF: 8, weapon: -34, hipF: 44, kneeF: 24, hipB: -26, kneeB: 54, offX: 10 }, "out"),
        kf(16, { ...STANCE, torso: 20, shoulderF: 46, elbowF: 18, weapon: -34, offX: 5 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "shadowStep",
      name: "Shadow Step",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "movement"],
      priority: 20,
      duration: 30,
      invuln: [{ from: 3, to: 16, kind: "strike" }],
      noTurn: true,
      vel: [
        { at: 2, x: 13 },
        { at: 18, x: 0 },
      ],
      friction: 0.8,
      desc: "Slides straight through the opponent, untouchable. No damage - it is entirely about where you end up.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 30, squash: 0.9, hipF: 40, kneeF: 30, hipB: -40, kneeB: 60, shoulderF: -20, elbowF: 70, shoulderB: -30, elbowB: 60, offY: 2 }, "out"),
        kf(14, { ...STANCE, torso: 26, squash: 0.92, hipF: 30, kneeF: 40, hipB: -30, kneeB: 50 }),
        kf(22, { ...STANCE, torso: 10 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "airDivide",
      name: "Falling Divide",
      input: { button: "B", motion: "qcb", stance: "air" },
      tags: ["special", "air", "overhead"],
      priority: 26,
      duration: 40,
      resourceCost: 1,
      resourceMin: 1,
      airborne: true,
      landCancel: true,
      landRecovery: 9,
      vel: [{ at: 3, x: 6.5, y: -13 }],
      hits: [
        hit(5, 30, bx(10, 4, 58, 56), 70, {
          guard: "overhead",
          fx: "slash",
          pushX: 4,
          hitstun: 22,
          knockdown: "hard",
        }),
      ],
      desc: "Air-only dive with the blade leading. Changes her jump arc and crosses people up.",
      notation: "(air) ↓↙← + B",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: 30, spin: -14, shoulderF: 40, elbowF: 6, weapon: -60, hipF: 50, kneeF: 20, hipB: -30, kneeB: 44 }, "out"),
        kf(30, { ...STANCE, free: 1, torso: 32, spin: -18, shoulderF: 44, elbowF: 4, weapon: -62 }),
        kf(40, { ...STANCE, free: 1 }),
      ],
    },

    // ----------------------------------------------------------------- skill
    {
      id: "focus",
      name: "Settle the Breath",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill"],
      priority: 18,
      duration: 48,
      resourceGain: 3,
      meterGain: 14,
      friction: 0.9,
      desc: "SKILL. Sheathes the blade and refills all three Ki, plus a little meter. Long, quiet, and completely open.",
      notation: "A + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(12, { ...STANCE, torso: -4, head: 6, shoulderF: 14, elbowF: 70, shoulderB: 10, elbowB: 62, weapon: -70, hipF: 8, kneeF: 16 }, "inOut"),
        kf(30, { ...STANCE, torso: -6, head: 8, shoulderF: 10, elbowF: 74, shoulderB: 6, elbowB: 66, weapon: -74, offY: 1 }),
        kf(40, { ...STANCE, torso: 0, head: 2, shoulderF: 20, elbowF: 62, weapon: -56 }, "inOut"),
        kf(48, { ...STANCE }),
      ],
    },

    // ------------------------------------------------------------------ EX
    {
      id: "iaiEx",
      name: "Iai Draw EX",
      input: { button: "S", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "ex"],
      priority: 26,
      duration: 52,
      meterCost: 50,
      invuln: [{ from: 1, to: 14, kind: "strike" }],
      vel: [
        { at: 8, x: 11 },
        { at: 26, x: 0 },
      ],
      friction: 0.88,
      hits: [
        hit(10, 14, bx(16, 18, 132, 70), 70, { group: 1, fx: "slash", pushX: 2, hitstun: 24, hitstop: 8 }),
        hit(18, 24, bx(16, 14, 138, 78), 86, {
          group: 2,
          fx: "slash",
          pushX: 10,
          knockdown: "wallbounce",
          hitstun: 30,
          hitstop: 14,
          shake: 2.4,
        }),
      ],
      vfx: [
        { at: 10, kind: "slash", x: 74, y: 54, scale: 1.7, color: "#9fe8ff" },
        { at: 18, kind: "slash", x: 82, y: 40, scale: 2, color: "#ffffff" },
      ],
      desc: "EX. Invincible on startup, two cuts, and the second slams them off the wall.",
      notation: "↓↘→ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, torso: -14, shoulderF: 4, elbowF: 88, weapon: -80, offX: -5 }, "inOut"),
        kf(10, { ...STANCE, torso: 24, shoulderF: 110, elbowF: -14, weapon: -26, hipF: 40, kneeF: 22, offX: 9 }, "out"),
        kf(16, { ...STANCE, torso: -10, shoulderF: 168, elbowF: -30, weapon: 26, offX: 4 }, "inOut"),
        kf(18, { ...STANCE, torso: 32, shoulderF: 40, elbowF: 12, weapon: -40, hipF: 46, kneeF: 26, hipB: -26, kneeB: 56, offX: 12 }, "out"),
        kf(34, { ...STANCE, torso: 18, shoulderF: 60, elbowF: 20, weapon: -34, offX: 6 }, "inOut"),
        kf(52, { ...STANCE }),
      ],
    },
    {
      id: "tsubameEx",
      name: "Swallow Cut EX",
      input: { button: "S", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "launcher"],
      priority: 30,
      duration: 54,
      meterCost: 50,
      airborne: true,
      invuln: [{ from: 1, to: 16, kind: "strike" }],
      vel: [
        { at: 1, x: 3, y: 14.5 },
        { at: 32, y: -1, mode: "add" },
      ],
      hits: [
        hit(3, 8, bx(8, 48, 68, 88), 66, { launch: [2, 12], knockdown: "launch", fx: "slash", hitstun: 28, shake: 2 }),
        hit(9, 16, bx(6, 62, 62, 80), 34, { group: 2, launch: [1.4, 5], fx: "slash" }),
        hit(17, 26, bx(6, 74, 60, 72), 52, { group: 3, launch: [2, 4], fx: "slash", knockdown: "hard" }),
      ],
      desc: "EX. Fully invincible and carries them all the way up with three cuts.",
      notation: "→↓↘ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 48 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -16, spin: -8, shoulderF: 156, elbowF: -14, weapon: 18 }, "out"),
        kf(16, { ...STANCE, free: 1, torso: -24, spin: -24, shoulderF: 178, elbowF: -6, weapon: 10 }),
        kf(36, { ...STANCE, free: 1, torso: -6, spin: -4, shoulderF: 116, elbowF: 2, weapon: -22 }, "inOut"),
        kf(54, { ...STANCE, free: 1 }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "One Thousand Cuts",
      input: { button: "S", motion: "dd", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 118,
      meterCost: 100,
      superFreeze: 44,
      invuln: [{ from: 1, to: 14, kind: "strike" }],
      vel: [
        { at: 8, x: 9 },
        { at: 34, x: 4 },
        { at: 70, x: 0 },
      ],
      friction: 0.92,
      hits: [
        hit(14, 17, bx(18, 24, 104, 62), 52, { group: 1, fx: "slash", pushX: 0.6, hitstun: 22, hitstop: 5 }),
        hit(22, 25, bx(18, 30, 104, 62), 40, { group: 2, fx: "slash", pushX: 0.6, hitstun: 20, hitstop: 4 }),
        hit(30, 33, bx(18, 20, 108, 68), 40, { group: 3, fx: "slash", pushX: 0.6, hitstun: 20, hitstop: 4 }),
        hit(38, 41, bx(18, 30, 108, 68), 40, { group: 4, fx: "slash", pushX: 0.6, hitstun: 20, hitstop: 4 }),
        hit(46, 49, bx(18, 22, 112, 72), 40, { group: 5, fx: "slash", pushX: 0.6, hitstun: 20, hitstop: 4 }),
        hit(58, 64, bx(14, 10, 128, 86), 150, {
          group: 6,
          fx: "slash",
          pushX: 12,
          knockdown: "hard",
          launch: [7, 8],
          hitstop: 18,
          shake: 3,
        }),
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 50, scale: 2.6, color: "#9fe8ff" },
        { at: 14, kind: "slash", x: 60, y: 60, scale: 1.4, color: "#9fe8ff" },
        { at: 30, kind: "slash", x: 60, y: 40, scale: 1.4, color: "#9fe8ff" },
        { at: 46, kind: "slash", x: 60, y: 55, scale: 1.4, color: "#9fe8ff" },
        { at: 58, kind: "slash", x: 70, y: 45, scale: 2.6, color: "#ffffff" },
      ],
      desc: "SUPER. Crosses the distance and cuts five times before the sheathe - and it is the sheathe that lands.",
      notation: "↓↓ + S  (100 meter)",
      frames: [
        kf(0, { ...STANCE, torso: -10, shoulderF: 8, elbowF: 84, weapon: -78, crouch: 0.35 }, "out"),
        kf(12, { ...STANCE, torso: 24, shoulderF: 100, elbowF: -10, weapon: -28, hipF: 40, kneeF: 22, offX: 8 }, "out"),
        kf(18, { ...STANCE, torso: -8, shoulderF: 166, elbowF: -28, weapon: 28, offX: 3 }, "inOut"),
        kf(22, { ...STANCE, torso: 28, shoulderF: 52, elbowF: 6, weapon: -40, offX: 8 }, "out"),
        kf(28, { ...STANCE, torso: -10, shoulderF: 170, elbowF: -30, weapon: 30, offX: 3 }, "inOut"),
        kf(30, { ...STANCE, torso: 30, shoulderF: 44, elbowF: 10, weapon: -44, offX: 9 }, "out"),
        kf(36, { ...STANCE, torso: -8, shoulderF: 164, elbowF: -26, weapon: 26, offX: 3 }, "inOut"),
        kf(38, { ...STANCE, torso: 28, shoulderF: 56, elbowF: 4, weapon: -36, offX: 9 }, "out"),
        kf(44, { ...STANCE, torso: -12, shoulderF: 172, elbowF: -32, weapon: 32, offX: 2 }, "inOut"),
        kf(46, { ...STANCE, torso: 32, shoulderF: 40, elbowF: 12, weapon: -46, offX: 10 }, "out"),
        kf(54, { ...STANCE, torso: -16, shoulderF: 20, elbowF: 80, shoulderB: 6, elbowB: 66, weapon: -74, offX: -4 }, "inOut"),
        kf(58, { ...STANCE, torso: 34, shoulderF: 118, elbowF: -18, shoulderB: 50, elbowB: 14, weapon: -22, hipF: 48, kneeF: 26, hipB: -28, kneeB: 58, offX: 13 }, "out"),
        kf(80, { ...STANCE, torso: 16, shoulderF: 70, elbowF: 20, weapon: -40, offX: 5 }, "inOut"),
        kf(118, { ...STANCE }),
      ],
    },
  ],
};
