/**
 * Kuro - the smoke that walks.
 *
 * The one fighter in the roster nobody can put a date or a face to. Every
 * other name here comes out of a record somewhere; his comes out of rumor,
 * repeated in enough different centuries that no two versions agree on
 * which war he was in. He carries a kunai in each hand and treats the fight
 * itself as something to slip out of, not just survive: a shuriken to keep
 * them honest at range, a hook to end the guessing game, a roll that clears
 * more ground than his legs should let him, and smoke to be somewhere else
 * entirely. Ash fuels the vanishing act, and like every shinobi's resource
 * in this roster it only fills while he holds still.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const CLOTH = "#241f2c";
const DARK = "#141019";
const STEEL = "#c9cfda";
const VIOLET = "#8a5fb0";

const STANCE = {
  torso: 6,
  head: -2,
  hipF: 16,
  kneeF: 20,
  hipB: -20,
  kneeB: 32,
  // Twin kunai, both live: front hand low and ready, back hand reverse-gripped.
  shoulderF: 60,
  elbowF: 58,
  weapon: 18,
  shoulderB: 34,
  elbowB: 64,
  weaponBack: 152,
  crouch: 0.16,
};

export const SHADE: FighterDef = {
  id: "shade",
  name: "Kuro",
  title: "The Smoke That Walks",
  era: "No fixed year - every generation swears they saw him",
  bio: "No temple keeps his name and no clan claims his grave. Villagers blamed him for missing rice, daimyo blamed him for missing heads, and no one could ever prove it was the same man twice. Whether he is one person or a job description passed down with the mask is the whole point of him.",
  archetype: "Mix-up / Wildcard",
  difficulty: 4,
  strengths: ["Full kit of ways to not be where he was", "Threatens from touching range and full screen both", "The hook ends a guessing game outright"],
  weaknesses: ["Ash runs out fast and only refills standing still", "No reversal - has to guess right on wakeup", "Lowest health alongside the rest of the shinobi"],
  winQuote: "You were fighting a rumor. Rumors don't lose.",
  palette: {
    body: "#d8c9b0",
    outline: "#100c14",
    accent: VIOLET,
    cloth: CLOTH,
    metal: STEEL,
    aura: "#c9a6ec",
  },
  stats: {
    health: 880,
    walkF: 3.35,
    walkB: 3.0,
    dashSpeed: 9.5,
    dashFrames: 13,
    backdashFrames: 17,
    jumpVel: 12.8,
    jumpFwd: 5.35,
    gravity: 0.61,
    weight: 1.04,
    airMoves: 2,
    doubleJump: true,
    airDash: true,
    width: 18,
    standHeight: 100,
    crouchHeight: 60,
    scale: 0.97,
  },
  stance: STANCE,
  clips: guardClips({
    high: { torso: 0, head: -6, shoulderF: 28, elbowF: 126, weapon: 60, shoulderB: 20, elbowB: 138, weaponBack: 152, crouch: 0.1, hipF: 16, kneeF: 24, hipB: -20, kneeB: 34, offX: -2 },
    low: { torso: 8, head: -5, shoulderF: 34, elbowF: 116, weapon: 60, shoulderB: 26, elbowB: 128, weaponBack: 152, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, offX: -2 },
  }),
  resource: {
    name: "Ash",
    max: 3,
    start: 2,
    regen: 0.0085,
    regenIdleOnly: true,
    color: VIOLET,
    pips: true,
  },
  props: [
    {
      id: "wrap",
      attach: "head",
      // Face wrap over the nose and jaw, hair loose above it.
      parts: [
        { geo: "poly", size: [-10, -6, -10, 3, -6, 8, 0, 9, 6, 8, 10, 2, 10, -6], pos: [0, 5], color: CLOTH },
        { geo: "box", size: [22, 4], pos: [0, 9], color: DARK },
        { geo: "poly", size: [-8, 6, 8, 5, 8, -4, -6, -5, -8, -1], pos: [1, -10], rot: -4, color: "#0e0b10", behind: true },
        { geo: "poly", size: [0, 4, -6, -5, -10, -10, -7, 3], pos: [-11, -6], rot: 10, color: DARK, behind: true },
      ],
    },
    {
      id: "vest",
      attach: "torso",
      // Sleeveless wrap top, cross-strapped, throwing spikes tucked in.
      parts: [
        { geo: "poly", size: [-12, -15, 12, -15, 13, 6, 8, 15, -8, 15, -13, 6], pos: [0, 4], color: CLOTH },
        { geo: "poly", size: [-8, -9, 8, -9, 9, 4, 4, 9, -4, 9, -9, 4], pos: [0, 4], color: "#1c1622" },
        { geo: "poly", size: [-3, 18, 3, 18, 3, -18, -3, -18], pos: [-4, 4], rot: 12, color: VIOLET },
        { geo: "box", size: [18, 1.6], pos: [0, -9], color: "#3a2e48" },
        { geo: "poly", size: [0, 4, 5, 1, 5, -1, 0, -4], pos: [-6, 11], rot: 12, color: STEEL, z: 0.3 },
        { geo: "poly", size: [0, 4, 5, 1, 5, -1, 0, -4], pos: [-3, 3], rot: 12, color: STEEL, z: 0.3 },
      ],
    },
    {
      id: "sash",
      attach: "pelvis",
      parts: [
        { geo: "poly", size: [-12, 4, 12, 3.5, 12, -4, -12, -4.5], pos: [0, 1], color: DARK },
        { geo: "box", size: [9, 2.2], pos: [-10, -1], color: VIOLET, z: 0.2 },
        { geo: "poly", size: [-4, 3, 4, 2, 4, -3, -4, -3], pos: [10, -2], color: "#3a2e48" },
      ],
      cloth: {
        segments: 3,
        segmentLength: 10,
        width: 10,
        endWidth: 4,
        color: "#3a2e48",
        lining: DARK,
        gravity: 0.4,
        stiffness: 0.55,
        drift: -0.3,
      },
    },
    {
      id: "kunaiF",
      attach: "handF",
      parts: [
        { geo: "box", size: [10, 4.6], pos: [-2, 0], color: DARK },
        { geo: "ring", size: [4, 1.6], pos: [-8, 0], color: DARK },
        { geo: "poly", size: [-4, 4.5, 9, 3, 16, 0, 9, -3, -4, -4.5], pos: [10, 0], color: STEEL },
      ],
    },
    {
      id: "kunaiB",
      attach: "handB",
      parts: [
        { geo: "box", size: [10, 4.6], pos: [-2, 0], color: DARK },
        { geo: "ring", size: [4, 1.6], pos: [-8, 0], color: DARK },
        { geo: "poly", size: [-4, 4.5, 9, 3, 16, 0, 9, -3, -4, -4.5], pos: [10, 0], color: STEEL },
      ],
    },
    {
      id: "pouch",
      attach: "pelvis",
      parts: [
        { geo: "poly", size: [-5, 6, 5, 5, 4, -7, -5, -6], pos: [11, -4], color: CLOTH },
        { geo: "box", size: [9, 2], pos: [11, 1], color: "#3a2e48", z: 0.2 },
      ],
    },
    {
      id: "shuriken",
      attach: "handF",
      conditional: true,
      parts: [
        { geo: "poly", size: [0, 8, 2.4, 2.4, 8, 0, 2.4, -2.4, 0, -8, -2.4, -2.4, -8, 0, -2.4, 2.4], pos: [4, 0], color: STEEL },
        { geo: "disc", size: [2], pos: [4, 0], color: DARK },
      ],
    },
    {
      id: "hook",
      attach: "handB",
      conditional: true,
      parts: [
        { geo: "cyl", size: [1.6, 24], pos: [11, 0], rot: 90, color: "#8a8f98" },
        { geo: "poly", size: [-4, 5, 4, 4, 5, -4, -4, -5], pos: [22, 0], color: "#6a707a" },
        { geo: "poly", size: [0, 0, 6, -2, 9, 4, 4, 6, -1, 3], pos: [26, 2], color: STEEL },
      ],
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 120,
      backThrowDamage: 136,
      throwRange: 56,
      rollSpeed: 9,
      weaponIdle: { shoulderB: 34, elbowB: 64, weaponBack: 152 },
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Twin Jab",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 11,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [3, 10],
      followUps: [
        { button: "A", move: "4A", from: 3, to: 8, string: "Twin Jab" },
      ],
      hits: [hit(3, 5, bx(16, 58, 42, 18), 24, { fx: "pierce", hitstun: 13, blockstun: 10, pushX: 2.4 })],
      desc: "Front kunai flicks out point-first. Three frames, cancels into everything.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderF: 92, elbowF: 6, weapon: 4, torso: 10, offX: 3 }),
        kf(7, { ...STANCE, shoulderF: 70, elbowF: 40, weapon: 14, torso: 6 }, "inOut"),
        kf(11, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Cross Cut",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 19,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [7, 17],
      followUps: [
        { button: "C", move: "6C", from: 6, to: 16, string: "Cross Cut" },
      ],
      hits: [hit(6, 9, bx(18, 46, 56, 32), 48, { fx: "slash", pushX: 4, hitstun: 17 })],
      desc: "Both kunai cross at the wrists and open away from each other.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderF: 20, elbowF: 100, shoulderB: -6, elbowB: 96, weaponBack: 90, torso: -6, offX: -2 }),
        kf(6, { ...STANCE, shoulderF: 96, elbowF: 8, shoulderB: 88, elbowB: 10, weaponBack: 10, torso: 18, hipF: 26, offX: 6 }, "out"),
        kf(12, { ...STANCE, shoulderF: 74, elbowF: 40, shoulderB: 60, elbowB: 48, weaponBack: 40, torso: 10 }, "inOut"),
        kf(19, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Rising Gouge",
      input: { button: "C", stance: "stand" },
      tags: ["heavy"],
      duration: 29,
      cancelInto: ["special", "super"],
      cancelWindow: [13, 25],
      followUps: [
        { button: "B", move: "4B", from: 12, to: 26, string: "Rising Gouge" },
      ],
      hits: [
        hit(12, 16, bx(20, 40, 66, 42), 80, {
          fx: "pierce",
          pushX: 7,
          knockdown: "soft",
          hitstun: 22,
          shake: 1.6,
        }),
      ],
      desc: "Both points driven up and through in one motion.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, torso: -10, shoulderF: 20, elbowF: 90, weapon: 40, shoulderB: -10, elbowB: 80, weaponBack: 100, offX: -3 }, "inOut"),
        kf(12, { ...STANCE, torso: 24, spin: -6, shoulderF: 108, elbowF: 0, weapon: -10, shoulderB: 96, elbowB: -4, weaponBack: 6, hipF: 26, kneeF: 18, offX: 7 }, "out"),
        kf(20, { ...STANCE, torso: 16, shoulderF: 78, elbowF: 40, shoulderB: 64, elbowB: 46, weaponBack: 60, offX: 4 }),
        kf(29, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Stab",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 12,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 11],
      hits: [hit(4, 6, bx(14, 14, 40, 18), 22, { guard: "low", fx: "pierce", hitstun: 13, blockstun: 10, pushX: 2.2 })],
      desc: "Point flicked at the shin from a crouch. His check button.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 22, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderF: 82, elbowF: 34, weapon: 6, offX: 4 }),
        kf(8, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderF: 64, elbowF: 56 }, "inOut"),
        kf(12, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }),
      ],
    },
    {
      id: "2B",
      name: "Ankle Cut",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 21,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [8, 19],
      hits: [hit(7, 10, bx(18, 8, 60, 24), 46, { guard: "low", fx: "slash", pushX: 3.8, hitstun: 17 })],
      desc: "Back kunai dragged across the ankle. Cancels into everything he has.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 10, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderB: -2, elbowB: 92, weaponBack: 78 }),
        kf(7, { ...STANCE, crouch: 1, torso: 26, hipF: 40, kneeF: 80, hipB: -22, kneeB: 86, shoulderB: 46, elbowB: 10, weaponBack: -26, offX: 6 }, "out"),
        kf(14, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderB: 30, elbowB: 50, weaponBack: 12 }, "inOut"),
        kf(21, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }),
      ],
    },
    {
      id: "2C",
      name: "Sweeping Slash",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 28,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 24],
      hits: [hit(10, 14, bx(16, 2, 78, 22), 68, { guard: "low", knockdown: "sweep", fx: "slash", pushX: 5.2 })],
      desc: "Both blades spin through the ankles at once.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }, "out"),
        kf(5, { ...STANCE, crouch: 1, torso: 22, hipF: 12, kneeF: 96, hipB: -34, kneeB: 100, offX: -2 }),
        kf(10, { ...STANCE, crouch: 1, torso: 28, spin: -12, hipF: 88, kneeF: 4, hipB: -38, kneeB: 106, shoulderF: 26, elbowF: 30, shoulderB: 10, elbowB: 30, offX: 6 }, "out"),
        kf(19, { ...STANCE, crouch: 1, torso: 20, hipF: 50, kneeF: 50, hipB: -28, kneeB: 94 }, "inOut"),
        kf(28, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }),
      ],
    },
    {
      id: "6B",
      name: "Overhead Drop",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "overhead"],
      priority: 10,
      duration: 30,
      vel: [{ at: 6, x: 3 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      hits: [hit(15, 19, bx(16, 32, 54, 44), 54, { guard: "overhead", fx: "slash", pushX: 4.4, hitstun: 20 })],
      desc: "Steps in and brings the back kunai down. Overhead - starts like his low cut.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, crouch: 0.5, torso: 14, hipF: 16, kneeF: 62 }),
        kf(11, { ...STANCE, free: 1, offY: 12, torso: -12, shoulderB: 168, elbowB: 6, weaponBack: -8, hipF: 112, kneeF: 12, hipB: -30, kneeB: 60 }, "out"),
        kf(15, { ...STANCE, free: 1, offY: 4, torso: 26, shoulderB: 92, elbowB: 4, weaponBack: 168, hipF: 30, kneeF: 4, hipB: -18, kneeB: 40, offX: 5 }, "out"),
        kf(22, { ...STANCE, offY: 0, torso: 14, hipF: 34, kneeF: 40 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Rising Slash",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 30,
      cancelInto: ["special", "super"],
      cancelWindow: [11, 26],
      hits: [hit(9, 13, bx(12, 40, 50, 74), 62, { launch: [2, 12.2], knockdown: "launch", fx: "slash", hitstun: 26 })],
      desc: "Both blades up through the chin. Launches for a follow-up.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 50 }, "out"),
        kf(5, { ...STANCE, crouch: 0.8, torso: 16, shoulderB: -8, elbowB: 82, weaponBack: 76 }),
        kf(9, { ...STANCE, torso: -14, shoulderF: 4, elbowF: 96, weapon: 40, shoulderB: 168, elbowB: 6, weaponBack: -14, hipF: 18, kneeF: 12, offY: 4 }, "out"),
        kf(18, { ...STANCE, torso: -6, shoulderF: 40, elbowF: 60, weapon: 20, shoulderB: 118, elbowB: 34, weaponBack: 10 }),
        kf(24, { ...STANCE, torso: 2, shoulderF: 56, elbowF: 58, shoulderB: 58, elbowB: 60 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "6A",
      name: "Forward Flick",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 20,
      vel: [{ at: 2, x: 2.2 }],
      friction: 0.88,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [6, 18],
      hits: [hit(6, 8, bx(20, 58, 42, 24), 26, { guard: "high", fx: "pierce", pushX: 3, hitstun: 13, hitstop: 5 })],
      desc: "Steps in and flicks the front kunai across. His fastest button by a wide margin.",
      notation: "→ + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderF: 34, elbowF: 78, weapon: 40, torso: -2, offX: -2 }, "out"),
        kf(6, { ...STANCE, shoulderF: 86, elbowF: 4, weapon: 2, torso: 14, hipF: 26, kneeF: 18, offX: 8 }, "out"),
        kf(11, { ...STANCE, shoulderF: 72, elbowF: 30, weapon: 14, torso: 10, offX: 5 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Charging Gouge",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 40,
      armor: [{ from: 8, to: 18, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 8, x: 5.4 }, { at: 26, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [20, 36],
      hits: [hit(16, 20, bx(16, 22, 52, 68), 84, { guard: "mid", fx: "pierce", pushX: 17, hitstun: 24, hitstop: 12, knockdown: "wallbounce", shake: 2.2 })],
      desc: "Closes the gap and drives both points through on the way past.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 14, elbowF: 92, weapon: 46, torso: -14, hipB: -30, kneeB: 48, offX: -6 }, "out"),
        kf(16, { ...STANCE, shoulderF: 98, elbowF: 4, weapon: -8, torso: 32, hipF: 42, kneeF: 20, hipB: -26, kneeB: 26, offX: 12 }, "out"),
        kf(24, { ...STANCE, shoulderF: 88, elbowF: 20, weapon: 4, torso: 24, hipF: 30, kneeF: 26, offX: 8 }),
        kf(32, { ...STANCE, shoulderF: 66, elbowF: 46, weapon: 14, torso: 10, offX: 3 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Backhand Cut",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 22,
      vel: [{ at: 1, x: -2.6 }],
      friction: 0.86,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [8, 20],
      hits: [hit(8, 10, bx(16, 52, 40, 30), 34, { guard: "mid", fx: "slash", pushX: 6, hitstun: 15, hitstop: 6 })],
      desc: "Slips back and opens the elbow so the back blade rakes across.",
      notation: "← + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -6, shoulderB: 4, elbowB: 108, weaponBack: 166, hipB: -26, kneeB: 40, offX: -6 }, "out"),
        kf(8, { ...STANCE, torso: 8, shoulderB: 68, elbowB: 24, weaponBack: 152, hipF: 22, kneeF: 20, offX: -3 }, "out"),
        kf(14, { ...STANCE, torso: 2, shoulderB: 40, elbowB: 54, weaponBack: 160, offX: -4 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Retreating Kick",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 30,
      vel: [{ at: 1, x: -3.4 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      hits: [hit(12, 15, bx(24, 44, 66, 30), 54, { guard: "mid", fx: "blunt", pushX: 7, hitstun: 18, hitstop: 8 })],
      desc: "Gives ground and snaps the lead leg out at whatever follows.",
      notation: "← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, hipF: 66, kneeF: 104, torso: -14, hipB: -34, kneeB: 46, offX: -8 }, "inOut"),
        kf(12, { ...STANCE, hipF: 96, kneeF: 10, hipB: -26, kneeB: 20, torso: -18, head: 6, offX: -4 }, "out"),
        kf(17, { ...STANCE, hipF: 90, kneeF: 14, torso: -16, offX: -6 }),
        kf(23, { ...STANCE, hipF: 44, kneeF: 54, torso: -2, offX: -4 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Falling Kunai",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 44,
      cancelInto: ["special", "super"],
      cancelWindow: [26, 40],
      hits: [hit(20, 23, bx(12, 20, 58, 86), 92, { guard: "overhead", fx: "pierce", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 })],
      desc: "Jumps both points up and drives them straight down. Blocked standing only.",
      notation: "← + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderB: 96, elbowB: 44, weaponBack: 166, torso: -12, offX: -5 }, "inOut"),
        kf(15, { ...STANCE, shoulderB: 170, elbowB: 18, weaponBack: 172, torso: -20, hipB: -26, kneeB: 38, offY: 4, offX: -3 }, "out"),
        kf(20, { ...STANCE, shoulderB: 90, elbowB: 4, weaponBack: 176, torso: 34, hipF: 36, kneeF: 18, hipB: -12, kneeB: 32, offX: 6 }, "out"),
        kf(26, { ...STANCE, shoulderB: 82, elbowB: 8, weaponBack: 174, torso: 26, offX: 4 }),
        kf(36, { ...STANCE, shoulderB: 42, elbowB: 58, weaponBack: 158, torso: 8 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Slice",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 17,
      airborne: true,
      landCancel: true,
      landRecovery: 2,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [4, 15],
      hits: [hit(4, 9, bx(14, 32, 42, 28), 26, { fx: "slash", hitstun: 14, pushX: 2.2 })],
      desc: "Quick flick in the air to keep a juggle alive.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 34, kneeF: 44, hipB: -24, kneeB: 44 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderB: 76, elbowB: 16, weaponBack: 10, torso: 12 }),
        kf(11, { ...STANCE, free: 1, shoulderB: 44, elbowB: 58, weaponBack: 32, torso: 6 }, "inOut"),
        kf(17, { ...STANCE, free: 1, hipF: 34, kneeF: 44, hipB: -24, kneeB: 44 }),
      ],
    },
    {
      id: "jB",
      name: "Air Knee",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 23,
      airborne: true,
      landCancel: true,
      landRecovery: 4,
      cancelInto: ["heavy", "special"],
      hits: [hit(6, 13, bx(16, 18, 50, 42), 50, { fx: "blunt", pushX: 3.8, hitstun: 18 })],
      desc: "Knee out in front of him on the way in.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 32, kneeF: 42, hipB: -22, kneeB: 40 }, "out"),
        kf(4, { ...STANCE, free: 1, hipF: 12, kneeF: 90, torso: 10 }),
        kf(7, { ...STANCE, free: 1, hipF: 98, kneeF: 106, hipB: -26, kneeB: 46, torso: 18 }, "out"),
        kf(15, { ...STANCE, free: 1, hipF: 58, kneeF: 68, torso: 8 }, "inOut"),
        kf(23, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "jC",
      name: "Falling Blade",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 27,
      airborne: true,
      landCancel: true,
      landRecovery: 6,
      hits: [
        hit(7, 17, bx(6, 4, 50, 48), 70, {
          guard: "overhead",
          fx: "slash",
          knockdown: "soft",
          pushX: 4.6,
          shake: 1.4,
        }),
      ],
      desc: "Point-down blade all the way to the floor. His jump-in.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, torso: -18, shoulderB: 170, elbowB: 18, weaponBack: 18, hipF: 40, kneeF: 56 }),
        kf(8, { ...STANCE, free: 1, torso: 30, shoulderB: 38, elbowB: 8, weaponBack: -66, hipF: 14, kneeF: 18 }, "out"),
        kf(27, { ...STANCE, free: 1, torso: 24, shoulderB: 32, elbowB: 12, weaponBack: -66 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Shadow Rush",
      input: { button: "C", dir: "f", stance: "stand", whileDashing: true },
      tags: ["command"],
      priority: 12,
      duration: 30,
      vel: [
        { at: 3, x: 11 },
        { at: 15, x: 0 },
      ],
      friction: 0.9,
      hits: [hit(7, 12, bx(18, 26, 60, 46), 64, { fx: "pierce", pushX: 6.5, knockdown: "soft", hitstun: 21, shake: 1.4 })],
      desc: "Runs both points forward at chest height. Closes the screen fast.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 26, crouch: 0.4, shoulderF: 10, elbowF: 88, weapon: 44, offX: -3 }),
        kf(7, { ...STANCE, torso: 32, crouch: 0.3, shoulderF: 90, elbowF: 4, weapon: -6, hipF: 46, kneeF: 24, offX: 8 }, "out"),
        kf(20, { ...STANCE, torso: 16, shoulderF: 68, elbowF: 42, offX: 3 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },

    // -------------------------------------------------------- five specials
    {
      id: "shurikenThrow",
      name: "Shuriken Throw",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      duration: 26,
      showProps: ["shuriken"],
      hideProps: ["kunaiF"],
      projectiles: [
        {
          at: 9,
          kind: "shuriken",
          x: 32,
          y: 60,
          vx: 18,
          vy: 0.2,
          gravity: 0.02,
          life: 66,
          box: { x: -8, y: -4, w: 16, h: 8 },
          damage: 38,
          hitstun: 16,
          blockstun: 11,
          chip: 3,
          pushX: 3,
          clashes: true,
          fx: "pierce",
          spin: 30,
          color: STEEL,
          trail: "#9aa2b3",
        },
      ],
      desc: "Flat and fast, not much damage - it exists so they have to hold still.",
      notation: "↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderF: 144, elbowF: 92, weapon: 30, torso: -12, offX: -3 }),
        kf(9, { ...STANCE, shoulderF: 76, elbowF: 4, weapon: -6, torso: 20, hipF: 26, offX: 6 }, "out"),
        kf(17, { ...STANCE, shoulderF: 66, elbowF: 44, weapon: 14, torso: 10 }, "inOut"),
        kf(26, { ...STANCE }),
      ],
    },
    {
      id: "smokeBomb",
      name: "Smoke Bomb",
      input: { button: "A", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      priority: 18,
      duration: 34,
      resourceCost: 1,
      resourceMin: 1,
      projectiles: [
        {
          at: 9,
          kind: "smokebomb",
          x: 24,
          y: 64,
          vx: 8,
          vy: 4.5,
          gravity: 0.42,
          life: 46,
          box: { x: -7, y: -7, w: 14, h: 14 },
          damage: 0,
          hitstun: 0,
          blockstun: 0,
          hits: 1,
          bounce: 0.3,
          bounces: 1,
          drag: 0.99,
          fx: "burn",
          detonate: {
            radius: 52,
            damage: 44,
            hitstun: 25,
            blockstun: 20,
            knockdown: "none",
            guard: "low",
            chip: 5,
          },
          scale: 0.9,
          color: "#7a6a8a",
        },
      ],
      desc: "Lobbed short, bursts into a cloud on the floor. Blocked low, and it lasts long enough to be behind them. Costs one Ash.",
      notation: "↓↙← + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderF: 138, elbowF: 106, weapon: 20, torso: -10, offX: -3 }),
        kf(9, { ...STANCE, shoulderF: 64, elbowF: 18, weapon: -4, torso: 22, hipF: 24, offX: 5 }, "out"),
        kf(20, { ...STANCE, shoulderF: 58, elbowF: 52, weapon: 10, torso: 8 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },
    {
      id: "smokeTeleport",
      name: "Smoke Teleport",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "movement"],
      priority: 22,
      duration: 26,
      resourceCost: 1,
      resourceMin: 1,
      invuln: [{ from: 4, to: 18, kind: "full" }],
      vel: [
        { at: 4, x: 17 },
        { at: 17, x: 0 },
      ],
      friction: 0.7,
      noTurn: true,
      vfx: [
        { at: 3, kind: "smoke", x: 0, y: 46, scale: 1.3, color: VIOLET },
        { at: 18, kind: "smoke", x: 0, y: 46, scale: 1.3, color: VIOLET },
      ],
      desc: "Gone in a burst of smoke, back past them on the other side. Invincible through the middle. Costs one Ash.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5 }, "out"),
        kf(4, { ...STANCE, crouch: 1, squash: 0.5, torso: 24, offY: -4 }, "linear"),
        kf(10, { ...STANCE, free: 1, crouch: 1, squash: 0.3, torso: 30, hipF: 70, kneeF: 90, hipB: -50, kneeB: 96 }, "linear"),
        kf(18, { ...STANCE, crouch: 0.8, squash: 0.7, torso: 20, hipF: 40, kneeF: 60 }, "out"),
        kf(26, { ...STANCE }),
      ],
    },
    {
      id: "hook",
      name: "Grappling Hook",
      input: { button: "B", motion: "hcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      priority: 18,
      duration: 40,
      showProps: ["hook"],
      hideProps: ["kunaiB"],
      projectiles: [
        {
          at: 12,
          kind: "hook",
          x: 34,
          y: 58,
          vx: 14,
          vy: 0,
          life: 26,
          box: { x: -18, y: -8, w: 36, h: 16 },
          damage: 42,
          hitstun: 28,
          blockstun: 16,
          pushX: -13,
          chip: 3,
          fx: "pierce",
          color: "#9aa4b1",
        },
      ],
      desc: "Throws the hook - on hit it drags them into point-blank range and ends the guessing game.",
      notation: "←↙↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderB: -68, elbowB: 32, weaponBack: 100, torso: -14, offX: -4 }, "inOut"),
        kf(12, { ...STANCE, shoulderB: 94, elbowB: 8, weaponBack: -8, torso: 20, offX: 5 }, "out"),
        kf(24, { ...STANCE, shoulderB: 58, elbowB: 42, weaponBack: 40, torso: 10 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "roll",
      name: "Roll Dodge",
      input: { motion: "ff", stance: ["stand", "crouch"] },
      tags: ["special", "movement"],
      priority: 55,
      duration: 32,
      // He is the one fighter with no forward dash - this roll answers the
      // same double-tap and takes it - so his dash attack has to come out of
      // the roll or it cannot come out at all.
      followUps: [{ button: "C", move: "dashAttack", from: 4, to: 22, string: "Shadow Rush" }],
      invuln: [{ from: 3, to: 24, kind: "strike" }],
      // Twice the universal sidestep's travel - a real escape, not a feint.
      vel: [
        { at: 3, x: 16 },
        { at: 24, x: 0 },
      ],
      friction: 0.95,
      desc: "A full tumbling roll that clears more ground than his legs should let him. Double-tap forward - no button needed.",
      notation: "→ →",
      frames: [
        kf(0, { ...STANCE, torso: 10, crouch: 0.3, offX: -3 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: 30, spin: 40, crouch: 0.6, offY: 6, hipF: 40, kneeF: 60, hipB: -34, kneeB: 30 }, "out"),
        kf(9, { ...STANCE, free: 1, torso: 10, spin: 180, offY: 10, hipF: 20, kneeF: 40, hipB: -20, kneeB: 40 }, "linear"),
        kf(15, { ...STANCE, free: 1, torso: -10, spin: 320, offY: 6, hipF: 30, kneeF: 40, hipB: -20, kneeB: 40 }, "linear"),
        kf(20, { ...STANCE, free: 1, torso: 6, spin: 360, crouch: 0.5, offY: 2, hipF: 40, kneeF: 60, hipB: -30, kneeB: 34 }, "out"),
        kf(26, { ...STANCE, torso: 8, crouch: 0.16 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- skill
    {
      id: "smokeSwap",
      name: "Smoke Swap",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill"],
      priority: 18,
      duration: 30,
      parryWindow: [2, 9],
      friction: 0.82,
      resourceGain: 1,
      vfx: [{ at: 2, kind: "smoke", x: 0, y: 46, scale: 1, color: VIOLET }],
      desc: "SKILL. Leaves a smoke double in his place. Deflects anything that lands in the first frames and hands back one Ash for it.",
      notation: "A + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, crouch: 0.7, squash: 0.7, torso: 20, shoulderF: 32, elbowF: 88, shoulderB: 12, elbowB: 96, offY: -2 }, "out"),
        kf(9, { ...STANCE, crouch: 0.5, torso: -8, shoulderF: 88, elbowF: 36, shoulderB: 58, elbowB: 58, offX: -4 }, "inOut"),
        kf(18, { ...STANCE, torso: 4, shoulderF: 64, elbowF: 54 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "Vanishing Rush",
      input: { button: "S", motion: "dd", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 108,
      meterCost: 100,
      superFreeze: 42,
      invuln: [{ from: 1, to: 18, kind: "full" }],
      noTurn: true,
      vel: [
        { at: 8, x: 13 },
        { at: 24, x: -10 },
        { at: 40, x: 12 },
        { at: 56, x: -8 },
        { at: 72, x: 6 },
        { at: 84, x: 0 },
      ],
      friction: 0.9,
      hits: [
        hit(13, 17, bx(-10, 32, 62, 50), 42, { group: 1, fx: "pierce", pushX: 0.6, hitstun: 21, hitstop: 5 }),
        hit(28, 32, bx(-10, 32, 62, 50), 36, { group: 2, fx: "slash", pushX: 0.6, hitstun: 19, hitstop: 4 }),
        hit(44, 48, bx(-10, 28, 62, 54), 36, { group: 3, fx: "pierce", pushX: 0.6, hitstun: 19, hitstop: 4 }),
        hit(60, 64, bx(-10, 28, 62, 54), 36, { group: 4, fx: "slash", pushX: 0.6, hitstun: 19, hitstop: 4 }),
        hit(84, 90, bx(2, 12, 74, 70), 132, {
          group: 5,
          fx: "slash",
          pushX: 11,
          knockdown: "hard",
          launch: [6, 8],
          hitstop: 17,
          shake: 2.9,
        }),
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 50, scale: 2.3, color: VIOLET },
        { at: 13, kind: "smoke", x: 0, y: 46, scale: 1.2, color: VIOLET },
        { at: 28, kind: "smoke", x: 0, y: 46, scale: 1.2, color: VIOLET },
        { at: 44, kind: "smoke", x: 0, y: 46, scale: 1.2, color: VIOLET },
        { at: 60, kind: "smoke", x: 0, y: 46, scale: 1.2, color: VIOLET },
        { at: 84, kind: "slash", x: 38, y: 50, scale: 1.6, color: "#e6d6f5" },
      ],
      desc: "SUPER. He is never where the last cut left him, until the one that ends it.",
      notation: "↓↓ + S (100 meter)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, torso: -8 }, "out"),
        kf(8, { ...STANCE, free: 1, crouch: 1, squash: 0.4, torso: 28 }, "linear"),
        kf(13, { ...STANCE, torso: -16, shoulderF: 6, elbowF: 92, weapon: 40, offX: -6 }, "out"),
        kf(22, { ...STANCE, free: 1, squash: 0.4, torso: 22 }, "linear"),
        kf(28, { ...STANCE, torso: -14, shoulderB: 150, elbowB: 10, weaponBack: -12, offX: -5 }, "out"),
        kf(38, { ...STANCE, free: 1, squash: 0.4, torso: 24 }, "linear"),
        kf(44, { ...STANCE, torso: 18, shoulderF: 8, elbowF: 90, weapon: 36, offX: 5 }, "out"),
        kf(54, { ...STANCE, free: 1, squash: 0.4, torso: 20 }, "linear"),
        kf(60, { ...STANCE, torso: -12, shoulderB: 148, elbowB: 14, weaponBack: -8, offX: -5 }, "out"),
        kf(70, { ...STANCE, free: 1, squash: 0.5, torso: 22 }, "linear"),
        kf(76, { ...STANCE, torso: 22, hipF: 92, kneeF: 86, offX: 5 }, "out"),
        kf(80, { ...STANCE, crouch: 0.8, torso: -18, shoulderB: -10, elbowB: 94, weaponBack: 90, offX: -4 }, "out"),
        kf(84, { ...STANCE, torso: 32, shoulderB: 76, elbowB: 6, weaponBack: -60, hipF: 38, kneeF: 20, offX: 10 }, "out"),
        kf(96, { ...STANCE, torso: 12, shoulderB: 48, elbowB: 44, offX: 4 }, "inOut"),
        kf(108, { ...STANCE }),
      ],
    },
  ],
};
