/**
 * Yuekong - Shaolin monk, Jiangnan coast, 1553.
 *
 * Not a legend. In the 1550s the Ming court, short of troops on the pirate
 * coast, called up fighting monks from Shaolin and other monasteries against
 * the wokou raiders. Zheng Ruoceng's "Jiangnan jinglue" records the campaign
 * and names Yuekong as the monk who led some forty of them; the detachment was
 * wiped out near Huangpu in 1555 after killing a great many raiders first.
 *
 * The monks fought with the iron-shod staff, not the sword - a monk was not
 * supposed to take life, and a staff lets you make that a matter of degree. In
 * game the staff is the longest weapon on the roster and the whole character is
 * about controlling the space it covers.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const OCHRE = "#c8722c";
const ROBE = "#6d2f14";
const SASH = "#e0b64a";
const IRON = "#6f7681";
const WOOD = "#8a6236";

/** Staff held across the body at a slant, hands apart, weight on the back leg. */
const STANCE = {
  torso: 4,
  head: -2,
  hipF: 16,
  kneeF: 20,
  hipB: -18,
  kneeB: 32,
  shoulderF: 44,
  elbowF: 58,
  shoulderB: 52,
  elbowB: 54,
  weapon: 18,
};

const guard = { shoulderB: 66, elbowB: 70 };

export const SHAOLIN: FighterDef = {
  id: "shaolin",
  name: "Yuekong",
  title: "Staff Monk of Shaolin",
  era: "Jiangnan Coast, 1553",
  bio: "Led some forty fighting monks down from the monastery when the Ming court ran out of soldiers for the pirate coast. Fights with an iron-shod staff because a staff lets a man who has sworn off killing decide, blow by blow, whether to break the rule.",
  archetype: "Zoner / Stance",
  difficulty: 4,
  strengths: ["Longest reach in the roster", "Staff spin swats projectiles", "Chi regenerates for free"],
  weaknesses: ["Almost nothing up close", "Low damage per hit", "Stances take real execution"],
  winQuote: "I have not killed you. Consider carefully what that cost me.",
  palette: {
    body: "#d8ab7c",
    outline: "#171410",
    accent: SASH,
    cloth: ROBE,
    metal: IRON,
    aura: "#ffe6a8",
  },
  stats: {
    health: 970,
    walkF: 2.75,
    walkB: 2.6,
    dashSpeed: 8,
    dashFrames: 15,
    backdashFrames: 18,
    jumpVel: 13,
    jumpFwd: 4.6,
    gravity: 0.6,
    weight: 0.96,
    airMoves: 2,
    doubleJump: false,
    airDash: false,
    width: 20,
    standHeight: 104,
    crouchHeight: 64,
    scale: 1,
  },
  stance: STANCE,
  // The staff comes up across the body and he blocks on the shaft.
  clips: guardClips({
    high: { torso: 0, head: -6, shoulderF: 126, elbowF: 34, weapon: -34, shoulderB: 30, elbowB: 116, hipF: 16, kneeF: 24, hipB: -18, kneeB: 34, offX: -2 },
    low: { torso: 8, head: -5, shoulderF: 118, elbowF: 38, weapon: -30, shoulderB: 34, elbowB: 112, hipF: 34, kneeF: 76, hipB: -20, kneeB: 86, offX: -2 },
  }),
  resource: {
    name: "Chi",
    max: 100,
    start: 60,
    // Breath work: it comes back on its own, but only while he is standing
    // still and not swinging at anybody.
    regen: 0.22,
    regenIdleOnly: true,
    color: "#ffe6a8",
  },
  props: [
    {
      id: "tonsure",
      attach: "head",
      // Shaved head with the nine incense scars burned into the crown at
      // ordination, and a plain cloth band against the sweat.
      parts: [
        { geo: "disc", size: [1.1], pos: [-4, 9], color: "#6b4a34" },
        { geo: "disc", size: [1.1], pos: [1, 11], color: "#6b4a34" },
        { geo: "disc", size: [1.1], pos: [6, 9], color: "#6b4a34" },
        { geo: "disc", size: [1.1], pos: [-2, 6], color: "#6b4a34" },
        { geo: "disc", size: [1.1], pos: [4, 6], color: "#6b4a34" },
        // Brow band.
        { geo: "poly", size: [-11, 2, 11, 2.5, 11, -1.5, -11, -2], pos: [0, 2], color: OCHRE, z: 0.5 },
      ],
    },
    {
      id: "staff",
      attach: "handF",
      // Gun: a long hardwood staff shod with iron at both ends. Nothing
      // ornamental on it - the monks' staffs were tools.
      parts: [
        { geo: "cyl", size: [3.2, 118], pos: [22, 0], rot: 90, color: WOOD },
        { geo: "cyl", size: [1.5, 118], pos: [22, 1.6], rot: 90, color: "#a67c47" },
        // Iron ferrules, bruised and bright at the edges.
        { geo: "box", size: [15, 8], pos: [75, 0], color: IRON },
        { geo: "box", size: [15, 8], pos: [-31, 0], color: IRON },
        { geo: "box", size: [3, 8.5], pos: [80, 0], color: "#8d959e" },
        { geo: "box", size: [3, 8.5], pos: [-36, 0], color: "#8d959e" },
        // Binding at the two grips.
        { geo: "box", size: [11, 7], pos: [4, 0], color: "#4a3220" },
        { geo: "box", size: [11, 7], pos: [38, 0], color: "#4a3220" },
      ],
    },
    {
      id: "kasaya",
      attach: "torso",
      // Kasaya: the patched robe, one shoulder bare. The patchwork is the point
      // of it - the cloth is meant to be scraps nobody else wanted.
      parts: [
        { geo: "poly", size: [-12, -16, 11, -16, 13, 6, 4, 16, -8, 14, -13, 4], pos: [0, 3], color: ROBE },
        // Patch seams running across the robe.
        { geo: "box", size: [26, 1.8], pos: [-1, 10], color: "#4d1f0c" },
        { geo: "box", size: [26, 1.8], pos: [-1, 2], color: "#4d1f0c" },
        { geo: "box", size: [24, 1.8], pos: [-1, -6], color: "#4d1f0c" },
        { geo: "box", size: [1.8, 32], pos: [-4, 0], color: "#4d1f0c" },
        { geo: "box", size: [1.8, 32], pos: [5, 0], color: "#4d1f0c" },
        // The bare shoulder, and the fold of the robe crossing the chest.
        { geo: "poly", size: [-13, 8, 2, 14, 10, 4, 8, -2, -12, -4], pos: [-1, 6], color: "#d8ab7c", z: 0.3 },
        // Prayer beads round the neck.
        { geo: "ring", size: [7.5, 1.4], pos: [0, 15], color: "#3b2a1a", z: 0.5 },
        { geo: "disc", size: [1.4], pos: [0, 8], color: "#3b2a1a", z: 0.55 },
      ],
    },
    {
      id: "sash",
      attach: "pelvis",
      // Waist wrap knotted at the front, with the robe skirt below it.
      parts: [
        { geo: "box", size: [27, 8], pos: [0, 2], color: SASH },
        { geo: "box", size: [27, 2], pos: [0, 4], color: "#f0d68a" },
        { geo: "poly", size: [-4, 5, 4, 5, 3, -12, -3, -12], pos: [6, -5], color: "#c99a3a", z: 0.2 },
        { geo: "poly", size: [-11, 4, 11, 4, 8, -18, -8, -18], pos: [0, -8], color: ROBE, behind: true },
      ],
    },
    {
      id: "sandals",
      attach: "footF",
      // Straw sandals, laced round the ankle.
      parts: [
        { geo: "poly", size: [-4, 2, 13, 1.5, 14, -1, -4, -1.5], pos: [3, -1], color: "#c9b183" },
        { geo: "box", size: [4, 5], pos: [-1, 3], color: "#a8916a" },
      ],
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 112,
      backThrowDamage: 124,
      throwRange: 58,
      rollSpeed: 8,
      weaponIdle: { weapon: STANCE.weapon },
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Butt Strike",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 13,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [3, 12],
      // Staff Form string continues into 5B.
      followUps: [
        { button: "B", move: "5B", from: 4, to: 10, string: "Staff Form" },
      ],
      hits: [hit(4, 6, bx(18, 52, 44, 22), 30, { blockstun: 10, hitstun: 14, fx: "blunt", pushX: 3 })],
      desc: "Snaps the near end of the staff into their face. His only genuinely fast button.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 76, elbowF: 20, weapon: 4, torso: 14, offX: 3 }),
        kf(8, { ...STANCE, shoulderF: 54, elbowF: 44, weapon: 20, torso: 8 }, "inOut"),
        kf(13, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Long Thrust",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 24,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [9, 22],
      // Staff Form string continues into 6C.
      followUps: [
        { button: "C", move: "6C", from: 9, to: 21, string: "Staff Form" },
      ],
      hits: [hit(9, 12, bx(34, 50, 92, 20), 56, { fx: "blunt", pushX: 5, hitstun: 18 })],
      desc: "Runs the staff out to full length. The longest normal in the game - he lives at this distance.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderF: 30, elbowF: 74, shoulderB: 34, elbowB: 76, weapon: 44, torso: -6, offX: -4 }),
        kf(9, { ...STANCE, shoulderF: 74, elbowF: 6, shoulderB: 66, elbowB: 10, weapon: 6, torso: 16, hipF: 32, kneeF: 18, offX: 9 }, "out"),
        kf(15, { ...STANCE, shoulderF: 70, elbowF: 10, shoulderB: 62, elbowB: 14, weapon: 8, torso: 12, offX: 7 }),
        kf(24, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Crown Strike",
      input: { button: "C", stance: "stand" },
      tags: ["heavy", "overhead"],
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [15, 28],
      hits: [
        hit(15, 19, bx(22, 32, 80, 72), 84, {
          guard: "overhead",
          fx: "blunt",
          knockdown: "soft",
          pushX: 6.5,
          shake: 1.5,
        }),
      ],
      desc: "Brings the iron end down on top of their head. Overhead, and it knocks down.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderF: 160, elbowF: 20, shoulderB: 146, elbowB: 26, weapon: 74, torso: -16, hipB: -26, kneeB: 40, offX: -4 }, "inOut"),
        kf(15, { ...STANCE, shoulderF: 40, elbowF: 14, shoulderB: 48, elbowB: 18, weapon: -14, torso: 30, hipF: 38, kneeF: 24, offX: 7 }, "out"),
        kf(22, { ...STANCE, shoulderF: 36, elbowF: 18, shoulderB: 44, elbowB: 22, weapon: -12, torso: 26, offX: 5 }),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Tap",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 14,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 13],
      hits: [hit(4, 6, bx(18, 16, 46, 20), 26, { guard: "low", blockstun: 10, hitstun: 13, pushX: 2.6 })],
      desc: "Taps the staff into their shin. Must be blocked crouching and links into itself.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, ...guard }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 20, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderF: 64, elbowF: 20, weapon: -22, offX: 4 }),
        kf(9, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderF: 46, elbowF: 46 }, "inOut"),
        kf(14, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, ...guard }),
      ],
    },
    {
      id: "2B",
      name: "Ground Sweep",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 26,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [10, 24],
      hits: [hit(10, 13, bx(30, 10, 92, 24), 52, { guard: "low", fx: "blunt", pushX: 4.4 })],
      desc: "Runs the staff along the floor. Enormous low poke - his main way to hold ground.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 14, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }, "out"),
        kf(5, { ...STANCE, crouch: 1, torso: 6, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderF: 20, elbowF: 56, weapon: 80 }),
        kf(10, { ...STANCE, crouch: 1, torso: 22, hipF: 42, kneeF: 80, hipB: -26, kneeB: 90, shoulderF: 86, elbowF: 26, weapon: -44, offX: 9 }, "out"),
        kf(17, { ...STANCE, crouch: 1, torso: 20, hipF: 40, kneeF: 78, hipB: -24, kneeB: 88, shoulderF: 82, elbowF: 30, weapon: -40, offX: 7 }),
        kf(26, { ...STANCE, crouch: 1, torso: 14, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }),
      ],
    },
    {
      id: "2C",
      name: "Ankle Break",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [14, 28],
      hits: [
        hit(13, 17, bx(22, 2, 88, 24), 74, {
          guard: "low",
          knockdown: "sweep",
          fx: "blunt",
          pushX: 6,
          shake: 1.2,
        }),
      ],
      desc: "Full-power sweep along the ground. Knocks down from further out than anything else in the game.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 14, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }, "out"),
        kf(6, { ...STANCE, crouch: 1, torso: 2, hipF: 30, kneeF: 72, hipB: -30, kneeB: 94, shoulderF: 12, elbowF: 40, weapon: 108 }),
        kf(13, { ...STANCE, crouch: 1, torso: 28, hipF: 46, kneeF: 86, hipB: -30, kneeB: 98, shoulderF: 98, elbowF: 34, weapon: -56, offX: 7 }, "out"),
        kf(21, { ...STANCE, crouch: 1, torso: 24, hipF: 42, kneeF: 82, hipB: -26, kneeB: 92, shoulderF: 92, elbowF: 30, weapon: -50 }),
        kf(32, { ...STANCE, crouch: 1, torso: 14, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }),
      ],
    },
    {
      id: "6B",
      name: "Rising Butt",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "overhead"],
      priority: 10,
      duration: 28,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 25],
      hits: [
        hit(16, 19, bx(20, 44, 54, 58), 58, {
          guard: "overhead",
          fx: "blunt",
          pushX: 4.6,
          hitstun: 21,
          shake: 1.1,
        }),
      ],
      desc: "Flips the staff over and brings the far end down short. Overhead, and it comes from a low stance.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 20, elbowF: 96, weapon: 150, torso: -8, crouch: 0.3 }, "inOut"),
        kf(16, { ...STANCE, shoulderF: 96, elbowF: 20, weapon: 190, torso: 26, hipF: 34, kneeF: 22, offX: 6 }, "out"),
        kf(22, { ...STANCE, shoulderF: 90, elbowF: 26, weapon: 186, torso: 20, offX: 4 }),
        kf(28, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Rising Staff",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 28],
      hits: [
        hit(10, 14, bx(14, 52, 60, 78), 68, {
          launch: [2, 12.5],
          knockdown: "launch",
          fx: "blunt",
          hitstun: 25,
          shake: 1.3,
        }),
      ],
      desc: "Whips the staff up through their guard. Launches - and he has the reach to follow it anywhere.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5, hipF: 24, kneeF: 46, hipB: -20, kneeB: 52 }, "out"),
        kf(5, { ...STANCE, crouch: 0.7, torso: 12, shoulderF: 12, elbowF: 50, weapon: 96 }),
        kf(10, { ...STANCE, torso: -18, shoulderF: 150, elbowF: 10, weapon: 14, hipF: 20, kneeF: 12, offY: 4 }, "out"),
        kf(17, { ...STANCE, torso: -14, shoulderF: 142, elbowF: 14, weapon: 16, hipF: 16, kneeF: 10 }),
        kf(25, { ...STANCE, torso: 4, shoulderF: 60, elbowF: 46 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },
    {
      // Forward and back sets. Forward takes space, back gives it up to buy
      // range or a hard read.
      id: "6A",
      name: "Sliding Thrust",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 20,
      vel: [{ at: 2, x: 2.2 }],
      friction: 0.88,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [7, 18],
      // Rising Pole string continues into 3C.
      followUps: [
        { button: "C", move: "3C", from: 7, to: 17, string: "Rising Pole" },
      ],
      hits: [hit(7, 9, bx(20, 60, 44, 26), 32, { guard: "high", fx: "blunt", pushX: 3, hitstun: 14, hitstop: 5 })],
      desc: "Slides the hands and drives the tip out. The staff's fastest answer.",
      notation: "\u2192 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 34, elbowF: 66, weapon: 52, torso: -2, offX: -2 }, "out"),
        // Tip driven straight down the line, shaft level throughout.
        kf(7, { ...STANCE, shoulderF: 88, elbowF: 4, weapon: 2, torso: 14, hipF: 26, kneeF: 18, offX: 7 }, "out"),
        kf(12, { ...STANCE, shoulderF: 72, elbowF: 26, weapon: 22, torso: 10, offX: 5 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Advancing Crown",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 40,
      armor: [{ from: 8, to: 18, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 8, x: 5.4 }, { at: 26, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [20, 36],
      hits: [hit(16, 20, bx(18, 22, 64, 68), 88, { guard: "mid", fx: "blunt", pushX: 17, hitstun: 24, hitstop: 12, knockdown: "wallbounce", shake: 2.2 })],
      desc: "Steps through and brings the staff down across the crown of the head.",
      notation: "\u2192 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 158, elbowF: -46, weapon: 96, torso: -12, hipB: -30, kneeB: 48, offX: -6 }, "out"),
        kf(16, { ...STANCE, shoulderF: 74, elbowF: 22, weapon: 62, torso: 32, hipF: 42, kneeF: 20, hipB: -26, kneeB: 26, offX: 12 }, "out"),
        kf(24, { ...STANCE, shoulderF: 66, elbowF: 30, weapon: 58, torso: 24, hipF: 30, kneeF: 26, offX: 8 }),
        kf(32, { ...STANCE, shoulderF: 54, elbowF: 50, weapon: 34, torso: 10, offX: 3 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Butt Jab",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 22,
      vel: [{ at: 1, x: -2.6 }],
      friction: 0.86,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [8, 20],
      hits: [hit(8, 10, bx(16, 52, 42, 30), 36, { guard: "mid", fx: "blunt", pushX: 6, hitstun: 15, hitstop: 6 })],
      desc: "Steps off the line and jabs backward with the butt end. Short, clean, safe.",
      notation: "\u2190 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -6, shoulderF: 26, elbowF: 74, weapon: 40, hipB: -26, kneeB: 40, offX: -6 }, "out"),
        // Reversed: the butt of the staff leads.
        kf(8, { ...STANCE, torso: 8, shoulderF: 74, elbowF: 18, weapon: 186, hipF: 22, kneeF: 20, offX: -3 }, "out"),
        kf(14, { ...STANCE, torso: 2, shoulderF: 58, elbowF: 42, weapon: 100, offX: -4 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Long Pole",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 30,
      vel: [{ at: 1, x: -3.4 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      // Pole Sweep string continues into 4C.
      followUps: [
        { button: "C", move: "4C", from: 12, to: 27, string: "Pole Sweep" },
      ],
      hits: [hit(12, 15, bx(48, 50, 112, 22), 56, { guard: "mid", fx: "blunt", pushX: 7, hitstun: 18, hitstop: 8 })],
      desc: "Gives ground and holds the far end out. Nothing on the roster reaches past this.",
      notation: "\u2190 + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 30, elbowF: 54, weapon: 56, torso: -12, hipB: -28, kneeB: 42, offX: -8 }, "inOut"),
        kf(12, { ...STANCE, shoulderF: 88, elbowF: 0, weapon: 2, torso: 4, hipF: 26, kneeF: 14, offX: -5 }, "out"),
        kf(17, { ...STANCE, shoulderF: 86, elbowF: 2, weapon: 2, torso: 2, offX: -6 }),
        kf(23, { ...STANCE, shoulderF: 64, elbowF: 30, weapon: 30, torso: 0, offX: -4 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Falling Mountain",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 44,
      cancelInto: ["special", "super"],
      cancelWindow: [26, 40],
      hits: [hit(20, 23, bx(14, 20, 70, 86), 98, { guard: "overhead", fx: "blunt", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 })],
      desc: "Both hands high and the whole staff brought down. Blocked standing only.",
      notation: "\u2190 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 146, elbowF: -44, weapon: 88, torso: -10, offX: -5 }, "inOut"),
        kf(15, { ...STANCE, shoulderF: 178, elbowF: -16, weapon: 94, torso: -20, hipB: -26, kneeB: 38, offY: 3, offX: -3 }, "out"),
        kf(20, { ...STANCE, shoulderF: 86, elbowF: 10, weapon: 68, torso: 32, hipF: 36, kneeF: 20, hipB: -12, kneeB: 32, offX: 6 }, "out"),
        kf(26, { ...STANCE, shoulderF: 78, elbowF: 14, weapon: 64, torso: 26, offX: 4 }),
        kf(36, { ...STANCE, shoulderF: 56, elbowF: 44, weapon: 36, torso: 8 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Tap",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 18,
      airborne: true,
      landCancel: true,
      landRecovery: 2,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [5, 16],
      hits: [hit(5, 11, bx(16, 32, 50, 28), 32, { fx: "blunt", pushX: 2.8, hitstun: 14 })],
      desc: "Short jab with the staff out of the air. Long enough to hit from outside their anti-air.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 34, kneeF: 46, hipB: -24, kneeB: 42 }, "out"),
        kf(5, { ...STANCE, free: 1, shoulderF: 86, elbowF: 14, weapon: 0, torso: 12, hipF: 30, kneeF: 42 }),
        kf(12, { ...STANCE, free: 1, shoulderF: 58, elbowF: 44, weapon: 22, torso: 6, hipF: 32, kneeF: 44 }, "inOut"),
        kf(18, { ...STANCE, free: 1, hipF: 34, kneeF: 46, hipB: -24, kneeB: 42 }),
      ],
    },
    {
      id: "jB",
      name: "Air Sweep",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 26,
      airborne: true,
      landCancel: true,
      landRecovery: 4,
      hits: [hit(7, 15, bx(24, 6, 80, 50), 58, { fx: "blunt", pushX: 4, hitstun: 19 })],
      desc: "Swings the staff down and through. Covers most of the screen under him.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 30, kneeF: 42, hipB: -22, kneeB: 40 }, "out"),
        kf(3, { ...STANCE, free: 1, shoulderF: 154, elbowF: 16, weapon: 66, torso: -12 }),
        kf(7, { ...STANCE, free: 1, shoulderF: 62, elbowF: 20, weapon: -18, torso: 24, hipF: 38, kneeF: 34 }, "out"),
        kf(17, { ...STANCE, free: 1, shoulderF: 56, elbowF: 24, weapon: -14, torso: 20 }),
        kf(26, { ...STANCE, free: 1, hipF: 30, kneeF: 42, hipB: -22, kneeB: 40 }),
      ],
    },
    {
      id: "jC",
      name: "Pillar Drop",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 30,
      airborne: true,
      landCancel: true,
      landRecovery: 8,
      vel: [{ at: 6, y: -4.5, mode: "add" }],
      hits: [
        hit(8, 19, bx(-4, -8, 56, 52), 82, {
          guard: "overhead",
          fx: "blunt",
          knockdown: "soft",
          pushX: 4.8,
          shake: 1.6,
        }),
      ],
      desc: "Turns the staff vertical and rides it down. Crushes low blocks.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, torso: -20, shoulderF: 162, elbowF: 8, shoulderB: 150, elbowB: 12, weapon: 88, hipF: 42, kneeF: 62, hipB: -30, kneeB: 60 }),
        kf(9, { ...STANCE, free: 1, torso: 30, shoulderF: 22, elbowF: 18, shoulderB: 30, elbowB: 22, weapon: -70, hipF: 20, kneeF: 20, hipB: -16, kneeB: 24 }, "out"),
        kf(30, { ...STANCE, free: 1, torso: 24, shoulderF: 26, elbowF: 22, weapon: -66 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Running Thrust",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command"],
      priority: 12,
      duration: 34,
      vel: [
        { at: 4, x: 9 },
        { at: 18, x: 0 },
      ],
      friction: 0.89,
      hits: [
        hit(9, 16, bx(26, 26, 84, 58), 78, {
          fx: "blunt",
          pushX: 8,
          knockdown: "soft",
          hitstun: 22,
          shake: 1.5,
        }),
      ],
      desc: "Charges with the staff levelled. Enormous range on a running attack.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: 14, shoulderF: 30, elbowF: 70, weapon: 40, hipB: -32, kneeB: 46, offX: -2 }),
        kf(9, { ...STANCE, torso: 24, shoulderF: 78, elbowF: 4, weapon: 4, hipF: 42, kneeF: 24, hipB: -26, kneeB: 56, offX: 8 }, "out"),
        kf(22, { ...STANCE, torso: 20, shoulderF: 72, elbowF: 8, weapon: 6, hipF: 30, kneeF: 32 }),
        kf(34, { ...STANCE }),
      ],
    },

    // --------------------------------------------------------------- specials
    {
      id: "wheel",
      name: "Wheel the Staff",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 22,
      duration: 40,
      resourceCost: 20,
      resourceMin: 20,
      // Spinning the staff in front of you is how a monk deals with arrows,
      // and it is how he deals with fireballs here.
      invuln: [{ from: 5, to: 28, kind: "projectile" }],
      friction: 0.88,
      hits: [
        hit(7, 11, bx(22, 30, 62, 62), 26, { group: 1, fx: "blunt", pushX: 1.4, hitstun: 13, hitstop: 4 }),
        hit(14, 18, bx(22, 30, 62, 62), 26, { group: 2, fx: "blunt", pushX: 1.4, hitstun: 13, hitstop: 4 }),
        hit(21, 25, bx(22, 30, 62, 62), 26, { group: 3, fx: "blunt", pushX: 1.4, hitstun: 13, hitstop: 4 }),
        hit(28, 33, bx(20, 26, 72, 68), 58, {
          group: 4,
          fx: "blunt",
          pushX: 8,
          knockdown: "soft",
          hitstun: 22,
          shake: 1.5,
        }),
      ],
      desc: "Spins the staff into a wall in front of him. Nothing thrown gets through it, and it ends in a knockdown.",
      notation: "↓↙← + B  (20 Chi)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, weapon: 90, shoulderF: 60, elbowF: 40, torso: 4 }, "linear"),
        kf(12, { ...STANCE, weapon: 260, shoulderF: 64, elbowF: 36, torso: 6 }, "linear"),
        kf(19, { ...STANCE, weapon: 430, shoulderF: 60, elbowF: 40, torso: 4 }, "linear"),
        kf(26, { ...STANCE, weapon: 600, shoulderF: 64, elbowF: 36, torso: 6 }, "linear"),
        kf(28, { ...STANCE, weapon: 640, shoulderF: 84, elbowF: 12, torso: 26, hipF: 36, kneeF: 22, offX: 7 }, "out"),
        kf(36, { ...STANCE, weapon: 660, shoulderF: 62, elbowF: 40, torso: 12 }, "inOut"),
        kf(40, { ...STANCE, weapon: 674 }),
      ],
    },
    {
      id: "wheelEx",
      name: "Wheel EX",
      input: { button: "S", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "ex"],
      priority: 30,
      duration: 52,
      meterCost: 50,
      invuln: [
        { from: 3, to: 40, kind: "projectile" },
        { from: 3, to: 10, kind: "strike" },
      ],
      friction: 0.9,
      vel: [
        { at: 6, x: 3.5 },
        { at: 34, x: 0 },
      ],
      hits: [
        hit(6, 10, bx(22, 26, 66, 70), 30, { group: 1, fx: "blunt", pushX: 1.2, hitstun: 14, hitstop: 4 }),
        hit(13, 17, bx(22, 26, 66, 70), 30, { group: 2, fx: "blunt", pushX: 1.2, hitstun: 14, hitstop: 4 }),
        hit(20, 24, bx(22, 26, 66, 70), 30, { group: 3, fx: "blunt", pushX: 1.2, hitstun: 14, hitstop: 4 }),
        hit(27, 31, bx(22, 26, 66, 70), 30, { group: 4, fx: "blunt", pushX: 1.2, hitstun: 14, hitstop: 4 }),
        hit(36, 42, bx(18, 22, 82, 76), 74, {
          group: 5,
          fx: "blunt",
          pushX: 10,
          knockdown: "hard",
          hitstun: 26,
          shake: 2,
        }),
      ],
      desc: "EX. Invincible on startup, walks forward behind the wheel, and hard-knockdowns out of it.",
      notation: "↓↙← + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, weapon: 80, shoulderF: 60, elbowF: 40, torso: 4 }, "linear"),
        kf(12, { ...STANCE, weapon: 280, shoulderF: 64, elbowF: 36, torso: 6 }, "linear"),
        kf(20, { ...STANCE, weapon: 480, shoulderF: 60, elbowF: 40, torso: 4 }, "linear"),
        kf(28, { ...STANCE, weapon: 680, shoulderF: 64, elbowF: 36, torso: 6 }, "linear"),
        kf(34, { ...STANCE, weapon: 820, shoulderF: 150, elbowF: 20, torso: -16, offX: -4 }, "inOut"),
        kf(36, { ...STANCE, weapon: 856, shoulderF: 40, elbowF: 12, torso: 32, hipF: 42, kneeF: 26, offX: 10 }, "out"),
        kf(46, { ...STANCE, weapon: 866, shoulderF: 56, elbowF: 40, torso: 14, offX: 5 }, "inOut"),
        kf(52, { ...STANCE, weapon: 874 }),
      ],
    },
    {
      id: "vault",
      name: "Staff Vault",
      input: { button: "C", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "overhead"],
      priority: 24,
      duration: 46,
      airborne: true,
      resourceCost: 25,
      resourceMin: 25,
      vel: [
        { at: 4, x: 8, y: 11.5 },
        { at: 24, y: -0.8, mode: "add" },
      ],
      hits: [
        hit(16, 26, bx(12, 6, 60, 56), 86, {
          guard: "overhead",
          fx: "blunt",
          pushX: 6.5,
          knockdown: "hard",
          hitstun: 25,
          shake: 1.7,
        }),
      ],
      desc: "Plants the staff, swings over the top of their guard and lands both heels on them. Overhead.",
      notation: "↓↙← + C  (25 Chi)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.55, hipF: 22, kneeF: 46 }, "out"),
        kf(6, { ...STANCE, free: 1, torso: 18, shoulderF: 26, elbowF: 20, weapon: -76, hipF: -20, kneeF: 70, hipB: -34, kneeB: 60 }, "out"),
        kf(16, { ...STANCE, free: 1, torso: 28, shoulderF: 10, elbowF: 34, weapon: -84, hipF: 88, kneeF: 10, hipB: -30, kneeB: 48 }, "out"),
        kf(30, { ...STANCE, free: 1, torso: 20, shoulderF: 24, elbowF: 28, weapon: -60, hipF: 58, kneeF: 30, hipB: -24, kneeB: 44 }, "inOut"),
        kf(46, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "palm",
      name: "Iron Palm",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      priority: 20,
      duration: 38,
      resourceCost: 30,
      resourceMin: 30,
      meterGain: 6,
      projectiles: [
        {
          at: 13,
          kind: "chi",
          x: 34,
          y: 54,
          vx: 7.5,
          vy: 0,
          life: 90,
          box: { x: -16, y: -16, w: 32, h: 32 },
          damage: 52,
          hitstun: 20,
          blockstun: 13,
          chip: 6,
          pushX: 6,
          clashes: true,
          fx: "spark",
          color: "#ffe6a8",
          trail: "#c8722c",
          scale: 1.1,
        },
      ],
      desc: "Drives the breath out through an open palm. Slow-moving, and it walks him in behind it.",
      notation: "↓↘→ + B  (30 Chi)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderB: 20, elbowB: 96, torso: -10, crouch: 0.35, hipB: -28, kneeB: 46, offX: -4 }, "inOut"),
        kf(13, { ...STANCE, shoulderB: 84, elbowB: 4, torso: 22, hipF: 36, kneeF: 22, hipB: -20, kneeB: 46, offX: 7 }, "out"),
        kf(24, { ...STANCE, shoulderB: 76, elbowB: 16, torso: 16, offX: 4 }),
        kf(38, { ...STANCE }),
      ],
    },
    {
      id: "palmEx",
      name: "Iron Palm EX",
      input: { button: "S", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "projectile"],
      priority: 28,
      duration: 46,
      meterCost: 50,
      projectiles: [
        {
          at: 11,
          kind: "chi",
          x: 34,
          y: 56,
          vx: 6,
          vy: 0,
          life: 110,
          box: { x: -22, y: -22, w: 44, h: 44 },
          damage: 44,
          hitstun: 20,
          blockstun: 14,
          chip: 6,
          pushX: 4,
          hits: 2,
          clashes: true,
          fx: "spark",
          color: "#ffe6a8",
          trail: "#c8722c",
          scale: 1.5,
        },
        {
          at: 20,
          kind: "chi",
          x: 34,
          y: 56,
          vx: 10,
          vy: 0,
          life: 90,
          box: { x: -18, y: -18, w: 36, h: 36 },
          damage: 50,
          hitstun: 22,
          blockstun: 14,
          chip: 6,
          pushX: 8,
          knockdown: "soft",
          clashes: true,
          fx: "spark",
          color: "#ffe6a8",
          scale: 1.2,
        },
      ],
      desc: "EX. A slow wall followed by a fast one. They cannot jump both, and it costs no Chi.",
      notation: "↓↘→ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderB: 18, elbowB: 98, torso: -12, crouch: 0.35, offX: -4 }, "inOut"),
        kf(11, { ...STANCE, shoulderB: 86, elbowB: 2, torso: 24, offX: 7 }, "out"),
        kf(16, { ...STANCE, shoulderF: 18, elbowF: 96, torso: -10, offX: -3 }, "inOut"),
        kf(20, { ...STANCE, shoulderF: 88, elbowF: 0, torso: 26, hipF: 38, kneeF: 22, offX: 8 }, "out"),
        kf(34, { ...STANCE, torso: 12 }, "inOut"),
        kf(46, { ...STANCE }),
      ],
    },
    {
      id: "rise",
      name: "Rising Dragon Staff",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 26,
      duration: 46,
      airborne: true,
      resourceCost: 25,
      resourceMin: 25,
      invuln: [{ from: 1, to: 8, kind: "strike" }],
      vel: [
        { at: 1, x: 2, y: 12.6 },
        { at: 26, y: -1, mode: "add" },
      ],
      hits: [
        hit(3, 8, bx(2, 54, 62, 82), 78, {
          launch: [2, 11.5],
          knockdown: "launch",
          fx: "blunt",
          hitstun: 25,
          shake: 1.8,
        }),
        hit(9, 18, bx(0, 68, 58, 72), 36, { group: 2, launch: [1.6, 5.5], fx: "blunt", hitstun: 17 }),
      ],
      desc: "Rises with the staff turning end over end above him. Invincible on startup - his reversal.",
      notation: "→↓↘ + C  (25 Chi)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 22, kneeF: 50, hipB: -20, kneeB: 54 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -12, shoulderF: 150, elbowF: 14, weapon: 60, hipF: 32, kneeF: 30, hipB: -26, kneeB: 40 }, "out"),
        kf(12, { ...STANCE, free: 1, torso: -18, shoulderF: 168, elbowF: 8, weapon: 240, hipF: 26, kneeF: 26 }, "linear"),
        kf(30, { ...STANCE, free: 1, torso: -2, shoulderF: 116, elbowF: 30, weapon: 400, hipF: 30, kneeF: 42 }, "inOut"),
        kf(46, { ...STANCE, free: 1, weapon: 394 }),
      ],
    },
    {
      id: "bridge",
      name: "Crossing the Bridge",
      input: { button: "B", motion: "hcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 24,
      duration: 50,
      resourceCost: 20,
      resourceMin: 20,
      vel: [
        { at: 2, x: 3.2 },
        { at: 16, x: 3 },
        { at: 30, x: 3.4 },
        { at: 40, x: 0 },
      ],
      friction: 0.94,
      hits: [
        hit(8, 11, bx(32, 48, 88, 22), 32, { group: 1, fx: "blunt", pushX: 1.6, hitstun: 15, hitstop: 5 }),
        hit(20, 23, bx(32, 20, 90, 24), 32, { group: 2, fx: "blunt", guard: "low", pushX: 1.6, hitstun: 15, hitstop: 5 }),
        hit(32, 37, bx(28, 34, 96, 58), 60, {
          group: 3,
          fx: "blunt",
          pushX: 9,
          knockdown: "hard",
          hitstun: 24,
          shake: 1.7,
        }),
      ],
      desc: "Walks them down with three thrusts - high, low, then through. The low one in the middle is the whole trick.",
      notation: "←↙↓↘→ + B  (20 Chi)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 28, elbowF: 76, weapon: 48, torso: -4 }),
        kf(8, { ...STANCE, shoulderF: 76, elbowF: 6, weapon: 4, torso: 18, hipF: 32, kneeF: 20, offX: 6 }, "out"),
        kf(16, { ...STANCE, shoulderF: 30, elbowF: 72, weapon: 74, torso: 2, hipF: 18, kneeF: 30 }, "inOut"),
        kf(20, { ...STANCE, crouch: 0.55, shoulderF: 96, elbowF: 22, weapon: -40, torso: 26, hipF: 36, kneeF: 54, offX: 6 }, "out"),
        kf(28, { ...STANCE, shoulderF: 26, elbowF: 78, weapon: 56, torso: 0, hipF: 16, kneeF: 32 }, "inOut"),
        kf(32, { ...STANCE, shoulderF: 84, elbowF: 0, weapon: 2, torso: 28, hipF: 42, kneeF: 22, hipB: -24, kneeB: 50, offX: 10 }, "out"),
        kf(42, { ...STANCE, torso: 12 }, "inOut"),
        kf(50, { ...STANCE }),
      ],
    },
    {
      id: "still",
      name: "Sit Still",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill", "stance"],
      priority: 18,
      duration: 34,
      resourceGain: 40,
      friction: 0.84,
      // Sitting down in a fight is only a good idea if nothing can reach you
      // while you do it.
      invuln: [{ from: 4, to: 12, kind: "projectile" }],
      parryWindow: [5, 20],
      holdLoop: { from: 12, to: 22, button: "S", maxFrames: 90 },
      vfx: [{ at: 6, kind: "aura", x: 0, y: 44, scale: 1.4, color: "#ffe6a8" }],
      desc: "SKILL. Drops into a seated guard and breathes. Refills 40 Chi, deflects anything thrown at him, and parries strikes while you hold Guard.",
      notation: "A + C, hold S",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, crouch: 0.9, torso: 0, head: 4, hipF: 46, kneeF: 90, hipB: -30, kneeB: 96, shoulderF: 34, elbowF: 60, shoulderB: 38, elbowB: 58, weapon: 88 }, "inOut"),
        kf(12, { ...STANCE, crouch: 0.95, torso: -2, head: 6, hipF: 46, kneeF: 92, hipB: -30, kneeB: 98, shoulderF: 30, elbowF: 64, shoulderB: 34, elbowB: 62, weapon: 90 }),
        kf(22, { ...STANCE, crouch: 0.92, torso: 0, head: 4, hipF: 46, kneeF: 90, hipB: -30, kneeB: 96, shoulderF: 34, elbowF: 60, shoulderB: 38, elbowB: 58, weapon: 88 }),
        kf(34, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "Eighteen Hands",
      input: { button: "S", motion: "dd", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 98,
      meterCost: 100,
      superFreeze: 40,
      invuln: [{ from: 1, to: 14, kind: "strike" }],
      vel: [
        { at: 5, x: 9 },
        { at: 30, x: 5 },
        { at: 54, x: 3 },
        { at: 70, x: 0 },
      ],
      friction: 0.93,
      hits: [
        hit(12, 15, bx(24, 44, 76, 40), 42, { group: 1, fx: "blunt", pushX: 1, hitstun: 19, hitstop: 5 }),
        hit(20, 23, bx(24, 12, 78, 34), 38, { group: 2, fx: "blunt", pushX: 1, hitstun: 17, hitstop: 4 }),
        hit(28, 31, bx(24, 40, 78, 46), 38, { group: 3, fx: "blunt", pushX: 1, hitstun: 17, hitstop: 4 }),
        hit(36, 39, bx(24, 20, 80, 40), 38, { group: 4, fx: "blunt", pushX: 1, hitstun: 17, hitstop: 4 }),
        hit(44, 47, bx(24, 48, 80, 44), 38, { group: 5, fx: "blunt", pushX: 1, hitstun: 17, hitstop: 4 }),
        hit(60, 68, bx(16, 14, 92, 90), 134, {
          group: 6,
          fx: "blunt",
          pushX: 12,
          knockdown: "hard",
          launch: [5, 9],
          hitstop: 17,
          shake: 3,
        }),
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 48, scale: 2.4, color: "#ffe6a8" },
        { at: 60, kind: "explode", x: 56, y: 46, scale: 1.4 },
      ],
      desc: "SUPER. The whole staff form at once - five strikes high and low, then the crown strike he is not supposed to throw.",
      notation: "↓↓ + S  (100 meter)",
      frames: [
        kf(0, { ...STANCE, torso: -12, shoulderF: 30, elbowF: 70, weapon: 60, crouch: 0.4 }, "out"),
        kf(6, { ...STANCE, torso: 22, shoulderF: 76, elbowF: 6, weapon: 4, hipF: 38, kneeF: 22, offX: 6 }, "out"),
        kf(12, { ...STANCE, torso: 24, shoulderF: 72, elbowF: 2, weapon: 2, hipF: 40, kneeF: 20, offX: 8 }),
        kf(17, { ...STANCE, torso: 6, shoulderF: 18, elbowF: 56, weapon: 96 }, "inOut"),
        kf(20, { ...STANCE, torso: 26, shoulderF: 92, elbowF: 28, weapon: -46, offX: 7 }, "out"),
        kf(25, { ...STANCE, torso: 6, shoulderF: 146, elbowF: 20, weapon: 70 }, "inOut"),
        kf(28, { ...STANCE, torso: 24, shoulderF: 66, elbowF: 8, weapon: 0, offX: 7 }, "out"),
        kf(33, { ...STANCE, torso: 8, shoulderF: 20, elbowF: 58, weapon: 100 }, "inOut"),
        kf(36, { ...STANCE, torso: 26, shoulderF: 88, elbowF: 24, weapon: -40, offX: 7 }, "out"),
        kf(41, { ...STANCE, torso: 6, shoulderF: 148, elbowF: 18, weapon: 72 }, "inOut"),
        kf(44, { ...STANCE, torso: 24, shoulderF: 64, elbowF: 6, weapon: 2, offX: 7 }, "out"),
        kf(54, { ...STANCE, torso: -26, shoulderF: 176, elbowF: 4, shoulderB: 160, elbowB: 10, weapon: 92, hipB: -30, kneeB: 44, offX: -6 }, "inOut"),
        kf(60, { ...STANCE, torso: 40, shoulderF: 24, elbowF: 8, shoulderB: 32, elbowB: 12, weapon: -24, hipF: 46, kneeF: 28, hipB: -24, kneeB: 54, offX: 11 }, "out"),
        kf(80, { ...STANCE, torso: 24, shoulderF: 42, elbowF: 44, offX: 5 }, "inOut"),
        kf(98, { ...STANCE }),
      ],
    },
  ],
};
