/**
 * Sgt. Ray Calloway - infantry rifleman, 1965.
 *
 * A mid-range control character built around a magazine. The knife is his fast
 * button, the rifle is his heavy - one aimed shot at a time - and his specials
 * spend rounds in bulk: full auto, a sliding burst along the dirt, and a
 * grenade for everything hiding behind a block. Run dry and he has to reload.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const OLIVE = "#4f5d3a";
const KHAKI = "#8d8560";
const GUNMETAL = "#3f454b";
const BRASS = "#d9b25a";

const STANCE = {
  torso: 6,
  head: -3,
  hipF: 15,
  kneeF: 15,
  hipB: -18,
  kneeB: 28,
  // Rifle carried across the chest: back hand on the grip, front on the fore-end.
  shoulderF: 54,
  elbowF: 40,
  shoulderB: 34,
  elbowB: 54,
  weaponBack: -14,
};

export const SOLDIER: FighterDef = {
  id: "soldier",
  name: "The Ia Drang Trooper",
  title: "1st Cavalry Division",
  era: "Ia Drang Valley, 1965",
  bio: "Not a name - a composite. The 1st Cavalry troopers who were put down in the Ia Drang in November 1965 and had to hold a clearing the size of a football field. The unit, the valley and every piece of the kit are real; the man is all of them.",
  archetype: "Zoner / Resource",
  difficulty: 4,
  strengths: ["Controls midscreen with rounds", "Grenade beats blocking", "Fast knife pressure"],
  weaknesses: ["Twenty rounds and no more", "Reload is a commitment", "Weak once you are inside"],
  winQuote: "We held the LZ. That was the whole job.",
  palette: {
    body: "#e6dcc6",
    outline: "#171913",
    accent: OLIVE,
    cloth: OLIVE,
    metal: GUNMETAL,
    aura: "#a7d16a",
  },
  stats: {
    health: 970,
    walkF: 2.75,
    walkB: 2.35,
    dashSpeed: 8,
    dashFrames: 15,
    backdashFrames: 20,
    jumpVel: 12.1,
    jumpFwd: 4.6,
    gravity: 0.62,
    weight: 1.02,
    airMoves: 2,
    doubleJump: false,
    airDash: false,
    width: 20,
    standHeight: 104,
    crouchHeight: 66,
    scale: 1,
  },
  stance: STANCE,
  // High port: the rifle taken across the body and used like a quarterstaff.
  clips: guardClips({
    high: { torso: 0, head: -6, shoulderB: 34, elbowB: 92, weaponBack: -6, shoulderF: 116, elbowF: 32, hipF: 13, kneeF: 20, hipB: -18, kneeB: 32, offX: -2 },
    low: { torso: 8, head: -5, shoulderB: 40, elbowB: 86, weaponBack: -6, shoulderF: 110, elbowF: 36, hipF: 32, kneeF: 72, hipB: -20, kneeB: 82, offX: -2 },
  }),
  resource: {
    name: "Rounds",
    // Three magazines of thirty. One in the rifle, two on the belt - when
    // those are gone the rifle is a club, which is what the butt-strokes and
    // the knife are for.
    max: 30,
    start: 30,
    spares: 2,
    spareName: "Mags",
    color: BRASS,
  },
  props: [
    {
      id: "helmet",
      attach: "head",
      // M1 steel pot under a camouflage cover, band round the outside with
      // cigarettes and a bottle of bug juice tucked in it.
      parts: [
        { geo: "poly", size: [-13, -6, -13, 3, -8, 10, 0, 12, 8, 10, 13, 3, 13, -6, 8, -8, -8, -8], pos: [0, 2], color: OLIVE },
        // Camo blotches on the cover.
        { geo: "poly", size: [-5, 3, 0, 5, 4, 1, -1, -3], pos: [-5, 7], color: "#3c472c" },
        { geo: "poly", size: [-4, 2, 1, 4, 4, 0, -1, -3], pos: [6, 4], color: "#6a734a" },
        { geo: "box", size: [27, 3.5], pos: [0, 0], color: "#333d24" },
        { geo: "box", size: [7, 5], pos: [-8, 1], color: KHAKI },
        { geo: "box", size: [4, 6], pos: [8, 1], color: "#7d7a4a" },
        { geo: "box", size: [28, 4], pos: [0, -6], rot: -3, color: "#46512f" },
      ],
    },
    {
      id: "rifle",
      attach: "handB",
      // M16A1: slab receiver, triangular handguard, carry handle with the rear
      // sight on it, twenty-round mag and an A1 birdcage.
      parts: [
        { geo: "poly", size: [-14, 4, 14, 4, 14, -4, -14, -4], pos: [-2, 2], color: GUNMETAL },
        // Triangular handguard.
        { geo: "poly", size: [-11, 4.5, 12, 3.5, 12, -3.5, -11, -4.5], pos: [22, 2], color: "#2f353a" },
        { geo: "box", size: [22, 1.5], pos: [22, 4], color: "#4a5158" },
        // Carry handle and rear sight.
        { geo: "poly", size: [-11, 0, -9, 5, 9, 5, 11, 0], pos: [-2, 6], color: "#2f353a" },
        { geo: "box", size: [5, 4], pos: [-11, 9], color: "#22262a" },
        // Barrel, front sight post and flash hider.
        { geo: "cyl", size: [1.6, 22], pos: [44, 2], rot: 90, color: "#22262a" },
        { geo: "poly", size: [-2.5, 0, -2, 7, 2, 7, 2.5, 0], pos: [37, 4], color: "#2f353a" },
        { geo: "poly", size: [-5, 2.8, 5, 3.4, 5, -3.4, -5, -2.8], pos: [58, 2], color: "#3f454b" },
        // Magazine and pistol grip.
        { geo: "poly", size: [-3.5, 7, 3.5, 6, 4.5, -7, -2.5, -7], pos: [4, -8], rot: -6, color: "#2b3036" },
        { geo: "poly", size: [3, 4, -2, 3, -5, -7, 0, -8], pos: [-6, -6], color: "#22262a" },
        // Stock.
        { geo: "poly", size: [-9, 5, 9, 6, 9, -3, -9, -5], pos: [-24, 0], color: "#2b3036" },
        { geo: "box", size: [4, 9], pos: [-33, 0], color: "#1c2024" },
      ],
    },
    {
      id: "knife",
      attach: "handF",
      conditional: true,
      // Ka-Bar: clip point, stacked leather grip, steel pommel.
      parts: [
        { geo: "blade", size: [28, 5.5, 0.35], pos: [17, 0], color: "#cfd6de" },
        { geo: "box", size: [24, 1.2], pos: [16, 1.6], color: "#f0f4f8" },
        { geo: "box", size: [2.5, 11], pos: [2, 0], color: "#3f454b" },
        { geo: "poly", size: [-6, 3.4, 6, 3, 6, -3, -6, -3.4], pos: [-5, 0], color: "#4a3422" },
        { geo: "box", size: [3, 7], pos: [-12, 0], color: "#3f454b" },
      ],
    },
    {
      id: "vest",
      attach: "torso",
      // M69 flak jacket over a jungle fatigue shirt: quilted panels, big
      // pockets, grenades and a spare mag on the front.
      parts: [
        { geo: "poly", size: [-14, -17, 14, -17, 15, 6, 10, 17, -10, 17, -15, 6], pos: [0, 2], color: "#54633e" },
        { geo: "box", size: [28, 2], pos: [0, 12], color: "#46512f" },
        { geo: "box", size: [28, 2], pos: [0, 4], color: "#46512f" },
        { geo: "box", size: [27, 2], pos: [0, -4], color: "#46512f" },
        { geo: "box", size: [3, 34], pos: [0, 0], color: "#3c472c" },
        // Chest pockets.
        { geo: "poly", size: [-5, 5, 5, 5, 5, -5, -5, -5], pos: [-8, 6], color: "#3c472c" },
        { geo: "poly", size: [-5, 5, 5, 5, 5, -5, -5, -5], pos: [8, 6], color: "#3c472c" },
        // A grenade and a spare magazine hung off the webbing.
        { geo: "poly", size: [-3, 4, 3, 4, 3, -4, -3, -4], pos: [-9, -8], color: "#2f3a24", z: 0.3 },
        { geo: "box", size: [2, 3], pos: [-9, -3], color: KHAKI, z: 0.35 },
        { geo: "poly", size: [-3, 5, 3, 4, 3, -5, -3, -4], pos: [8, -8], color: "#2b3036", z: 0.3 },
        { geo: "poly", size: [-8, 15, 8, 14, 7, -15, -8, -14], pos: [-13, -6], rot: 6, color: "#46512f", behind: true },
      ],
    },
    {
      id: "webbing",
      attach: "pelvis",
      parts: [
        { geo: "poly", size: [-13, 3.5, 13, 3, 13, -3.5, -13, -4], pos: [0, 2], rot: -6, color: "#3c472c" },
        { geo: "poly", size: [-4, 4, 4, 4, 4, -4, -4, -4], pos: [0, 2], color: BRASS, z: 0.3 },
        { geo: "poly", size: [-5, 6, 5, 6, 4, -7, -4, -7], pos: [-10, -5], rot: 6, color: "#46512f" },
        { geo: "cyl", size: [4, 13], pos: [9, -4], rot: 84, color: "#5a6b3f" },
        { geo: "box", size: [9, 3], pos: [9, -4], rot: 84, color: "#7d8a5a" },
      ],
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 124,
      backThrowDamage: 134,
      throwRange: 58,
      rollSpeed: 8.2,
      weaponIdle: { weaponBack: STANCE.weaponBack },
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Knife Jab",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 12,
      showProps: ["knife"],
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [3, 11],
      // Knife Work string continues into 4A.
      followUps: [
        { button: "A", move: "4A", from: 3, to: 9, string: "Knife Work" },
      ],
      hits: [hit(3, 5, bx(16, 52, 44, 22), 30, { fx: "slash", hitstun: 14, blockstun: 10, pushX: 2.8 })],
      desc: "Three-frame knife jab. His fastest button, and the head of the knife string.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, shoulderF: 92, elbowF: 4, weapon: -8, torso: 14, offX: 4 }),
        kf(8, { ...STANCE, shoulderF: 64, elbowF: 30, weapon: -20, torso: 8 }, "inOut"),
        kf(12, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Rifle Butt",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 21,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [8, 19],
      // Butt-Strokes string continues into 6C.
      followUps: [
        { button: "C", move: "6C", from: 8, to: 18, string: "Butt-Strokes" },
      ],
      hits: [hit(8, 11, bx(20, 46, 58, 34), 54, { fx: "blunt", pushX: 4.6, hitstun: 17 })],
      desc: "Swings the stock into their jaw. Solid confirm into a shot.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderB: -20, elbowB: 84, weaponBack: 40, torso: -8, offX: -3 }),
        kf(8, { ...STANCE, shoulderB: 84, elbowB: 10, weaponBack: -46, torso: 20, hipF: 28, offX: 6 }, "out"),
        kf(14, { ...STANCE, shoulderB: 58, elbowB: 32, weaponBack: -24, torso: 12 }, "inOut"),
        kf(21, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Aimed Shot",
      input: { button: "C", stance: "stand" },
      tags: ["heavy", "projectile"],
      duration: 28,
      resourceCost: 1,
      resourceMin: 1,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 24],
      projectiles: [
        {
          at: 9,
          kind: "rifle",
          x: 48,
          y: 66,
          vx: 26,
          vy: 0,
          life: 50,
          box: { x: -12, y: -4, w: 24, h: 8 },
          damage: 60,
          hitstun: 20,
          blockstun: 13,
          chip: 5,
          pushX: 5,
          clashes: true,
          fx: "shot",
          color: "#fff0c0",
          trail: "#ffcf6b",
        },
      ],
      vfx: [{ at: 9, kind: "shot", x: 52, y: 66, scale: 1.1, color: "#fff0c0" }],
      desc: "Shoulders the rifle and puts one round downrange. Heavy button, one shot at a time.",
      notation: "C  (1 round)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 84, elbowF: 6, shoulderB: 74, elbowB: 10, weaponBack: -4, torso: 4, head: 2 }, "out"),
        kf(9, { ...STANCE, shoulderF: 86, elbowF: 4, shoulderB: 76, elbowB: 8, weaponBack: -2, torso: 2, offX: -2 }),
        kf(14, { ...STANCE, shoulderF: 90, elbowF: 2, shoulderB: 80, elbowB: 4, weaponBack: 6, torso: -4, offX: -4 }, "inOut"),
        kf(28, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Knife",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 13,
      showProps: ["knife"],
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [3, 12],
      hits: [hit(3, 5, bx(14, 12, 44, 22), 28, { guard: "low", fx: "slash", hitstun: 13, blockstun: 10, pushX: 2.6 })],
      desc: "Knife across the shins. His fastest low.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(3, { ...STANCE, crouch: 1, torso: 24, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderF: 98, elbowF: 40, weapon: -30, offX: 4 }),
        kf(8, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderF: 70, elbowF: 44, weapon: -10 }, "inOut"),
        kf(13, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "2B",
      name: "Crouch Shot",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "projectile"],
      duration: 26,
      resourceCost: 1,
      resourceMin: 1,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [10, 24],
      projectiles: [
        {
          at: 8,
          kind: "rifle",
          x: 46,
          y: 36,
          vx: 25,
          vy: 0,
          life: 50,
          box: { x: -12, y: -4, w: 24, h: 8 },
          damage: 46,
          hitstun: 18,
          blockstun: 12,
          chip: 4,
          pushX: 4,
          clashes: true,
          fx: "shot",
          color: "#fff0c0",
          trail: "#ffcf6b",
        },
      ],
      vfx: [{ at: 8, kind: "shot", x: 50, y: 36, scale: 1, color: "#fff0c0" }],
      desc: "Fires from a knee, under the usual jump-in arc.",
      notation: "↓ + B  (1 round)",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(6, { ...STANCE, crouch: 1, torso: 12, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderF: 78, elbowF: 10, shoulderB: 70, elbowB: 14, weaponBack: -6 }, "out"),
        kf(12, { ...STANCE, crouch: 1, torso: 8, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderF: 82, elbowF: 6, shoulderB: 74, elbowB: 10, weaponBack: 2, offX: -3 }, "inOut"),
        kf(26, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "2C",
      name: "Boot Sweep",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 30,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 26],
      hits: [hit(11, 15, bx(18, 2, 78, 24), 74, { guard: "low", knockdown: "sweep", fx: "blunt", pushX: 6 })],
      desc: "Takes their legs out with a low boot. Knockdown into grenade oki.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(6, { ...STANCE, crouch: 1, torso: 22, hipF: 8, kneeF: 94, hipB: -32, kneeB: 98, offX: -2 }),
        kf(11, { ...STANCE, crouch: 1, torso: 28, hipF: 82, kneeF: 8, hipB: -34, kneeB: 100, offX: 5 }, "out"),
        kf(20, { ...STANCE, crouch: 1, torso: 22, hipF: 50, kneeF: 50, hipB: -30, kneeB: 92 }, "inOut"),
        kf(30, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "6B",
      name: "Boot Stomp",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "overhead"],
      priority: 10,
      duration: 30,
      vel: [{ at: 5, x: 3 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [14, 26],
      hits: [hit(13, 17, bx(20, 34, 54, 50), 58, { guard: "overhead", fx: "blunt", pushX: 5, hitstun: 20 })],
      desc: "Stomping overhead. His only way through a low block without a grenade.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, crouch: 0.4, torso: 10, hipF: 16, kneeF: 56 }),
        kf(10, { ...STANCE, free: 1, offY: 12, torso: -8, hipF: -26, kneeF: 76, hipB: -28, kneeB: 56 }, "out"),
        kf(13, { ...STANCE, free: 1, offY: 6, torso: 24, hipF: 80, kneeF: 10, hipB: -24, kneeB: 66, offX: 4 }, "out"),
        kf(20, { ...STANCE, offY: 0, torso: 16, hipF: 40, kneeF: 40 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Stock Uppercut",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [11, 28],
      hits: [hit(9, 13, bx(12, 48, 58, 72), 72, { launch: [2, 12], knockdown: "launch", fx: "blunt", hitstun: 26 })],
      desc: "Drives the rifle stock up under their chin. Launches for a juggle.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 26, kneeF: 48 }, "out"),
        kf(5, { ...STANCE, crouch: 0.8, shoulderB: -16, elbowB: 76, weaponBack: 40, torso: 16 }),
        kf(9, { ...STANCE, torso: -14, shoulderB: 158, elbowB: -20, weaponBack: -40, hipF: 22, kneeF: 12, offY: 3 }, "out"),
        kf(17, { ...STANCE, torso: -10, shoulderB: 148, elbowB: -14, weaponBack: -34 }),
        kf(24, { ...STANCE, torso: 2, shoulderB: 60, elbowB: 30, weaponBack: -20 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },
    {
      // Forward and back sets. Forward takes space, back gives it up to buy
      // range or a hard read.
      id: "6A",
      name: "Muzzle Jab",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 20,
      vel: [{ at: 2, x: 2.2 }],
      friction: 0.88,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [7, 18],
      // Muzzle To Shot string continues into 5C.
      followUps: [
        { button: "C", move: "5C", from: 7, to: 17, string: "Muzzle To Shot" },
      ],
      hits: [hit(7, 9, bx(20, 60, 44, 26), 32, { guard: "high", fx: "blunt", pushX: 3, hitstun: 14, hitstop: 5 })],
      desc: "Steps in and jabs the muzzle into them. Short, fast, buys space to shoot.",
      notation: "\u2192 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderB: 44, elbowB: 62, weaponBack: -6, shoulderF: 66, elbowF: 32, torso: -2, offX: -2 }, "out"),
        // Rifle driven straight forward, held level in both hands.
        kf(7, { ...STANCE, shoulderB: 82, elbowB: 8, weaponBack: -4, shoulderF: 92, elbowF: -4, torso: 14, hipF: 24, kneeF: 16, offX: 7 }, "out"),
        kf(12, { ...STANCE, shoulderB: 66, elbowB: 28, weaponBack: -8, shoulderF: 78, elbowF: 14, torso: 10, offX: 5 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Vertical Butt-Stroke",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 40,
      armor: [{ from: 8, to: 18, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 8, x: 5.4 }, { at: 26, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [20, 36],
      // Butt-Strokes string continues into 4C.
      followUps: [
        { button: "C", move: "4C", from: 16, to: 37, string: "Butt-Strokes" },
      ],
      hits: [hit(16, 20, bx(20, 22, 84, 68), 90, { guard: "mid", fx: "blunt", pushX: 16, hitstun: 24, hitstop: 12, knockdown: "wallbounce", shake: 2.2 })],
      desc: "Steps through and drives the stock up under the jaw. Standard close-quarters drill.",
      notation: "\u2192 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderB: 18, elbowB: 88, weaponBack: -40, shoulderF: 34, elbowF: 66, torso: -12, hipB: -30, kneeB: 48, crouch: 0.24, offX: -6 }, "out"),
        // Butt swung up and forward, muzzle dropping behind.
        kf(16, { ...STANCE, shoulderB: 96, elbowB: -18, weaponBack: 44, shoulderF: 112, elbowF: -26, torso: 26, hipF: 40, kneeF: 18, hipB: -24, kneeB: 24, offX: 12 }, "out"),
        kf(24, { ...STANCE, shoulderB: 86, elbowB: -10, weaponBack: 38, shoulderF: 102, elbowF: -18, torso: 20, hipF: 28, kneeF: 24, offX: 8 }),
        kf(32, { ...STANCE, shoulderB: 50, elbowB: 40, weaponBack: -2, torso: 10, offX: 3 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Knife Slash",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 22,
      vel: [{ at: 1, x: -2.6 }],
      friction: 0.86,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [8, 20],
      // Knife Work string continues into 2A.
      followUps: [
        { button: "A", move: "2A", from: 8, to: 19, string: "Knife Work" },
      ],
      hits: [hit(8, 10, bx(16, 52, 42, 30), 36, { guard: "mid", fx: "slash", pushX: 6, hitstun: 15, hitstop: 6 })],
      desc: "Steps back and cuts across with the knife. Keeps hands off him.",
      notation: "\u2190 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -6, shoulderF: 26, elbowF: 86, weapon: 40, hipB: -26, kneeB: 40, offX: -6 }, "out"),
        kf(8, { ...STANCE, torso: 8, shoulderF: 78, elbowF: 18, weapon: -12, hipF: 22, kneeF: 16, offX: -3 }, "out"),
        kf(14, { ...STANCE, torso: 2, shoulderF: 58, elbowF: 44, weapon: 12, offX: -4 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Bayonet Reach",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 30,
      vel: [{ at: 1, x: -3.4 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      hits: [hit(12, 15, bx(42, 50, 100, 22), 56, { guard: "mid", fx: "pierce", pushX: 7, hitstun: 18, hitstop: 8 })],
      desc: "Gives ground and holds the muzzle out at full stretch. His longest melee.",
      notation: "\u2190 + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderB: 40, elbowB: 60, weaponBack: -10, torso: -12, hipB: -28, kneeB: 42, offX: -8 }, "inOut"),
        kf(12, { ...STANCE, shoulderB: 86, elbowB: 2, weaponBack: -2, shoulderF: 94, elbowF: -8, torso: 4, hipF: 26, kneeF: 14, offX: -5 }, "out"),
        kf(17, { ...STANCE, shoulderB: 84, elbowB: 4, weaponBack: -2, shoulderF: 92, elbowF: -6, torso: 2, offX: -6 }),
        kf(23, { ...STANCE, shoulderB: 60, elbowB: 34, weaponBack: -10, torso: 0, offX: -4 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Smash Butt-Stroke",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 44,
      cancelInto: ["special", "super"],
      cancelWindow: [26, 40],
      hits: [hit(20, 23, bx(16, 20, 92, 86), 98, { guard: "overhead", fx: "blunt", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 })],
      desc: "Rifle over the shoulder and the stock brought down. Blocked standing only.",
      notation: "\u2190 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderB: 150, elbowB: -60, weaponBack: 66, torso: -10, offX: -5 }, "inOut"),
        // Stock up over the shoulder, muzzle down behind him.
        kf(15, { ...STANCE, shoulderB: 188, elbowB: -34, weaponBack: 84, torso: -20, hipB: -26, kneeB: 38, offY: 3, offX: -3 }, "out"),
        kf(20, { ...STANCE, shoulderB: 92, elbowB: 6, weaponBack: 40, torso: 32, hipF: 34, kneeF: 16, hipB: -12, kneeB: 32, offX: 6 }, "out"),
        kf(26, { ...STANCE, shoulderB: 84, elbowB: 10, weaponBack: 36, torso: 26, offX: 4 }),
        kf(36, { ...STANCE, shoulderB: 52, elbowB: 40, weaponBack: -4, torso: 8 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Knife",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 18,
      airborne: true,
      showProps: ["knife"],
      landCancel: true,
      landRecovery: 2,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [4, 16],
      hits: [hit(4, 9, bx(14, 32, 46, 30), 32, { fx: "slash", hitstun: 14, pushX: 2.6 })],
      desc: "Quick knife slash out of a jump.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 32, kneeF: 42, hipB: -22, kneeB: 40 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderF: 94, elbowF: 12, weapon: -16, torso: 12 }),
        kf(11, { ...STANCE, free: 1, shoulderF: 62, elbowF: 36, weapon: -6, torso: 6 }, "inOut"),
        kf(18, { ...STANCE, free: 1, hipF: 32, kneeF: 42, hipB: -22, kneeB: 40 }),
      ],
    },
    {
      id: "jB",
      name: "Air Kick",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 24,
      airborne: true,
      landCancel: true,
      landRecovery: 4,
      hits: [hit(6, 13, bx(20, 16, 60, 42), 54, { fx: "blunt", pushX: 4, hitstun: 18 })],
      desc: "Forward boot with good horizontal range.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 30, kneeF: 40, hipB: -22, kneeB: 38 }, "out"),
        kf(4, { ...STANCE, free: 1, hipF: 4, kneeF: 90, torso: 10 }),
        kf(7, { ...STANCE, free: 1, hipF: 76, kneeF: 8, hipB: -26, kneeB: 44, torso: 18 }, "out"),
        kf(16, { ...STANCE, free: 1, hipF: 50, kneeF: 40, torso: 10 }, "inOut"),
        kf(24, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "jC",
      name: "Rifle Smash",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 28,
      airborne: true,
      landCancel: true,
      landRecovery: 7,
      hits: [
        hit(8, 18, bx(2, -2, 58, 46), 80, {
          guard: "overhead",
          fx: "blunt",
          knockdown: "soft",
          pushX: 5,
          shake: 1.5,
        }),
      ],
      desc: "Brings the rifle down two-handed. His jump-in.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, torso: -22, shoulderB: 168, elbowB: -12, shoulderF: 158, elbowF: -8, weaponBack: 30, hipF: 40, kneeF: 56 }),
        kf(9, { ...STANCE, free: 1, torso: 30, shoulderB: 24, elbowB: 14, shoulderF: 30, elbowF: 10, weaponBack: -44, hipF: 16, kneeF: 20 }, "out"),
        kf(28, { ...STANCE, free: 1, torso: 24, shoulderB: 28, elbowB: 18, weaponBack: -40 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Bayonet Rush",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command"],
      priority: 12,
      duration: 34,
      vel: [
        { at: 3, x: 9.6 },
        { at: 16, x: 0 },
      ],
      friction: 0.9,
      hits: [hit(8, 14, bx(24, 30, 70, 52), 76, { fx: "pierce", pushX: 8, knockdown: "soft", hitstun: 22, shake: 1.5 })],
      desc: "Sprints in behind the muzzle. Covers ground fast.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 26, shoulderB: 54, elbowB: 26, weaponBack: -26, hipB: -32, kneeB: 50, offX: -3 }),
        kf(8, { ...STANCE, torso: 32, shoulderB: 86, elbowB: -2, weaponBack: -14, hipF: 44, kneeF: 24, hipB: -26, kneeB: 56, offX: 9 }, "out"),
        kf(22, { ...STANCE, torso: 22, shoulderB: 66, elbowB: 16, offX: 4 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },

    // -------------------------------------------------------- five specials
    {
      id: "fullAuto",
      name: "Full Auto",
      input: { button: "C", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      priority: 20,
      duration: 52,
      resourceCost: 8,
      resourceMin: 8,
      friction: 0.9,
      vel: [{ at: 10, x: -1.2 }],
      projectiles: [
        { at: 8, kind: "rifle", x: 46, y: 68, vx: 25, vy: 0, life: 46, box: { x: -12, y: -4, w: 24, h: 8 }, damage: 26, hitstun: 14, blockstun: 10, chip: 2, pushX: 1.2, clashes: true, fx: "shot", color: "#fff0c0", trail: "#ffcf6b" },
        { at: 12, kind: "rifle", x: 46, y: 64, vx: 25, vy: 0, life: 46, box: { x: -12, y: -4, w: 24, h: 8 }, damage: 24, hitstun: 14, blockstun: 10, chip: 2, pushX: 1.2, clashes: true, fx: "shot", color: "#fff0c0", trail: "#ffcf6b" },
        { at: 16, kind: "rifle", x: 46, y: 60, vx: 25, vy: 0, life: 46, box: { x: -12, y: -4, w: 24, h: 8 }, damage: 24, hitstun: 14, blockstun: 10, chip: 2, pushX: 1.2, clashes: true, fx: "shot", color: "#fff0c0", trail: "#ffcf6b" },
        { at: 20, kind: "rifle", x: 46, y: 56, vx: 25, vy: 0, life: 46, box: { x: -12, y: -4, w: 24, h: 8 }, damage: 22, hitstun: 14, blockstun: 10, chip: 2, pushX: 1.2, clashes: true, fx: "shot", color: "#fff0c0", trail: "#ffcf6b" },
        { at: 24, kind: "rifle", x: 46, y: 54, vx: 25, vy: 0, life: 46, box: { x: -12, y: -4, w: 24, h: 8 }, damage: 22, hitstun: 14, blockstun: 10, chip: 2, pushX: 1.2, clashes: true, fx: "shot", color: "#fff0c0", trail: "#ffcf6b" },
        { at: 28, kind: "rifle", x: 46, y: 52, vx: 26, vy: 0, life: 46, box: { x: -12, y: -4, w: 24, h: 8 }, damage: 22, hitstun: 14, blockstun: 10, chip: 2, pushX: 1.2, clashes: true, fx: "shot", color: "#fff0c0", trail: "#ffcf6b" },
        { at: 32, kind: "rifle", x: 46, y: 50, vx: 26, vy: 0, life: 46, box: { x: -12, y: -4, w: 24, h: 8 }, damage: 22, hitstun: 15, blockstun: 10, chip: 2, pushX: 1.2, clashes: true, fx: "shot", color: "#fff0c0", trail: "#ffcf6b" },
        { at: 36, kind: "rifle", x: 46, y: 48, vx: 26, vy: 0, life: 46, box: { x: -12, y: -4, w: 24, h: 8 }, damage: 34, hitstun: 24, blockstun: 13, chip: 4, pushX: 9, knockdown: "soft", clashes: true, fx: "shot", color: "#fff6dd", trail: "#ffcf6b" },
      ],
      vfx: [
        { at: 8, kind: "shot", x: 50, y: 68, scale: 1, color: "#fff0c0" },
        { at: 16, kind: "shot", x: 50, y: 60, scale: 1, color: "#fff0c0" },
        { at: 24, kind: "shot", x: 50, y: 54, scale: 1, color: "#fff0c0" },
        { at: 32, kind: "shot", x: 50, y: 50, scale: 1.1, color: "#fff0c0" },
        { at: 36, kind: "shot", x: 50, y: 48, scale: 1.3, color: "#fff6dd" },
      ],
      desc: "Empties eight rounds on the trigger. The muzzle climbs as it goes, so the burst walks upward - the last shot knocks down.",
      notation: "↓↘→ + C  (8 rounds)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 82, elbowF: 8, shoulderB: 72, elbowB: 12, weaponBack: -6, torso: 8 }, "out"),
        kf(12, { ...STANCE, shoulderF: 84, elbowF: 6, shoulderB: 74, elbowB: 10, weaponBack: -2, torso: 4, offX: -2 }),
        kf(20, { ...STANCE, shoulderF: 88, elbowF: 4, shoulderB: 78, elbowB: 8, weaponBack: 4, torso: 0, offX: -4 }),
        kf(28, { ...STANCE, shoulderF: 92, elbowF: 2, shoulderB: 82, elbowB: 6, weaponBack: 10, torso: -4, offX: -6 }),
        kf(36, { ...STANCE, shoulderF: 96, elbowF: 0, shoulderB: 86, elbowB: 4, weaponBack: 16, torso: -8, offX: -7 }),
        kf(44, { ...STANCE, shoulderF: 74, elbowF: 18, weaponBack: -6, torso: 2, offX: -2 }, "inOut"),
        kf(52, { ...STANCE }),
      ],
    },
    {
      id: "slideShoot",
      name: "Slide Shoot",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile", "low"],
      duration: 44,
      resourceCost: 3,
      resourceMin: 3,
      hurtbox: { x: -20, y: 0, w: 52, h: 40 },
      invuln: [{ from: 6, to: 20, kind: "projectile" }],
      vel: [
        { at: 4, x: 11 },
        { at: 26, x: 0 },
      ],
      friction: 0.9,
      hits: [hit(6, 16, bx(16, 0, 56, 28), 42, { guard: "low", fx: "blunt", pushX: 4, hitstun: 18 })],
      projectiles: [
        { at: 10, kind: "rifle", x: 40, y: 26, vx: 24, vy: 1.4, life: 46, box: { x: -12, y: -4, w: 24, h: 8 }, damage: 30, hitstun: 16, blockstun: 11, chip: 3, pushX: 2, clashes: true, fx: "shot", color: "#fff0c0", trail: "#ffcf6b" },
        { at: 15, kind: "rifle", x: 40, y: 28, vx: 24, vy: 2.2, life: 46, box: { x: -12, y: -4, w: 24, h: 8 }, damage: 28, hitstun: 16, blockstun: 11, chip: 3, pushX: 2, clashes: true, fx: "shot", color: "#fff0c0", trail: "#ffcf6b" },
        { at: 20, kind: "rifle", x: 40, y: 30, vx: 24, vy: 3, life: 46, box: { x: -12, y: -4, w: 24, h: 8 }, damage: 36, hitstun: 24, blockstun: 13, chip: 4, pushX: 8, knockdown: "soft", clashes: true, fx: "shot", color: "#fff6dd", trail: "#ffcf6b" },
      ],
      vfx: [
        { at: 10, kind: "dust", x: -10, y: 2, scale: 1.2 },
        { at: 10, kind: "shot", x: 44, y: 26, scale: 1, color: "#fff0c0" },
        { at: 15, kind: "shot", x: 44, y: 28, scale: 1, color: "#fff0c0" },
        { at: 20, kind: "shot", x: 44, y: 30, scale: 1.2, color: "#fff6dd" },
      ],
      desc: "Slides in under fire on his hip, firing upward as he goes. The slide hits low and ducks projectiles.",
      notation: "↓↘→ + B  (3 rounds)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 34, squash: 0.86, hipF: 74, kneeF: 30, hipB: -18, kneeB: 96, shoulderF: 66, elbowF: 16, shoulderB: 56, elbowB: 20, weaponBack: -30, offY: -2 }, "out"),
        kf(12, { ...STANCE, crouch: 1, torso: 36, squash: 0.84, hipF: 78, kneeF: 26, hipB: -16, kneeB: 100, shoulderF: 70, elbowF: 12, shoulderB: 60, elbowB: 16, weaponBack: -34 }),
        kf(22, { ...STANCE, crouch: 1, torso: 32, squash: 0.86, hipF: 70, kneeF: 34, hipB: -20, kneeB: 94, shoulderF: 64, elbowF: 18, weaponBack: -28 }),
        kf(34, { ...STANCE, crouch: 0.8, torso: 22, hipF: 40, kneeF: 70, hipB: -24, kneeB: 80 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "frag",
      name: "Frag Out",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      priority: 18,
      duration: 40,
      projectiles: [
        {
          at: 12,
          kind: "grenade",
          x: 28,
          y: 74,
          vx: 7,
          vy: 7.5,
          gravity: 0.42,
          bounce: 0.42,
          bounces: 2,
          life: 76,
          box: { x: -9, y: -9, w: 18, h: 18 },
          damage: 34,
          hitstun: 18,
          blockstun: 12,
          pushX: 3,
          fx: "explode",
          color: "#4f5d3a",
          spin: 12,
          detonate: {
            radius: 78,
            damage: 74,
            hitstun: 28,
            blockstun: 16,
            knockdown: "hard",
            chip: 8,
          },
        },
      ],
      desc: "Lobs a frag in an arc. It skips off the dirt twice, then goes off - blocking only saves you from part of it.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderF: -84, elbowF: 60, torso: -16, offX: -4 }, "inOut"),
        kf(12, { ...STANCE, shoulderF: 128, elbowF: -18, torso: 18, hipF: 30, kneeF: 20, offX: 5 }, "out"),
        kf(22, { ...STANCE, shoulderF: 70, elbowF: 22, torso: 8 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "flakRise",
      name: "Stock Rise",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 24,
      duration: 44,
      airborne: true,
      invuln: [{ from: 1, to: 8, kind: "strike" }],
      vel: [
        { at: 1, x: 2.4, y: 12 },
        { at: 24, y: -0.9, mode: "add" },
      ],
      hits: [
        hit(3, 9, bx(8, 48, 60, 78), 82, { launch: [2.2, 10.5], knockdown: "launch", fx: "blunt", hitstun: 26, shake: 1.8 }),
        hit(10, 17, bx(6, 60, 54, 68), 34, { group: 2, launch: [1.4, 5], fx: "blunt" }),
      ],
      desc: "Invincible rising rifle-butt. His reversal and his anti-air.",
      notation: "→↓↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 48 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -14, shoulderB: 158, elbowB: -22, weaponBack: -40, hipF: 30, kneeF: 30 }, "out"),
        kf(14, { ...STANCE, free: 1, torso: -20, shoulderB: 176, elbowB: -14, weaponBack: -32, hipF: 26, kneeF: 26 }),
        kf(30, { ...STANCE, free: 1, torso: -4, shoulderB: 110, elbowB: 10, weaponBack: -20 }, "inOut"),
        kf(44, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "bayonetCharge",
      name: "Bayonet Charge",
      input: { button: "B", motion: "hcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 22,
      duration: 50,
      armor: [{ from: 3, to: 26, hits: 1, damageScale: 0.35 }],
      vel: [
        { at: 2, x: 7.5 },
        { at: 22, x: 6 },
        { at: 36, x: 0 },
      ],
      friction: 0.92,
      hits: [
        hit(10, 14, bx(26, 40, 72, 26), 44, { group: 1, fx: "pierce", pushX: 1.6, hitstun: 18, hitstop: 5 }),
        hit(22, 28, bx(24, 30, 80, 46), 72, {
          group: 2,
          fx: "pierce",
          pushX: 12,
          knockdown: "wallbounce",
          hitstun: 26,
          shake: 2,
        }),
      ],
      desc: "Fixed bayonet, straight down the line. Absorbs a hit and carries them to the corner.",
      notation: "←↙↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, torso: 22, shoulderB: 60, elbowB: 16, weaponBack: -22, hipF: 30, kneeF: 22, offX: 3 }),
        kf(10, { ...STANCE, torso: 26, shoulderB: 84, elbowB: -4, weaponBack: -12, hipF: 36, kneeF: 20, offX: 7 }, "out"),
        kf(18, { ...STANCE, torso: 20, shoulderB: 62, elbowB: 14, weaponBack: -24, hipF: 20, kneeF: 32 }, "inOut"),
        kf(22, { ...STANCE, torso: 32, shoulderB: 92, elbowB: -10, weaponBack: -6, hipF: 44, kneeF: 24, hipB: -26, kneeB: 56, offX: 10 }, "out"),
        kf(38, { ...STANCE, torso: 18, shoulderB: 60, elbowB: 18, offX: 4 }, "inOut"),
        kf(50, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- skill
    {
      id: "reload",
      name: "Reload",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill"],
      priority: 18,
      duration: 54,
      resourceGain: 30,
      meterGain: 10,
      friction: 0.9,
      desc: "SKILL. Drops the magazine and seats a fresh one - all twenty rounds. Long enough that they will make you pay if they are close.",
      notation: "A + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(10, { ...STANCE, shoulderF: 20, elbowF: 84, shoulderB: 40, elbowB: 56, weaponBack: -30, torso: 12, head: 6 }, "inOut"),
        kf(22, { ...STANCE, shoulderF: 8, elbowF: 96, shoulderB: 44, elbowB: 60, weaponBack: -36, torso: 16, head: 8 }),
        kf(34, { ...STANCE, shoulderF: 30, elbowF: 72, shoulderB: 38, elbowB: 52, weaponBack: -26, torso: 10, head: 4 }, "inOut"),
        kf(44, { ...STANCE, shoulderF: 48, elbowF: 48, weaponBack: -18, torso: 6 }, "inOut"),
        kf(54, { ...STANCE }),
      ],
    },

    // ------------------------------------------------------------------ EX
    {
      id: "fullAutoEx",
      name: "Full Auto EX",
      input: { button: "S", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "projectile"],
      priority: 26,
      duration: 54,
      meterCost: 50,
      friction: 0.9,
      projectiles: [
        { at: 6, kind: "rifle", x: 46, y: 70, vx: 27, vy: 0, life: 50, box: { x: -13, y: -5, w: 26, h: 10 }, damage: 24, hitstun: 15, blockstun: 10, chip: 3, pushX: 1, hits: 2, fx: "shot", color: "#fff6dd", trail: "#ffcf6b" },
        { at: 10, kind: "rifle", x: 46, y: 64, vx: 27, vy: 0, life: 50, box: { x: -13, y: -5, w: 26, h: 10 }, damage: 22, hitstun: 15, blockstun: 10, chip: 3, pushX: 1, hits: 2, fx: "shot", color: "#fff6dd", trail: "#ffcf6b" },
        { at: 14, kind: "rifle", x: 46, y: 58, vx: 27, vy: 0, life: 50, box: { x: -13, y: -5, w: 26, h: 10 }, damage: 22, hitstun: 15, blockstun: 10, chip: 3, pushX: 1, hits: 2, fx: "shot", color: "#fff6dd", trail: "#ffcf6b" },
        { at: 18, kind: "rifle", x: 46, y: 52, vx: 27, vy: 0, life: 50, box: { x: -13, y: -5, w: 26, h: 10 }, damage: 22, hitstun: 15, blockstun: 10, chip: 3, pushX: 1, hits: 2, fx: "shot", color: "#fff6dd", trail: "#ffcf6b" },
        { at: 22, kind: "rifle", x: 46, y: 48, vx: 27, vy: 0, life: 50, box: { x: -13, y: -5, w: 26, h: 10 }, damage: 22, hitstun: 15, blockstun: 10, chip: 3, pushX: 1, hits: 2, fx: "shot", color: "#fff6dd", trail: "#ffcf6b" },
        { at: 26, kind: "rifle", x: 46, y: 44, vx: 28, vy: 0, life: 50, box: { x: -13, y: -5, w: 26, h: 10 }, damage: 22, hitstun: 15, blockstun: 10, chip: 3, pushX: 1, hits: 2, fx: "shot", color: "#fff6dd", trail: "#ffcf6b" },
        { at: 30, kind: "rifle", x: 46, y: 40, vx: 28, vy: 0, life: 50, box: { x: -13, y: -5, w: 26, h: 10 }, damage: 24, hitstun: 16, blockstun: 11, chip: 3, pushX: 1, hits: 2, fx: "shot", color: "#fff6dd", trail: "#ffcf6b" },
        { at: 34, kind: "rifle", x: 46, y: 38, vx: 28, vy: 0, life: 50, box: { x: -13, y: -5, w: 26, h: 10 }, damage: 40, hitstun: 26, blockstun: 14, chip: 5, pushX: 11, knockdown: "hard", hits: 2, fx: "shot", color: "#ffffff", trail: "#fff2c9" },
      ],
      vfx: [
        { at: 6, kind: "shot", x: 50, y: 70, scale: 1.2, color: "#fff6dd" },
        { at: 14, kind: "shot", x: 50, y: 58, scale: 1.2, color: "#fff6dd" },
        { at: 22, kind: "shot", x: 50, y: 48, scale: 1.2, color: "#fff6dd" },
        { at: 34, kind: "shot", x: 50, y: 38, scale: 1.5, color: "#ffffff" },
      ],
      desc: "EX. Eight rounds that punch through anything in the air, and no magazine cost.",
      notation: "↓↘→ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderF: 84, elbowF: 6, shoulderB: 74, elbowB: 10, weaponBack: -4, torso: 6 }, "out"),
        kf(14, { ...STANCE, shoulderF: 90, elbowF: 2, shoulderB: 80, elbowB: 6, weaponBack: 6, torso: 0, offX: -3 }),
        kf(26, { ...STANCE, shoulderF: 96, elbowF: -2, shoulderB: 86, elbowB: 2, weaponBack: 16, torso: -6, offX: -6 }),
        kf(34, { ...STANCE, shoulderF: 102, elbowF: -4, shoulderB: 92, elbowB: 0, weaponBack: 22, torso: -10, offX: -8 }),
        kf(44, { ...STANCE, shoulderF: 74, elbowF: 18, weaponBack: -4, torso: 2, offX: -2 }, "inOut"),
        kf(54, { ...STANCE }),
      ],
    },
    {
      id: "fragEx",
      name: "Frag Out EX",
      input: { button: "S", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "projectile"],
      priority: 26,
      duration: 46,
      meterCost: 50,
      projectiles: [
        {
          at: 10,
          kind: "grenade",
          x: 28,
          y: 74,
          vx: 4.5,
          vy: 8,
          gravity: 0.42,
          bounce: 0.4,
          bounces: 1,
          life: 70,
          box: { x: -9, y: -9, w: 18, h: 18 },
          damage: 30,
          hitstun: 18,
          blockstun: 12,
          pushX: 3,
          fx: "explode",
          color: "#4f5d3a",
          spin: 14,
          detonate: { radius: 74, damage: 62, hitstun: 26, blockstun: 15, knockdown: "hard", chip: 6 },
        },
        {
          at: 16,
          kind: "grenade",
          x: 28,
          y: 74,
          vx: 9.5,
          vy: 6.4,
          gravity: 0.42,
          bounce: 0.4,
          bounces: 1,
          life: 70,
          box: { x: -9, y: -9, w: 18, h: 18 },
          damage: 30,
          hitstun: 18,
          blockstun: 12,
          pushX: 3,
          fx: "explode",
          color: "#5a6b3f",
          spin: -14,
          detonate: { radius: 80, damage: 68, hitstun: 28, blockstun: 16, knockdown: "hard", chip: 7 },
        },
      ],
      desc: "EX. Two frags, short and long. There is no gap between them to walk through.",
      notation: "↓↙← + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: -90, elbowF: 64, torso: -18, offX: -5 }, "inOut"),
        kf(10, { ...STANCE, shoulderF: 124, elbowF: -14, torso: 16, offX: 4 }, "out"),
        kf(13, { ...STANCE, shoulderF: -76, elbowF: 58, torso: -12, offX: -3 }, "inOut"),
        kf(16, { ...STANCE, shoulderF: 132, elbowF: -20, torso: 20, hipF: 30, kneeF: 20, offX: 6 }, "out"),
        kf(28, { ...STANCE, shoulderF: 62, elbowF: 26, torso: 6 }, "inOut"),
        kf(46, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "Danger Close",
      input: { button: "S", motion: "hcf", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 120,
      meterCost: 100,
      superFreeze: 46,
      invuln: [{ from: 1, to: 20, kind: "strike" }],
      friction: 0.9,
      projectiles: [
        {
          at: 30,
          kind: "grenade",
          x: 120,
          y: 300,
          vx: 2,
          vy: -6,
          gravity: 0.3,
          life: 60,
          box: { x: -12, y: -12, w: 24, h: 24 },
          damage: 40,
          hitstun: 22,
          blockstun: 14,
          pushX: 4,
          fx: "explode",
          color: "#2f353a",
          spin: 20,
          detonate: { radius: 86, damage: 60, hitstun: 26, blockstun: 15, knockdown: "hard", chip: 8 },
        },
        {
          at: 44,
          kind: "grenade",
          x: 230,
          y: 320,
          vx: -1,
          vy: -6,
          gravity: 0.3,
          life: 60,
          box: { x: -12, y: -12, w: 24, h: 24 },
          damage: 40,
          hitstun: 22,
          blockstun: 14,
          pushX: 4,
          fx: "explode",
          color: "#2f353a",
          spin: -20,
          detonate: { radius: 86, damage: 60, hitstun: 26, blockstun: 15, knockdown: "hard", chip: 8 },
        },
        {
          at: 58,
          kind: "grenade",
          x: 60,
          y: 320,
          vx: 3,
          vy: -7,
          gravity: 0.32,
          life: 60,
          box: { x: -14, y: -14, w: 28, h: 28 },
          damage: 60,
          hitstun: 30,
          blockstun: 18,
          pushX: 10,
          knockdown: "hard",
          fx: "explode",
          color: "#2f353a",
          spin: 24,
          detonate: { radius: 110, damage: 96, hitstun: 34, blockstun: 18, knockdown: "hard", chip: 12 },
        },
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 50, scale: 2.6, color: "#a7d16a" },
        { at: 26, kind: "spark", x: 40, y: 90, scale: 1.4, color: "#a7d16a" },
      ],
      desc: "SUPER. Calls the coordinates in on his own position and waits. Three walking impacts, the last one right on top of you.",
      notation: "←↙↓↘→ + S  (100 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(10, { ...STANCE, shoulderF: 30, elbowF: 96, torso: 6, head: 8, weaponBack: -30 }, "inOut"),
        kf(24, { ...STANCE, shoulderF: 26, elbowF: 104, torso: 8, head: 10, weaponBack: -34 }),
        kf(34, { ...STANCE, crouch: 0.7, torso: 22, head: -8, shoulderF: 40, elbowF: 70, shoulderB: 44, elbowB: 50, hipF: 30, kneeF: 60, hipB: -22, kneeB: 66 }, "out"),
        kf(70, { ...STANCE, crouch: 0.7, torso: 24, head: -10, shoulderF: 44, elbowF: 66, hipF: 30, kneeF: 62 }),
        kf(90, { ...STANCE, crouch: 0.3, torso: 12, head: -2 }, "inOut"),
        kf(120, { ...STANCE }),
      ],
    },
  ],
};
