/**
 * Thessalos of Sparta - hoplite.
 *
 * A wall that walks forward. The aspis is half his offence: he throws it,
 * charges behind it, and hides behind it while the guard bar refills. Slow,
 * heavy, and the hardest fighter in the roster to push out of the corner.
 */

import type { FighterDef } from "../types";
import { bx, hit, kf, universalMoves } from "./builders";

const BRONZE = "#c98f3a";
const CRIMSON = "#9e2b2b";
const IRON = "#c2c9d1";

const STANCE = {
  torso: 8,
  head: -3,
  hipF: 16,
  kneeF: 15,
  hipB: -19,
  kneeB: 28,
  // Shield arm forward and high, spear cocked overhand behind the shoulder.
  shoulderF: 62,
  elbowF: 56,
  shoulderB: 128,
  elbowB: -34,
  weaponBack: 28,
};

export const SPARTAN: FighterDef = {
  id: "spartan",
  name: "Dienekes",
  title: "Spartiate of the Three Hundred",
  era: "Thermopylae, 480 BC",
  bio: "Herodotus records that when a Trachinian warned him the Persian arrows would blot out the sun, he answered that they would fight in the shade. Fights exactly like a man who meant it.",
  archetype: "Grappler / Wall",
  difficulty: 2,
  strengths: ["Heaviest fighter", "Armour on almost everything", "Corner carry for days"],
  weaknesses: ["Slowest walk speed", "No air game", "Aegis runs out"],
  winQuote: "Good. Now we fight in the shade.",
  palette: {
    body: "#e6e2d8",
    outline: "#191713",
    accent: CRIMSON,
    cloth: CRIMSON,
    metal: BRONZE,
    aura: "#ffb648",
  },
  stats: {
    health: 1120,
    walkF: 2.2,
    walkB: 1.8,
    dashSpeed: 6.8,
    dashFrames: 17,
    backdashFrames: 24,
    jumpVel: 11.8,
    jumpFwd: 4,
    gravity: 0.66,
    weight: 1.22,
    airMoves: 2,
    doubleJump: false,
    airDash: false,
    width: 22,
    standHeight: 106,
    crouchHeight: 70,
    scale: 1.04,
  },
  stance: STANCE,
  resource: {
    name: "Aegis",
    max: 100,
    start: 100,
    regen: 0.16,
    regenIdleOnly: true,
    color: BRONZE,
  },
  props: [
    {
      id: "helm",
      attach: "head",
      // Corinthian: one piece of bronze over the whole face, with eye slits and
      // a nose bar left in it, and the crest running ear to ear.
      parts: [
        { geo: "poly", size: [-12, -6, -12, 4, -7, 11, 4, 12, 11, 7, 12, -2, 10, -12, 4, -14, -6, -12], pos: [0, 1], color: BRONZE },
        // Eye slit and the nasal between the two halves of the face guard.
        { geo: "poly", size: [-6, 2, 4, 3, 5, -1, -6, -2], pos: [5, 1], color: "#3a2a12", z: 0.9 },
        { geo: "box", size: [3.5, 15], pos: [8, -5], color: "#a8752c", z: 0.95 },
        { geo: "poly", size: [-4, 7, 4, 6, 3, -7, -3, -6], pos: [11, -4], color: BRONZE, z: 0.92 },
        // Cheek edge catching the light.
        { geo: "box", size: [12, 2], pos: [4, -12], rot: -6, color: "#e0ad57", z: 0.93 },
        // Transverse crest: a rail across the crown with horsehair on it.
        { geo: "box", size: [30, 4], pos: [-1, 11], color: "#8a5a1f" },
        { geo: "poly", size: [-16, -1, -14, 8, -6, 12, 4, 12, 12, 8, 15, -1], pos: [-1, 12], color: CRIMSON },
        { geo: "poly", size: [-13, 0, -11, 5, -4, 8, 4, 8, 10, 5, 12, 0], pos: [-1, 13], color: "#c74848" },
      ],
    },
    {
      id: "dory",
      attach: "handB",
      // Dory: ash shaft, iron leaf blade at the front, bronze sauroter behind.
      parts: [
        { geo: "cyl", size: [2.8, 122], pos: [18, 0], rot: 90, color: "#8a6238" },
        { geo: "box", size: [10, 7], pos: [76, 0], color: BRONZE },
        // Leaf blade with a raised midrib.
        { geo: "poly", size: [-14, 0, -6, 8, 8, 5, 22, 0, 8, -5, -6, -8], pos: [94, 0], color: IRON },
        { geo: "box", size: [26, 2], pos: [92, 0], color: "#eef2f6" },
        // Grip binding at the balance point.
        { geo: "box", size: [16, 7], pos: [2, 0], color: "#5a3d22" },
        { geo: "box", size: [16, 2], pos: [2, 2.4], color: "#7d5730" },
        // Sauroter - the butt-spike, for finishing the man on the ground.
        { geo: "box", size: [8, 6.5], pos: [-40, 0], color: "#8a6a2f" },
        { geo: "poly", size: [0, 0, 10, 4, 16, 0, 10, -4], pos: [-56, 0], color: "#a8823a" },
      ],
    },
    {
      id: "aspis",
      attach: "forearmF",
      // Aspis: a domed bowl of bronze with a rolled rim and the lambda of
      // Lacedaemon painted across the whole face.
      parts: [
        { geo: "disc", size: [27], pos: [15, 0], color: "#7c5a24", z: 0.5 },
        { geo: "ring", size: [27, 4.5], pos: [15, 0], color: "#e2b45c", z: 0.55 },
        { geo: "disc", size: [22.5], pos: [15, 0], color: BRONZE, z: 0.6 },
        { geo: "ring", size: [22.5, 2], pos: [15, 0], color: "#8a6228", z: 0.62 },
        { geo: "disc", size: [19.5], pos: [15, 0], color: CRIMSON, z: 0.7 },
        // Lambda, one stroke down and one kicked out.
        { geo: "poly", size: [-3, 16, 3, 16, 6, -15, 0, -15], pos: [12, 0], rot: 12, color: "#f0e6d2", z: 0.8 },
        { geo: "poly", size: [-3, 15, 3, 15, 5, -14, -1, -14], pos: [19, -1], rot: -22, color: "#f0e6d2", z: 0.8 },
        // Rivets around the rim.
        { geo: "disc", size: [1.5], pos: [15, 24], color: "#f2d68e", z: 0.85 },
        { geo: "disc", size: [1.5], pos: [15, -24], color: "#f2d68e", z: 0.85 },
        { geo: "disc", size: [1.5], pos: [39, 0], color: "#f2d68e", z: 0.85 },
        { geo: "disc", size: [1.5], pos: [-9, 0], color: "#f2d68e", z: 0.85 },
      ],
    },
    {
      id: "cloak",
      attach: "neck",
      parts: [
        { geo: "box", size: [26, 7], pos: [-5, -3], color: CRIMSON, behind: true },
        { geo: "disc", size: [3.2], pos: [8, -2], color: BRONZE },
      ],
      cloth: {
        segments: 5,
        segmentLength: 12,
        width: 22,
        endWidth: 13,
        color: CRIMSON,
        gravity: 0.55,
        stiffness: 0.55,
        drift: -0.3,
      },
    },
    {
      id: "cuirass",
      attach: "torso",
      // Bronze muscle cuirass: shaped to the chest, with the abdominal lines
      // hammered into it and leather pteruges under the waist.
      parts: [
        { geo: "poly", size: [-13, -16, 13, -16, 15, 2, 12, 14, 3, 18, -9, 17, -14, 6], pos: [0, 3], color: BRONZE },
        // Pectorals.
        { geo: "poly", size: [-11, -4, -2, -6, 1, 3, -4, 6, -11, 4], pos: [-2, 11], color: "#e0ad57" },
        { geo: "poly", size: [-2, -5, 8, -4, 9, 4, 1, 6, -3, 2], pos: [5, 12], color: "#e6b862" },
        // Abdominal seams.
        { geo: "box", size: [22, 2], pos: [0, 2], color: "#8a6228" },
        { geo: "box", size: [20, 2], pos: [0, -4], color: "#8a6228" },
        { geo: "box", size: [17, 2], pos: [0, -10], color: "#8a6228" },
        { geo: "box", size: [2, 26], pos: [1, -2], color: "#8a6228" },
        // Shoulder straps buckled down at the front.
        { geo: "poly", size: [-6, 0, -4, 6, 6, 7, 8, 1], pos: [-4, 17], color: "#c98f3a" },
        { geo: "disc", size: [2], pos: [-2, 15], color: "#f2d68e", z: 0.3 },
        { geo: "disc", size: [2], pos: [8, 15], color: "#f2d68e", z: 0.3 },
        // Pteruges hanging off the bottom edge.
        { geo: "poly", size: [-3, 5, 3, 5, 2, -6, -2, -6], pos: [-8, -20], color: "#7d4a28", behind: true },
        { geo: "poly", size: [-3, 6, 3, 6, 2, -7, -2, -7], pos: [0, -21], color: "#8f5730", behind: true },
        { geo: "poly", size: [-3, 5, 3, 5, 2, -6, -2, -6], pos: [8, -20], color: "#7d4a28", behind: true },
      ],
    },
    {
      id: "greaveF",
      attach: "footF",
      parts: [
        { geo: "poly", size: [-4, -2, 4, -2, 5, 9, 2, 15, -2, 15, -5, 8], pos: [-1, 11], color: BRONZE },
        { geo: "box", size: [2.4, 15], pos: [1, 11], color: "#e0ad57" },
      ],
    },
    {
      id: "greaveB",
      attach: "footB",
      parts: [
        { geo: "poly", size: [-4, -2, 4, -2, 5, 9, 2, 15, -2, 15, -5, 8], pos: [-1, 11], color: "#a8752c" },
      ],
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 140,
      backThrowDamage: 150,
      throwRange: 66,
      rollSpeed: 6.2,
      weaponIdle: { weaponBack: STANCE.weaponBack },
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Shield Punch",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 14,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 13],
      hits: [hit(4, 6, bx(20, 50, 48, 24), 36, { fx: "blunt", hitstun: 15, blockstun: 11, pushX: 3.6 })],
      desc: "Short punch with the rim of the aspis. His fastest button.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 92, elbowF: 6, torso: 14, offX: 5 }),
        kf(9, { ...STANCE, shoulderF: 70, elbowF: 40, torso: 8 }, "inOut"),
        kf(14, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Overhand Thrust",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 24,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [9, 22],
      hits: [hit(9, 12, bx(30, 56, 88, 22), 62, { fx: "pierce", pushX: 5, hitstun: 18 })],
      desc: "Spear thrust over the shield wall - long, and safe behind the aspis.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderB: 148, elbowB: -50, weaponBack: 46, torso: -6, offX: -3 }),
        kf(9, { ...STANCE, shoulderB: 96, elbowB: -12, weaponBack: 12, torso: 18, hipF: 30, kneeF: 20, offX: 8 }, "out"),
        kf(16, { ...STANCE, shoulderB: 104, elbowB: -18, weaponBack: 18, torso: 14, offX: 6 }),
        kf(24, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Aspis Slam",
      input: { button: "C", stance: "stand" },
      tags: ["heavy"],
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [14, 28],
      armor: [{ from: 4, to: 14, hits: 1, damageScale: 0.4 }],
      hits: [
        hit(14, 18, bx(20, 28, 66, 66), 92, {
          fx: "blunt",
          pushX: 9,
          knockdown: "hard",
          hitstun: 24,
          shake: 2,
        }),
      ],
      desc: "Steps in and slams the full weight of the shield down. Armoured, and it knocks down hard.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderF: 158, elbowF: 10, torso: -16, hipB: -26, kneeB: 40, offX: -4 }, "inOut"),
        kf(14, { ...STANCE, shoulderF: 26, elbowF: 24, torso: 34, hipF: 38, kneeF: 24, hipB: -22, kneeB: 48, offX: 8 }, "out"),
        kf(22, { ...STANCE, shoulderF: 32, elbowF: 30, torso: 28, offX: 6 }),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Jab",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 15,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 14],
      hits: [hit(4, 6, bx(18, 16, 46, 22), 30, { guard: "low", fx: "pierce", hitstun: 14, blockstun: 10, pushX: 3 })],
      desc: "Short spear jab at the shins from behind the shield.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 24, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderB: 72, elbowB: 10, weaponBack: -18, offX: 5 }),
        kf(9, { ...STANCE, crouch: 1, torso: 20, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderB: 104, elbowB: -20, weaponBack: 16 }, "inOut"),
        kf(15, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "2B",
      name: "Low Thrust",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 26,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [10, 24],
      hits: [hit(10, 13, bx(28, 10, 92, 24), 58, { guard: "low", fx: "pierce", pushX: 4.6, hitstun: 17 })],
      desc: "Underhand thrust along the ground. The longest low in the game.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(6, { ...STANCE, crouch: 1, torso: 8, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderB: 40, elbowB: 20, weaponBack: -50 }),
        kf(10, { ...STANCE, crouch: 1, torso: 26, hipF: 42, kneeF: 78, hipB: -26, kneeB: 88, shoulderB: 74, elbowB: -6, weaponBack: -22, offX: 9 }, "out"),
        kf(18, { ...STANCE, crouch: 1, torso: 20, hipF: 38, kneeF: 76, hipB: -22, kneeB: 86, shoulderB: 84, elbowB: -14, weaponBack: -10 }, "inOut"),
        kf(26, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "2C",
      name: "Shield Sweep",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [13, 28],
      hits: [hit(12, 16, bx(18, 2, 82, 26), 80, { guard: "low", knockdown: "sweep", fx: "blunt", pushX: 6.5 })],
      desc: "Drags the shield rim along the ground. Knocks them off their feet.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(7, { ...STANCE, crouch: 1, torso: 6, hipF: 30, kneeF: 70, hipB: -30, kneeB: 92, shoulderF: 10, elbowF: 60 }),
        kf(12, { ...STANCE, crouch: 1, torso: 32, hipF: 46, kneeF: 84, hipB: -30, kneeB: 96, shoulderF: 104, elbowF: 34, offX: 7 }, "out"),
        kf(22, { ...STANCE, crouch: 1, torso: 26, hipF: 42, kneeF: 80, hipB: -26, kneeB: 90, shoulderF: 84, elbowF: 44 }, "inOut"),
        kf(32, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "6B",
      name: "Shield Ram",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command"],
      priority: 10,
      duration: 32,
      armor: [{ from: 3, to: 15, hits: 2, damageScale: 0.3 }],
      vel: [{ at: 6, x: 4.8 }],
      friction: 0.86,
      cancelInto: ["special", "super"],
      cancelWindow: [13, 28],
      hits: [
        hit(11, 15, bx(24, 30, 58, 58), 72, {
          fx: "blunt",
          pushX: 8,
          hitstun: 22,
          knockdown: "crumple",
          shake: 1.6,
        }),
      ],
      desc: "Walks through two hits and crumples them on contact. The core of his pressure.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, torso: -8, shoulderF: 74, elbowF: 30, hipB: -30, kneeB: 46, offX: -4 }),
        kf(11, { ...STANCE, torso: 28, shoulderF: 96, elbowF: 4, hipF: 38, kneeF: 22, hipB: -20, kneeB: 48, offX: 9 }, "out"),
        kf(18, { ...STANCE, torso: 22, shoulderF: 88, elbowF: 12, offX: 6 }),
        kf(32, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Raised Spear",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 34,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 30],
      hits: [hit(9, 14, bx(14, 54, 64, 76), 76, { launch: [2.2, 12], knockdown: "launch", fx: "pierce", hitstun: 26 })],
      desc: "Angles the dory upward to spike anyone jumping in. Launches on hit.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5, hipF: 26, kneeF: 46 }, "out"),
        kf(5, { ...STANCE, crouch: 0.7, shoulderB: 150, elbowB: -60, weaponBack: 60, torso: 12 }),
        kf(9, { ...STANCE, torso: -14, shoulderB: 176, elbowB: -18, weaponBack: 14, hipF: 22, kneeF: 12, offY: 4 }, "out"),
        kf(18, { ...STANCE, torso: -8, shoulderB: 166, elbowB: -14, weaponBack: 18 }),
        kf(26, { ...STANCE, torso: 4, shoulderB: 140, elbowB: -30, weaponBack: 26 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Rim",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 20,
      airborne: true,
      landCancel: true,
      landRecovery: 3,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [5, 18],
      hits: [hit(5, 10, bx(16, 32, 50, 32), 38, { fx: "blunt", hitstun: 15, pushX: 3 })],
      desc: "Shield swat in the air. Good for stuffing other jump-ins.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 32, kneeF: 44, hipB: -24, kneeB: 40 }, "out"),
        kf(5, { ...STANCE, free: 1, shoulderF: 104, elbowF: 18, torso: 14 }),
        kf(12, { ...STANCE, free: 1, shoulderF: 76, elbowF: 46, torso: 8 }, "inOut"),
        kf(20, { ...STANCE, free: 1, hipF: 32, kneeF: 44, hipB: -24, kneeB: 40 }),
      ],
    },
    {
      id: "jB",
      name: "Air Thrust",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 26,
      airborne: true,
      landCancel: true,
      landRecovery: 5,
      hits: [hit(7, 14, bx(24, 12, 78, 46), 62, { fx: "pierce", pushX: 4.4, hitstun: 19 })],
      desc: "Downward-angled spear thrust with all his reach.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 30, kneeF: 40, hipB: -22, kneeB: 38 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderB: 156, elbowB: -56, weaponBack: 54, torso: -8 }),
        kf(7, { ...STANCE, free: 1, shoulderB: 84, elbowB: -4, weaponBack: -8, torso: 24, hipF: 40, kneeF: 34 }, "out"),
        kf(17, { ...STANCE, free: 1, shoulderB: 92, elbowB: -10, weaponBack: 0, torso: 20 }),
        kf(26, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "jC",
      name: "Shield Drop",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 30,
      airborne: true,
      landCancel: true,
      landRecovery: 9,
      vel: [{ at: 6, y: -4.5, mode: "add" }],
      hits: [
        hit(8, 20, bx(-4, -6, 62, 48), 86, {
          guard: "overhead",
          fx: "blunt",
          knockdown: "hard",
          pushX: 5,
          shake: 1.8,
        }),
      ],
      desc: "Drops the full weight of shield and man straight down.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, torso: -22, shoulderF: 160, elbowF: 14, hipF: 40, kneeF: 60, hipB: -30, kneeB: 60 }),
        kf(9, { ...STANCE, free: 1, torso: 32, shoulderF: 22, elbowF: 20, hipF: 18, kneeF: 20, hipB: -14, kneeB: 24 }, "out"),
        kf(30, { ...STANCE, free: 1, torso: 26, shoulderF: 26, elbowF: 24 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Hoplite Rush",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command"],
      priority: 12,
      duration: 38,
      vel: [
        { at: 4, x: 8.6 },
        { at: 20, x: 0 },
      ],
      friction: 0.9,
      armor: [{ from: 3, to: 18, hits: 1, damageScale: 0.45 }],
      hits: [hit(10, 18, bx(22, 26, 68, 62), 86, { fx: "blunt", pushX: 9, knockdown: "hard", hitstun: 24, shake: 1.9 })],
      desc: "Armoured shoulder-and-shield charge. Closes ground and ends in a knockdown.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: 22, shoulderF: 80, elbowF: 20, hipB: -32, kneeB: 48, offX: -3 }),
        kf(10, { ...STANCE, torso: 32, shoulderF: 92, elbowF: 6, hipF: 42, kneeF: 24, hipB: -26, kneeB: 54, offX: 9 }, "out"),
        kf(24, { ...STANCE, torso: 22, shoulderF: 80, elbowF: 18, offX: 5 }, "inOut"),
        kf(38, { ...STANCE }),
      ],
    },

    // -------------------------------------------------------- five specials
    {
      id: "aspisThrow",
      name: "Aspis Throw",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      duration: 42,
      resourceCost: 34,
      resourceMin: 34,
      hideProps: ["aspis"],
      projectiles: [
        {
          at: 12,
          kind: "aspis",
          x: 34,
          y: 56,
          vx: 11,
          vy: 0.2,
          drag: 0.012,
          life: 70,
          box: { x: -22, y: -22, w: 44, h: 44 },
          damage: 64,
          hitstun: 22,
          blockstun: 15,
          chip: 6,
          pushX: 6,
          hits: 2,
          clashes: true,
          fx: "blunt",
          spin: 26,
          color: BRONZE,
          scale: 1,
        },
      ],
      desc: "Hurls the shield like a discus. Costs Aegis, and it stays gone until the bar refills.",
      notation: "↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderF: -30, elbowF: 40, torso: -18, offX: -5 }, "inOut"),
        kf(12, { ...STANCE, shoulderF: 108, elbowF: 4, torso: 26, hipF: 38, kneeF: 22, offX: 8 }, "out"),
        kf(24, { ...STANCE, shoulderF: 70, elbowF: 34, torso: 14 }, "inOut"),
        kf(42, { ...STANCE }),
      ],
    },
    {
      id: "phalanx",
      name: "Phalanx Charge",
      input: { button: "B", motion: "hcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 22,
      duration: 56,
      armor: [{ from: 3, to: 40, hits: 3, damageScale: 0.25 }],
      vel: [
        { at: 1, x: 4.2 },
        { at: 16, x: 4.2 },
        { at: 32, x: 4.6 },
        { at: 44, x: 0 },
      ],
      friction: 0.94,
      hits: [
        hit(10, 13, bx(24, 34, 62, 52), 38, { group: 1, fx: "blunt", pushX: 1.4, hitstun: 16, hitstop: 5 }),
        hit(22, 25, bx(24, 34, 66, 52), 38, { group: 2, fx: "blunt", pushX: 1.4, hitstun: 16, hitstop: 5 }),
        hit(34, 40, bx(22, 26, 74, 62), 70, {
          group: 3,
          fx: "blunt",
          pushX: 12,
          knockdown: "wallbounce",
          hitstun: 26,
          shake: 2,
        }),
      ],
      desc: "Marches forward behind the shield, absorbing three hits. Carries them to the corner and slams them off it.",
      notation: "←↙↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, torso: 20, shoulderF: 84, elbowF: 18, hipF: 26, kneeF: 22 }),
        kf(10, { ...STANCE, torso: 26, shoulderF: 94, elbowF: 8, hipF: 34, kneeF: 20, offX: 5 }, "out"),
        kf(18, { ...STANCE, torso: 20, shoulderF: 84, elbowF: 18, hipF: 20, kneeF: 30 }, "inOut"),
        kf(22, { ...STANCE, torso: 26, shoulderF: 94, elbowF: 8, hipF: 36, kneeF: 20, offX: 5 }, "out"),
        kf(30, { ...STANCE, torso: 18, shoulderF: 80, elbowF: 22, hipF: 18, kneeF: 32 }, "inOut"),
        kf(34, { ...STANCE, torso: 34, shoulderF: 30, elbowF: 22, hipF: 44, kneeF: 24, hipB: -26, kneeB: 56, offX: 10 }, "out"),
        kf(46, { ...STANCE, torso: 20, shoulderF: 60, elbowF: 34, offX: 5 }, "inOut"),
        kf(56, { ...STANCE }),
      ],
    },
    {
      id: "aegisRise",
      name: "Rising Aegis",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 24,
      duration: 46,
      airborne: true,
      invuln: [{ from: 1, to: 9, kind: "strike" }],
      vel: [
        { at: 1, x: 2, y: 12 },
        { at: 26, y: -1, mode: "add" },
      ],
      hits: [
        hit(4, 9, bx(6, 54, 64, 78), 84, { launch: [2, 10.5], knockdown: "launch", fx: "blunt", hitstun: 26, shake: 1.9 }),
        hit(10, 18, bx(4, 66, 58, 68), 36, { group: 2, launch: [1.4, 5], fx: "blunt" }),
      ],
      desc: "Invincible rising shield bash. His reversal and his answer to jump-ins.",
      notation: "→↓↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 50 }, "out"),
        kf(4, { ...STANCE, free: 1, torso: -16, shoulderF: 158, elbowF: 6, hipF: 30, kneeF: 30, hipB: -26, kneeB: 40 }, "out"),
        kf(14, { ...STANCE, free: 1, torso: -22, shoulderF: 172, elbowF: 2, hipF: 26, kneeF: 26 }),
        kf(32, { ...STANCE, free: 1, torso: -4, shoulderF: 120, elbowF: 24, hipF: 30, kneeF: 40 }, "inOut"),
        kf(46, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "spartanKick",
      name: "This Is Sparta",
      input: { button: "C", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 22,
      duration: 44,
      resourceCost: 20,
      vel: [{ at: 8, x: 4 }],
      friction: 0.86,
      armor: [{ from: 6, to: 14, hits: 1, damageScale: 0.35 }],
      hits: [
        hit(14, 19, bx(24, 30, 72, 50), 88, {
          fx: "blunt",
          pushX: 22,
          knockdown: "wallbounce",
          hitstun: 30,
          hitstop: 14,
          shake: 2.6,
        }),
      ],
      vfx: [{ at: 14, kind: "blunt", x: 60, y: 52, scale: 1.6 }],
      desc: "A full-body boot to the chest. Sends them the length of the arena and bounces them off the wall.",
      notation: "↓↙← + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, torso: -14, hipF: -22, kneeF: 74, hipB: -28, kneeB: 46, shoulderF: 40, elbowF: 60, offX: -4 }, "inOut"),
        kf(14, { ...STANCE, torso: 26, hipF: 96, kneeF: 4, hipB: -30, kneeB: 34, shoulderF: 20, elbowF: 30, shoulderB: 150, elbowB: -50, offX: 8 }, "out"),
        kf(26, { ...STANCE, torso: 18, hipF: 60, kneeF: 30, hipB: -22, kneeB: 40, offX: 4 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "spearWall",
      name: "Spear Wall",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "low"],
      priority: 20,
      duration: 40,
      resourceCost: 16,
      friction: 0.9,
      hits: [
        hit(9, 12, bx(28, 4, 96, 28), 46, { group: 1, guard: "low", fx: "pierce", pushX: 3, hitstun: 18 }),
        hit(18, 22, bx(28, 40, 100, 30), 58, {
          group: 2,
          fx: "pierce",
          pushX: 7,
          knockdown: "soft",
          hitstun: 22,
          shake: 1.4,
        }),
      ],
      desc: "Two thrusts at the ankles then the throat. The first must be blocked low, the second high.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, crouch: 0.8, torso: 16, shoulderB: 46, elbowB: 14, weaponBack: -54, hipF: 34, kneeF: 66 }),
        kf(9, { ...STANCE, crouch: 0.9, torso: 26, shoulderB: 70, elbowB: -4, weaponBack: -34, hipF: 42, kneeF: 74, offX: 8 }, "out"),
        kf(15, { ...STANCE, crouch: 0.4, torso: 6, shoulderB: 140, elbowB: -50, weaponBack: 40, offX: 2 }, "inOut"),
        kf(18, { ...STANCE, torso: 20, shoulderB: 100, elbowB: -14, weaponBack: 8, hipF: 34, kneeF: 22, offX: 9 }, "out"),
        kf(28, { ...STANCE, torso: 12, shoulderB: 118, elbowB: -26, weaponBack: 20, offX: 4 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- skill
    {
      id: "aegisGuard",
      name: "Hold the Line",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill", "stance"],
      priority: 18,
      duration: 34,
      armor: [{ from: 3, to: 26, hits: 3, damageScale: 0.2 }],
      resourceGain: 45,
      friction: 0.88,
      holdLoop: { from: 12, to: 22, button: "C", maxFrames: 100 },
      desc: "SKILL. Plants behind the aspis, soaking up to three hits and rebuilding Aegis. Hold Heavy to stay there.",
      notation: "A + C (hold C)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: -6, shoulderF: 96, elbowF: 12, shoulderB: 100, elbowB: -20, weaponBack: 20, crouch: 0.4, hipF: 22, kneeF: 46, hipB: -18, kneeB: 50 }),
        kf(12, { ...STANCE, torso: -8, shoulderF: 100, elbowF: 8, shoulderB: 104, elbowB: -24, weaponBack: 22, crouch: 0.45, hipF: 22, kneeF: 48, hipB: -18, kneeB: 52 }),
        kf(22, { ...STANCE, torso: -6, shoulderF: 96, elbowF: 12, shoulderB: 100, elbowB: -20, weaponBack: 20, crouch: 0.4 }),
        kf(34, { ...STANCE }),
      ],
    },

    // ------------------------------------------------------------------ EX
    {
      id: "aspisThrowEx",
      name: "Aspis Throw EX",
      input: { button: "S", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "projectile"],
      priority: 26,
      duration: 46,
      meterCost: 50,
      hideProps: ["aspis"],
      projectiles: [
        {
          at: 10,
          kind: "aspis",
          x: 34,
          y: 66,
          vx: 13,
          vy: 0.4,
          drag: 0.008,
          life: 80,
          box: { x: -24, y: -24, w: 48, h: 48 },
          damage: 52,
          hitstun: 22,
          blockstun: 15,
          chip: 5,
          pushX: 4,
          hits: 3,
          fx: "blunt",
          spin: 30,
          color: BRONZE,
          scale: 1.05,
        },
        {
          at: 20,
          kind: "aspis",
          x: 34,
          y: 40,
          vx: 12,
          vy: 0.1,
          drag: 0.008,
          life: 80,
          box: { x: -24, y: -24, w: 48, h: 48 },
          damage: 58,
          hitstun: 26,
          blockstun: 16,
          chip: 6,
          pushX: 11,
          knockdown: "hard",
          hits: 3,
          fx: "blunt",
          spin: -30,
          color: "#e0b13a",
          scale: 1.05,
        },
      ],
      desc: "EX. Two shields at two heights that plough through anything in the way. No Aegis cost.",
      notation: "↓↘→ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: -34, elbowF: 36, torso: -18, offX: -5 }, "inOut"),
        kf(10, { ...STANCE, shoulderF: 112, elbowF: 2, torso: 26, offX: 8 }, "out"),
        kf(16, { ...STANCE, shoulderF: -26, elbowF: 40, torso: -12, offX: -3 }, "inOut"),
        kf(20, { ...STANCE, shoulderF: 104, elbowF: 6, torso: 28, hipF: 38, kneeF: 22, offX: 9 }, "out"),
        kf(32, { ...STANCE, shoulderF: 70, elbowF: 34, torso: 12 }, "inOut"),
        kf(46, { ...STANCE }),
      ],
    },
    {
      id: "spartanKickEx",
      name: "This Is Sparta EX",
      input: { button: "S", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "ex"],
      priority: 28,
      duration: 48,
      meterCost: 50,
      invuln: [{ from: 1, to: 12, kind: "strike" }],
      vel: [{ at: 6, x: 7 }],
      friction: 0.86,
      hits: [
        hit(12, 18, bx(24, 28, 78, 54), 110, {
          fx: "blunt",
          pushX: 26,
          knockdown: "wallbounce",
          hitstun: 34,
          hitstop: 16,
          shake: 3,
        }),
      ],
      vfx: [{ at: 12, kind: "explode", x: 64, y: 52, scale: 0.9 }],
      desc: "EX. Invincible on the way in, and the wall bounce leaves them lying at your feet.",
      notation: "↓↙← + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, torso: -18, hipF: -26, kneeF: 78, hipB: -30, kneeB: 48, shoulderF: 44, elbowF: 56, offX: -5 }, "inOut"),
        kf(12, { ...STANCE, torso: 30, hipF: 104, kneeF: 2, hipB: -32, kneeB: 30, shoulderF: 16, elbowF: 26, shoulderB: 158, elbowB: -54, offX: 10 }, "out"),
        kf(28, { ...STANCE, torso: 20, hipF: 64, kneeF: 28, hipB: -24, kneeB: 42, offX: 5 }, "inOut"),
        kf(48, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "Molon Labe",
      input: { button: "S", motion: "hcb", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 116,
      meterCost: 100,
      superFreeze: 44,
      invuln: [{ from: 1, to: 18, kind: "strike" }],
      armor: [{ from: 19, to: 70, hits: 5, damageScale: 0.15 }],
      vel: [
        { at: 8, x: 7 },
        { at: 30, x: 5 },
        { at: 56, x: 4 },
        { at: 74, x: 0 },
      ],
      friction: 0.93,
      hits: [
        hit(14, 18, bx(22, 30, 70, 56), 58, { group: 1, fx: "blunt", pushX: 1, hitstun: 22, hitstop: 6 }),
        hit(26, 30, bx(24, 34, 78, 52), 46, { group: 2, fx: "pierce", pushX: 1, hitstun: 20, hitstop: 5 }),
        hit(38, 42, bx(24, 28, 82, 60), 46, { group: 3, fx: "pierce", pushX: 1, hitstun: 20, hitstop: 5 }),
        hit(50, 54, bx(22, 24, 84, 64), 52, { group: 4, fx: "blunt", pushX: 1, hitstun: 20, hitstop: 5 }),
        hit(64, 70, bx(18, 16, 92, 76), 140, {
          group: 5,
          fx: "blunt",
          pushX: 24,
          knockdown: "wallbounce",
          launch: [9, 7],
          hitstop: 18,
          shake: 3.2,
        }),
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 50, scale: 2.5, color: "#ffb648" },
        { at: 64, kind: "explode", x: 62, y: 48, scale: 1.3 },
      ],
      desc: "SUPER. The whole phalanx in one man: shield, spear, shield, and a kick that ends at the far wall.",
      notation: "→↘↓↙← + S  (100 meter)",
      frames: [
        kf(0, { ...STANCE, torso: -12, shoulderF: 80, elbowF: 26, crouch: 0.35 }, "out"),
        kf(12, { ...STANCE, torso: 26, shoulderF: 96, elbowF: 4, hipF: 38, kneeF: 22, offX: 7 }, "out"),
        kf(20, { ...STANCE, torso: 16, shoulderB: 150, elbowB: -52, weaponBack: 44, hipF: 20, kneeF: 30 }, "inOut"),
        kf(26, { ...STANCE, torso: 24, shoulderB: 98, elbowB: -12, weaponBack: 10, hipF: 36, kneeF: 22, offX: 8 }, "out"),
        kf(34, { ...STANCE, torso: 14, shoulderB: 154, elbowB: -56, weaponBack: 48 }, "inOut"),
        kf(38, { ...STANCE, torso: 26, shoulderB: 100, elbowB: -14, weaponBack: 8, offX: 8 }, "out"),
        kf(46, { ...STANCE, torso: -8, shoulderF: 150, elbowF: 16, offX: 2 }, "inOut"),
        kf(50, { ...STANCE, torso: 32, shoulderF: 28, elbowF: 24, hipF: 40, kneeF: 24, offX: 9 }, "out"),
        kf(60, { ...STANCE, torso: -18, hipF: -28, kneeF: 80, hipB: -30, kneeB: 50, shoulderF: 44, elbowF: 58, offX: -4 }, "inOut"),
        kf(64, { ...STANCE, torso: 32, hipF: 108, kneeF: 0, hipB: -34, kneeB: 28, shoulderF: 14, elbowF: 24, shoulderB: 162, elbowB: -58, offX: 12 }, "out"),
        kf(84, { ...STANCE, torso: 18, hipF: 50, kneeF: 34, offX: 5 }, "inOut"),
        kf(116, { ...STANCE }),
      ],
    },
  ],
};
