/**
 * Sigrún Bloodmane - viking raider.
 *
 * Trades health for position and never stops walking forward. Her Fury bar
 * fills from the exchange itself - landing hits, and especially taking them -
 * and her best moves spend it, so the way to power her up is to be in a fight
 * she is losing.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const IRON = "#b9c0c8";
const LEATHER = "#6d4a2c";
const FUR = "#8d7f6a";
const BLOOD = "#8f2f2f";

const STANCE = {
  torso: 10,
  head: -4,
  hipF: 17,
  kneeF: 16,
  hipB: -20,
  kneeB: 30,
  // Axe resting on the shoulder, shield arm loose across the body.
  shoulderF: 40,
  elbowF: 54,
  shoulderB: 156,
  elbowB: -66,
  weaponBack: 116,
};

export const VIKING: FighterDef = {
  id: "viking",
  name: "Freydís Eiríksdóttir",
  title: "Daughter of Erik the Red",
  era: "Vinland, c. 1000",
  bio: "The Vinland sagas have her turning alone on a Skræling attack that had put every man on the beach to flight - pregnant, unarmed, and beating a sword flat against her chest until they ran. She has not softened.",
  archetype: "Berserker / Bruiser",
  difficulty: 3,
  strengths: ["Huge damage on every button", "Fury feeds on taking hits", "Best corner pressure"],
  weaknesses: ["No projectile without Fury", "Slow recovery", "Nothing safe on block"],
  winQuote: "They ran from me once already. You had your chance.",
  palette: {
    body: "#eee6d6",
    outline: "#17140f",
    accent: BLOOD,
    cloth: LEATHER,
    metal: IRON,
    aura: "#ff6a4a",
  },
  stats: {
    health: 1080,
    walkF: 2.6,
    walkB: 2.05,
    dashSpeed: 7.6,
    dashFrames: 16,
    backdashFrames: 22,
    jumpVel: 12.2,
    jumpFwd: 4.5,
    gravity: 0.64,
    weight: 1.15,
    airMoves: 2,
    doubleJump: false,
    airDash: false,
    width: 21,
    standHeight: 106,
    crouchHeight: 68,
    scale: 1.03,
  },
  stance: STANCE,
  // A buckler is too small to hide behind, so it gets punched out to meet
  // the blow instead, axe still cocked over the shoulder.
  clips: guardClips({
    high: { torso: 4, head: -8, shoulderF: 18, elbowF: 126, shoulderB: 168, elbowB: -84, weaponBack: 128, hipF: 15, kneeF: 22, hipB: -20, kneeB: 34, offX: -3 },
    low: { torso: 10, head: -6, shoulderF: 6, elbowF: 122, shoulderB: 160, elbowB: -80, weaponBack: 128, hipF: 32, kneeF: 74, hipB: -22, kneeB: 84, offX: -3 },
  }),
  resource: {
    name: "Fury",
    max: 100,
    start: 20,
    // Rage builds from the fight, and faster when she is the one bleeding.
    gainOnHit: 7,
    gainOnTakeHit: 11,
    gainOnBlocked: 3,
    color: "#ff6a4a",
  },
  props: [
    {
      id: "helm",
      attach: "head",
      // Spangenhelm: iron plates riveted to a browband, with a nose bar and a
      // pair of horns she took off something that lost.
      parts: [
        { geo: "poly", size: [-11, -5, -11, 3, -6, 10, 0, 13, 6, 10, 11, 3, 11, -5], pos: [0, 2], color: IRON },
        { geo: "box", size: [2.5, 17], pos: [-1, 4], color: "#8f979f" },
        { geo: "box", size: [24, 4.5], pos: [0, -5], color: "#9aa2ab" },
        { geo: "poly", size: [-3, 8, 3, 8, 3, -7, -3, -7], pos: [7, -6], color: "#8f979f", z: 0.9 },
        { geo: "disc", size: [1.4], pos: [-7, -1], color: "#e6ebef", z: 0.9 },
        { geo: "disc", size: [1.4], pos: [6, -1], color: "#e6ebef", z: 0.9 },
        // Horns, curving up and out from the browband.
        { geo: "poly", size: [0, -4, -3, 3, -9, 9, -15, 12, -13, 6, -8, 0, -4, -4], pos: [-9, 6], color: "#e8dfc8" },
        { geo: "poly", size: [0, -4, 3, 3, 9, 9, 15, 12, 13, 6, 8, 0, 4, -4], pos: [9, 6], color: "#efe7d3" },
      ],
    },
    {
      id: "beard",
      attach: "head",
      parts: [
        // Braid falling out from under the helm.
        { geo: "poly", size: [-5, 8, 5, 6, 4, -10, -2, -12, -6, -4], pos: [-8, -6], color: "#a8763c", behind: true },
        { geo: "box", size: [7, 4], pos: [-9, -18], color: "#5a3a1c", behind: true },
        { geo: "poly", size: [-4, 6, 4, 5, 2, -9, -2, -9], pos: [-9, -24], color: "#a8763c", behind: true },
      ],
    },
    {
      id: "axe",
      attach: "handB",
      // Bearded axe: a broad blade that hangs well below the haft, with a
      // langet strapping it on and a leather-wrapped grip.
      parts: [
        { geo: "cyl", size: [2.8, 72], pos: [20, 0], rot: 90, color: LEATHER },
        { geo: "box", size: [12, 5], pos: [40, 0], color: "#4a3422" },
        // Bearded axe: a narrow eye at the haft that opens into a thin
        // crescent, with the beard hooking well below the shaft.
        { geo: "poly", size: [-3, 7, 4, 7, 12, 1, 16, -10, 12, -22, 4, -28, 0, -20, 3, -10, -1, -3, -3, 0], pos: [48, 1], color: IRON },
        // The edge itself, catching the light along the whole curve.
        { geo: "poly", size: [0, 0, 5, -9, 3, -20, -2, -25, -4, -18, -1, -9], pos: [61, -1], color: "#eef2f6" },
        // Langets strapping the head to the haft.
        { geo: "box", size: [3.4, 18], pos: [42, -1], color: "#8f979f" },
        { geo: "box", size: [16, 5], pos: [4, 0], color: "#4a3422" },
        { geo: "box", size: [16, 1.8], pos: [4, 1.6], color: "#8a6440" },
        { geo: "poly", size: [-4, 4, 4, 4, 3, -4, -3, -4], pos: [-14, 0], color: "#c9a24a" },
      ],
    },
    {
      id: "buckler",
      attach: "forearmF",
      // Round shield: planks, an iron rim and a domed boss over the grip.
      parts: [
        { geo: "disc", size: [22], pos: [12, 0], color: "#5b3d24", z: 0.5 },
        { geo: "ring", size: [22, 3], pos: [12, 0], color: IRON, z: 0.55 },
        { geo: "disc", size: [19], pos: [12, 0], color: LEATHER, z: 0.6 },
        // Painted quarters.
        { geo: "poly", size: [0, 0, 18, 6, 18, -6], pos: [12, 0], color: BLOOD, z: 0.62 },
        { geo: "poly", size: [0, 0, -18, 6, -18, -6], pos: [12, 0], color: BLOOD, z: 0.62 },
        { geo: "box", size: [38, 2], pos: [12, 0], rot: 90, color: "#4a3422", z: 0.65 },
        { geo: "disc", size: [6], pos: [12, 0], color: IRON, z: 0.7 },
        { geo: "disc", size: [2.6], pos: [12, 1], color: "#e6ebef", z: 0.72 },
        { geo: "disc", size: [1.3], pos: [12, 19], color: "#9aa2ab", z: 0.72 },
        { geo: "disc", size: [1.3], pos: [12, -19], color: "#9aa2ab", z: 0.72 },
      ],
    },
    {
      id: "pelt",
      attach: "torso",
      // Mail over a padded coat, with a wolf pelt across the shoulders.
      parts: [
        { geo: "poly", size: [-12, -16, 12, -16, 13, 8, 8, 16, -8, 16, -13, 8], pos: [0, 3], color: "#6f7681" },
        { geo: "box", size: [24, 2], pos: [0, 11], color: "#585f69" },
        { geo: "box", size: [24, 2], pos: [0, 5], color: "#585f69" },
        { geo: "box", size: [23, 2], pos: [0, -1], color: "#585f69" },
        { geo: "box", size: [22, 2], pos: [0, -7], color: "#585f69" },
        { geo: "box", size: [21, 2], pos: [0, -13], color: "#585f69" },
        // Pelt: a ragged collar over the mail.
        { geo: "poly", size: [-16, -3, -13, 7, -4, 11, 6, 10, 14, 4, 15, -5, 6, 0, -4, 1], pos: [-2, 13], rot: 4, color: FUR },
        { geo: "poly", size: [-9, 8, 9, 6, 7, -9, -8, -8], pos: [-11, 0], rot: 8, color: "#7a6d5a", behind: true },
      ],
      cloth: {
        segments: 3,
        segmentLength: 10,
        width: 20,
        endWidth: 14,
        color: "#7a6d5a",
        gravity: 0.52,
        stiffness: 0.56,
        drift: -0.26,
      },
    },
    {
      id: "belt",
      attach: "pelvis",
      parts: [
        { geo: "box", size: [26, 8], pos: [0, 2], rot: -6, color: LEATHER },
        { geo: "poly", size: [-4, 5, 4, 5, 4, -5, -4, -5], pos: [0, 2], color: "#c9a24a" },
        { geo: "disc", size: [1.8], pos: [0, 2], color: "#8a6a2f", z: 0.2 },
        { geo: "poly", size: [-5, 9, 5, 9, 4, -9, -4, -9], pos: [-9, -8], rot: 8, color: "#6b5a44", behind: true },
      ],
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 132,
      backThrowDamage: 142,
      throwRange: 62,
      rollSpeed: 7,
      weaponIdle: { weaponBack: STANCE.weaponBack },
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Buckler Smash",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 14,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 13],
      hits: [hit(4, 6, bx(18, 52, 46, 22), 36, { fx: "blunt", hitstun: 15, blockstun: 11, pushX: 3.4 })],
      desc: "Short shield smash. Her fastest button and it chains into everything.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 90, elbowF: 8, torso: 16, offX: 4 }),
        kf(9, { ...STANCE, shoulderF: 54, elbowF: 38, torso: 10 }, "inOut"),
        kf(14, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Axe Swing",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 24,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [9, 22],
      hits: [hit(9, 12, bx(22, 40, 74, 46), 62, { fx: "slash", pushX: 5, hitstun: 18 })],
      desc: "Horizontal chop across the ribs. Her bread-and-butter poke.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderB: -70, elbowB: 90, weaponBack: 30, torso: -8, offX: -4 }),
        kf(9, { ...STANCE, shoulderB: 92, elbowB: 8, weaponBack: -40, torso: 24, hipF: 30, kneeF: 20, offX: 7 }, "out"),
        kf(16, { ...STANCE, shoulderB: 66, elbowB: 30, weaponBack: -20, torso: 16 }, "inOut"),
        kf(24, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Skull Splitter",
      input: { button: "C", stance: "stand" },
      tags: ["heavy"],
      duration: 34,
      cancelInto: ["special", "super"],
      cancelWindow: [15, 30],
      armor: [{ from: 3, to: 14, hits: 1, damageScale: 0.4 }],
      hits: [
        hit(15, 19, bx(18, 22, 76, 80), 98, {
          fx: "slash",
          pushX: 7,
          knockdown: "hard",
          hitstun: 26,
          shake: 2.1,
        }),
      ],
      desc: "Both hands, straight down, through the guard. Armoured on the way up.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderB: 180, elbowB: -20, shoulderF: 160, elbowF: -10, weaponBack: 40, torso: -20, hipB: -28, kneeB: 42, offX: -5 }, "inOut"),
        kf(15, { ...STANCE, shoulderB: 30, elbowB: 12, shoulderF: 40, elbowF: 10, weaponBack: -56, torso: 34, hipF: 38, kneeF: 26, hipB: -22, kneeB: 48, offX: 8 }, "out"),
        kf(24, { ...STANCE, shoulderB: 24, elbowB: 18, weaponBack: -50, torso: 28, offX: 6 }),
        kf(34, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Hack",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 15,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 14],
      hits: [hit(4, 6, bx(16, 14, 46, 22), 30, { guard: "low", fx: "slash", hitstun: 14, blockstun: 10, pushX: 2.8 })],
      desc: "Quick chop at the shins from a crouch.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 24, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderB: 74, elbowB: 30, weaponBack: -60, offX: 4 }),
        kf(9, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderB: 20, elbowB: 54, weaponBack: -40 }, "inOut"),
        kf(15, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "2B",
      name: "Hamstring",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 26,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [10, 24],
      hits: [hit(10, 13, bx(20, 6, 76, 26), 58, { guard: "low", fx: "slash", pushX: 4.6, hitstun: 17 })],
      desc: "Low sweeping chop. Must be blocked crouching.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(6, { ...STANCE, crouch: 1, torso: 6, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderB: -50, elbowB: 90, weaponBack: 20 }),
        kf(10, { ...STANCE, crouch: 1, torso: 28, hipF: 42, kneeF: 78, hipB: -26, kneeB: 88, shoulderB: 100, elbowB: 30, weaponBack: -62, offX: 8 }, "out"),
        kf(18, { ...STANCE, crouch: 1, torso: 20, hipF: 38, kneeF: 76, hipB: -22, kneeB: 86, shoulderB: 70, elbowB: 44, weaponBack: -44 }, "inOut"),
        kf(26, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "2C",
      name: "Leg Reaper",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [13, 28],
      hits: [hit(12, 16, bx(18, 2, 84, 26), 82, { guard: "low", knockdown: "sweep", fx: "slash", pushX: 6.5 })],
      desc: "Full-swing sweep with the axe head. Knocks them flat.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(7, { ...STANCE, crouch: 1, torso: 2, hipF: 30, kneeF: 70, hipB: -30, kneeB: 92, shoulderB: -74, elbowB: 100, weaponBack: 40 }),
        kf(12, { ...STANCE, crouch: 1, torso: 32, hipF: 46, kneeF: 84, hipB: -30, kneeB: 96, shoulderB: 112, elbowB: 24, weaponBack: -70, offX: 8 }, "out"),
        kf(22, { ...STANCE, crouch: 1, torso: 24, hipF: 42, kneeF: 80, hipB: -26, kneeB: 90, shoulderB: 82, elbowB: 40, weaponBack: -50 }, "inOut"),
        kf(32, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "6B",
      name: "Horned Headbutt",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "overhead"],
      priority: 10,
      duration: 30,
      vel: [{ at: 6, x: 3.6 }],
      friction: 0.88,
      armor: [{ from: 4, to: 12, hits: 1, damageScale: 0.35 }],
      cancelInto: ["special", "super"],
      cancelWindow: [14, 26],
      hits: [hit(13, 17, bx(20, 44, 52, 44), 64, { guard: "overhead", fx: "blunt", pushX: 5.5, hitstun: 20 })],
      desc: "Leads with the helmet. Armoured, and it has to be blocked standing.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, torso: -14, head: -16, hipB: -30, kneeB: 44, offX: -4 }),
        kf(13, { ...STANCE, torso: 36, head: 14, hipF: 40, kneeF: 24, hipB: -22, kneeB: 50, shoulderF: 10, elbowF: 40, offX: 8 }, "out"),
        kf(20, { ...STANCE, torso: 26, head: 8, offX: 5 }),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Rising Axe",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 34,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 30],
      hits: [hit(9, 14, bx(12, 50, 60, 76), 78, { launch: [2.2, 12], knockdown: "launch", fx: "slash", hitstun: 26 })],
      desc: "Upward chop that launches. Start your juggles here.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5, hipF: 26, kneeF: 46 }, "out"),
        kf(5, { ...STANCE, crouch: 0.7, shoulderB: -40, elbowB: 96, weaponBack: 30, torso: 14 }),
        kf(9, { ...STANCE, torso: -16, shoulderB: 162, elbowB: -14, weaponBack: -30, hipF: 22, kneeF: 12, offY: 4 }, "out"),
        kf(18, { ...STANCE, torso: -10, shoulderB: 150, elbowB: -8, weaponBack: -24 }),
        kf(26, { ...STANCE, torso: 4, shoulderB: 40, elbowB: 40, weaponBack: -34 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },
    {
      // Forward and back sets. Forward takes space, back gives it up to buy
      // range or a hard read.
      id: "6A",
      name: "Boss Punch",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 20,
      vel: [{ at: 2, x: 2.2 }],
      friction: 0.88,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [7, 18],
      hits: [hit(7, 9, bx(20, 60, 44, 26), 32, { guard: "high", fx: "blunt", pushX: 3, hitstun: 14, hitstop: 5 })],
      desc: "Punches in with the iron boss of the shield. Her fastest way in.",
      notation: "\u2192 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 26, elbowF: 74, torso: -2, offX: -2 }, "out"),
        kf(7, { ...STANCE, shoulderF: 76, elbowF: 12, torso: 16, hipF: 28, kneeF: 16, offX: 7 }, "out"),
        kf(12, { ...STANCE, shoulderF: 62, elbowF: 34, torso: 12, offX: 5 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Cleave",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 40,
      armor: [{ from: 8, to: 18, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 8, x: 5.4 }, { at: 26, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [20, 36],
      hits: [hit(16, 20, bx(18, 22, 64, 68), 96, { guard: "mid", fx: "slash", pushX: 17, hitstun: 24, hitstop: 12, knockdown: "wallbounce", shake: 2.4 })],
      desc: "Steps in and buries the axe. No guard on the way in and none on the way out.",
      notation: "\u2192 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderB: 176, elbowB: -30, weaponBack: 150, torso: -14, hipB: -32, kneeB: 50, offX: -6 }, "out"),
        // The whole arc comes over the top and through them.
        kf(16, { ...STANCE, shoulderB: 84, elbowB: 22, weaponBack: 44, torso: 32, hipF: 42, kneeF: 18, hipB: -26, kneeB: 24, offX: 12 }, "out"),
        kf(24, { ...STANCE, shoulderB: 72, elbowB: 30, weaponBack: 36, torso: 24, hipF: 30, kneeF: 24, offX: 8 }),
        kf(32, { ...STANCE, shoulderB: 120, elbowB: -30, weaponBack: 90, torso: 10, offX: 3 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Buckler Check",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 22,
      vel: [{ at: 1, x: -2.6 }],
      friction: 0.86,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [8, 20],
      hits: [hit(8, 10, bx(16, 52, 42, 30), 36, { guard: "mid", fx: "blunt", pushX: 6, hitstun: 15, hitstop: 6 })],
      desc: "Gives ground and gets the shield in the way. Punishes a step-in.",
      notation: "\u2190 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -6, shoulderF: 18, elbowF: 82, hipB: -26, kneeB: 40, offX: -6 }, "out"),
        kf(8, { ...STANCE, torso: 8, shoulderF: 68, elbowF: 22, hipF: 22, kneeF: 18, offX: -3 }, "out"),
        kf(14, { ...STANCE, torso: 2, shoulderF: 54, elbowF: 44, offX: -4 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Axe Hook",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 30,
      vel: [{ at: 1, x: -3.4 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      hits: [hit(12, 15, bx(30, 50, 78, 30), 56, { guard: "mid", fx: "slash", pushX: 7, hitstun: 18, hitstop: 8 })],
      desc: "Steps out and hooks with the beard of the axe. Drags their guard down with it.",
      notation: "\u2190 + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderB: 168, elbowB: -74, weaponBack: 134, torso: -12, hipB: -28, kneeB: 42, offX: -8 }, "inOut"),
        // Edge turned in so the beard leads and pulls back through them.
        kf(12, { ...STANCE, shoulderB: 96, elbowB: -4, weaponBack: 34, torso: 6, hipF: 26, kneeF: 14, offX: -5 }, "out"),
        kf(17, { ...STANCE, shoulderB: 88, elbowB: 2, weaponBack: 28, torso: 4, offX: -6 }),
        kf(23, { ...STANCE, shoulderB: 130, elbowB: -46, weaponBack: 88, torso: 0, offX: -4 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Skull Hew",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 44,
      cancelInto: ["special", "super"],
      cancelWindow: [26, 40],
      hits: [hit(20, 23, bx(14, 20, 70, 86), 108, { guard: "overhead", fx: "slash", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 })],
      desc: "Takes the axe all the way back and splits down through the crown. Blocked standing only.",
      notation: "\u2190 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderB: 186, elbowB: -50, weaponBack: 140, torso: -10, offX: -5 }, "inOut"),
        // Axe head straight up and behind, then the full arc down.
        kf(15, { ...STANCE, shoulderB: 206, elbowB: -22, weaponBack: 128, torso: -22, hipB: -26, kneeB: 38, offY: 3, offX: -3 }, "out"),
        kf(20, { ...STANCE, shoulderB: 86, elbowB: 16, weaponBack: 32, torso: 32, hipF: 36, kneeF: 18, hipB: -12, kneeB: 32, offX: 6 }, "out"),
        kf(26, { ...STANCE, shoulderB: 78, elbowB: 20, weaponBack: 28, torso: 26, offX: 4 }),
        kf(36, { ...STANCE, shoulderB: 130, elbowB: -40, weaponBack: 92, torso: 8 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Buckler",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 19,
      airborne: true,
      landCancel: true,
      landRecovery: 3,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [5, 17],
      hits: [hit(5, 10, bx(16, 32, 48, 30), 38, { fx: "blunt", hitstun: 15, pushX: 3 })],
      desc: "Shield swat on the way down.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 32, kneeF: 44, hipB: -24, kneeB: 40 }, "out"),
        kf(5, { ...STANCE, free: 1, shoulderF: 100, elbowF: 16, torso: 14 }),
        kf(12, { ...STANCE, free: 1, shoulderF: 66, elbowF: 44, torso: 8 }, "inOut"),
        kf(19, { ...STANCE, free: 1, hipF: 32, kneeF: 44, hipB: -24, kneeB: 40 }),
      ],
    },
    {
      id: "jB",
      name: "Air Chop",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 25,
      airborne: true,
      landCancel: true,
      landRecovery: 5,
      cancelInto: ["heavy", "special"],
      cancelWindow: [8, 23],
      hits: [hit(6, 13, bx(18, 14, 68, 50), 60, { fx: "slash", pushX: 4.2, hitstun: 19 })],
      desc: "Wide air swing that covers the whole arc in front of her.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 30, kneeF: 40, hipB: -22, kneeB: 38 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderB: -60, elbowB: 96, weaponBack: 34, torso: -10 }),
        kf(7, { ...STANCE, free: 1, shoulderB: 98, elbowB: 14, weaponBack: -48, torso: 22, hipF: 36, kneeF: 34 }, "out"),
        kf(17, { ...STANCE, free: 1, shoulderB: 74, elbowB: 30, weaponBack: -34, torso: 14 }, "inOut"),
        kf(25, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "jC",
      name: "Raven Drop",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 30,
      airborne: true,
      landCancel: true,
      landRecovery: 8,
      vel: [{ at: 6, y: -4, mode: "add" }],
      hits: [
        hit(8, 20, bx(0, -6, 64, 52), 88, {
          guard: "overhead",
          fx: "slash",
          knockdown: "hard",
          pushX: 5,
          shake: 1.8,
        }),
      ],
      desc: "Falls out of the sky with the axe leading. Her jump-in.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, torso: -22, shoulderB: 176, elbowB: -18, weaponBack: 34, hipF: 40, kneeF: 58 }),
        kf(9, { ...STANCE, free: 1, torso: 30, shoulderB: 26, elbowB: 16, weaponBack: -58, hipF: 16, kneeF: 20 }, "out"),
        kf(30, { ...STANCE, free: 1, torso: 24, shoulderB: 30, elbowB: 20, weaponBack: -54 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Raid Charge",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command"],
      priority: 12,
      duration: 36,
      vel: [
        { at: 3, x: 9.8 },
        { at: 18, x: 0 },
      ],
      friction: 0.9,
      armor: [{ from: 3, to: 16, hits: 1, damageScale: 0.45 }],
      hits: [hit(9, 16, bx(20, 26, 70, 60), 82, { fx: "slash", pushX: 8.5, knockdown: "soft", hitstun: 23, shake: 1.7 })],
      desc: "Runs in behind the shield with the axe already swinging.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 26, shoulderB: -50, elbowB: 88, weaponBack: 26, hipB: -34, kneeB: 50, offX: -3 }),
        kf(9, { ...STANCE, torso: 32, shoulderB: 96, elbowB: 12, weaponBack: -50, hipF: 44, kneeF: 24, hipB: -28, kneeB: 56, offX: 9 }, "out"),
        kf(22, { ...STANCE, torso: 22, shoulderB: 70, elbowB: 30, weaponBack: -36, offX: 5 }, "inOut"),
        kf(36, { ...STANCE }),
      ],
    },

    // -------------------------------------------------------- five specials
    {
      id: "axeThrow",
      name: "Hand Axe",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      duration: 40,
      resourceCost: 20,
      resourceMin: 20,
      projectiles: [
        {
          at: 13,
          kind: "axe",
          x: 34,
          y: 58,
          vx: 12,
          vy: 1.2,
          gravity: 0.06,
          drag: 0.004,
          life: 80,
          box: { x: -18, y: -16, w: 36, h: 32 },
          damage: 62,
          hitstun: 22,
          blockstun: 15,
          chip: 6,
          pushX: 7,
          clashes: true,
          fx: "slash",
          spin: 34,
          color: IRON,
        },
      ],
      desc: "Throws a hand axe end over end. Costs Fury - she has to earn her zoning.",
      notation: "↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderB: 168, elbowB: -30, weaponBack: 40, torso: -18, offX: -5 }, "inOut"),
        kf(13, { ...STANCE, shoulderB: 66, elbowB: 4, weaponBack: -46, torso: 26, hipF: 38, kneeF: 22, offX: 8 }, "out"),
        kf(24, { ...STANCE, shoulderB: 20, elbowB: 40, torso: 14 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "whirlwind",
      name: "Whirlwind",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 20,
      duration: 52,
      resourceCost: 25,
      resourceMin: 25,
      vel: [
        { at: 1, x: 3.6 },
        { at: 18, x: 3.2 },
        { at: 34, x: 2.4 },
        { at: 44, x: 0 },
      ],
      friction: 0.92,
      armor: [{ from: 4, to: 40, hits: 2, damageScale: 0.3 }],
      hits: [
        hit(8, 12, bx(-30, 26, 108, 58), 44, { group: 1, fx: "slash", pushX: 1.6, hitstun: 18, hitstop: 5 }),
        hit(20, 24, bx(-30, 26, 108, 58), 40, { group: 2, fx: "slash", pushX: 1.6, hitstun: 18, hitstop: 5 }),
        hit(32, 38, bx(-28, 20, 112, 66), 66, {
          group: 3,
          fx: "slash",
          pushX: 9,
          knockdown: "hard",
          hitstun: 26,
          shake: 2,
        }),
      ],
      desc: "Spins forward with the axe out, hitting on both sides. Absorbs two hits while she turns.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, spin: -80, torso: 6, shoulderB: 96, elbowB: -10, weaponBack: -70, hipF: 24, kneeF: 20 }, "linear"),
        kf(14, { ...STANCE, spin: -220, torso: 4, shoulderB: 96, elbowB: -10, weaponBack: -70 }, "linear"),
        kf(22, { ...STANCE, spin: -400, torso: 6, shoulderB: 96, elbowB: -10, weaponBack: -70 }, "linear"),
        kf(32, { ...STANCE, spin: -620, torso: 4, shoulderB: 96, elbowB: -10, weaponBack: -70 }, "linear"),
        kf(40, { ...STANCE, spin: -720, torso: 20, shoulderB: 60, elbowB: 20, weaponBack: -50, hipF: 34, kneeF: 26 }, "out"),
        kf(52, { ...STANCE }),
      ],
    },
    {
      id: "odinsWrath",
      name: "Odin's Wrath",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 24,
      duration: 46,
      airborne: true,
      invuln: [{ from: 1, to: 8, kind: "strike" }],
      vel: [
        { at: 1, x: 2.4, y: 12.4 },
        { at: 26, y: -1, mode: "add" },
      ],
      hits: [
        hit(3, 8, bx(8, 50, 64, 84), 86, { launch: [2, 10.5], knockdown: "launch", fx: "slash", hitstun: 26, shake: 2 }),
        hit(9, 17, bx(6, 64, 58, 72), 38, { group: 2, launch: [1.6, 5], fx: "slash" }),
      ],
      desc: "Invincible rising axe. Her reversal, and it takes them up with her.",
      notation: "→↓↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 48 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -14, shoulderB: 156, elbowB: -12, weaponBack: -26, hipF: 30, kneeF: 30 }, "out"),
        kf(14, { ...STANCE, free: 1, torso: -22, spin: -20, shoulderB: 176, elbowB: -6, weaponBack: -18, hipF: 26, kneeF: 26 }),
        kf(32, { ...STANCE, free: 1, torso: -4, spin: -6, shoulderB: 120, elbowB: 10, weaponBack: -36 }, "inOut"),
        kf(46, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "shieldRam",
      name: "Skjaldborg Ram",
      input: { button: "B", motion: "hcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 22,
      duration: 48,
      armor: [{ from: 3, to: 30, hits: 2, damageScale: 0.25 }],
      vel: [
        { at: 2, x: 6.5 },
        { at: 20, x: 5.5 },
        { at: 34, x: 0 },
      ],
      friction: 0.92,
      hits: [
        hit(12, 16, bx(22, 30, 60, 56), 48, { group: 1, fx: "blunt", pushX: 2, hitstun: 18, hitstop: 5 }),
        hit(24, 30, bx(20, 24, 70, 64), 74, {
          group: 2,
          fx: "blunt",
          pushX: 14,
          knockdown: "wallbounce",
          hitstun: 26,
          shake: 2.2,
        }),
      ],
      desc: "Puts her shoulder into the shield and walks them into the wall.",
      notation: "←↙↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, torso: 26, shoulderF: 82, elbowF: 16, hipF: 30, kneeF: 22, offX: 3 }),
        kf(12, { ...STANCE, torso: 32, shoulderF: 94, elbowF: 6, hipF: 38, kneeF: 20, offX: 7 }, "out"),
        kf(20, { ...STANCE, torso: 26, shoulderF: 84, elbowF: 14, hipF: 24, kneeF: 30 }, "inOut"),
        kf(24, { ...STANCE, torso: 36, shoulderF: 30, elbowF: 20, shoulderB: 88, elbowB: 6, weaponBack: -48, hipF: 44, kneeF: 24, offX: 10 }, "out"),
        kf(38, { ...STANCE, torso: 20, offX: 4 }, "inOut"),
        kf(48, { ...STANCE }),
      ],
    },
    {
      id: "leapCleave",
      name: "Leaping Cleave",
      input: { button: "C", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "overhead"],
      priority: 22,
      duration: 50,
      resourceCost: 15,
      airborne: true,
      vel: [
        { at: 5, x: 8, y: 11 },
        { at: 26, y: -0.7, mode: "add" },
      ],
      hits: [
        hit(20, 30, bx(10, 4, 66, 66), 92, {
          guard: "overhead",
          fx: "slash",
          pushX: 8,
          knockdown: "hard",
          hitstun: 26,
          shake: 2.2,
        }),
      ],
      vfx: [{ at: 20, kind: "slash", x: 40, y: 30, scale: 1.5 }],
      desc: "Jumps the gap and brings the axe down on their head. Overhead, and it travels.",
      notation: "↓↙← + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 50 }, "out"),
        kf(6, { ...STANCE, free: 1, torso: -18, shoulderB: 170, elbowB: -24, weaponBack: 36, hipF: 30, kneeF: 60, hipB: -30, kneeB: 50 }, "out"),
        kf(18, { ...STANCE, free: 1, torso: -12, shoulderB: 182, elbowB: -18, weaponBack: 30, hipF: 20, kneeF: 50 }),
        kf(22, { ...STANCE, free: 1, torso: 32, shoulderB: 24, elbowB: 14, weaponBack: -60, hipF: 16, kneeF: 22, hipB: -14, kneeB: 26 }, "out"),
        kf(36, { ...STANCE, free: 1, torso: 26, shoulderB: 28, elbowB: 18, weaponBack: -54 }),
        kf(50, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- skill
    {
      id: "berserk",
      name: "Berserkergang",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill", "stance"],
      priority: 18,
      duration: 40,
      armor: [{ from: 4, to: 30, hits: 3, damageScale: 0.2 }],
      resourceGain: 45,
      meterGain: 12,
      friction: 0.9,
      holdLoop: { from: 14, to: 26, button: "C", maxFrames: 90 },
      desc: "SKILL. Roars and plants her feet - soaks up to three hits and builds Fury fast. Hold Heavy to keep going.",
      notation: "A + C (hold C)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, torso: -16, head: -18, shoulderF: -50, elbowF: 40, shoulderB: -56, elbowB: 44, weaponBack: 20, hipF: 20, kneeF: 24, hipB: -24, kneeB: 40 }, "out"),
        kf(14, { ...STANCE, torso: -20, head: -22, shoulderF: -60, elbowF: 34, shoulderB: -66, elbowB: 38, weaponBack: 24, offY: 2 }),
        kf(26, { ...STANCE, torso: -16, head: -18, shoulderF: -52, elbowF: 40, shoulderB: -58, elbowB: 44, weaponBack: 20 }),
        kf(40, { ...STANCE }),
      ],
    },

    // ------------------------------------------------------------------ EX
    {
      id: "whirlwindEx",
      name: "Whirlwind EX",
      input: { button: "S", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "ex"],
      priority: 28,
      duration: 62,
      meterCost: 50,
      invuln: [{ from: 1, to: 8, kind: "strike" }],
      armor: [{ from: 9, to: 50, hits: 4, damageScale: 0.2 }],
      vel: [
        { at: 1, x: 4.4 },
        { at: 20, x: 4 },
        { at: 40, x: 3 },
        { at: 52, x: 0 },
      ],
      friction: 0.92,
      hits: [
        hit(8, 12, bx(-32, 24, 116, 62), 42, { group: 1, fx: "slash", pushX: 1.2, hitstun: 18, hitstop: 5 }),
        hit(20, 24, bx(-32, 24, 116, 62), 38, { group: 2, fx: "slash", pushX: 1.2, hitstun: 18, hitstop: 5 }),
        hit(32, 36, bx(-32, 24, 116, 62), 38, { group: 3, fx: "slash", pushX: 1.2, hitstun: 18, hitstop: 5 }),
        hit(44, 50, bx(-30, 16, 120, 74), 76, {
          group: 4,
          fx: "slash",
          pushX: 12,
          knockdown: "wallbounce",
          hitstun: 28,
          shake: 2.4,
        }),
      ],
      desc: "EX. Invincible into four rotations of armour, and the last one throws them at the wall.",
      notation: "↓↙← + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, spin: -120, shoulderB: 96, elbowB: -10, weaponBack: -70 }, "linear"),
        kf(20, { ...STANCE, spin: -360, shoulderB: 96, elbowB: -10, weaponBack: -70 }, "linear"),
        kf(32, { ...STANCE, spin: -600, shoulderB: 96, elbowB: -10, weaponBack: -70 }, "linear"),
        kf(44, { ...STANCE, spin: -840, shoulderB: 96, elbowB: -10, weaponBack: -70 }, "linear"),
        kf(52, { ...STANCE, spin: -1080, torso: 22, shoulderB: 60, elbowB: 20, weaponBack: -50 }, "out"),
        kf(62, { ...STANCE }),
      ],
    },
    {
      id: "odinsWrathEx",
      name: "Odin's Wrath EX",
      input: { button: "S", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "launcher"],
      priority: 30,
      duration: 54,
      meterCost: 50,
      airborne: true,
      invuln: [{ from: 1, to: 16, kind: "strike" }],
      vel: [
        { at: 1, x: 3, y: 14 },
        { at: 32, y: -1, mode: "add" },
      ],
      hits: [
        hit(3, 8, bx(8, 48, 70, 90), 70, { launch: [2, 12], knockdown: "launch", fx: "slash", hitstun: 28, shake: 2.2 }),
        hit(9, 18, bx(6, 62, 64, 82), 36, { group: 2, launch: [1.4, 5], fx: "slash" }),
        hit(19, 28, bx(6, 74, 62, 74), 56, { group: 3, launch: [2, 4], fx: "slash", knockdown: "hard" }),
      ],
      desc: "EX. Fully invincible, higher, and it drags them up the whole way.",
      notation: "→↓↘ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 48 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -16, spin: -20, shoulderB: 160, elbowB: -10, weaponBack: -24 }, "out"),
        kf(18, { ...STANCE, free: 1, torso: -24, spin: -260, shoulderB: 178, elbowB: -4, weaponBack: -16 }, "linear"),
        kf(36, { ...STANCE, free: 1, torso: -8, spin: -360, shoulderB: 120, elbowB: 8, weaponBack: -34 }, "inOut"),
        kf(54, { ...STANCE, free: 1 }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "Ragnarök",
      input: { button: "S", motion: "dd", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 116,
      meterCost: 100,
      superFreeze: 44,
      invuln: [{ from: 1, to: 14, kind: "strike" }],
      armor: [{ from: 15, to: 72, hits: 6, damageScale: 0.12 }],
      vel: [
        { at: 8, x: 8 },
        { at: 32, x: 5 },
        { at: 58, x: 3 },
        { at: 76, x: 0 },
      ],
      friction: 0.93,
      hits: [
        hit(14, 18, bx(20, 26, 80, 64), 56, { group: 1, fx: "slash", pushX: 1, hitstun: 22, hitstop: 6 }),
        hit(24, 28, bx(-24, 24, 104, 62), 44, { group: 2, fx: "slash", pushX: 1, hitstun: 20, hitstop: 5 }),
        hit(34, 38, bx(20, 20, 84, 70), 44, { group: 3, fx: "slash", pushX: 1, hitstun: 20, hitstop: 5 }),
        hit(46, 50, bx(-24, 22, 108, 66), 46, { group: 4, fx: "slash", pushX: 1, hitstun: 20, hitstop: 5 }),
        hit(62, 70, bx(16, 8, 96, 92), 148, {
          group: 5,
          fx: "slash",
          pushX: 14,
          knockdown: "groundbounce",
          launch: [6, 11],
          hitstop: 18,
          shake: 3.2,
        }),
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 50, scale: 2.6, color: "#ff6a4a" },
        { at: 24, kind: "slash", x: 30, y: 50, scale: 1.5 },
        { at: 46, kind: "slash", x: 30, y: 50, scale: 1.5 },
        { at: 62, kind: "explode", x: 50, y: 30, scale: 1.2 },
      ],
      desc: "SUPER. Walks into them swinging and does not stop until the last blow puts them through the floor.",
      notation: "↓↓ + S  (100 meter)",
      frames: [
        kf(0, { ...STANCE, torso: -18, head: -20, shoulderB: -60, elbowB: 50, weaponBack: 20, crouch: 0.3 }, "out"),
        kf(12, { ...STANCE, torso: 26, shoulderB: 92, elbowB: 8, weaponBack: -48, hipF: 40, kneeF: 22, offX: 8 }, "out"),
        kf(20, { ...STANCE, spin: -120, shoulderB: 96, elbowB: -8, weaponBack: -66 }, "linear"),
        kf(28, { ...STANCE, spin: -300, shoulderB: 96, elbowB: -8, weaponBack: -66 }, "linear"),
        kf(34, { ...STANCE, spin: -360, torso: 24, shoulderB: 90, elbowB: 6, weaponBack: -50, offX: 7 }, "out"),
        kf(42, { ...STANCE, spin: -520, shoulderB: 96, elbowB: -8, weaponBack: -66 }, "linear"),
        kf(50, { ...STANCE, spin: -720, torso: 22, shoulderB: 88, elbowB: 8, weaponBack: -48, offX: 6 }, "out"),
        kf(58, { ...STANCE, spin: -720, torso: -24, shoulderB: 184, elbowB: -22, shoulderF: 168, elbowF: -12, weaponBack: 42, hipB: -30, kneeB: 46, offX: -4 }, "inOut"),
        kf(62, { ...STANCE, spin: -720, torso: 38, shoulderB: 22, elbowB: 14, shoulderF: 34, elbowF: 12, weaponBack: -62, hipF: 46, kneeF: 28, hipB: -24, kneeB: 56, offX: 12 }, "out"),
        kf(84, { ...STANCE, spin: -720, torso: 24, shoulderB: 30, elbowB: 22, weaponBack: -50, offX: 6 }, "inOut"),
        kf(116, { ...STANCE, spin: -720 }),
      ],
    },
  ],
};
