/**
 * Cole "Dust" Hargrave - gunslinger.
 *
 * Six rounds, a stick of dynamite and a temper. Controls space with bullets,
 * punishes greed with the quickdraw, and has to reload like everybody else.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const LEATHER = "#8a5a2b";
const PONCHO = "#b2543a";
const IRON = "#b8bfc7";
const BRASSY = "#c9a24a";

const STANCE = {
  torso: 4,
  head: -2,
  hipF: 14,
  kneeF: 16,
  hipB: -16,
  kneeB: 26,
  shoulderF: 18,
  elbowF: 46,
  shoulderB: -12,
  elbowB: 30,
  weapon: -18,
};

export const WESTERN: FighterDef = {
  id: "western",
  name: "Wyatt Earp",
  title: "Deputy US Marshal",
  era: "Tombstone, 1881",
  bio: "Deputy US Marshal at Tombstone, and the one man to walk out of the lot behind the O.K. Corral without a scratch on him. Not the fastest. Simply the one who does not hurry.",
  archetype: "Zoner / Punisher",
  difficulty: 4,
  strengths: ["Screen-long bullets", "Dynamite controls space", "Huge punish damage"],
  weaknesses: ["Ammo is finite", "Reload leaves him open", "Mediocre normals"],
  winQuote: "Fast is fine. Accurate is final.",
  palette: {
    body: "#e9dfcd",
    outline: "#191512",
    accent: PONCHO,
    cloth: LEATHER,
    metal: IRON,
    aura: "#ffcf6b",
  },
  stats: {
    health: 980,
    walkF: 2.7,
    walkB: 2.3,
    dashSpeed: 7.8,
    dashFrames: 15,
    backdashFrames: 20,
    jumpVel: 12.2,
    jumpFwd: 4.7,
    gravity: 0.61,
    weight: 1,
    airMoves: 2,
    doubleJump: false,
    airDash: false,
    width: 20,
    standHeight: 104,
    crouchHeight: 66,
    scale: 1,
  },
  stance: STANCE,
  // No shield and no blade worth parrying with - the forearms go up and
  // he eats it.
  clips: guardClips({
    high: { torso: 0, head: -6, shoulderF: 32, elbowF: 132, weapon: -30, shoulderB: 16, elbowB: 136, hipF: 12, kneeF: 20, hipB: -16, kneeB: 30, offX: -2 },
    low: { torso: 8, head: -5, shoulderF: 38, elbowF: 124, weapon: -30, shoulderB: 22, elbowB: 128, hipF: 32, kneeF: 72, hipB: -18, kneeB: 82, offX: -2 },
  }),
  resource: {
    name: "Rounds",
    max: 6,
    start: 6,
    color: "#ffcf6b",
    pips: true,
  },
  props: [
    {
      id: "hat",
      attach: "head",
      // Cattleman: a creased crown with a pinch at the front and a brim that
      // rolls up at the sides.
      parts: [
        { geo: "poly", size: [-19, 0, -14, 3, 0, 4, 14, 3, 19, 0, 13, -3, 0, -4, -13, -3], pos: [1, 7], color: "#6b4423" },
        { geo: "poly", size: [-9, -3, -10, 8, -5, 12, 0, 8, 5, 12, 10, 8, 9, -3], pos: [0, 12], color: "#7d5029" },
        { geo: "box", size: [19, 3.5], pos: [0, 9], color: "#4a2f18" },
        { geo: "poly", size: [-2, 2, 2, 3, 3, -2, -2, -3], pos: [7, 9], color: "#c9a24a", z: 0.3 },
      ],
    },
    {
      id: "bandana",
      attach: "head",
      parts: [
        { geo: "poly", size: [-9, 4, 9, 3, 8, -4, -8, -5], pos: [1, -6], color: PONCHO, z: 0.9 },
        { geo: "poly", size: [-4, 5, 4, 4, 3, -5, -4, -5], pos: [-9, -8], rot: 18, color: "#96442f", z: 0.85 },
      ],
    },
    {
      id: "revolver",
      attach: "handF",
      // Single-action army: octagonal barrel, fluted cylinder, loading gate,
      // hammer spur and a plough-handle grip.
      parts: [
        { geo: "poly", size: [-11, 2.4, 11, 2, 11, -2, -11, -2.4], pos: [15, 2], color: "#5b6068" },
        { geo: "box", size: [10, 1.2], pos: [15, 4], color: "#8f979f" },
        { geo: "poly", size: [-5, 5, 5, 4.5, 5, -4.5, -5, -5], pos: [2, 1], color: IRON },
        { geo: "box", size: [9, 1.4], pos: [2, 3], color: "#8f979f" },
        { geo: "box", size: [9, 1.4], pos: [2, -1], color: "#8f979f" },
        // Hammer, cocked.
        { geo: "poly", size: [0, 0, -3, 4, -6, 3, -4, -2], pos: [-4, 3], color: "#3f444b" },
        { geo: "box", size: [3, 5], pos: [1, -5], rot: 8, color: "#3f444b" },
        // Grip.
        { geo: "poly", size: [4, 4, -1, 2, -6, -7, -1, -10, 3, -4], pos: [-3, -4], color: "#4a2f18" },
        { geo: "disc", size: [1.4], pos: [-4, -6], color: "#c9a24a", z: 0.3 },
      ],
    },
    {
      id: "dynamite",
      attach: "handB",
      conditional: true,
      parts: [
        { geo: "cyl", size: [4.4, 17], pos: [8, 0], rot: 90, color: "#a83b2a" },
        { geo: "box", size: [17, 3], pos: [8, 0], rot: 90, color: "#e2c98a" },
        { geo: "cyl", size: [1, 9], pos: [18, 4], rot: 60, color: "#d8cdb4" },
        { geo: "disc", size: [2.2], pos: [22, 8], color: "#ffcf6b" },
      ],
    },
    {
      id: "poncho",
      attach: "torso",
      // Serape over a waistcoat, with the striped weave showing.
      parts: [
        { geo: "poly", size: [-15, -15, 15, -15, 17, 6, 11, 17, -11, 17, -17, 6], pos: [-1, 1], rot: 3, color: PONCHO, behind: true },
        { geo: "box", size: [31, 2.5], pos: [-2, 10], color: "#8f3d2a", behind: true },
        { geo: "box", size: [31, 2.5], pos: [-2, 2], color: "#d8785a", behind: true },
        { geo: "box", size: [30, 2.5], pos: [-2, -6], color: "#8f3d2a", behind: true },
        { geo: "box", size: [12, 6], pos: [-1, 15], color: "#7d3527", behind: true },
      ],
      cloth: {
        segments: 3,
        segmentLength: 10,
        width: 24,
        endWidth: 18,
        color: PONCHO,
        gravity: 0.46,
        stiffness: 0.6,
        drift: -0.2,
      },
    },
    {
      id: "holster",
      attach: "pelvis",
      // Gunbelt: cartridge loops all the way round, holster on the hip.
      parts: [
        { geo: "poly", size: [-13, 4, 13, 3.5, 13, -4, -13, -4.5], pos: [0, 2], rot: -10, color: "#5b3a1c" },
        { geo: "box", size: [2.4, 7], pos: [-8, 2], color: BRASSY },
        { geo: "box", size: [2.4, 7], pos: [-3, 2], color: BRASSY },
        { geo: "box", size: [2.4, 7], pos: [2, 2], color: BRASSY },
        { geo: "box", size: [2.4, 7], pos: [7, 2], color: BRASSY },
        { geo: "poly", size: [-4, 4, 4, 4, 4, -4, -4, -4], pos: [-1, 2], color: "#c9a24a", z: 0.3 },
        { geo: "poly", size: [-5, 7, 5, 8, 4, -8, -4, -7], pos: [-11, -7], rot: 6, color: "#4a2f18" },
        { geo: "box", size: [11, 2.4], pos: [-11, -1], rot: 6, color: "#6b4423", z: 0.2 },
      ],
    },
    {
      id: "spur",
      attach: "footB",
      parts: [
        { geo: "box", size: [6, 2.2], pos: [-3, 4], color: IRON },
        { geo: "poly", size: [0, 3, 3, 1.5, 3, -1.5, 0, -3, -3, -1.5, -3, 1.5], pos: [-6, 4], color: IRON },
      ],
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 122,
      backThrowDamage: 132,
      throwRange: 60,
      rollSpeed: 8,
      weaponIdle: { weapon: STANCE.weapon },
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Pistol Whip",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 13,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 12],
      // Fanning string continues into 6A.
      followUps: [
        { button: "A", move: "6A", from: 4, to: 10, string: "Fanning" },
      ],
      hits: [hit(4, 6, bx(18, 54, 46, 22), 32, { fx: "blunt", hitstun: 14, blockstun: 10, pushX: 3 })],
      desc: "Backhand with the revolver. Quick, cancellable, gets him out of trouble.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 96, elbowF: 4, weapon: -40, torso: 12, offX: 3 }),
        kf(9, { ...STANCE, shoulderF: 54, elbowF: 30, weapon: -24, torso: 6 }, "inOut"),
        kf(13, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Straight Right",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 20,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [7, 18],
      // Bare Knuckle string continues into 5C.
      followUps: [
        { button: "C", move: "5C", from: 7, to: 17, string: "Bare Knuckle" },
      ],
      hits: [hit(7, 10, bx(22, 50, 58, 26), 52, { fx: "blunt", pushX: 4.4, hitstun: 17 })],
      desc: "Honest straight punch. Confirms into the quickdraw.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderB: -46, elbowB: 70, torso: -8, offX: -3 }),
        kf(7, { ...STANCE, shoulderB: 84, elbowB: 4, torso: 18, hipF: 26, offX: 6 }, "out"),
        kf(13, { ...STANCE, shoulderB: 50, elbowB: 34, torso: 10 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Haymaker",
      input: { button: "C", stance: "stand" },
      tags: ["heavy"],
      duration: 30,
      cancelInto: ["special", "super"],
      cancelWindow: [13, 26],
      // Bare Knuckle string continues into 4C.
      followUps: [
        { button: "C", move: "4C", from: 13, to: 27, string: "Bare Knuckle" },
      ],
      hits: [
        hit(13, 17, bx(20, 40, 66, 46), 88, {
          fx: "blunt",
          pushX: 8,
          knockdown: "hard",
          hitstun: 24,
          shake: 1.8,
        }),
      ],
      desc: "Wind-up hook that knocks down hard. Slow, but it ends the conversation.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderB: -80, elbowB: 90, torso: -20, hipB: -26, kneeB: 40, offX: -5 }, "inOut"),
        kf(13, { ...STANCE, shoulderB: 92, elbowB: 10, torso: 30, hipF: 38, kneeF: 22, hipB: -20, kneeB: 46, offX: 8 }, "out"),
        kf(20, { ...STANCE, shoulderB: 70, elbowB: 24, torso: 22, offX: 5 }),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Jab",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 14,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 13],
      hits: [hit(4, 6, bx(16, 16, 44, 22), 28, { guard: "low", fx: "blunt", hitstun: 13, blockstun: 10, pushX: 2.6 })],
      desc: "Crouching jab at the knees. Chains into low pressure.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 24, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderB: 74, elbowB: 30, offX: 4 }),
        kf(9, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84, shoulderB: 30, elbowB: 40 }, "inOut"),
        kf(14, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "2B",
      name: "Knee Cracker",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 22,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [8, 20],
      hits: [hit(8, 11, bx(20, 6, 62, 26), 48, { guard: "low", fx: "blunt", pushX: 4, hitstun: 16 })],
      desc: "Low kick to the shin. Cancel it into a dynamite toss on block.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(5, { ...STANCE, crouch: 1, torso: 18, hipF: 16, kneeF: 92, hipB: -26, kneeB: 90 }),
        kf(8, { ...STANCE, crouch: 1, torso: 24, hipF: 70, kneeF: 16, hipB: -30, kneeB: 96, offX: 5 }, "out"),
        kf(16, { ...STANCE, crouch: 1, torso: 20, hipF: 46, kneeF: 54, hipB: -26, kneeB: 88 }, "inOut"),
        kf(22, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "2C",
      name: "Spur Sweep",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 30,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 26],
      hits: [hit(11, 15, bx(18, 2, 80, 24), 74, { guard: "low", knockdown: "sweep", fx: "slash", pushX: 6 })],
      desc: "Spurred boot along the dirt. Knocks down and sets up dynamite oki.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }, "out"),
        kf(6, { ...STANCE, crouch: 1, torso: 22, hipF: 6, kneeF: 96, hipB: -32, kneeB: 100, offX: -2 }),
        kf(11, { ...STANCE, crouch: 1, torso: 28, hipF: 84, kneeF: 6, hipB: -36, kneeB: 104, shoulderF: 10, elbowF: 40, offX: 5 }, "out"),
        kf(20, { ...STANCE, crouch: 1, torso: 22, hipF: 52, kneeF: 48, hipB: -30, kneeB: 94 }, "inOut"),
        kf(30, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 74, hipB: -22, kneeB: 84 }),
      ],
    },
    {
      id: "6B",
      name: "Boot Stomp",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "overhead"],
      priority: 10,
      duration: 30,
      vel: [{ at: 5, x: 3 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [14, 26],
      hits: [hit(13, 17, bx(20, 34, 56, 50), 60, { guard: "overhead", fx: "blunt", pushX: 5, hitstun: 20 })],
      desc: "Stomping overhead. His only way through a low block without a bullet.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, crouch: 0.4, torso: 10, hipF: 16, kneeF: 56 }),
        kf(10, { ...STANCE, free: 1, offY: 12, torso: -8, hipF: -26, kneeF: 76, hipB: -28, kneeB: 56 }, "out"),
        kf(13, { ...STANCE, free: 1, offY: 6, torso: 24, hipF: 80, kneeF: 10, hipB: -24, kneeB: 66, offX: 4 }, "out"),
        kf(20, { ...STANCE, offY: 0, torso: 16, hipF: 40, kneeF: 40 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Uppercut",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [11, 28],
      hits: [hit(9, 13, bx(12, 50, 56, 70), 72, { launch: [2, 12], knockdown: "launch", fx: "blunt", hitstun: 26 })],
      desc: "Classic uppercut launcher. Combo into a jump attack or a bullet.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 26, kneeF: 48 }, "out"),
        kf(5, { ...STANCE, crouch: 0.8, shoulderB: -20, elbowB: 70, torso: 16 }),
        kf(9, { ...STANCE, torso: -14, shoulderB: 158, elbowB: -8, hipF: 22, kneeF: 12, offY: 3 }, "out"),
        kf(17, { ...STANCE, torso: -10, shoulderB: 146, elbowB: -4 }),
        kf(24, { ...STANCE, torso: 2, shoulderB: 40, elbowB: 30 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },
    {
      // Forward and back sets. Forward takes space, back gives it up to buy
      // range or a hard read.
      id: "6A",
      name: "Barrel Jab",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 20,
      vel: [{ at: 2, x: 2.2 }],
      friction: 0.88,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [7, 18],
      // Fanning string continues into 4A.
      followUps: [
        { button: "A", move: "4A", from: 7, to: 17, string: "Fanning" },
      ],
      hits: [hit(7, 9, bx(20, 60, 44, 26), 32, { guard: "high", fx: "blunt", pushX: 3, hitstun: 14, hitstop: 5 })],
      desc: "Steps in and jabs the barrel into their face. Quick and mean.",
      notation: "\u2192 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 14, elbowF: 82, weapon: -8, torso: -2, offX: -2 }, "out"),
        kf(7, { ...STANCE, shoulderF: 78, elbowF: 10, weapon: -12, torso: 14, hipF: 24, kneeF: 16, offX: 7 }, "out"),
        kf(12, { ...STANCE, shoulderF: 56, elbowF: 34, weapon: -14, torso: 10, offX: 5 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Charging Haymaker",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 40,
      armor: [{ from: 8, to: 18, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 8, x: 5.4 }, { at: 26, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [20, 36],
      // Bull Rush string continues into 3C.
      followUps: [
        { button: "C", move: "3C", from: 16, to: 37, string: "Bull Rush" },
      ],
      hits: [hit(16, 20, bx(16, 22, 52, 68), 92, { guard: "mid", fx: "blunt", pushX: 18, hitstun: 24, hitstop: 12, knockdown: "wallbounce", shake: 2.4 })],
      desc: "Walks in and throws everything behind one hand. Ends the exchange or ends him.",
      notation: "\u2192 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderB: -46, elbowB: 40, torso: -16, hipB: -32, kneeB: 50, offX: -6 }, "out"),
        kf(16, { ...STANCE, shoulderB: 86, elbowB: 6, torso: 34, hipF: 42, kneeF: 18, hipB: -24, kneeB: 24, offX: 12 }, "out"),
        kf(24, { ...STANCE, shoulderB: 76, elbowB: 14, torso: 26, hipF: 30, kneeF: 24, offX: 8 }),
        kf(32, { ...STANCE, shoulderB: 20, elbowB: 40, torso: 10, offX: 3 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Pistol Whip",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 22,
      vel: [{ at: 1, x: -2.6 }],
      friction: 0.86,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [8, 20],
      hits: [hit(8, 10, bx(16, 52, 42, 30), 36, { guard: "mid", fx: "blunt", pushX: 6, hitstun: 15, hitstop: 6 })],
      desc: "Steps off and rakes the revolver back across their jaw.",
      notation: "\u2190 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -6, shoulderF: 46, elbowF: 84, weapon: 40, hipB: -26, kneeB: 40, offX: -6 }, "out"),
        kf(8, { ...STANCE, torso: 10, shoulderF: 96, elbowF: 8, weapon: -20, hipF: 22, kneeF: 16, offX: -3 }, "out"),
        kf(14, { ...STANCE, torso: 2, shoulderF: 62, elbowF: 40, weapon: -10, offX: -4 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Back Hook",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 30,
      vel: [{ at: 1, x: -3.4 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      hits: [hit(12, 15, bx(26, 54, 72, 30), 56, { guard: "mid", fx: "blunt", pushX: 7, hitstun: 18, hitstop: 8 })],
      desc: "Gives ground and throws a long hook at whatever follows him in.",
      notation: "\u2190 + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderB: -36, elbowB: 62, torso: -14, hipB: -28, kneeB: 42, offX: -8 }, "inOut"),
        kf(12, { ...STANCE, shoulderB: 74, elbowB: 34, torso: 6, hipF: 24, kneeF: 14, offX: -5 }, "out"),
        kf(17, { ...STANCE, shoulderB: 70, elbowB: 38, torso: 4, offX: -6 }),
        kf(23, { ...STANCE, shoulderB: 16, elbowB: 44, torso: 0, offX: -4 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Overhand Right",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 44,
      cancelInto: ["special", "super"],
      cancelWindow: [26, 40],
      hits: [hit(20, 23, bx(12, 20, 58, 86), 100, { guard: "overhead", fx: "blunt", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 })],
      desc: "Loads it up and drops it over the top of their guard. Blocked standing only.",
      notation: "\u2190 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderB: -30, elbowB: 92, torso: -12, offX: -5 }, "inOut"),
        // Fist cocked above and behind the ear.
        kf(15, { ...STANCE, shoulderB: 176, elbowB: 34, torso: -18, hipB: -26, kneeB: 38, offY: 3, offX: -3 }, "out"),
        kf(20, { ...STANCE, shoulderB: 96, elbowB: 8, torso: 34, hipF: 34, kneeF: 16, hipB: -12, kneeB: 32, offX: 6 }, "out"),
        kf(26, { ...STANCE, shoulderB: 88, elbowB: 12, torso: 26, offX: 4 }),
        kf(36, { ...STANCE, shoulderB: 20, elbowB: 40, torso: 8 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Jab",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 18,
      airborne: true,
      landCancel: true,
      landRecovery: 2,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [4, 16],
      hits: [hit(4, 9, bx(16, 34, 46, 28), 32, { fx: "blunt", hitstun: 14, pushX: 2.6 })],
      desc: "Quick air punch to stuff other jump-ins.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 32, kneeF: 42, hipB: -22, kneeB: 40 }, "out"),
        kf(4, { ...STANCE, free: 1, shoulderB: 88, elbowB: 10, torso: 12 }),
        kf(11, { ...STANCE, free: 1, shoulderB: 40, elbowB: 34, torso: 6 }, "inOut"),
        kf(18, { ...STANCE, free: 1, hipF: 32, kneeF: 42, hipB: -22, kneeB: 40 }),
      ],
    },
    {
      id: "jB",
      name: "Air Kick",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 24,
      airborne: true,
      landCancel: true,
      landRecovery: 4,
      hits: [hit(6, 13, bx(20, 16, 60, 42), 54, { fx: "blunt", pushX: 4, hitstun: 18 })],
      desc: "Forward air kick with good horizontal range.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 30, kneeF: 40, hipB: -22, kneeB: 38 }, "out"),
        kf(4, { ...STANCE, free: 1, hipF: 4, kneeF: 90, torso: 10 }),
        kf(7, { ...STANCE, free: 1, hipF: 76, kneeF: 8, hipB: -26, kneeB: 44, torso: 18, shoulderF: -20, elbowF: 50 }, "out"),
        kf(16, { ...STANCE, free: 1, hipF: 50, kneeF: 40, torso: 10 }, "inOut"),
        kf(24, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "jC",
      name: "Falling Hammer",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 28,
      airborne: true,
      landCancel: true,
      landRecovery: 7,
      hits: [
        hit(8, 18, bx(4, -2, 58, 46), 82, {
          guard: "overhead",
          fx: "blunt",
          knockdown: "soft",
          pushX: 5,
          shake: 1.5,
        }),
      ],
      desc: "Two-fisted hammer blow straight down. Big jump-in damage.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, torso: -22, shoulderF: 170, elbowF: -10, shoulderB: 160, elbowB: -6, hipF: 40, kneeF: 56 }),
        kf(9, { ...STANCE, free: 1, torso: 30, shoulderF: 22, elbowF: 10, shoulderB: 26, elbowB: 8, hipF: 16, kneeF: 20 }, "out"),
        kf(28, { ...STANCE, free: 1, torso: 24, shoulderF: 26, elbowF: 14, shoulderB: 30, elbowB: 12 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Shoulder Barge",
      input: { button: "C", dir: "f", stance: "stand", whileDashing: true },
      tags: ["command"],
      priority: 12,
      duration: 34,
      vel: [
        { at: 3, x: 9.4 },
        { at: 16, x: 0 },
      ],
      friction: 0.9,
      armor: [{ from: 3, to: 13, hits: 1, damageScale: 0.5 }],
      hits: [hit(8, 14, bx(18, 30, 60, 54), 74, { fx: "blunt", pushX: 8, knockdown: "soft", hitstun: 22, shake: 1.5 })],
      desc: "Running shoulder charge with one hit of armour.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 26, shoulderF: -30, elbowF: 60, shoulderB: -34, elbowB: 56, hipB: -32, kneeB: 50, offX: -3 }),
        kf(8, { ...STANCE, torso: 34, shoulderF: -20, elbowF: 40, shoulderB: -24, elbowB: 36, hipF: 44, kneeF: 26, hipB: -26, kneeB: 56, offX: 8 }, "out"),
        kf(22, { ...STANCE, torso: 20, offX: 4 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },

    // --------------------------------------------------------------- specials
    {
      id: "quickdraw",
      name: "Quickdraw",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      duration: 30,
      resourceCost: 1,
      resourceMin: 1,
      projectiles: [
        {
          at: 9,
          kind: "bullet",
          x: 44,
          y: 62,
          vx: 24,
          vy: 0,
          life: 50,
          box: { x: -10, y: -4, w: 20, h: 8 },
          damage: 52,
          hitstun: 18,
          blockstun: 12,
          chip: 4,
          pushX: 4,
          clashes: true,
          fx: "shot",
          color: "#ffcf6b",
          trail: "#ffcf6b",
        },
      ],
      vfx: [{ at: 9, kind: "shot", x: 48, y: 62, scale: 1, color: "#ffcf6b" }],
      desc: "One round, straight and fast. The core of his zoning.",
      notation: "↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderF: 40, elbowF: 20, weapon: -30, torso: -4 }),
        kf(9, { ...STANCE, shoulderF: 88, elbowF: -2, weapon: -6, torso: 8, offX: 2 }, "out"),
        kf(15, { ...STANCE, shoulderF: 100, elbowF: -12, weapon: 14, torso: -6, offX: -2 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "fanHammer",
      name: "Fan the Hammer",
      input: { button: "C", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      priority: 20,
      duration: 46,
      resourceCost: 3,
      resourceMin: 3,
      friction: 0.92,
      projectiles: [
        {
          at: 8,
          kind: "bullet",
          x: 44,
          y: 64,
          vx: 23,
          vy: 0,
          life: 50,
          box: { x: -10, y: -4, w: 20, h: 8 },
          damage: 34,
          hitstun: 16,
          blockstun: 11,
          chip: 3,
          pushX: 2,
          clashes: true,
          fx: "shot",
          color: "#ffcf6b",
          trail: "#ffcf6b",
        },
        {
          at: 14,
          kind: "bullet",
          x: 44,
          y: 58,
          vx: 23,
          vy: 0,
          life: 50,
          box: { x: -10, y: -4, w: 20, h: 8 },
          damage: 30,
          hitstun: 16,
          blockstun: 11,
          chip: 3,
          pushX: 2,
          clashes: true,
          fx: "shot",
          color: "#ffcf6b",
          trail: "#ffcf6b",
        },
        {
          at: 20,
          kind: "bullet",
          x: 44,
          y: 52,
          vx: 24,
          vy: 0,
          life: 50,
          box: { x: -10, y: -4, w: 20, h: 8 },
          damage: 42,
          hitstun: 22,
          blockstun: 13,
          chip: 4,
          pushX: 8,
          knockdown: "soft",
          clashes: true,
          fx: "shot",
          color: "#ffcf6b",
          trail: "#ffcf6b",
        },
      ],
      vfx: [
        { at: 8, kind: "shot", x: 48, y: 64, scale: 1, color: "#ffcf6b" },
        { at: 14, kind: "shot", x: 48, y: 58, scale: 1, color: "#ffcf6b" },
        { at: 20, kind: "shot", x: 48, y: 52, scale: 1.2, color: "#ffcf6b" },
      ],
      desc: "Three rounds in half a second. Expensive, but it wins fireball wars.",
      notation: "↓↘→ + C  (3 rounds)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, shoulderF: 74, elbowF: 8, weapon: -14, torso: 4 }),
        kf(8, { ...STANCE, shoulderF: 90, elbowF: -4, weapon: -4, shoulderB: 60, elbowB: 30, torso: 8 }, "out"),
        kf(14, { ...STANCE, shoulderF: 86, elbowF: -2, weapon: 2, shoulderB: 74, elbowB: 20, torso: 2, offX: -1 }, "out"),
        kf(20, { ...STANCE, shoulderF: 92, elbowF: -6, weapon: 8, shoulderB: 66, elbowB: 26, torso: -2, offX: -2 }, "out"),
        kf(32, { ...STANCE, shoulderF: 60, elbowF: 20, weapon: -10, torso: 2 }, "inOut"),
        kf(46, { ...STANCE }),
      ],
    },
    {
      id: "quickdrawEx",
      name: "Six Shooter",
      input: { button: "S", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "projectile"],
      priority: 26,
      duration: 42,
      meterCost: 50,
      projectiles: [
        {
          at: 7,
          kind: "bullet",
          x: 44,
          y: 66,
          vx: 26,
          vy: 0,
          life: 50,
          box: { x: -12, y: -5, w: 24, h: 10 },
          damage: 40,
          hitstun: 18,
          blockstun: 12,
          chip: 4,
          pushX: 2,
          hits: 2,
          clashes: false,
          fx: "shot",
          color: "#fff2c9",
          trail: "#ffcf6b",
        },
        {
          at: 13,
          kind: "bullet",
          x: 44,
          y: 56,
          vx: 26,
          vy: 0,
          life: 50,
          box: { x: -12, y: -5, w: 24, h: 10 },
          damage: 38,
          hitstun: 18,
          blockstun: 12,
          chip: 4,
          pushX: 2,
          hits: 2,
          clashes: false,
          fx: "shot",
          color: "#fff2c9",
          trail: "#ffcf6b",
        },
        {
          at: 19,
          kind: "bullet",
          x: 44,
          y: 46,
          vx: 26,
          vy: 0,
          life: 50,
          box: { x: -12, y: -5, w: 24, h: 10 },
          damage: 48,
          hitstun: 26,
          blockstun: 14,
          chip: 5,
          pushX: 10,
          knockdown: "hard",
          hits: 2,
          clashes: false,
          fx: "shot",
          color: "#fff2c9",
          trail: "#ffcf6b",
        },
      ],
      vfx: [
        { at: 7, kind: "shot", x: 48, y: 66, scale: 1.2, color: "#fff2c9" },
        { at: 13, kind: "shot", x: 48, y: 56, scale: 1.2, color: "#fff2c9" },
        { at: 19, kind: "shot", x: 48, y: 46, scale: 1.4, color: "#fff2c9" },
      ],
      desc: "EX. Three armour-piercing rounds that plough through other projectiles - and no ammo cost.",
      notation: "↓↘→ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 80, elbowF: 4, weapon: -10, torso: 6 }),
        kf(7, { ...STANCE, shoulderF: 94, elbowF: -6, weapon: 0, torso: 10, offX: 1 }, "out"),
        kf(13, { ...STANCE, shoulderF: 90, elbowF: -4, weapon: 6, torso: 4, offX: -1 }, "out"),
        kf(19, { ...STANCE, shoulderF: 96, elbowF: -8, weapon: 12, torso: -2, offX: -3 }, "out"),
        kf(30, { ...STANCE, shoulderF: 62, elbowF: 18, weapon: -12, torso: 2 }, "inOut"),
        kf(42, { ...STANCE }),
      ],
    },
    {
      id: "dynamite",
      name: "Dynamite Toss",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      priority: 18,
      duration: 40,
      resourceCost: 2,
      resourceMin: 2,
      showProps: ["dynamite"],
      projectiles: [
        {
          at: 12,
          kind: "dynamite",
          x: 28,
          y: 74,
          vx: 7.5,
          vy: 7,
          gravity: 0.42,
          bounce: 0.46,
          bounces: 2,
          life: 70,
          box: { x: -10, y: -10, w: 20, h: 20 },
          damage: 40,
          hitstun: 20,
          blockstun: 12,
          pushX: 4,
          fx: "explode",
          color: "#a83b2a",
          detonate: {
            radius: 76,
            damage: 76,
            hitstun: 28,
            blockstun: 16,
            knockdown: "hard",
            chip: 8,
          },
          scale: 1,
          spin: 14,
        },
      ],
      desc: "Lobs a stick of dynamite in an arc. Explodes on landing - controls the whole midscreen.",
      notation: "↓↙← + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(7, { ...STANCE, shoulderB: -90, elbowB: 60, torso: -16, offX: -4 }, "inOut"),
        kf(12, { ...STANCE, shoulderB: 130, elbowB: -20, torso: 18, hipF: 30, kneeF: 20, offX: 5 }, "out"),
        kf(22, { ...STANCE, shoulderB: 70, elbowB: 20, torso: 8 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "dynamiteEx",
      name: "Powder Keg",
      input: { button: "S", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "ex", "projectile"],
      priority: 26,
      duration: 46,
      meterCost: 50,
      showProps: ["dynamite"],
      projectiles: [
        {
          at: 10,
          kind: "dynamite",
          x: 28,
          y: 74,
          vx: 5,
          vy: 8,
          gravity: 0.42,
          bounce: 0.4,
          bounces: 1,
          life: 70,
          box: { x: -10, y: -10, w: 20, h: 20 },
          damage: 36,
          hitstun: 20,
          blockstun: 12,
          pushX: 4,
          fx: "explode",
          color: "#a83b2a",
          detonate: { radius: 74, damage: 60, hitstun: 26, blockstun: 15, knockdown: "hard", chip: 6 },
          spin: 16,
        },
        {
          at: 16,
          kind: "dynamite",
          x: 28,
          y: 74,
          vx: 10,
          vy: 6.4,
          gravity: 0.42,
          bounce: 0.4,
          bounces: 1,
          life: 70,
          box: { x: -10, y: -10, w: 20, h: 20 },
          damage: 36,
          hitstun: 20,
          blockstun: 12,
          pushX: 4,
          fx: "explode",
          color: "#d8552f",
          detonate: { radius: 80, damage: 66, hitstun: 28, blockstun: 16, knockdown: "hard", chip: 7 },
          spin: -16,
        },
      ],
      desc: "EX. Two sticks at different ranges - almost impossible to walk through.",
      notation: "↓↙← + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderB: -96, elbowB: 66, torso: -18, offX: -5 }, "inOut"),
        kf(10, { ...STANCE, shoulderB: 126, elbowB: -16, torso: 16, offX: 4 }, "out"),
        kf(13, { ...STANCE, shoulderB: -80, elbowB: 60, torso: -12, offX: -3 }, "inOut"),
        kf(16, { ...STANCE, shoulderB: 134, elbowB: -22, torso: 20, hipF: 30, kneeF: 20, offX: 6 }, "out"),
        kf(28, { ...STANCE, shoulderB: 60, elbowB: 26, torso: 6 }, "inOut"),
        kf(46, { ...STANCE }),
      ],
    },
    {
      id: "ricochet",
      name: "Ricochet Shot",
      input: { button: "C", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "projectile"],
      priority: 20,
      duration: 36,
      resourceCost: 1,
      resourceMin: 1,
      projectiles: [
        {
          at: 10,
          kind: "bullet",
          x: 36,
          y: 20,
          vx: 9,
          vy: 9.5,
          gravity: 0.14,
          life: 80,
          box: { x: -10, y: -6, w: 20, h: 12 },
          damage: 56,
          hitstun: 24,
          blockstun: 14,
          chip: 5,
          pushX: 6,
          knockdown: "soft",
          clashes: true,
          fx: "shot",
          color: "#ffe6a8",
          trail: "#ffcf6b",
        },
      ],
      vfx: [{ at: 10, kind: "shot", x: 38, y: 18, scale: 1, color: "#ffcf6b" }],
      desc: "Bounces a round off the dirt into an arc - a bullet that beats jump-ins.",
      notation: "↓↙← + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, crouch: 0.5, shoulderF: 8, elbowF: 30, weapon: -50, torso: 18 }),
        kf(10, { ...STANCE, crouch: 0.6, shoulderF: 22, elbowF: 16, weapon: -60, torso: 24, offX: 2 }, "out"),
        kf(20, { ...STANCE, crouch: 0.4, shoulderF: 40, elbowF: 30, weapon: -30, torso: 10 }, "inOut"),
        kf(36, { ...STANCE }),
      ],
    },
    {
      id: "risingSpur",
      name: "Rising Spur",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 24,
      duration: 44,
      airborne: true,
      invuln: [{ from: 1, to: 8, kind: "strike" }],
      vel: [
        { at: 1, x: 2.6, y: 12 },
        { at: 24, y: -0.9, mode: "add" },
      ],
      hits: [
        hit(3, 9, bx(8, 46, 58, 78), 84, { launch: [2.4, 10], knockdown: "launch", fx: "slash", hitstun: 26, shake: 1.8 }),
        hit(10, 16, bx(6, 60, 52, 66), 34, { group: 2, launch: [1.4, 5], fx: "slash" }),
      ],
      desc: "Invincible rising spur kick. Reversal, anti-air, and combo ender.",
      notation: "→↓↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 24, kneeF: 48 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -14, hipF: 96, kneeF: 6, hipB: -30, kneeB: 40, shoulderF: -30, elbowF: 40, shoulderB: -40, elbowB: 36 }, "out"),
        kf(14, { ...STANCE, free: 1, torso: -20, hipF: 110, kneeF: 2, hipB: -34, kneeB: 30, shoulderF: -50, shoulderB: -56 }),
        kf(30, { ...STANCE, free: 1, torso: -4, hipF: 50, kneeF: 34, hipB: -20, kneeB: 40 }, "inOut"),
        kf(44, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "airShot",
      name: "Air Quickdraw",
      input: { button: "B", motion: "qcf", stance: "air" },
      tags: ["special", "air", "projectile"],
      variant: "quickdraw",
      priority: 26,
      duration: 30,
      airborne: true,
      resourceCost: 1,
      resourceMin: 1,
      projectiles: [
        {
          at: 8,
          kind: "bullet",
          x: 34,
          y: 40,
          vx: 17,
          vy: -6,
          gravity: 0.12,
          life: 60,
          box: { x: -10, y: -4, w: 20, h: 8 },
          damage: 46,
          hitstun: 18,
          blockstun: 12,
          chip: 4,
          pushX: 4,
          clashes: true,
          fx: "shot",
          color: "#ffcf6b",
          trail: "#ffcf6b",
        },
      ],
      vfx: [{ at: 8, kind: "shot", x: 38, y: 40, scale: 1, color: "#ffcf6b" }],
      desc: "Fires down at an angle from a jump. Great for controlling the ground.",
      notation: "(air) ↓↘→ + B",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(5, { ...STANCE, free: 1, shoulderF: 60, elbowF: 20, weapon: -40, torso: 14 }),
        kf(8, { ...STANCE, free: 1, shoulderF: 76, elbowF: 6, weapon: -50, torso: 20, hipF: 34, kneeF: 40 }, "out"),
        kf(18, { ...STANCE, free: 1, shoulderF: 50, elbowF: 26, weapon: -30, torso: 10 }, "inOut"),
        kf(30, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "reload",
      name: "Reload",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill"],
      priority: 18,
      duration: 52,
      resourceGain: 6,
      meterGain: 8,
      friction: 0.9,
      desc: "SKILL. Fills all six chambers. Long recovery - do it after a knockdown, not in their face.",
      notation: "A + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(10, { ...STANCE, shoulderF: 66, elbowF: 60, shoulderB: 50, elbowB: 74, weapon: -70, torso: 10, head: 6 }, "inOut"),
        kf(24, { ...STANCE, shoulderF: 70, elbowF: 66, shoulderB: 56, elbowB: 80, weapon: -80, torso: 14, head: 8 }),
        kf(34, { ...STANCE, shoulderF: 60, elbowF: 50, shoulderB: 40, elbowB: 60, weapon: -60, torso: 8, head: 4 }, "inOut"),
        kf(42, { ...STANCE, shoulderF: 30, elbowF: 40, weapon: -20, torso: 2 }, "inOut"),
        kf(52, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "High Noon",
      input: { button: "S", motion: "hcb", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 116,
      meterCost: 100,
      superFreeze: 46,
      invuln: [{ from: 1, to: 16, kind: "strike" }],
      friction: 0.9,
      projectiles: [
        {
          at: 40,
          kind: "bullet",
          armAfter: 0,
          x: 46,
          y: 66,
          vx: 30,
          vy: 0,
          life: 60,
          box: { x: -16, y: -8, w: 32, h: 16 },
          damage: 70,
          hitstun: 30,
          blockstun: 18,
          chip: 10,
          pushX: 4,
          hits: 3,
          fx: "shot",
          color: "#fff6dd",
          trail: "#ffcf6b",
        },
        {
          at: 48,
          kind: "bullet",
          armAfter: 0,
          x: 46,
          y: 58,
          vx: 30,
          vy: 0,
          life: 60,
          box: { x: -16, y: -8, w: 32, h: 16 },
          damage: 60,
          hitstun: 30,
          blockstun: 18,
          chip: 8,
          pushX: 4,
          hits: 3,
          fx: "shot",
          color: "#fff6dd",
          trail: "#ffcf6b",
        },
        {
          at: 56,
          kind: "bullet",
          armAfter: 0,
          x: 46,
          y: 50,
          vx: 32,
          vy: 0,
          life: 60,
          box: { x: -18, y: -10, w: 36, h: 20 },
          damage: 110,
          hitstun: 40,
          blockstun: 20,
          chip: 14,
          pushX: 14,
          knockdown: "hard",
          hits: 3,
          fx: "shot",
          color: "#ffffff",
          trail: "#fff2c9",
          detonate: { radius: 40, damage: 20, hitstun: 20, blockstun: 12, knockdown: "hard" },
        },
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 50, scale: 2.6, color: "#ffcf6b" },
        { at: 40, kind: "shot", x: 50, y: 66, scale: 1.6, color: "#fff6dd" },
        { at: 48, kind: "shot", x: 50, y: 58, scale: 1.6, color: "#fff6dd" },
        { at: 56, kind: "shot", x: 50, y: 50, scale: 2, color: "#ffffff" },
      ],
      desc: "SUPER. Squares up, hat down - then empties the iron in three screen-long shots.",
      notation: "→↘↓↙← + S  (100 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(14, { ...STANCE, torso: -6, head: 10, shoulderF: 4, elbowF: 20, shoulderB: -8, elbowB: 16, hipF: 8, kneeF: 10 }, "inOut"),
        kf(30, { ...STANCE, torso: -8, head: 12, shoulderF: 0, elbowF: 14, weapon: -40, offY: 1 }),
        kf(38, { ...STANCE, torso: 6, head: -4, shoulderF: 86, elbowF: -4, weapon: -4, offX: 3 }, "out"),
        kf(46, { ...STANCE, torso: 2, shoulderF: 92, elbowF: -8, weapon: 4, offX: 1 }, "out"),
        kf(56, { ...STANCE, torso: -2, shoulderF: 98, elbowF: -12, weapon: 12, offX: -2 }, "out"),
        kf(78, { ...STANCE, torso: 4, shoulderF: 50, elbowF: 24, weapon: -20 }, "inOut"),
        kf(116, { ...STANCE }),
      ],
    },
  ],
};
