/**
 * Mgobozi ovela Ntla (d. c. 1828) - Zulu induna, Shaka's friend from boyhood
 * and one of his most trusted commanders.
 *
 * Shaka's regiments threw away the throwing spear and closed to arm's length
 * with a short stabbing blade and a shield taller than a man. That is the whole
 * character: the isihlangu hooks their guard aside and the iklwa goes into the
 * gap. He has no answer at range because he was never meant to have one.
 */

import type { FighterDef } from "../types";
import { bx, guardClips, hit, kf, universalMoves } from "./builders";

const HIDE = "#efe8dc";
const HIDE_DARK = "#3a3229";
const OX = "#a8724a";
const IRON = "#b9c2c9";
const BEAD = "#c23a2f";

/** Shield up and forward, the iklwa held low and hidden behind it. */
const STANCE = {
  torso: 9,
  head: -3,
  hipF: 17,
  kneeF: 18,
  hipB: -18,
  kneeB: 30,
  shoulderF: 26,
  elbowF: 74,
  shoulderB: 22,
  elbowB: 68,
  weapon: 22,
};

const guard = { shoulderB: 54, elbowB: 88 };

export const ZULU: FighterDef = {
  id: "zulu",
  name: "Mgobozi ovela Ntla",
  title: "Induna of the Fasimba",
  era: "Gqokli Hill, 1818",
  bio: "Shaka's companion since boyhood and an induna of the Fasimba regiment. Held the ridge at Gqokli Hill against a force several times his own. Believes a fight has exactly one correct distance and spends the round getting there.",
  archetype: "Pressure / Footsies",
  difficulty: 3,
  strengths: ["Relentless forward pressure", "Shield hooks break guards", "Excellent normals"],
  weaknesses: ["No projectile at all", "Short reach on everything", "Loses badly to zoning"],
  winQuote: "The horns close. There was never anywhere to go.",
  palette: {
    body: "#7a5236",
    outline: "#141210",
    accent: BEAD,
    cloth: OX,
    metal: IRON,
    aura: "#ff8a5c",
  },
  stats: {
    health: 1000,
    walkF: 3.15,
    walkB: 2.5,
    dashSpeed: 9,
    dashFrames: 14,
    backdashFrames: 19,
    jumpVel: 12.8,
    jumpFwd: 5.2,
    gravity: 0.64,
    weight: 0.98,
    airMoves: 2,
    doubleJump: false,
    airDash: false,
    width: 20,
    standHeight: 106,
    crouchHeight: 66,
    scale: 1.02,
  },
  stance: STANCE,
  // The isihlangu covers him from head to knee; the iklwa waits behind it,
  // which is exactly how the shield and the stabbing spear were meant to work.
  clips: guardClips({
    high: { torso: 4, head: -8, shoulderB: -12, elbowB: 100, shoulderF: 6, elbowF: 96, weapon: 58, hipF: 15, kneeF: 24, hipB: -18, kneeB: 34, offX: -3 },
    low: { torso: 10, head: -6, shoulderB: -26, elbowB: 108, shoulderF: 10, elbowF: 92, weapon: 58, hipF: 32, kneeF: 74, hipB: -20, kneeB: 84, offX: -3 },
  }),
  resource: {
    name: "Impi",
    max: 100,
    start: 30,
    // The regiment's momentum: it builds by fighting forward and bleeds away
    // the moment he stops. Spent on the encirclement.
    gainOnHit: 6,
    gainOnBlocked: 3,
    gainOnTakeHit: 2,
    color: "#ff8a5c",
  },
  props: [
    {
      id: "headring",
      attach: "head",
      // Isicoco: the married man's head ring, sewn into the hair and polished
      // with beeswax, with a crane feather standing out of it.
      parts: [
        { geo: "poly", size: [-11, 0, -9, 6, 0, 8, 9, 5, 11, -1, 8, -4, -8, -3], pos: [0, 3], color: "#241c15" },
        { geo: "ring", size: [10, 3.2], pos: [0, 3], color: "#3b2c1c" },
        // Crane feather rising from the back of the ring.
        { geo: "poly", size: [0, 0, -5, 9, -4, 18, 0, 22, 3, 16, 4, 8], pos: [-6, 10], color: HIDE },
        { geo: "box", size: [1.4, 20], pos: [-5, 14], color: "#c8bfae" },
        // Beaded band across the brow.
        { geo: "box", size: [16, 2.6], pos: [1, 1], color: BEAD, z: 0.6 },
        { geo: "disc", size: [1.1], pos: [-4, 1], color: HIDE, z: 0.7 },
        { geo: "disc", size: [1.1], pos: [2, 1.3], color: "#2f6fb5", z: 0.7 },
        { geo: "disc", size: [1.1], pos: [7, 1.3], color: HIDE, z: 0.7 },
      ],
    },
    {
      id: "iklwa",
      attach: "handF",
      // Iklwa: a broad leaf-shaped blade on a short haft. Named for the sound
      // it makes coming back out.
      parts: [
        { geo: "cyl", size: [2.6, 30], pos: [14, 0], rot: 90, color: "#6b4a2c" },
        // Binding where the tang is set into the haft.
        { geo: "box", size: [9, 6.5], pos: [30, 0], color: OX },
        { geo: "box", size: [9, 1.6], pos: [30, 2], color: "#5c3a1e" },
        // Broad leaf blade with a raised midrib.
        { geo: "poly", size: [0, 0, 8, 9, 22, 8, 34, 0, 22, -8, 8, -9], pos: [36, 0], color: "#dbe3ea" },
        { geo: "box", size: [30, 2.4], pos: [50, 0], color: "#9aa6b1" },
        // Grip binding and a cow-tail tassel at the butt.
        { geo: "box", size: [12, 6], pos: [2, 0], color: "#4a3220" },
        { geo: "poly", size: [0, 4, -8, 6, -12, 0, -8, -6, 0, -4], pos: [-6, 0], color: HIDE },
      ],
    },
    {
      id: "isihlangu",
      attach: "forearmB",
      // War shield: a tall oval of ox hide over a stick, white with the black
      // patches of the beast it came from, laced with a double row of hide
      // strips down the middle.
      parts: [
        { geo: "poly", size: [-16, 30, -13, 38, 0, 42, 13, 38, 16, 30, 16, -30, 13, -38, 0, -42, -13, -38, -16, -30], pos: [10, 0], color: HIDE, z: 0.5 },
        // Hide patches - every shield in a regiment was a different beast.
        { geo: "poly", size: [-9, 10, 2, 13, 8, 4, 4, -8, -6, -10, -11, -1], pos: [4, 16], color: HIDE_DARK, z: 0.55 },
        { geo: "poly", size: [-7, 7, 4, 9, 7, 0, 1, -8, -8, -5], pos: [15, -18], color: HIDE_DARK, z: 0.55 },
        // The stick running the full height, and the lacing over it.
        { geo: "box", size: [4, 92], pos: [10, 0], color: "#6b4a2c", z: 0.6 },
        { geo: "box", size: [12, 2.4], pos: [10, 22], color: "#4a3220", z: 0.65 },
        { geo: "box", size: [12, 2.4], pos: [10, 11], color: "#4a3220", z: 0.65 },
        { geo: "box", size: [12, 2.4], pos: [10, 0], color: "#4a3220", z: 0.65 },
        { geo: "box", size: [12, 2.4], pos: [10, -11], color: "#4a3220", z: 0.65 },
        { geo: "box", size: [12, 2.4], pos: [10, -22], color: "#4a3220", z: 0.65 },
        // Fur tuft at the top of the stick.
        { geo: "poly", size: [0, 0, -4, 8, 0, 12, 4, 8], pos: [10, 44], color: HIDE_DARK, z: 0.7 },
      ],
    },
    {
      id: "amashoba",
      attach: "torso",
      // Cow-tail bundles worn over the chest and shoulders - the regiment's
      // dress, and they hide the shape of a man in long grass.
      parts: [
        { geo: "poly", size: [-9, -12, 9, -12, 10, 8, 6, 14, -6, 14, -10, 8], pos: [0, 3], color: OX },
        // Tail bundles hanging off the shoulders.
        { geo: "poly", size: [-4, 8, 4, 8, 3, -12, -3, -12], pos: [-8, 8], color: HIDE },
        { geo: "poly", size: [-4, 8, 4, 8, 3, -12, -3, -12], pos: [-1, 10], color: HIDE_DARK, z: 0.1 },
        { geo: "poly", size: [-4, 8, 4, 8, 3, -12, -3, -12], pos: [6, 8], color: HIDE },
        // Beadwork bandolier across the chest.
        { geo: "poly", size: [-13, 3, 12, -9, 11, -12, -14, 0], pos: [0, 6], color: BEAD, z: 0.4 },
        { geo: "disc", size: [1.2], pos: [-9, 4], color: HIDE, z: 0.5 },
        { geo: "disc", size: [1.2], pos: [-2, 1], color: "#2f6fb5", z: 0.5 },
        { geo: "disc", size: [1.2], pos: [5, -3], color: HIDE, z: 0.5 },
      ],
    },
    {
      id: "umutsha",
      attach: "pelvis",
      // Hide belt with the tails hanging front and back.
      parts: [
        { geo: "box", size: [26, 6], pos: [0, 1], color: "#4a3220" },
        { geo: "poly", size: [-3, 6, 3, 6, 2, -13, -2, -13], pos: [-7, -7], color: HIDE, behind: true },
        { geo: "poly", size: [-3, 7, 3, 7, 2, -15, -2, -15], pos: [0, -8], color: HIDE_DARK, behind: true },
        { geo: "poly", size: [-3, 6, 3, 6, 2, -13, -2, -13], pos: [7, -7], color: HIDE, behind: true },
        { geo: "disc", size: [1.4], pos: [0, -24], color: BEAD, behind: true },
      ],
    },
    {
      id: "ankleTails",
      attach: "footF",
      // More cow tails, tied below the knee.
      parts: [
        { geo: "poly", size: [-4, 3, 4, 3, 3, -8, -3, -8], pos: [-1, 8], color: HIDE },
        { geo: "box", size: [7, 2], pos: [-1, 11], color: BEAD },
      ],
    },
  ],

  moves: [
    ...universalMoves({
      throwDamage: 128,
      backThrowDamage: 138,
      throwRange: 60,
      rollSpeed: 8,
      weaponIdle: { weapon: STANCE.weapon },
    }),

    // ---------------------------------------------------------------- normals
    {
      id: "5A",
      name: "Shield Edge",
      input: { button: "A", stance: "stand" },
      tags: ["light"],
      duration: 13,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [3, 12],
      // Shield Hook string continues into 6A.
      followUps: [
        { button: "A", move: "6A", from: 4, to: 10, string: "Shield Hook" },
      ],
      hits: [hit(4, 6, bx(18, 52, 42, 24), 32, { blockstun: 10, hitstun: 14, fx: "blunt", pushX: 3 })],
      desc: "Snaps the rim of the shield into their face. Fast, and it opens every string he has.",
      notation: "A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderB: 84, elbowB: 24, torso: 14, offX: 3 }),
        kf(8, { ...STANCE, shoulderB: 52, elbowB: 62, torso: 10 }, "inOut"),
        kf(13, { ...STANCE }),
      ],
    },
    {
      id: "5B",
      name: "Stab",
      input: { button: "B", stance: "stand" },
      tags: ["medium"],
      duration: 20,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [7, 18],
      // Iklwa Work string continues into 4B.
      followUps: [
        { button: "B", move: "4B", from: 7, to: 17, string: "Iklwa Work" },
      ],
      hits: [hit(7, 9, bx(24, 48, 60, 22), 58, { fx: "pierce", pushX: 4.2, hitstun: 18 })],
      desc: "Straight underarm thrust from behind the shield. Short, quick, and hard to see coming.",
      notation: "B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderF: 12, elbowF: 96, weapon: 44, torso: 0, offX: -3 }),
        kf(7, { ...STANCE, shoulderF: 62, elbowF: 14, weapon: 8, torso: 22, hipF: 32, kneeF: 18, offX: 8 }, "out"),
        kf(12, { ...STANCE, shoulderF: 58, elbowF: 18, weapon: 10, torso: 18, offX: 6 }),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "5C",
      name: "Rib Cut",
      input: { button: "C", stance: "stand" },
      tags: ["heavy"],
      duration: 30,
      cancelInto: ["special", "super"],
      cancelWindow: [14, 26],
      hits: [
        hit(13, 17, bx(20, 34, 66, 56), 88, {
          fx: "pierce",
          knockdown: "soft",
          pushX: 6.5,
          shake: 1.5,
        }),
      ],
      desc: "Hooks the shield out of the way and puts the blade in under the arm. Knocks down.",
      notation: "C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderB: 96, elbowB: 30, shoulderF: 6, elbowF: 100, weapon: 56, torso: -8, offX: -3 }, "inOut"),
        kf(13, { ...STANCE, shoulderB: 30, elbowB: 100, shoulderF: 74, elbowF: 8, weapon: 4, torso: 30, hipF: 38, kneeF: 22, offX: 9 }, "out"),
        kf(20, { ...STANCE, shoulderB: 36, elbowB: 94, shoulderF: 70, elbowF: 12, weapon: 6, torso: 26, offX: 6 }),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "2A",
      name: "Low Jab",
      input: { button: "A", stance: "crouch" },
      tags: ["light", "low"],
      duration: 14,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [4, 13],
      hits: [hit(4, 6, bx(16, 18, 40, 20), 28, { guard: "low", blockstun: 10, hitstun: 13, pushX: 2.6 })],
      desc: "Quick low stab. Must be blocked crouching, and it links into itself twice.",
      notation: "↓ + A",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, ...guard }, "out"),
        kf(4, { ...STANCE, crouch: 1, torso: 22, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderF: 62, elbowF: 12, weapon: 6, offX: 4 }),
        kf(9, { ...STANCE, crouch: 1, torso: 20, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderF: 36, elbowF: 56 }, "inOut"),
        kf(14, { ...STANCE, crouch: 1, torso: 18, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, ...guard }),
      ],
    },
    {
      id: "2B",
      name: "Knee Thrust",
      input: { button: "B", stance: "crouch" },
      tags: ["medium", "low"],
      duration: 24,
      cancelInto: ["heavy", "special", "super"],
      cancelWindow: [9, 22],
      hits: [hit(9, 12, bx(22, 12, 64, 26), 54, { guard: "low", fx: "pierce", pushX: 4.4 })],
      desc: "Drives the iklwa into the knee. His longest low.",
      notation: "↓ + B",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }, "out"),
        kf(5, { ...STANCE, crouch: 1, torso: 8, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86, shoulderF: 24, elbowF: 46, weapon: 26 }),
        kf(9, { ...STANCE, crouch: 1, torso: 26, hipF: 42, kneeF: 80, hipB: -26, kneeB: 90, shoulderF: 52, elbowF: 8, weapon: -30, offX: 9 }, "out"),
        kf(15, { ...STANCE, crouch: 1, torso: 24, hipF: 40, kneeF: 78, hipB: -24, kneeB: 88, shoulderF: 48, elbowF: 12, weapon: -30, offX: 7 }),
        kf(24, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }),
      ],
    },
    {
      id: "2C",
      name: "Hook the Ankle",
      input: { button: "C", stance: "crouch" },
      tags: ["heavy", "low"],
      duration: 30,
      cancelInto: ["special", "super"],
      cancelWindow: [13, 26],
      hits: [
        hit(12, 16, bx(16, 2, 70, 24), 76, {
          guard: "low",
          knockdown: "sweep",
          fx: "blunt",
          pushX: 5.8,
          shake: 1.2,
        }),
      ],
      desc: "Puts the bottom edge of the shield through their ankles. Knocks down and he is already standing over them.",
      notation: "↓ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }, "out"),
        kf(6, { ...STANCE, crouch: 1, torso: 4, hipF: 30, kneeF: 72, hipB: -30, kneeB: 94, shoulderB: 12, elbowB: 40 }),
        kf(12, { ...STANCE, crouch: 1, torso: 32, hipF: 46, kneeF: 86, hipB: -30, kneeB: 98, shoulderB: 96, elbowB: 40, offX: 7 }, "out"),
        kf(20, { ...STANCE, crouch: 1, torso: 28, hipF: 42, kneeF: 82, hipB: -26, kneeB: 92, shoulderB: 84, elbowB: 52 }),
        kf(30, { ...STANCE, crouch: 1, torso: 16, hipF: 34, kneeF: 76, hipB: -22, kneeB: 86 }),
      ],
    },
    {
      id: "6B",
      name: "Rim Overhead",
      input: { button: "B", dir: "f", stance: "stand" },
      tags: ["command", "overhead"],
      priority: 10,
      duration: 27,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 24],
      // Rim Strike string continues into 5C.
      followUps: [
        { button: "C", move: "5C", from: 16, to: 24, string: "Rim Strike" },
      ],
      hits: [
        hit(16, 19, bx(16, 42, 52, 58), 62, {
          guard: "overhead",
          fx: "blunt",
          pushX: 5,
          hitstun: 21,
          shake: 1.2,
        }),
      ],
      desc: "Chops the top rim of the shield down onto them. Overhead - pairs with his low.",
      notation: "→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderB: 156, elbowB: 20, torso: -14, offX: -3 }, "inOut"),
        kf(16, { ...STANCE, shoulderB: 40, elbowB: 40, torso: 32, hipF: 34, kneeF: 22, offX: 6 }, "out"),
        kf(21, { ...STANCE, shoulderB: 44, elbowB: 46, torso: 26, offX: 4 }),
        kf(27, { ...STANCE }),
      ],
    },
    {
      id: "3C",
      name: "Rising Iklwa",
      input: { button: "C", dir: "df", stance: ["stand", "crouch"] },
      tags: ["command", "launcher"],
      priority: 14,
      duration: 32,
      cancelInto: ["special", "super"],
      cancelWindow: [12, 28],
      hits: [
        hit(10, 14, bx(12, 50, 54, 74), 70, {
          launch: [2, 12.5],
          knockdown: "launch",
          fx: "pierce",
          hitstun: 24,
          shake: 1.3,
        }),
      ],
      desc: "Comes up under the chin. Launches - chase it into a jump attack.",
      notation: "↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.5, hipF: 24, kneeF: 46, hipB: -20, kneeB: 52 }, "out"),
        kf(5, { ...STANCE, crouch: 0.7, torso: 14, shoulderF: 4, elbowF: 92, weapon: 62 }),
        kf(10, { ...STANCE, torso: -16, shoulderF: 148, elbowF: 6, weapon: 12, hipF: 20, kneeF: 12, offY: 4 }, "out"),
        kf(17, { ...STANCE, torso: -12, shoulderF: 140, elbowF: 10, weapon: 14, hipF: 16, kneeF: 10 }),
        kf(25, { ...STANCE, torso: 6, shoulderF: 52, elbowF: 56 }, "inOut"),
        kf(32, { ...STANCE }),
      ],
    },
    {
      // Forward and back sets. Forward takes space, back gives it up to buy
      // range or a hard read.
      id: "6A",
      name: "Shield Hook",
      input: { button: "A", dir: "f", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 20,
      vel: [{ at: 2, x: 2.2 }],
      friction: 0.88,
      cancelInto: ["light", "medium", "heavy", "special", "super"],
      cancelWindow: [7, 18],
      // Shield Hook string continues into 6C.
      followUps: [
        { button: "C", move: "6C", from: 7, to: 17, string: "Shield Hook" },
      ],
      hits: [hit(7, 9, bx(20, 60, 44, 26), 32, { guard: "high", fx: "blunt", pushX: 3, hitstun: 14, hitstop: 5 })],
      desc: "Drives the shield edge in to hook theirs aside. Opens them up for everything else.",
      notation: "\u2192 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderB: 6, elbowB: 88, torso: -2, offX: -2 }, "out"),
        kf(7, { ...STANCE, shoulderB: 54, elbowB: 26, torso: 16, hipF: 28, kneeF: 18, offX: 7 }, "out"),
        kf(12, { ...STANCE, shoulderB: 40, elbowB: 50, torso: 12, offX: 5 }, "inOut"),
        kf(20, { ...STANCE }),
      ],
    },
    {
      id: "6C",
      name: "Horn of the Buffalo",
      input: { button: "C", dir: "f", stance: "stand" },
      tags: ["command", "heavy"],
      priority: 12,
      duration: 40,
      armor: [{ from: 8, to: 18, hits: 1, damageScale: 0.35 }],
      vel: [{ at: 8, x: 5.4 }, { at: 26, x: 0 }],
      friction: 0.9,
      cancelInto: ["special", "super"],
      cancelWindow: [20, 36],
      hits: [hit(16, 20, bx(19, 22, 70, 68), 88, { guard: "mid", fx: "blunt", pushX: 17, hitstun: 24, hitstop: 12, knockdown: "wallbounce", shake: 2.2 })],
      desc: "Runs them down behind the war shield. Carries them all the way to the wall.",
      notation: "\u2192 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, torso: -10, shoulderB: 2, elbowB: 94, hipB: -32, kneeB: 52, crouch: 0.28, offX: -6 }, "out"),
        kf(16, { ...STANCE, torso: 34, shoulderB: 48, elbowB: 44, hipF: 44, kneeF: 18, hipB: -28, kneeB: 24, crouch: 0.14, offX: 12 }, "out"),
        kf(24, { ...STANCE, torso: 26, shoulderB: 40, elbowB: 52, hipF: 30, kneeF: 24, offX: 8 }),
        kf(32, { ...STANCE, torso: 12, offX: 3 }, "inOut"),
        kf(40, { ...STANCE }),
      ],
    },
    {
      id: "4A",
      name: "Rim Rake",
      input: { button: "A", dir: "b", stance: "stand" },
      tags: ["command", "light"],
      priority: 12,
      duration: 22,
      vel: [{ at: 1, x: -2.6 }],
      friction: 0.86,
      cancelInto: ["medium", "heavy", "special", "super"],
      cancelWindow: [8, 20],
      hits: [hit(8, 10, bx(16, 52, 42, 30), 36, { guard: "mid", fx: "blunt", pushX: 6, hitstun: 15, hitstop: 6 })],
      desc: "Backs off and rakes the hide rim across them on the way out.",
      notation: "\u2190 + A",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, torso: -6, shoulderB: -6, elbowB: 98, hipB: -26, kneeB: 40, offX: -6 }, "out"),
        kf(8, { ...STANCE, torso: 8, shoulderB: 46, elbowB: 42, hipF: 22, kneeF: 20, offX: -3 }, "out"),
        kf(14, { ...STANCE, torso: 2, shoulderB: 34, elbowB: 58, offX: -4 }, "inOut"),
        kf(22, { ...STANCE }),
      ],
    },
    {
      id: "4B",
      name: "Underhand Stab",
      input: { button: "B", dir: "b", stance: "stand" },
      tags: ["command", "medium"],
      priority: 12,
      duration: 30,
      vel: [{ at: 1, x: -3.4 }],
      friction: 0.88,
      cancelInto: ["special", "super"],
      cancelWindow: [16, 27],
      // Iklwa Work string continues into 4C.
      followUps: [
        { button: "C", move: "4C", from: 12, to: 27, string: "Iklwa Work" },
      ],
      hits: [hit(12, 15, bx(30, 46, 76, 22), 56, { guard: "mid", fx: "pierce", pushX: 7, hitstun: 18, hitstop: 8 })],
      desc: "Gives ground and stabs out low from behind the shield. Exactly what the iklwa was made for.",
      notation: "\u2190 + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(6, { ...STANCE, shoulderF: 12, elbowF: 88, weapon: 56, torso: -10, hipB: -28, kneeB: 42, offX: -8 }, "inOut"),
        // Short spear driven straight out at waist height, blade level.
        kf(12, { ...STANCE, shoulderF: 62, elbowF: 20, weapon: 8, torso: 6, hipF: 28, kneeF: 14, offX: -5 }, "out"),
        kf(17, { ...STANCE, shoulderF: 60, elbowF: 22, weapon: 8, torso: 4, offX: -6 }),
        kf(23, { ...STANCE, shoulderF: 38, elbowF: 58, weapon: 30, torso: 0, offX: -4 }, "inOut"),
        kf(30, { ...STANCE }),
      ],
    },
    {
      id: "4C",
      name: "Overarm Iklwa",
      input: { button: "C", dir: "b", stance: "stand" },
      tags: ["command", "heavy", "overhead"],
      priority: 12,
      duration: 44,
      cancelInto: ["special", "super"],
      cancelWindow: [26, 40],
      hits: [hit(20, 23, bx(14, 20, 70, 86), 100, { guard: "overhead", fx: "pierce", pushX: 9, hitstun: 28, hitstop: 13, knockdown: "hard", shake: 2.4 })],
      desc: "Lifts the spear overhand and drives it down past the shield. Blocked standing only.",
      notation: "\u2190 + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(8, { ...STANCE, shoulderF: 132, elbowF: -40, weapon: 88, torso: -10, offX: -5 }, "inOut"),
        // Point up and back, then driven down over the shield rim.
        kf(15, { ...STANCE, shoulderF: 172, elbowF: -14, weapon: 96, torso: -20, hipB: -26, kneeB: 38, offY: 3, offX: -3 }, "out"),
        kf(20, { ...STANCE, shoulderF: 96, elbowF: 8, weapon: 62, torso: 30, hipF: 34, kneeF: 18, hipB: -12, kneeB: 32, offX: 6 }, "out"),
        kf(26, { ...STANCE, shoulderF: 88, elbowF: 12, weapon: 58, torso: 24, offX: 4 }),
        kf(36, { ...STANCE, shoulderF: 60, elbowF: 52, weapon: 40, torso: 8 }, "inOut"),
        kf(44, { ...STANCE }),
      ],
    },
    {
      id: "jA",
      name: "Air Rim",
      input: { button: "A", stance: "air" },
      tags: ["light", "air"],
      duration: 18,
      airborne: true,
      landCancel: true,
      landRecovery: 2,
      cancelInto: ["medium", "heavy", "special"],
      cancelWindow: [5, 16],
      hits: [hit(5, 10, bx(14, 32, 46, 30), 34, { fx: "blunt", pushX: 2.8, hitstun: 14 })],
      desc: "Shield swat out of the air. Beats most other jump-ins outright.",
      notation: "(air) A",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 34, kneeF: 46, hipB: -24, kneeB: 42 }, "out"),
        kf(5, { ...STANCE, free: 1, shoulderB: 110, elbowB: 26, torso: 16, hipF: 30, kneeF: 42 }),
        kf(12, { ...STANCE, free: 1, shoulderB: 66, elbowB: 66, torso: 10, hipF: 32, kneeF: 44 }, "inOut"),
        kf(18, { ...STANCE, free: 1, hipF: 34, kneeF: 46, hipB: -24, kneeB: 42 }),
      ],
    },
    {
      id: "jB",
      name: "Air Stab",
      input: { button: "B", stance: "air" },
      tags: ["medium", "air"],
      duration: 24,
      airborne: true,
      landCancel: true,
      landRecovery: 4,
      hits: [hit(6, 14, bx(18, 10, 58, 44), 60, { fx: "pierce", pushX: 4, hitstun: 19 })],
      desc: "Thrusts down through the arc. Deep jump-in that leaves him right on top of them.",
      notation: "(air) B",
      frames: [
        kf(0, { ...STANCE, free: 1, hipF: 30, kneeF: 42, hipB: -22, kneeB: 40 }, "out"),
        kf(3, { ...STANCE, free: 1, shoulderF: 6, elbowF: 96, weapon: 66, torso: -8 }),
        kf(6, { ...STANCE, free: 1, shoulderF: 76, elbowF: 12, weapon: 4, torso: 26, hipF: 38, kneeF: 34 }, "out"),
        kf(15, { ...STANCE, free: 1, shoulderF: 70, elbowF: 16, weapon: 6, torso: 22 }),
        kf(24, { ...STANCE, free: 1, hipF: 30, kneeF: 42, hipB: -22, kneeB: 40 }),
      ],
    },
    {
      id: "jC",
      name: "Shield Drop",
      input: { button: "C", stance: "air" },
      tags: ["heavy", "air", "overhead"],
      duration: 28,
      airborne: true,
      landCancel: true,
      landRecovery: 7,
      vel: [{ at: 5, y: -4, mode: "add" }],
      hits: [
        hit(7, 17, bx(-4, -6, 56, 46), 80, {
          guard: "overhead",
          fx: "blunt",
          knockdown: "soft",
          pushX: 4.6,
          shake: 1.6,
        }),
      ],
      desc: "Brings the whole shield down edge-first. Crushes low blocks.",
      notation: "(air) C",
      frames: [
        kf(0, { ...STANCE, free: 1 }, "out"),
        kf(4, { ...STANCE, free: 1, torso: -22, shoulderB: 156, elbowB: 6, hipF: 42, kneeF: 62, hipB: -30, kneeB: 60 }),
        kf(8, { ...STANCE, free: 1, torso: 32, shoulderB: 22, elbowB: 44, hipF: 20, kneeF: 20, hipB: -16, kneeB: 24 }, "out"),
        kf(28, { ...STANCE, free: 1, torso: 26, shoulderB: 26, elbowB: 48 }),
      ],
    },
    {
      id: "dashAttack",
      name: "Horn Rush",
      input: { button: "C", dir: "f", stance: "stand", whileDashing: true },
      tags: ["command"],
      priority: 12,
      duration: 32,
      vel: [
        { at: 3, x: 10 },
        { at: 16, x: 0 },
      ],
      friction: 0.89,
      hits: [
        hit(8, 14, bx(16, 26, 58, 60), 76, {
          fx: "blunt",
          pushX: 8,
          knockdown: "crumple",
          hitstun: 22,
          shake: 1.5,
        }),
      ],
      desc: "Runs the shield into them at full speed. Crumples on contact.",
      notation: "→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 26, shoulderB: 60, elbowB: 60, hipB: -34, kneeB: 46, offX: -2 }),
        kf(8, { ...STANCE, torso: 34, shoulderB: 88, elbowB: 20, hipF: 44, kneeF: 24, hipB: -26, kneeB: 56, offX: 8 }, "out"),
        kf(20, { ...STANCE, torso: 28, shoulderB: 80, elbowB: 32, hipF: 30, kneeF: 32 }),
        kf(32, { ...STANCE }),
      ],
    },

    // --------------------------------------------------------------- specials
    {
      id: "hook",
      name: "Hook the Shield",
      input: { button: "B", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 20,
      duration: 34,
      vel: [
        { at: 3, x: 4.5 },
        { at: 18, x: 0 },
      ],
      friction: 0.9,
      meterGain: 8,
      hits: [
        hit(9, 13, bx(18, 30, 58, 60), 56, {
          fx: "blunt",
          pushX: 3,
          hitstun: 20,
          // A hooked shield is a broken guard: this hurts far more to block
          // than it does to eat.
          blockstun: 4,
          shake: 1.3,
        }),
        hit(18, 22, bx(22, 40, 62, 34), 62, { group: 2, fx: "pierce", pushX: 6, hitstun: 22, knockdown: "soft" }),
      ],
      desc: "Catches the rim of their guard, drags it aside and puts the blade through the gap. Chews guard bars.",
      notation: "↓↘→ + B",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderB: 78, elbowB: 40, torso: 16, offX: 2 }, "out"),
        kf(9, { ...STANCE, shoulderB: 104, elbowB: 4, torso: 26, hipF: 34, kneeF: 20, offX: 7 }, "out"),
        kf(15, { ...STANCE, shoulderB: 128, elbowB: -12, torso: 12, offX: 5 }, "inOut"),
        kf(18, { ...STANCE, shoulderB: 130, elbowB: -14, shoulderF: 68, elbowF: 8, weapon: 4, torso: 28, offX: 8 }, "out"),
        kf(26, { ...STANCE, shoulderB: 70, elbowB: 50, shoulderF: 44, elbowF: 44, torso: 14 }, "inOut"),
        kf(34, { ...STANCE }),
      ],
    },
    {
      id: "hookEx",
      name: "Hook EX",
      input: { button: "S", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special", "ex"],
      priority: 28,
      duration: 46,
      meterCost: 50,
      vel: [
        { at: 3, x: 6 },
        { at: 26, x: 0 },
      ],
      friction: 0.92,
      hits: [
        hit(8, 12, bx(18, 30, 60, 60), 44, { group: 1, fx: "blunt", pushX: 2, hitstun: 18, blockstun: 3, hitstop: 5 }),
        hit(17, 21, bx(20, 34, 62, 52), 44, { group: 2, fx: "pierce", pushX: 2, hitstun: 18, blockstun: 3, hitstop: 5 }),
        hit(28, 34, bx(20, 24, 70, 68), 78, {
          group: 3,
          fx: "pierce",
          pushX: 10,
          knockdown: "hard",
          hitstun: 26,
          shake: 2,
        }),
      ],
      desc: "EX. Hooks twice and stabs once. Two of these break almost any guard bar outright.",
      notation: "↓↘→ + S  (50 meter)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(4, { ...STANCE, shoulderB: 82, elbowB: 34, torso: 18, offX: 3 }, "out"),
        kf(8, { ...STANCE, shoulderB: 108, elbowB: 0, torso: 26, offX: 6 }, "out"),
        kf(13, { ...STANCE, shoulderB: 60, elbowB: 60, torso: 10 }, "inOut"),
        kf(17, { ...STANCE, shoulderB: 112, elbowB: -6, torso: 28, offX: 6 }, "out"),
        kf(24, { ...STANCE, shoulderF: 4, elbowF: 100, weapon: 62, torso: -10, offX: -4 }, "inOut"),
        kf(28, { ...STANCE, shoulderF: 76, elbowF: 4, weapon: 2, torso: 34, hipF: 44, kneeF: 24, offX: 11 }, "out"),
        kf(38, { ...STANCE, shoulderF: 56, elbowF: 34, torso: 18, offX: 5 }, "inOut"),
        kf(46, { ...STANCE }),
      ],
    },
    {
      id: "gore",
      name: "Gore",
      input: { button: "C", motion: "qcf", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 22,
      duration: 42,
      armor: [{ from: 5, to: 18, hits: 1, damageScale: 0.4 }],
      vel: [
        { at: 4, x: 8 },
        { at: 24, x: 0 },
      ],
      friction: 0.91,
      hits: [
        hit(12, 20, bx(18, 22, 66, 66), 98, {
          fx: "pierce",
          pushX: 10,
          knockdown: "hard",
          hitstun: 26,
          shake: 2,
        }),
      ],
      desc: "Puts his shoulder behind the shield and the blade under it. Walks through one hit on the way.",
      notation: "↓↘→ + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, torso: 22, shoulderB: 66, elbowB: 56, shoulderF: 8, elbowF: 96, weapon: 56, hipB: -34, kneeB: 46, offX: -2 }, "out"),
        kf(12, { ...STANCE, torso: 34, shoulderB: 92, elbowB: 16, shoulderF: 66, elbowF: 8, weapon: 2, hipF: 44, kneeF: 24, hipB: -26, kneeB: 56, offX: 9 }, "out"),
        kf(26, { ...STANCE, torso: 28, shoulderB: 84, elbowB: 26, shoulderF: 58, elbowF: 16, hipF: 30, kneeF: 32, offX: 5 }),
        kf(42, { ...STANCE }),
      ],
    },
    {
      id: "leap",
      name: "Leaping Stab",
      input: { button: "C", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special", "overhead"],
      priority: 24,
      duration: 42,
      airborne: true,
      vel: [
        { at: 4, x: 7.5, y: 11 },
        { at: 22, y: -0.8, mode: "add" },
      ],
      hits: [
        hit(14, 23, bx(10, 8, 56, 54), 82, {
          guard: "overhead",
          fx: "pierce",
          pushX: 6,
          knockdown: "hard",
          hitstun: 24,
          shake: 1.6,
        }),
      ],
      desc: "Jumps their guard and comes down blade-first. Overhead, and it knocks down hard.",
      notation: "↓↙← + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 22, kneeF: 46 }, "out"),
        kf(6, { ...STANCE, free: 1, torso: -14, shoulderF: 148, elbowF: 8, weapon: 30, hipF: -14, kneeF: 66, hipB: -34, kneeB: 58 }, "out"),
        kf(14, { ...STANCE, free: 1, torso: 30, shoulderF: 64, elbowF: 10, weapon: 2, hipF: 52, kneeF: 20, hipB: -22, kneeB: 44 }, "out"),
        kf(30, { ...STANCE, free: 1, torso: 24, shoulderF: 58, elbowF: 18, hipF: 40, kneeF: 34 }, "inOut"),
        kf(42, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "rise",
      name: "Bull's Head",
      input: { button: "C", motion: "dp", stance: ["stand", "crouch"] },
      tags: ["special", "launcher"],
      priority: 26,
      duration: 44,
      airborne: true,
      invuln: [{ from: 1, to: 8, kind: "strike" }],
      vel: [
        { at: 1, x: 2.4, y: 12.4 },
        { at: 26, y: -1, mode: "add" },
      ],
      hits: [
        hit(3, 8, bx(4, 54, 58, 78), 80, {
          launch: [2, 11],
          knockdown: "launch",
          fx: "blunt",
          hitstun: 25,
          shake: 1.8,
        }),
        hit(9, 16, bx(2, 66, 54, 66), 38, { group: 2, launch: [1.6, 5.5], fx: "pierce", hitstun: 17 }),
      ],
      desc: "Drives up off the back foot behind the shield. Invincible on startup - his reversal.",
      notation: "→↓↘ + C",
      frames: [
        kf(0, { ...STANCE, crouch: 0.6, hipF: 22, kneeF: 50, hipB: -20, kneeB: 54 }, "out"),
        kf(3, { ...STANCE, free: 1, torso: -16, shoulderB: 152, elbowB: 10, shoulderF: 120, elbowF: 20, weapon: 24, hipF: 32, kneeF: 30, hipB: -26, kneeB: 40 }, "out"),
        kf(12, { ...STANCE, free: 1, torso: -22, shoulderB: 166, elbowB: 4, shoulderF: 138, elbowF: -14, weapon: 20, hipF: 26, kneeF: 26 }),
        kf(30, { ...STANCE, free: 1, torso: -2, shoulderB: 108, elbowB: 46, shoulderF: 90, elbowF: 40, hipF: 30, kneeF: 42 }, "inOut"),
        kf(44, { ...STANCE, free: 1 }),
      ],
    },
    {
      id: "encircle",
      name: "Encirclement",
      input: { button: "B", motion: "qcb", stance: ["stand", "crouch"] },
      tags: ["special"],
      priority: 24,
      duration: 54,
      resourceCost: 70,
      resourceMin: 70,
      vel: [
        { at: 3, x: 12 },
        { at: 14, x: 0 },
        { at: 22, x: -9 },
        { at: 32, x: 0 },
      ],
      friction: 0.9,
      noTurn: true,
      invuln: [{ from: 3, to: 16, kind: "strike" }],
      hits: [
        hit(9, 14, bx(16, 24, 60, 62), 66, { group: 1, fx: "pierce", pushX: 2, hitstun: 22, hitstop: 7 }),
        hit(26, 32, bx(-70, 24, 62, 62), 88, {
          group: 2,
          fx: "pierce",
          pushX: 9,
          knockdown: "hard",
          hitstun: 26,
          shake: 2.2,
        }),
      ],
      vfx: [{ at: 3, kind: "dust", x: 10, y: 4, scale: 1.4 }],
      desc: "Spends 70 Impi to run straight past them, stab, turn and stab again from behind. They cannot block both.",
      notation: "↓↙← + B  (70 Impi)",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(3, { ...STANCE, torso: 34, shoulderF: 10, elbowF: 90, weapon: 50, hipF: 46, kneeF: 24, hipB: -34, kneeB: 52, offX: 4 }, "out"),
        kf(9, { ...STANCE, torso: 32, shoulderF: 70, elbowF: 8, weapon: 4, hipF: 44, kneeF: 26, offX: 8 }, "out"),
        kf(18, { ...STANCE, torso: 12, spin: -40, shoulderF: 30, elbowF: 60, hipF: 28, kneeF: 44 }, "inOut"),
        kf(24, { ...STANCE, torso: -14, spin: -180, shoulderF: 20, elbowF: 84, weapon: 46, hipF: 20, kneeF: 40, offX: -4 }, "out"),
        kf(28, { ...STANCE, torso: -20, spin: -180, shoulderF: 78, elbowF: 6, weapon: 2, hipF: 30, kneeF: 26, offX: -8 }, "out"),
        kf(40, { ...STANCE, torso: -6, spin: -180, shoulderF: 44, elbowF: 46 }, "inOut"),
        kf(54, { ...STANCE, spin: -360 }),
      ],
    },
    {
      id: "war",
      name: "War Cry",
      input: { buttons: ["A", "C"], stance: ["stand", "crouch"] },
      tags: ["skill"],
      priority: 18,
      duration: 34,
      resourceGain: 45,
      friction: 0.86,
      armor: [{ from: 4, to: 22, hits: 1, damageScale: 0.5 }],
      vfx: [{ at: 8, kind: "aura", x: 0, y: 50, scale: 1.5, color: "#ff8a5c" }],
      desc: "SKILL. Hammers the iklwa on the shield and shouts. Fills 45 Impi and absorbs one hit while he does it.",
      notation: "A + C",
      frames: [
        kf(0, { ...STANCE }, "out"),
        kf(5, { ...STANCE, torso: -8, shoulderB: 84, elbowB: 30, shoulderF: 46, elbowF: 40, weapon: -10, head: -14, offX: -2 }, "out"),
        kf(10, { ...STANCE, torso: -14, shoulderB: 96, elbowB: 16, shoulderF: 62, elbowF: 20, weapon: -20, head: -20 }),
        kf(16, { ...STANCE, torso: -10, shoulderB: 88, elbowB: 26, shoulderF: 50, elbowF: 34, weapon: -12, head: -16 }),
        kf(22, { ...STANCE, torso: -14, shoulderB: 96, elbowB: 16, shoulderF: 62, elbowF: 20, weapon: -20, head: -20 }),
        kf(34, { ...STANCE }),
      ],
    },

    // ----------------------------------------------------------------- super
    {
      id: "super",
      name: "The Horns of the Buffalo",
      input: { button: "S", motion: "dd", stance: ["stand", "crouch"] },
      tags: ["super"],
      priority: 60,
      duration: 96,
      meterCost: 100,
      superFreeze: 40,
      invuln: [{ from: 1, to: 14, kind: "strike" }],
      vel: [
        { at: 5, x: 12 },
        { at: 28, x: 6 },
        { at: 52, x: 4 },
        { at: 68, x: 0 },
      ],
      friction: 0.93,
      hits: [
        hit(12, 15, bx(18, 40, 62, 42), 46, { group: 1, fx: "pierce", pushX: 1, hitstun: 20, hitstop: 5 }),
        hit(20, 23, bx(18, 20, 62, 44), 42, { group: 2, fx: "pierce", pushX: 1, hitstun: 18, hitstop: 4 }),
        hit(28, 31, bx(18, 44, 62, 42), 42, { group: 3, fx: "blunt", pushX: 1, hitstun: 18, hitstop: 4 }),
        hit(36, 39, bx(18, 26, 64, 50), 42, { group: 4, fx: "pierce", pushX: 1, hitstun: 18, hitstop: 4 }),
        hit(44, 47, bx(18, 38, 64, 46), 42, { group: 5, fx: "pierce", pushX: 1, hitstun: 18, hitstop: 4 }),
        hit(58, 66, bx(12, 12, 82, 92), 138, {
          group: 6,
          fx: "pierce",
          pushX: 11,
          knockdown: "hard",
          launch: [5.5, 8.5],
          hitstop: 17,
          shake: 3,
        }),
      ],
      vfx: [
        { at: 2, kind: "super", x: 0, y: 50, scale: 2.4, color: "#ff8a5c" },
        { at: 58, kind: "explode", x: 52, y: 46, scale: 1.4 },
      ],
      desc: "SUPER. The formation in one man: the chest holds them, the horns come round, and the blade finishes it.",
      notation: "↓↓ + S  (100 meter)",
      frames: [
        kf(0, { ...STANCE, torso: -14, shoulderB: 70, elbowB: 60, shoulderF: 8, elbowF: 94, weapon: 56, crouch: 0.4 }, "out"),
        kf(6, { ...STANCE, torso: 32, shoulderB: 84, elbowB: 24, shoulderF: 66, elbowF: 10, weapon: 4, hipF: 42, kneeF: 22, offX: 7 }, "out"),
        kf(12, { ...STANCE, torso: 34, shoulderF: 70, elbowF: 6, weapon: 2, hipF: 44, kneeF: 20, offX: 9 }),
        kf(17, { ...STANCE, torso: 12, shoulderF: 8, elbowF: 96, weapon: 58 }, "inOut"),
        kf(20, { ...STANCE, torso: 32, shoulderF: 56, elbowF: 6, weapon: 6, offX: 7 }, "out"),
        kf(25, { ...STANCE, torso: 10, shoulderB: 150, elbowB: 20 }, "inOut"),
        kf(28, { ...STANCE, torso: 34, shoulderB: 44, elbowB: 42, offX: 7 }, "out"),
        kf(33, { ...STANCE, torso: 10, shoulderF: 6, elbowF: 98, weapon: 60 }, "inOut"),
        kf(36, { ...STANCE, torso: 32, shoulderF: 74, elbowF: 8, weapon: 2, offX: 7 }, "out"),
        kf(41, { ...STANCE, torso: 10, shoulderF: 10, elbowF: 92, weapon: 54 }, "inOut"),
        kf(44, { ...STANCE, torso: 32, shoulderF: 62, elbowF: 8, weapon: 4, offX: 7 }, "out"),
        kf(52, { ...STANCE, torso: -22, shoulderB: 160, elbowB: 10, shoulderF: 20, elbowF: 92, weapon: 62, hipB: -30, kneeB: 44, offX: -6 }, "inOut"),
        kf(58, { ...STANCE, torso: 42, shoulderB: 40, elbowB: 30, shoulderF: 80, elbowF: 2, weapon: 0, hipF: 48, kneeF: 28, hipB: -24, kneeB: 56, offX: 12 }, "out"),
        kf(78, { ...STANCE, torso: 26, shoulderF: 50, elbowF: 40, offX: 5 }, "inOut"),
        kf(96, { ...STANCE }),
      ],
    },
  ],
};
